// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/villas/ru.ts (Balinese (Basa Bali, polite register)).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Pira rega vila ring Bali",
      "paragraphs": [
        "Ring katalog wenten 358 vila kaadol saking pangembang miwah pamilik. Rega medianne — $350,000, punika titik tengah pasar sane jujur, nenten angka pajangan: 8 saking 10 properti wenten ring kisaran $169,000 ngantos $850,000. Wates paling sor — kirang langkung $80,000 antuk vila 1 kamar turu sane kompak ring jero pulo, wates paling duwur — $6,5 juta antuk griya ageng ring garis ngarep sagara.",
        "Tigang indik sane nentuang rega: jumlah kamar turu, wewidangan, miwah tahap kesiapan. Kamar turu ngicen langkah sane paling prasida katebak — saben tambahan biasane regane dados kirang langkung 1,5 tikel saking sane sadurunge, margi luas griya miwah tanahnyane taler ngikut megedé."
      ]
    },
    {
      "heading": "Numbas proyek konstruksi utawi griya sane sampun dados",
      "paragraphs": [
        "Saking 358 vila, 251 kantun ring tahap konstruksi miwah 101 sampun kaserahang. Properti sane kantun kawangun regane langkung murah tinimbang sane sampun dados: pamegat nyanggra risiko jadwal, dados polih diskon, taler cicilan salami masa konstruksi — pembayaran awal paling asiki 30–50%, sisane kabage manut tahap pakaryan. Vila sane sampun dados langkung larang, nanging prasida kauningin langsung, kaicenang mriksa kualitas finishing, miwah langsung kasade ring pasar sewa.",
        "Rega median per meter persegi ring pulo — saking $2,000 ngantos $3,300 manut wewidangan. Rega per meter sane paling murah ring Ubud miwah pasisir kulon, sane paling larang ring tebing Bukit miwah ring Berawa. Nandingang properti pinaka sane paling leres punika manut rega per meter: dua griya sareng rega sami prasida beda luas ngantos 2 tikel."
      ]
    },
    {
      "heading": "Ring dija becik numbas vila ring Bali: wewidangan miwah rega",
      "paragraphs": [
        "Pulone kompak — saking Canggu ngantos Bukit kirang langkung 1–1,5 jam lelampahan — nanging pasar ring tiap wewidangan polih pola sane beda. Rega median manut katalog kadi puniki:"
      ],
      "bullets": [
        "Canggu — Berawa, Batu Bolong, Pererenan. Vila 2 kamar turu $330,000–390,000, vila 3 kamar turu ring Pererenan — saking $649,000. Puniki pasar sewa sane paling padet: surfing, kafe, miwah coworking kathah, nanging kompetisi ngrebut penyewa taler paling tinggi.",
        "Bukit — Uluwatu, Pandawa, Melasti, Ungasan. Median saking $270,000 ring Pandawa ngantos $560,000 ring tebing. Vila mawidang pemandangan, segmen premium, high season kuat miwah low season nyidayang turun nyata.",
        "Ubud — median $310,000, 1 kamar turu saking $172,000. Alas miwah sawah berundak, pamargin sewa bulanan wenten satata sasih setahun, ka sagara 30–40 menit.",
        "Nusa Dua miwah Jimbaran — median $248,500. Infrastruktur hotel, segara tenang, format kulawarga miwah okupansi sane langkung prasida katebak.",
        "Pasisir kulon — Nyanyi, Seseh, Cemagi. Median $276,500: lawang paling murah ka sagara miwah pertumbuhan rega tanah sane paling cepet ring warsa-warsa pungkasan.",
        "Sanur miwah Umalas — $207,500 miwah $255,000. Wewidangan tenang antuk melaksana urip, sekolah miwah klinik caket; sewa harian langkung lemah, nanging sewa bulanan stabil."
      ]
    },
    {
      "heading": "Cara warga asing numbas vila ring Bali",
      "paragraphs": [
        "Hak milik pribadi pinuh ring tanah (Hak Milik, freehold) manut hukum Indonesia nenten kasagedang antuk warga asing. Wenten tiga jalur sane lumrah. Leasehold (Hak Sewa) — hak nganggén salami waktu tartamtu sareng opsi perpanjangan: ring katalog, 161 vila gados masa 26–30 warsa, 98 — ngantos 25 warsa, 85 — 31 warsa utawi langkung. Hak Pakai — hak nganggén antuk residen sane ngamolihang KITAS, siklus 30+30+20 warsa. PT PMA sareng HGB ring tahap salajengnyane — jalur antuk sane nganggé properti pinaka usaha: gados sawatara properti utawi nyewayang resmi.",
        "Transaksi punika biasane mlampah ring skema sane sami: milih miwah booking sareng deposit, sasampunipun due diligence hukum (sertipikat tanah, zoning, idin, beban), kontrak ring notaris PPAT, pembayaran manut jadwal, registrasi miwah serah terima properti. Transaksi jarak jauh taler prasida kalaksanayang — nganggén surat kuasa, nanging pemeriksaan becik kaparingang ring pengacara idane sendiri, nenten ring pengacara pamedal.",
        "Ring biaya wajib: PPh 2,5% saking rega transaksi kabayar antuk pamedal, BPHTB ngantos 5% — antuk pamegat rikala ngurus hak, PPN ring rega properti anyar efektif 11%. Tarif pasti manut kabupaten miwah status pamedal, dados perkiraan biaya pungkasan patut kaonengin sareng notaris sadurung nyetor deposit."
      ]
    },
    {
      "heading": "Indik sane patut kapariksa sadurung numbas",
      "paragraphs": [
        "Sejatiné, pinaka masalah ring Bali paling asiki medal nenten margi rega, nanging margi dokumen. Checklist minimalne:"
      ],
      "bullets": [
        "Zoning tanah (RDTR miwah warna tanah) — ring tanah kuning perumahan, sewa harian ka turis nenten legal.",
        "Masa leasehold miwah syarat perpanjangan: napi rega siklus kaping kalih sampun kaiket ring kontrak utawi engké kakocapang manut pasar sasampun 25 warsa.",
        "Idin PBG miwah SLF — tanpa punika, griya sane kasanggra sampun nenten legal.",
        "Sira pamilik tanahe, napi wenten gadai, sengketa waris, utawi penyewa kaping kalih.",
        "Riwayat pangembang: proyek sane sampun kaserahang, ketepatan jadwal, miwah napi sane kelaksanayang ring dana yening konstruksi mandeg.",
        "Jadwal pembayaran miwah denda yening telat serah terima — ring kalih pihak.",
        "Sambungan toya miwah listrik miwah daya sane sajatosne — ring Bukit puniki langkung sering dados masalah tinimbang formalitas."
      ]
    },
    {
      "heading": "Sewa, imbal hasil, miwah biaya pangupajiwa",
      "paragraphs": [
        "Sewa bulanan ngicen dasar itungan sane cetha: median manut katalog — $2,585 ring Berawa, $2,113 ring Canggu, $1,608 ring Bukit miwah $1,300 ring Ubud. Sewa harian ring high season langkung duwur, nanging okupansi taler naik-turun: Desember–Maret miwah Juli–Agustus ngicen puncak, April miwah Oktober ngicen penurunan.",
        "Imbal hasil bersih vila sane kaurus manajemen kanthi realistis — 8–12% setahun yening okupansi 70–80%. Angka 10–15% sane kasurat antuk pangembang meh salantur kaetang saking omzet kotor ring sasih puncak. Sadurung ngitung balik modal, kurangi komisi perusahaan manajemen 15–25%, biaya operasional (kolam, taman, listrik, beberesih) — 5–8% saking omzet, pajak sewa, miwah amortisasi leasehold: makin nyedek ka pungkasan masa, makin murah properti punika yening kaadol malih."
      ]
    }
  ],
  "priceTable": {
    "caption": "Rega vila ring Bali manut jumlah kamar turu",
    "columns": [
      "Kamar turu",
      "Luas griya",
      "Rega lumrah",
      "Median"
    ],
    "rows": [
      [
        "1 kamar turu",
        "72 m²",
        "$127,000 – $285,000",
        "$188,000"
      ],
      [
        "2 kamar turu",
        "110 m²",
        "$185,000 – $510,000",
        "$320,000"
      ],
      [
        "3 kamar turu",
        "193 m²",
        "$300,000 – $781,000",
        "$473,700"
      ],
      [
        "4+ kamar turu",
        "310 m²",
        "$477,000 – $1,850,000",
        "$869,800"
      ]
    ],
    "note": "Kisaran — persentil ka-10 miwah ka-90 saking 357 vila sane ngantosin rega. Data katalog, kaanyarang manut pricelist pangembang."
  },
  "faqExtra": [
    {
      "q": "Sane langkung nguntungang — leasehold utawi freehold?",
      "a": "Freehold (Hak Milik) nenten kasagedang antuk warga asing, dados pilihan sane nyata punika antawis leasehold, Hak Pakai, miwah kepemilikan ngalantur PT PMA. Leasehold langkung enteng ring biaya awal miwah langkung sederhana ring proses, nanging nilai properti nyusut manut masa sane nyisa. PT PMA langkung awis ring pangupajiwa (pajak korporasi, pelaporan), nanging haknyane langkung dawa miwah properti prasida kasade sacara legal pinaka usaha."
    },
    {
      "q": "Napi sane dados ring vila sasampun leaseholdne telas?",
      "a": "Hak ring tanah miwah sakancan bangunan sane wenten ring luhure bali ka pamilik tanah yening masa nenten kawehin perpanjangan. Dados, syarat perpanjangan punika pasal sane paling penting ring kontrak: ring skema sane becik, rega miwah tata cara siklus kaping kalih sampun kaiket sadurungne; ring skema sane kirang becik, pamilik tanah bakal nyariosang rega manut pasar. Perpanjangan biasane kaurus langkung dini, nenten ngantos warsa pungkasan."
    },
    {
      "q": "Napi prasida numbas vila sareng cicilan?",
      "a": "Ring tahap konstruksi, punika standar: pembayaran awal biasane 30–50%, sisane kabagi manut tahap ngantos serah terima. Hipotek antuk warga asing ring Bali sakadi sane lumrah ring negara sané nenten wenten — cicilan biasane kaicen antuk pangembang, umumnya tanpa bunga salami masa konstruksi. Ring properti sane sampun dados, cicilan langkung jarang kapanggih miwah masane langkung cepak."
    },
    {
      "q": "Pira biaya pangupajiwa vila ring Bali?",
      "a": "Patokanipun — 5–8% saking pendapatan sewa yening vila kaséwahang, utawi $300–700 per sasih antuk griya mawi kolam yening kaanggén manggen pribadi: listrik, toya, perawatan kolam, tukang taman, beberesih, internet. Kapisah saking punika kaetang pajak tanah miwah bangunan PBB miwah komisi perusahaan manajemen 15–25%, yening properti punika kaséwahang."
    },
    {
      "q": "Napi bedane vila ring kompleks sareng vila sane ngadeg soroh?",
      "a": "Vila ring kompleks ngabageang wilayah, kaamanan, perawatan, miwah asiki perusahaan manajemen sareng tetangga — punika langkung irit ring biaya pangupajiwa miwah langkung gampang ring sewa, nanging dados wenten service charge miwah aturan kompleks. Vila sane ngadeg soroh ngicen privasi miwah kaleluasan sane langkung akéh antuk renovasi, nanging sadaya perawatan miwah pados penyewa dados tanggung jawab iraga."
    },
    {
      "q": "Napi prasida numbas vila sacara jarak jauh, tanpa rauh ka Bali?",
      "a": "Inggih, transaksi kadi puniki rutin kalaksanayang nganggén surat kuasa: viewing liwat video, dokumen ngalantur notaris PPAT, pembayaran nganggén transfer bank. Sane paling penting siji — pemeriksaan hukum miwah serah terima patut kalaksanayang antuk pengacara independen utawi wakil sane kaandelang ring lokasi, nenten antuk wakil pamedal."
    }
  ]
}

export default copy
