// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/villas/ru.ts (German).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Was kostet eine Villa auf Bali",
      "paragraphs": [
        "Im Katalog finden Sie 358 Villen zum Verkauf von Bauträgern und Eigentümern. Der Medianpreis liegt bei $350.000, und das ist die ehrliche Mitte des Marktes, keine Schaufensterzahl: Acht von zehn Objekten liegen in der Spanne von $169.000 bis $850.000. Die Untergrenze liegt bei rund $80.000 für eine kompakte Villa mit 1 Schlafzimmer im Inselinneren, die Obergrenze bei $6,5 млн für ein Anwesen in erster Meereslinie.",
        "Den Preis bestimmen drei Faktoren: die Anzahl der Schlafzimmer, die Lage und der Fertigstellungsgrad. Die Schlafzimmer sorgen für den berechenbarsten Sprung — jedes weitere ist ungefähr eineinhalbmal teurer als das vorherige, weil damit sowohl die Wohnfläche als auch das Grundstück wachsen."
      ]
    },
    {
      "heading": "Neubau oder fertiges Haus",
      "paragraphs": [
        "Von 358 Villen sind 251 im Bau und 101 bereits fertiggestellt. Ein Objekt im Bau ist spürbar günstiger als eine fertige Villa: Der Käufer übernimmt das Terminrisiko und erhält dafür einen Preisnachlass sowie eine Ratenzahlung über die Bauzeit — die Anzahlung liegt meist bei 30–50%, der Rest wird nach Baufortschritt aufgeteilt. Eine fertige Villa ist teurer, dafür kann man sie vor Ort besichtigen, die Ausführungsqualität prüfen und sofort in die Vermietung geben.",
        "Der Medianpreis pro Quadratmeter auf der Insel liegt je nach Lage zwischen $2.000 und $3.300. Am günstigsten ist der Quadratmeter in Ubud und an der Westküste, am teuersten auf den Klippen von Bukit und in Berawa. Vergleichen sollte man Objekte sinnvollerweise именно nach dem Quadratmeterpreis: Zwei Häuser mit demselben Kaufpreis können sich in der Fläche um das Doppelte unterscheiden."
      ]
    },
    {
      "heading": "Wo man auf Bali eine Villa kaufen kann: Lagen und Preise",
      "paragraphs": [
        "Die Insel ist kompakt — von Canggu bis Bukit fährt man eine bis anderthalb Stunden —, aber die Teilmärkte in den einzelnen Lagen verhalten sich unterschiedlich. Die Medianpreise im Katalog sehen so aus:"
      ],
      "bullets": [
        "Canggu — Berawa, Batu Bolong, Pererenan. Villen mit 2 Schlafzimmern $330.000–390.000, Villen mit 3 Schlafzimmern in Pererenan ab $649.000. Der dichteste Mietmarkt: Surfen, Cafés und Coworking, aber auch die höchste Konkurrenz um Mieter.",
        "Bukit — Uluwatu, Pandawa, Melasti, Ungasan. Median von $270.000 in Pandawa bis $560.000 auf den Klippen. Villen mit Aussicht, Premiumsegment, starke Hochsaison und ein deutlicher Einbruch in der Nebensaison.",
        "Ubud — Median $310.000, Villen mit 1 Schlafzimmer ab $172.000. Dschungel und Reisterrassen, ganzjährig Nachfrage nach Langzeitmiete, 30–40 Minuten bis zum Ozean.",
        "Nusa Dua und Jimbaran — Median $248.500. Hotelinfrastruktur, ruhiges Meer, familienfreundliches Format und gut planbare Auslastung.",
        "Westküste — Nyanyi, Seseh, Cemagi. Median $276.500: der günstigste Einstieg nah am Ozean und in den letzten Jahren das schnellste Wachstum der Bodenpreise.",
        "Sanur und Umalas — $207.500 und $255.000. Ruhige Wohnlagen, Schulen und Kliniken in der Nähe; die Kurzzeitvermietung ist schwächer, dafür ist die monatliche Vermietung stabil."
      ]
    },
    {
      "heading": "Wie Ausländer auf Bali eine Villa kaufen",
      "paragraphs": [
        "Volles privates Eigentum an Land (Hak Milik, Freehold) ist für Ausländer nach indonesischem Recht nicht möglich. Es gibt drei praktikable Wege. leasehold (Hak Sewa) — ein Nutzungsrecht für einen festen Zeitraum mit Verlängerungsoption: Bei 161 Villen im Katalog beträgt die Laufzeit 26–30 Jahre, bei 98 — bis 25 Jahre, bei 85 — ab 31 Jahren und mehr. Hak Pakai — Nutzungsrecht für einen Residenten mit KITAS, Zyklus 30+30+20 Jahre. PT PMA mit anschließendem HGB — der Weg für alle, für die Immobilien ein Geschäft sind: mehrere Objekte oder offizielle Vermietung.",
        "Der Ablauf der Transaktion folgt demselben Schema: Auswahl und Reservierung mit Deposit, dann rechtliche Prüfung (Landzertifikat, zoning, Genehmigungen, Belastungen), Vertrag beim Notar PPAT, Zahlung nach Zeitplan, Registrierung und Abnahme des Objekts. Auch aus der Ferne lassen sich Transaktionen abwickeln — per Vollmacht, aber die Prüfung sollte Ihr eigener Anwalt übernehmen und nicht der Anwalt des Verkäufers.",
        "Zu den Pflichtabgaben: PPh 2,5% des Kaufpreises zahlt der Verkäufer, BPHTB bis 5% zahlt der Käufer bei der Eintragung der Rechte, die Mehrwertsteuer im Preis eines Neubaus beträgt effektiv 11%. Die genauen Sätze hängen vom Kabupaten und vom Status des Verkäufers ab, deshalb sollte die endgültige Kalkulation vor Zahlung des Deposits mit dem Notar abgestimmt werden."
      ]
    },
    {
      "heading": "Was vor dem Kauf zu prüfen ist",
      "paragraphs": [
        "Die meisten Probleme auf Bali entstehen nicht wegen des Preises, sondern wegen der Unterlagen. Die minimale Checkliste:"
      ],
      "bullets": [
        "zoning des Grundstücks (RDTR und Landfarbe) — auf gelbem Wohnbauland ist die touristische Kurzzeitvermietung illegal.",
        "Laufzeit des leasehold und Bedingungen der Verlängerung: Ist der Preis für den zweiten Zyklus im Vertrag festgeschrieben oder wird er in 25 Jahren zum Marktpreis genannt.",
        "Genehmigungen PBG und SLF — ohne sie ist ein gebautes Haus nicht legalisiert.",
        "Wer ist Eigentümer des Grundstücks, gibt es ein Pfandrecht, einen Erbstreit oder einen zweiten Mieter.",
        "Historie des Bauträgers: fertiggestellte Projekte, Einhaltung von Fristen und was mit dem Geld passiert, wenn der Bau stoppt.",
        "Zahlungsplan und Vertragsstrafen bei verspäteter Fertigstellung — für beide Seiten.",
        "Anschluss an Wasser und Strom sowie die tatsächliche Leistung — auf Bukit ist das häufiger ein Problem als bloße Formalität."
      ]
    },
    {
      "heading": "Vermietung, Rendite und laufende Kosten",
      "paragraphs": [
        "Die monatliche Vermietung liefert eine verständliche Basis für die Kalkulation: Der Median im Katalog liegt bei $2.585 in Berawa, $2.113 in Canggu, $1.608 auf Bukit und $1.300 in Ubud. Die Tagesmiete ist in der Hochsaison höher, aber auch die Auslastung schwankt: Dezember–März und Juli–August bringen den Peak, April und Oktober den Einbruch.",
        "Eine realistische Nettorendite für eine Villa im Management liegt bei 8–12% pro Jahr bei einer Auslastung von 70–80%. Die von Bauträgern genannten 10–15% werden fast immer auf Basis des Bruttoumsatzes eines Spitzenmonats gerechnet. Bevor Sie die Amortisation kalkulieren, ziehen Sie die Provision der Verwaltungsgesellschaft von 15–25%, die laufenden Kosten (Pool, Garten, Strom, Reinigung) — 5–8% des Umsatzes, die Steuer auf Mieteinnahmen und die Abschreibung des leasehold ab: Je näher das Laufzeitende rückt, desto günstiger wird das Objekt beim Wiederverkauf."
      ]
    }
  ],
  "priceTable": {
    "caption": "Preise für Villen auf Bali nach Anzahl der Schlafzimmer",
    "columns": [
      "Schlafzimmer",
      "Wohnfläche",
      "Typischer Preis",
      "Median"
    ],
    "rows": [
      [
        "1 Schlafzimmer",
        "72 m²",
        "$127.000 – $285.000",
        "$188.000"
      ],
      [
        "2 Schlafzimmer",
        "110 m²",
        "$185.000 – $510.000",
        "$320.000"
      ],
      [
        "3 Schlafzimmer",
        "193 m²",
        "$300.000 – $781.000",
        "$473.700"
      ],
      [
        "4+ Schlafzimmer",
        "310 m²",
        "$477.000 – $1.850.000",
        "$869.800"
      ]
    ],
    "note": "Die Spanne zeigt den 10. und 90. Perzentilwert für 357 Villen mit ausgewiesenem Preis. Katalogdaten, aktualisiert zusammen mit den Preislisten der Bauträger."
  },
  "faqExtra": [
    {
      "q": "Was ist vorteilhafter — leasehold oder freehold?",
      "a": "Freehold (Hak Milik) ist für Ausländer nicht verfügbar, daher besteht die reale Wahl zwischen leasehold, Hak Pakai und Eigentum über eine PT PMA. leasehold ist beim Einstieg günstiger und in der Abwicklung einfacher, das Objekt schreibt sich aber zusammen mit der Laufzeit ab. PT PMA ist im Unterhalt teurer (Körperschaftsteuer, Reporting), dafür sind die Rechte länger und die Immobilie kann legal als Geschäft vermietet werden."
    },
    {
      "q": "Was passiert mit der Villa nach Ablauf des leasehold?",
      "a": "Die Rechte am Grundstück und alles, was darauf gebaut wurde, fallen an den Grundstückseigentümer zurück, wenn die Laufzeit nicht verlängert wird. Deshalb ist die Verlängerungsklausel ein zentraler Punkt im Vertrag: Im guten Fall sind Preis und Ablauf des zweiten Zyklus vorab fixiert, im schlechten nennt der Eigentümer den Marktpreis. Eine Verlängerung wird in der Regel rechtzeitig vereinbart und nicht erst im letzten Jahr."
    },
    {
      "q": "Kann man eine Villa in Raten kaufen?",
      "a": "In der Bauphase ist das Standard: Die Anzahlung beträgt meist 30–50%, der Rest wird bis zur Fertigstellung nach Etappen aufgeteilt. Hypotheken für Ausländer in der üblichen Form gibt es auf Bali nicht — die Ratenzahlung kommt direkt vom Bauträger, in der Regel zinsfrei für die Bauzeit. Bei fertigen Objekten ist eine Ratenzahlung seltener und die Laufzeit kürzer."
    },
    {
      "q": "Was kostet der Unterhalt einer Villa auf Bali?",
      "a": "Als Richtwert gelten 5–8% der Mieteinnahmen, wenn die Villa vermietet wird, oder $300–700 pro Monat für ein Haus mit Pool bei Eigennutzung: Strom, Wasser, Poolservice, Gärtner, Reinigung, Internet. Separat zu kalkulieren sind die Steuer auf Land und Gebäude PBB sowie die Provision der Verwaltungsgesellschaft von 15–25%, wenn das Objekt vermietet wird."
    },
    {
      "q": "Worin unterscheidet sich eine Villa in einer Anlage von einer freistehenden Villa?",
      "a": "Eine Villa in einer Anlage teilt sich mit den Nachbarn das Gelände, die Sicherheit, den Unterhalt und oft auch die Verwaltungsgesellschaft — das ist günstiger im Betrieb und einfacher in der Vermietung, dafür fallen service charge und Regeln der Anlage an. Eine freistehende Villa bietet mehr Privatsphäre und Freiheit bei Umbauten, aber der gesamte Unterhalt und die Mietersuche liegen bei Ihnen."
    },
    {
      "q": "Kann man eine Villa aus der Ferne kaufen, ohne nach Bali zu kommen?",
      "a": "Ja, Transaktionen werden regelmäßig per Vollmacht abgewickelt: Besichtigung per Video, Unterlagen über den Notar PPAT, Zahlung per Banküberweisung. Ein Punkt ist entscheidend — die rechtliche Prüfung und die Abnahme sollte Ihr unabhängiger Anwalt oder eine Vertrauensperson vor Ort übernehmen und nicht der Vertreter des Verkäufers."
    }
  ]
}

export default copy
