// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/villas/ru.ts (English).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "How much does a villa in Bali cost",
      "paragraphs": [
        "The catalogue lists 358 villas for sale from developers and private owners. The median price is $350,000, and that is a real market midpoint rather than a showcase figure: eight out of ten properties fall within the $169,000 to $850,000 range. The lower end is around $80,000 for a compact one-bedroom villa inland, while the upper end is $6.5 million for a mansion on the front ocean line.",
        "Price is driven by three things: bedroom count, area, and stage of completion. Bedrooms give the most predictable step-up — each additional bedroom is roughly one and a half times more expensive than the previous one, because both the house size and the plot size increase with it."
      ]
    },
    {
      "heading": "Off-plan or completed villa",
      "paragraphs": [
        "Out of 358 villas, 251 are under construction and 101 have already been completed. An off-plan property is noticeably cheaper than a completed one: the buyer takes on timing risk and gets a discount for it, as well as instalments during construction — the first payment is usually 30–50%, with the balance split by construction stages. A completed villa costs more, but you can inspect it in person, check the finishing quality, and put it into rental immediately.",
        "The island-wide median price per square metre is from $2,000 to $3,300 depending on the area. The cheapest square metre is in Ubud and on the west coast, while the most expensive is on the Bukit cliffs and in Berawa. It is more accurate to compare properties by price per square metre: two houses with the same asking price can differ twofold in size."
      ]
    },
    {
      "heading": "Where to buy a villa in Bali: areas and prices",
      "paragraphs": [
        "The island is compact — from Canggu to Bukit is an hour to an hour and a half by car — but each area behaves differently. Median catalogue prices look like this:"
      ],
      "bullets": [
        "Canggu — Berawa, Batu Bolong, Pererenan. Two-bedroom villas are $330,000–$390,000, three-bedroom villas in Pererenan start from $649,000. This is the densest rental market: surf, cafés, and coworking, but also the highest competition for tenants.",
        "Bukit — Uluwatu, Pandawa, Melasti, Ungasan. Median prices range from $270,000 in Pandawa to $560,000 on the cliffs. View villas, premium segment, a strong high season, and a noticeable drop in the low season.",
        "Ubud — median price $310,000, one-bedroom villas from $172,000. Jungle and rice terrace setting, year-round demand for long-term rental, 30–40 minutes to the ocean.",
        "Nusa Dua and Jimbaran — median price $248,500. Hotel infrastructure, calm sea, family-oriented format, and predictable occupancy.",
        "West coast — Nyanyi, Seseh, Cemagi. Median price $276,500: the cheapest entry point near the ocean and the fastest land price growth in recent years.",
        "Sanur and Umalas — $207,500 and $255,000. Quiet residential areas with schools and clinics nearby; daily rental is weaker, but monthly rental is stable."
      ]
    },
    {
      "heading": "How a foreigner can buy a villa in Bali",
      "paragraphs": [
        "Full private land ownership (Hak Milik, freehold) is not available to foreigners under Indonesian law. There are three workable routes. Leasehold (Hak Sewa) is a right of use for a fixed term with an extension option: 161 villas in the catalogue have 26–30 years remaining, 98 have up to 25 years, and 85 have 31 years or more. Hak Pakai is a right of use for a resident with KITAS, on a 30+30+20 year cycle. PT PMA followed by HGB is the route for those treating property as a business: multiple units or licensed rental operations.",
        "The transaction itself follows one standard process: selection and reservation with a deposit, then legal due diligence (land certificate, zoning, permits, encumbrances), contract signing with a PPAT notary, payment on schedule, registration, and handover of the property. Remote transactions are also done — by power of attorney, but due diligence should be handled by your own lawyer, not the seller’s lawyer.",
        "Mandatory taxes and fees: PPh 2.5% of the transaction price is paid by the seller, BPHTB up to 5% is paid by the buyer when registering rights, and VAT included in the price of a new-build is effectively 11%. Exact rates depend on the kabupaten and the seller’s status, so confirm the final cost estimate with the notary before paying a deposit."
      ]
    },
    {
      "heading": "What to check before buying",
      "paragraphs": [
        "Most problems in Bali come not from the price, but from the paperwork. Minimum checklist:"
      ],
      "bullets": [
        "Plot zoning (RDTR and land colour) — on yellow residential land, short-term tourist rental is illegal.",
        "Leasehold term and extension terms: whether the price for the second term is fixed in the contract or will be set at market rate in 25 years.",
        "PBG and SLF permits — without them, a completed house is not legally regularised.",
        "Who owns the land, and whether there is a mortgage, inheritance dispute, or a second tenant.",
        "Developer track record: completed projects, delivery record, and what happens to the funds if construction stops.",
        "Payment schedule and late-delivery penalties — on both sides.",
        "Water and electricity connections and actual power capacity — on Bukit this is more often a real issue than a formality."
      ]
    },
    {
      "heading": "Rental, yield, and running costs",
      "paragraphs": [
        "Monthly rent gives a clear basis for calculation: the catalogue median is $2,585 in Berawa, $2,113 in Canggu, $1,608 in Bukit, and $1,300 in Ubud. Daily rental in high season is higher, but occupancy also fluctuates: December–March and July–August are peak periods, while April and October are weaker.",
        "A realistic net yield for a managed villa is 8–12% per year at 70–80% occupancy. The 10–15% claimed by developers is almost always calculated from gross revenue in a peak month. Before estimating payback, deduct the management company fee of 15–25%, running costs (pool, garden, electricity, cleaning) — 5–8% of revenue, rental tax, and leasehold amortisation: the closer the end of the term, the cheaper the property becomes on resale."
      ]
    }
  ],
  "priceTable": {
    "caption": "Bali villa prices by number of bedrooms",
    "columns": [
      "Bedrooms",
      "House size",
      "Typical price",
      "Median"
    ],
    "rows": [
      [
        "1 bedroom",
        "72 m²",
        "$127,000 – $285,000",
        "$188,000"
      ],
      [
        "2 bedrooms",
        "110 m²",
        "$185,000 – $510,000",
        "$320,000"
      ],
      [
        "3 bedrooms",
        "193 m²",
        "$300,000 – $781,000",
        "$473,700"
      ],
      [
        "4+ bedrooms",
        "310 m²",
        "$477,000 – $1,850,000",
        "$869,800"
      ]
    ],
    "note": "The range is the 10th and 90th percentiles across 357 villas with a listed price. Catalogue data, updated together with developer price lists."
  },
  "faqExtra": [
    {
      "q": "What is better value — leasehold or freehold?",
      "a": "Freehold (Hak Milik) is not available to foreigners, so in practice the choice is between leasehold, Hak Pakai, and ownership through a PT PMA. Leasehold is cheaper at entry and simpler to structure, but the asset depreciates as the term runs down. PT PMA is more expensive to maintain (corporate tax, reporting), but the rights are longer and the property can be rented out legally as a business."
    },
    {
      "q": "What happens to the villa when the leasehold ends?",
      "a": "The land rights and everything built on it revert to the landowner unless the term is extended. That is why the extension clause is a key part of the contract: in a good structure, the price and procedure for the second term are fixed in advance; in a weak one, the owner will name a market price later. Extensions are usually arranged well in advance, not in the final year."
    },
    {
      "q": "Can you buy a villa in instalments?",
      "a": "At the construction stage, this is standard: the first payment is usually 30–50%, with the balance split into stages until completion. Foreign-style mortgages are not really available in Bali for foreigners — instalments are provided by the developer directly, usually interest-free for the construction period. For completed properties, instalments are less common and usually for a shorter term."
    },
    {
      "q": "How much does it cost to maintain a villa in Bali?",
      "a": "A practical benchmark is 5–8% of rental revenue if the villa is rented out, or $300–$700 per month for a house with a pool if you live in it yourself: electricity, water, pool service, gardener, cleaning, internet. PBB land and building tax and the management company fee of 15–25% are calculated separately if the property is in rental operation."
    },
    {
      "q": "How is a villa in a complex different from a standalone villa?",
      "a": "A villa in a complex shares grounds, security, maintenance, and often the management company with neighbours — this makes it cheaper to run and easier to rent out, but there is a service charge and complex rules. A standalone villa gives more privacy and more freedom to renovate, but all maintenance and tenant sourcing fall on you."
    },
    {
      "q": "Can you buy a villa remotely without coming to Bali?",
      "a": "Yes, transactions are regularly done by power of attorney: viewings by video, documents through a PPAT notary, payment by bank transfer. One point is critical — legal due diligence and acceptance of the property should be handled by your independent lawyer or trusted representative on the ground, not by the seller’s representative."
    }
  ]
}

export default copy
