// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/villas/ru.ts (French).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Quel est le prix d’une villa à Bali",
      "paragraphs": [
        "Le catalogue propose 358 villas à vendre, directement auprès de promoteurs et de propriétaires. Le prix médian est de 350 000 $, et c’est un vrai milieu de marché, pas un prix de vitrine : huit biens sur dix se situent entre 169 000 et 850 000 $. Le seuil bas commence autour de 80 000 $ pour une petite villa d’une chambre à l’intérieur de l’île, le haut atteint 6,5 млн $ pour une demeure en première ligne face à l’océan.",
        "Le prix dépend de trois facteurs : le nombre de chambres, le quartier et l’état d’avancement du bien. Le nombre de chambres reste le critère le plus prévisible : chaque chambre supplémentaire coûte en moyenne une fois et demie plus cher que la précédente, car la surface de la maison et celle du terrain augmentent aussi."
      ]
    },
    {
      "heading": "Acheter sur plan ou une maison déjà livrée",
      "paragraphs": [
        "Sur 358 villas, 251 sont en construction et 101 sont déjà livrées. Un bien en cours de construction coûte sensiblement moins cher qu’un bien terminé : l’acheteur prend le risque lié aux délais et obtient en contrepartie une décote, ainsi qu’un paiement échelonné pendant les travaux — l’acompte initial est le plus souvent de 30–50%, le solde étant réparti selon les étapes du chantier. Une villa achevée est plus chère, mais on peut la visiter, vérifier la qualité des finitions et la mettre immédiatement en location.",
        "Le prix médian au mètre carré sur l’île varie de 2 000 à 3 300 $ selon le secteur. Les mètres carrés les moins chers se trouvent à Ubud et sur la côte ouest, les plus chers sur les falaises du Bukit et à Berawa. Pour comparer correctement des biens, il vaut mieux regarder le prix au mètre carré : deux maisons affichées au même prix peuvent avoir une surface qui varie du simple au double."
      ]
    },
    {
      "heading": "Où acheter une villa à Bali : quartiers et prix",
      "paragraphs": [
        "L’île est compacte — de Canggu au Bukit il faut compter une heure à une heure et demie de route — mais les marchés locaux se comportent différemment. Voici les prix médians du catalogue :"
      ],
      "bullets": [
        "Canggu — Berawa, Batu Bolong, Pererenan. Villas de deux chambres à 330 000–390 000 $, villas de trois chambres à Pererenan à partir de 649 000 $. C’est le marché locatif le plus dense : surf, cafés et coworkings, mais aussi la concurrence la plus forte pour attirer les locataires.",
        "Bukit — Uluwatu, Pandawa, Melasti, Ungasan. Médiane à partir de 270 000 $ à Pandawa jusqu’à 560 000 $ sur les falaises. Villas avec vue, segment premium, haute saison solide et baisse marquée en basse saison.",
        "Ubud — médiane de 310 000 $, villas d’une chambre à partir de 172 000 $. Jungle et rizières, demande locative longue durée toute l’année, à 30–40 minutes de l’océan.",
        "Nusa Dua et Jimbaran — médiane de 248 500 $. Infrastructures hôtelières, mer calme, format familial et taux d’occupation prévisible.",
        "Côte ouest — Nyanyi, Seseh, Cemagi. Médiane de 276 500 $ : l’accès à l’océan le moins cher et la hausse la plus rapide du prix du foncier ces dernières années.",
        "Sanur et Umalas — 207 500 $ et 255 000 $. Quartiers calmes pour y vivre, avec écoles et cliniques à proximité ; la location courte durée y est plus faible, mais la location mensuelle y est plus stable."
      ]
    },
    {
      "heading": "Comment un étranger peut acheter une villa à Bali",
      "paragraphs": [
        "La pleine propriété privée du terrain (Hak Milik, freehold) n’est pas accessible à un étranger selon le droit indonésien. Il existe trois options réellement utilisées. Le leasehold (Hak Sewa) — droit d’usage pour une durée fixe avec option de prolongation : dans le catalogue, 161 villas ont une durée de 26–30 ans, 98 jusqu’à 25 ans, et 85 à partir de 31 ans et plus. Hak Pakai — droit d’usage pour un résident avec KITAS, selon un cycle de 30+30+20 ans. PT PMA avec HGB ensuite — une solution pour ceux qui traitent l’immobilier comme une activité commerciale : plusieurs biens ou location exploitée officiellement.",
        "La transaction elle-même suit en général le même schéma : sélection et réservation avec dépôt, puis vérification juridique (certificat foncier, zonage, autorisations, charges), signature chez le notaire PPAT, paiement selon l’échéancier, enregistrement et remise du bien. Une transaction à distance est également possible — par procuration — mais il est préférable de confier la due diligence à votre propre avocat, et non à celui du vendeur.",
        "Parmi les frais obligatoires : le PPh de 2,5% sur le prix de vente est payé par le vendeur, le BPHTB jusqu’à 5% est à la charge de l’acheteur lors de l’enregistrement des droits, et la TVA incluse dans le prix d’un bien neuf est effectivement de 11%. Les taux exacts dépendent du kabupaten et du statut du vendeur ; il faut donc vérifier le budget final avec le notaire avant de verser le dépôt."
      ]
    },
    {
      "heading": "Ce qu’il faut vérifier avant d’acheter",
      "paragraphs": [
        "À Bali, la plupart des problèmes ne viennent pas du prix, mais des documents. Checklist minimale :"
      ],
      "bullets": [
        "Le zonage du terrain (RDTR et couleur du terrain) — sur une zone résidentielle jaune, la location touristique courte durée est illégale.",
        "La durée du leasehold et les conditions de prolongation : le prix du deuxième cycle est-il fixé dans le contrat ou sera-t-il déterminé au prix du marché dans 25 ans.",
        "Les autorisations PBG et SLF — sans elles, la maison construite n’est pas régularisée.",
        "Qui est propriétaire du terrain, et s’il existe un nantissement, un litige successoral ou un second locataire.",
        "L’historique du promoteur : projets livrés, respect des délais et sort des fonds si le chantier s’arrête.",
        "L’échéancier de paiement et les pénalités de retard de livraison — dans les deux sens.",
        "Le raccordement à l’eau et à l’électricité, ainsi que la puissance réelle — dans le Bukit, c’est plus souvent un vrai sujet qu’une simple formalité."
      ]
    },
    {
      "heading": "Location, rendement et charges",
      "paragraphs": [
        "La location mensuelle donne une base claire de calcul : la médiane du catalogue est de 2 585 $ à Berawa, 2 113 $ à Canggu, 1 608 $ dans le Bukit et 1 300 $ à Ubud. En location courte durée, les revenus sont plus élevés en haute saison, mais l’occupation varie fortement : décembre–mars et juillet–août correspondent au pic, avril et octobre au creux.",
        "Un rendement net réaliste pour une villa gérée par un opérateur se situe entre 8–12% par an avec un taux d’occupation de 70–80%. Les 10–15% annoncés par les promoteurs sont presque toujours calculés sur le chiffre d’affaires brut d’un mois de pointe. Avant d’estimer le retour sur investissement, il faut déduire la commission de la société de gestion de 15–25%, les frais d’exploitation (piscine, jardin, électricité, ménage) — 5–8% du chiffre d’affaires, l’impôt sur les revenus locatifs et l’amortissement du leasehold : plus la fin du bail approche, plus le bien perd de la valeur à la revente."
      ]
    }
  ],
  "priceTable": {
    "caption": "Prix des villas à Bali selon le nombre de chambres",
    "columns": [
      "Chambres",
      "Surface de la maison",
      "Prix type",
      "Médiane"
    ],
    "rows": [
      [
        "1 chambre",
        "72 m²",
        "127 000 – 285 000 $",
        "188 000 $"
      ],
      [
        "2 chambres",
        "110 m²",
        "185 000 – 510 000 $",
        "320 000 $"
      ],
      [
        "3 chambres",
        "193 m²",
        "300 000 – 781 000 $",
        "473 700 $"
      ],
      [
        "4+ chambres",
        "310 m²",
        "477 000 – 1 850 000 $",
        "869 800 $"
      ]
    ],
    "note": "La fourchette correspond aux 10e et 90e percentiles sur 357 villas avec prix indiqué. Données du catalogue, mises à jour avec les tarifs des promoteurs."
  },
  "faqExtra": [
    {
      "q": "Qu’est-ce qui est plus avantageux — leasehold ou freehold ?",
      "a": "Le freehold (Hak Milik) n’est pas accessible à un étranger, donc le vrai choix se fait entre leasehold, Hak Pakai et la détention via PT PMA. Le leasehold demande moins de capital au départ et reste plus simple à structurer, mais le bien s’amortit avec la durée restante. Une PT PMA coûte plus cher à gérer (fiscalité d’entreprise, reporting), mais les droits sont plus longs et le bien peut être loué légalement comme activité commerciale."
    },
    {
      "q": "Que devient la villa à la fin du leasehold ?",
      "a": "Les droits sur le terrain et tout ce qui a été construit reviennent au propriétaire du terrain si la durée n’est pas prolongée. La clause de prolongation est donc un point central du contrat : dans un bon schéma, le prix et les modalités du second cycle sont fixés à l’avance ; dans un mauvais, le propriétaire fixera le prix au marché. En pratique, la prolongation se traite en général bien avant la dernière année."
    },
    {
      "q": "Peut-on acheter une villa avec paiement échelonné ?",
      "a": "En phase de construction, c’est la norme : l’acompte initial est généralement de 30–50%, puis le solde est réparti par étapes jusqu’à la livraison. Il n’existe pas à Bali de crédit hypothécaire classique pour un étranger — l’échelonnement est accordé directement par le promoteur, en général sans intérêt pendant la durée du chantier. Pour les biens déjà terminés, ce type de paiement est plus rare et sur une durée plus courte."
    },
    {
      "q": "Combien coûte l’entretien d’une villa à Bali ?",
      "a": "Comptez environ 5–8% des revenus locatifs si la villa est exploitée en location, ou 300–700 $ par mois pour une maison avec piscine occupée par son propriétaire : électricité, eau, entretien de la piscine, jardinier, ménage, internet. À cela s’ajoutent la taxe foncière et bâtiment PBB, ainsi que la commission de gestion de 15–25% si le bien est loué."
    },
    {
      "q": "Quelle est la différence entre une villa dans une résidence et une villa indépendante ?",
      "a": "Une villa dans une résidence partage avec les voisins le terrain, la sécurité, l’entretien et souvent la société de gestion — c’est moins coûteux à exploiter et plus simple à louer, mais il y a des service charge et un règlement interne. Une villa indépendante offre plus d’intimité et de liberté pour modifier le bien, mais tout l’entretien et la recherche de locataires reposent sur vous."
    },
    {
      "q": "Peut-on acheter une villa à distance, sans venir à Bali ?",
      "a": "Oui, les transactions par procuration se font régulièrement : visite vidéo, documents via le notaire PPAT, paiement par virement bancaire. Un point est essentiel : la vérification juridique et la réception du bien doivent être assurées par votre avocat indépendant ou par une personne de confiance sur place, et non par le représentant du vendeur."
    }
  ]
}

export default copy
