// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/villas/ru.ts (Indonesian).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Berapa harga vila di Bali",
      "paragraphs": [
        "Di katalog ada 358 vila dijual dari developer dan pemilik langsung. Harga median — $350.000, dan ini benar-benar titik tengah pasar, bukan angka pajangan: delapan dari sepuluh properti berada di kisaran $169.000 hingga $850.000. Batas bawah — sekitar $80.000 untuk vila kompak 1 kamar tidur di bagian dalam pulau, batas atas — $6,5 juta untuk mansion di garis depan laut.",
        "Harga ditentukan oleh tiga faktor: jumlah kamar tidur, area, dan tahap kesiapan. Kamar tidur memberi kenaikan paling mudah diprediksi — setiap tambahan kamar berikutnya rata-rata sekitar satu setengah kali lebih mahal dari sebelumnya, karena luas bangunan dan lahan juga ikut bertambah."
      ]
    },
    {
      "heading": "Bangun baru atau rumah siap huni",
      "paragraphs": [
        "Dari 358 vila, 251 masih dalam pembangunan dan 101 sudah selesai. Properti yang masih dibangun harganya jelas lebih rendah daripada yang siap huni: pembeli mengambil risiko waktu penyelesaian dan sebagai gantinya mendapat diskon, serta cicilan selama masa konstruksi — uang muka pertama paling sering 30–50%, sisanya dibagi sesuai tahapan pekerjaan. Vila jadi lebih mahal, tetapi bisa dilihat langsung, kualitas finishing bisa diperiksa, dan bisa segera disewakan.",
        "Harga median per meter persegi di pulau ini — dari $2.000 hingga $3.300 tergantung area. Harga per meter paling murah di Ubud dan pesisir barat, paling mahal — di tebing Bukit dan di Berawa. Membandingkan properti paling tepat justru berdasarkan harga per meter: dua rumah dengan harga sama bisa berbeda luas sampai dua kali lipat."
      ]
    },
    {
      "heading": "Di mana beli vila di Bali: area dan harga",
      "paragraphs": [
        "Pulaunya kompak — dari Canggu ke Bukit sekitar satu sampai satu setengah jam berkendara, — tetapi pasar di tiap area bergerak berbeda. Harga median di katalog terlihat seperti ini:"
      ],
      "bullets": [
        "Canggu — Berawa, Batu Bolong, Pererenan. Vila 2 kamar tidur $330.000–$390.000, vila 3 kamar tidur di Pererenan — dari $649.000. Pasar sewa paling padat: selancar, kafe, dan coworking, tetapi persaingan mendapatkan penyewa juga paling tinggi.",
        "Bukit — Uluwatu, Pandawa, Melasti, Ungasan. Median dari $270.000 di Pandawa hingga $560.000 di tebing. Vila dengan view, segmen premium, high season kuat dan penurunan yang terasa saat low season.",
        "Ubud — median $310.000, 1 kamar tidur mulai dari $172.000. Hutan dan sawah bertingkat, permintaan sewa bulanan stabil sepanjang tahun, ke laut 30–40 menit.",
        "Nusa Dua dan Jimbaran — median $248.500. Infrastruktur hotel, laut tenang, format keluarga, dan tingkat okupansi yang lebih mudah diprediksi.",
        "Pesisir barat — Nyanyi, Seseh, Cemagi. Median $276.500: titik masuk termurah ke area dekat laut dan pertumbuhan harga tanah tercepat dalam beberapa tahun terakhir.",
        "Sanur dan Umalas — $207.500 dan $255.000. Area tenang untuk tinggal, dekat sekolah dan klinik; sewa harian lebih lemah, tetapi sewa bulanan stabil."
      ]
    },
    {
      "heading": "Cara orang asing membeli vila di Bali",
      "paragraphs": [
        "Kepemilikan tanah pribadi penuh (Hak Milik, freehold) tidak tersedia bagi orang asing menurut hukum Indonesia. Ada tiga jalur yang benar-benar dipakai. Leasehold (Hak Sewa) — hak pakai untuk jangka waktu tetap dengan opsi perpanjangan: pada 161 vila di katalog, masa berlakunya 26–30 tahun, pada 98 — hingga 25 tahun, pada 85 — 31 tahun ke atas. Hak Pakai — hak penggunaan untuk residen dengan KITAS, siklus 30+30+20 tahun. PT PMA dengan HGB setelahnya — jalur untuk mereka yang menjadikan properti sebagai bisnis: beberapa unit atau penyewaan resmi.",
        "Transaksinya sendiri mengikuti satu skema: pilih properti dan reservasi dengan deposit, lalu legal due diligence (sertifikat tanah, zonasi, izin, beban), perjanjian di hadapan notaris PPAT, pembayaran sesuai jadwal, registrasi, dan serah terima properti. Transaksi jarak jauh juga biasa dilakukan — dengan surat kuasa, tetapi pemeriksaan tetap sebaiknya ditangani pengacara Anda sendiri, bukan pengacara penjual.",
        "Biaya wajibnya: PPh 2,5% dari nilai transaksi dibayar penjual, BPHTB hingga 5% — pembeli saat pengurusan hak, PPN dalam harga properti baru secara efektif 11%. Tarif pasti tergantung kabupaten dan status penjual, jadi total perhitungan akhir sebaiknya dikonfirmasi dengan notaris sebelum membayar deposit."
      ]
    },
    {
      "heading": "Apa yang harus dicek sebelum membeli",
      "paragraphs": [
        "Sebagian besar masalah di Bali muncul bukan karena harga, tetapi karena dokumen. Checklist minimum:"
      ],
      "bullets": [
        "Zonasi lahan (RDTR dan warna tanah) — di tanah kuning residensial, sewa harian untuk turis adalah ilegal.",
        "Sisa masa leasehold dan syarat perpanjangan: apakah harga siklus kedua sudah ditetapkan dalam perjanjian atau akan ditentukan mengikuti pasar setelah 25 tahun.",
        "Izin PBG dan SLF — tanpa ini rumah yang sudah dibangun belum legal.",
        "Siapa pemilik tanahnya, apakah ada agunan, sengketa waris, atau penyewa kedua.",
        "Riwayat developer: proyek yang sudah diserahterimakan, kepatuhan terhadap jadwal, dan apa yang terjadi dengan dana jika pembangunan berhenti.",
        "Jadwal pembayaran dan denda keterlambatan serah terima — untuk kedua pihak.",
        "Sambungan air dan listrik serta daya riil — di Bukit ini lebih sering menjadi masalah daripada sekadar formalitas."
      ]
    },
    {
      "heading": "Sewa, hasil investasi, dan biaya operasional",
      "paragraphs": [
        "Sewa bulanan memberi dasar hitung yang jelas: median di katalog — $2.585 di Berawa, $2.113 di Canggu, $1.608 di Bukit, dan $1.300 di Ubud. Sewa harian pada high season lebih tinggi, tetapi okupansinya juga naik turun: Desember–Maret dan Juli–Agustus memberi puncak, April dan Oktober — penurunan.",
        "Imbal hasil bersih yang realistis untuk vila yang dikelola operator — 8–12% per tahun dengan okupansi 70–80%. Angka 10–15% yang diklaim developer hampir selalu dihitung dari pendapatan kotor pada bulan puncak. Sebelum menghitung payback, kurangi komisi perusahaan pengelola 15–25%, biaya operasional (kolam, taman, listrik, kebersihan) — 5–8% dari pendapatan, pajak sewa, dan amortisasi leasehold: semakin dekat ke akhir masa berlaku, semakin murah properti saat dijual kembali."
      ]
    }
  ],
  "priceTable": {
    "caption": "Harga vila di Bali berdasarkan jumlah kamar tidur",
    "columns": [
      "Kamar tidur",
      "Luas bangunan",
      "Harga tipikal",
      "Median"
    ],
    "rows": [
      [
        "1 kamar tidur",
        "72 m²",
        "$127.000 – $285.000",
        "$188.000"
      ],
      [
        "2 kamar tidur",
        "110 m²",
        "$185.000 – $510.000",
        "$320.000"
      ],
      [
        "3 kamar tidur",
        "193 m²",
        "$300.000 – $781.000",
        "$473.700"
      ],
      [
        "4+ kamar tidur",
        "310 m²",
        "$477.000 – $1.850.000",
        "$869.800"
      ]
    ],
    "note": "Rentang — persentil ke-10 dan ke-90 untuk 357 vila dengan harga tercantum. Data katalog, diperbarui bersama price list developer."
  },
  "faqExtra": [
    {
      "q": "Mana yang lebih menguntungkan — leasehold atau freehold?",
      "a": "Freehold (Hak Milik) tidak tersedia bagi orang asing, jadi pilihan riilnya adalah antara leasehold, Hak Pakai, dan kepemilikan melalui PT PMA. Leasehold lebih murah saat masuk dan lebih sederhana dalam pengurusan, tetapi properti ikut terdepresiasi seiring berjalannya masa hak. PT PMA lebih mahal dalam biaya pemeliharaan (pajak perusahaan, pelaporan), tetapi haknya lebih panjang dan properti bisa disewakan secara legal sebagai bisnis."
    },
    {
      "q": "Apa yang terjadi dengan vila setelah masa leasehold berakhir?",
      "a": "Hak atas tanah dan semua bangunan yang ada di atasnya kembali ke pemilik tanah jika masa berlakunya tidak diperpanjang. Karena itu, syarat perpanjangan adalah poin kunci dalam perjanjian: dalam skema yang baik, harga dan mekanisme siklus kedua sudah ditetapkan sejak awal, dalam skema yang buruk — pemilik akan menyebut harga mengikuti pasar. Perpanjangan biasanya diurus lebih awal, bukan pada tahun terakhir."
    },
    {
      "q": "Apakah bisa membeli vila dengan cicilan?",
      "a": "Pada tahap pembangunan ini adalah praktik standar: uang muka pertama biasanya 30–50%, sisanya dibagi per tahap sampai serah terima. KPR untuk orang asing dalam bentuk yang umum tidak ada di Bali — cicilan diberikan oleh developer sendiri, biasanya tanpa bunga selama masa pembangunan. Untuk properti siap huni, skema cicilan lebih jarang dan jangka waktunya lebih pendek."
    },
    {
      "q": "Berapa biaya operasional vila di Bali?",
      "a": "Patokannya — 5–8% dari pendapatan sewa jika vila disewakan, atau $300–$700 per bulan untuk rumah dengan kolam renang jika ditempati sendiri: listrik, air, perawatan kolam, tukang kebun, kebersihan, internet. Di luar itu ada pajak bumi dan bangunan PBB serta komisi perusahaan pengelola 15–25% jika properti disewakan."
    },
    {
      "q": "Apa bedanya vila di kompleks dengan vila berdiri sendiri?",
      "a": "Vila di kompleks berbagi area, keamanan, perawatan, dan sering kali juga perusahaan pengelola dengan tetangga — ini lebih murah dalam operasional dan lebih mudah disewakan, tetapi ada service charge dan aturan kompleks. Vila berdiri sendiri memberi privasi lebih tinggi dan kebebasan lebih besar untuk renovasi, tetapi seluruh perawatan dan pencarian penyewa menjadi tanggung jawab Anda."
    },
    {
      "q": "Apakah bisa membeli vila dari jarak jauh tanpa datang ke Bali?",
      "a": "Ya, transaksi rutin dilakukan dengan surat kuasa: viewing lewat video, dokumen melalui notaris PPAT, pembayaran lewat transfer bank. Ada satu hal yang krusial — legal due diligence dan serah terima harus dilakukan oleh pengacara independen Anda atau pihak yang Anda percaya di lokasi, bukan perwakilan penjual."
    }
  ]
}

export default copy
