// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/villas/ru.ts (Dutch).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Wat kost een villa op Bali",
      "paragraphs": [
        "In de catalogus staan 358 villa’s te koop van projectontwikkelaars en particuliere eigenaren. De mediaanprijs is $350.000, en dat is een eerlijke middenwaarde van de markt, geen etalagecijfer: acht van de tien objecten vallen in de bandbreedte van $169.000 tot $850.000. De ondergrens ligt rond $80.000 voor een compacte villa met 1 slaapkamer landinwaarts, de bovengrens op $6,5 mln voor een mansion aan de eerste oceaanlijn.",
        "De prijs wordt door drie zaken bepaald: het aantal slaapkamers, de locatie en de bouwfase. Slaapkamers geven de meest voorspelbare stap — elke volgende is ongeveer anderhalf keer duurder dan de vorige, omdat daarmee zowel de woonoppervlakte als het perceel meegroeien."
      ]
    },
    {
      "heading": "Nieuwbouw of instapklare woning",
      "paragraphs": [
        "Van de 358 villa’s zijn er 251 in aanbouw en 101 al opgeleverd. Een object in aanbouw kost merkbaar minder dan een instapklare villa: de koper neemt het risico op de oplevertermijn over en krijgt daarvoor korting, plus gespreide betaling tijdens de bouw — de eerste aanbetaling is meestal 30–50%, het restant wordt verdeeld over de bouwfasen. Een instapklare villa is duurder, maar die kunt u ter plekke bekijken, de afwerkingskwaliteit controleren en direct verhuren.",
        "De mediaanprijs per vierkante meter op het eiland ligt tussen $2.000 en $3.300, afhankelijk van de locatie. Het goedkoopst is de m² in Ubud en aan de westkust, het duurst op de kliffen van Bukit en in Berawa. Objecten vergelijkt u het best op prijs per m²: twee huizen met hetzelfde prijskaartje kunnen qua oppervlakte twee keer zo groot verschillen."
      ]
    },
    {
      "heading": "Waar een villa kopen op Bali: regio’s en prijzen",
      "paragraphs": [
        "Het eiland is compact — van Canggu naar Bukit is het 1 tot 1,5 uur rijden — maar de deelmarkten per regio gedragen zich verschillend. De mediaanprijzen in de catalogus zien er als volgt uit:"
      ],
      "bullets": [
        "Canggu — Berawa, Batu Bolong, Pererenan. Villa’s met 2 slaapkamers $330.000–$390.000, villa’s met 3 slaapkamers in Pererenan vanaf $649.000. De dichtste huurmarkt: surfen, cafés en coworkings, maar ook de hoogste concurrentie om huurders.",
        "Bukit — Uluwatu, Pandawa, Melasti, Ungasan. Mediaan vanaf $270.000 in Pandawa tot $560.000 op de kliffen. Villa’s met uitzicht, premium segment, sterk hoogseizoen en een duidelijke terugval in het laagseizoen.",
        "Ubud — mediaan $310.000, villa’s met 1 slaapkamer vanaf $172.000. Jungle en rijstterrassen, het hele jaar vraag naar langetermijnverhuur, 30–40 minuten van de oceaan.",
        "Nusa Dua en Jimbaran — mediaan $248.500. Hotelfaciliteiten, rustige zee, gezinsgericht profiel en voorspelbare bezetting.",
        "Westkust — Nyanyi, Seseh, Cemagi. Mediaan $276.500: de goedkoopste instap richting oceaan en de snelste stijging van grondprijzen in de afgelopen jaren.",
        "Sanur en Umalas — $207.500 en $255.000. Rustige woonwijken, scholen en klinieken dichtbij; dagverhuur is zwakker, maar maandverhuur stabieler."
      ]
    },
    {
      "heading": "Hoe een buitenlander een villa op Bali kan kopen",
      "paragraphs": [
        "Volledig particulier grondbezit (Hak Milik, freehold) is voor buitenlanders volgens de Indonesische wet niet beschikbaar. Er zijn drie werkbare routes. Leasehold (Hak Sewa) — gebruiksrecht voor een vaste termijn met verlengingsoptie: bij 161 villa’s in de catalogus is de looptijd 26–30 jaar, bij 98 tot 25 jaar, bij 85 vanaf 31 jaar en langer. Hak Pakai — gebruiksrecht voor een resident met KITAS, cyclus 30+30+20 jaar. PT PMA met vervolgens HGB — de route voor wie vastgoed als bedrijf ziet: meerdere objecten of officiële verhuur.",
        "De transactie zelf verloopt volgens één vast schema: selectie en reservering met een aanbetaling, daarna juridische controle (grondcertificaat, zoning, vergunningen, lasten), contract bij de PPAT-notaris, betaling volgens schema, registratie en oplevering van het object. Op afstand kan de transactie ook worden uitgevoerd — via volmacht, maar de controle laat u beter doen door uw eigen jurist en niet door de jurist van de verkoper.",
        "Aan verplichte betalingen geldt: PPh 2,5% van de transactiewaarde betaalt de verkoper, BPHTB tot 5% betaalt de koper bij de registratie van de rechten, btw in de prijs van nieuwbouw is effectief 11%. De exacte tarieven hangen af van het kabupaten en de status van de verkoper, dus controleer de eindbegroting met de notaris voordat u de aanbetaling doet."
      ]
    },
    {
      "heading": "Wat u vóór aankoop moet controleren",
      "paragraphs": [
        "De meeste problemen op Bali ontstaan niet door de prijs, maar door de documenten. Minimale checklist:"
      ],
      "bullets": [
        "Zoning van het perceel (RDTR en de kleur van de grond) — op gele woongrond is kortetermijnverhuur aan toeristen niet toegestaan.",
        "De leasehold-termijn en de verlengingsvoorwaarden: staat de prijs van de tweede cyclus in het contract vast of wordt die over 25 jaar tegen marktprijs bepaald.",
        "Vergunningen PBG en SLF — zonder die is een gebouwd huis niet gelegaliseerd.",
        "Wie de grondeigenaar is en of er geen pandrecht, erfenisgeschil of tweede huurder is.",
        "De historie van de projectontwikkelaar: opgeleverde objecten, naleving van termijnen en wat er met het geld gebeurt als de bouw stilvalt.",
        "Het betalingsschema en boetes bij te late oplevering — voor beide partijen.",
        "Aansluiting op water en elektriciteit en het werkelijke vermogen — op Bukit is dit vaker een probleem dan een formaliteit."
      ]
    },
    {
      "heading": "Verhuur, rendement en onderhoud",
      "paragraphs": [
        "Maandverhuur geeft een duidelijke basis voor de berekening: de mediaan in de catalogus is $2.585 in Berawa, $2.113 in Canggu, $1.608 op Bukit en $1.300 in Ubud. Dagverhuur ligt in het hoogseizoen hoger, maar de bezetting schommelt ook sterker: december–maart en juli–augustus geven de piek, april en oktober de terugval.",
        "Een realistisch netto rendement van een villa onder beheer is 8–12% per jaar bij een bezetting van 70–80%. De 10–15% die projectontwikkelaars noemen, wordt bijna altijd berekend op basis van de brutoumszet in de piekmaand. Voordat u de terugverdientijd berekent, trekt u de commissie van de beheermaatschappij 15–25% af, het onderhoud (zwembad, tuin, elektriciteit, schoonmaak) — 5–8% van de omzet, de huurbelasting en de afschrijving van de leasehold: hoe dichter het einde van de looptijd, hoe goedkoper het object bij doorverkoop."
      ]
    }
  ],
  "priceTable": {
    "caption": "Villa prijzen op Bali naar aantal slaapkamers",
    "columns": [
      "Slaapkamers",
      "Woonoppervlakte",
      "Gebruikelijke prijs",
      "Mediaan"
    ],
    "rows": [
      [
        "1 slaapkamer",
        "72 m²",
        "$127.000 – $285.000",
        "$188.000"
      ],
      [
        "2 slaapkamers",
        "110 m²",
        "$185.000 – $510.000",
        "$320.000"
      ],
      [
        "3 slaapkamers",
        "193 m²",
        "$300.000 – $781.000",
        "$473.700"
      ],
      [
        "4+ slaapkamers",
        "310 m²",
        "$477.000 – $1.850.000",
        "$869.800"
      ]
    ],
    "note": "De bandbreedte is het 10e en 90e percentiel van 357 villa’s met vermelde prijs. Catalogusdata, bijgewerkt tegelijk met de prijslijsten van projectontwikkelaars."
  },
  "faqExtra": [
    {
      "q": "Wat is gunstiger — leasehold of freehold?",
      "a": "Freehold (Hak Milik) is niet beschikbaar voor buitenlanders, dus in de praktijk gaat de keuze tussen leasehold, Hak Pakai en eigendom via PT PMA. Leasehold is goedkoper bij instap en eenvoudiger in de afhandeling, maar het object schrijft af naarmate de looptijd korter wordt. PT PMA is duurder in onderhoud (vennootschapsbelasting, rapportage), maar de rechten lopen langer en het vastgoed kan legaal als bedrijf worden verhuurd."
    },
    {
      "q": "Wat gebeurt er met de villa na afloop van de leasehold?",
      "a": "De rechten op de grond en alles wat erop is gebouwd gaan terug naar de grondeigenaar als de termijn niet wordt verlengd. Daarom is de verlengingsclausule een kernpunt van het contract: in een goede variant liggen prijs en procedure van de tweede cyclus vooraf vast, in een slechte noemt de eigenaar later een marktprijs. Verlenging wordt meestal ruim van tevoren geregeld en niet pas in het laatste jaar."
    },
    {
      "q": "Kan ik een villa in termijnen kopen?",
      "a": "In de bouwfase is dat standaard: de eerste aanbetaling is meestal 30–50%, het restant wordt in fasen verdeeld tot aan oplevering. Hypotheken voor buitenlanders in de gebruikelijke vorm bestaan op Bali niet — de termijnenregeling wordt door de projectontwikkelaar zelf gegeven, doorgaans renteloos voor de duur van de bouw. Bij instapklare objecten komt gespreide betaling minder vaak voor en voor een kortere termijn."
    },
    {
      "q": "Wat kost het onderhoud van een villa op Bali?",
      "a": "Reken op 5–8% van de huuropbrengst als de villa wordt verhuurd, of $300–$700 per maand voor een huis met zwembad bij eigen bewoning: elektriciteit, water, zwembadonderhoud, tuinman, schoonmaak, internet. Apart komen daar nog de belasting op grond en gebouw PBB en de commissie van de beheermaatschappij 15–25% bij, als het object in de verhuur zit."
    },
    {
      "q": "Waarin verschilt een villa in een complex van een vrijstaande villa?",
      "a": "Een villa in een complex deelt terrein, beveiliging, onderhoud en vaak ook de beheermaatschappij met buren — dat is goedkoper in onderhoud en eenvoudiger in de verhuur, maar er komt een service charge en er gelden regels van het complex. Een vrijstaande villa biedt meer privacy en vrijheid voor verbouwingen, maar al het onderhoud en het vinden van huurders komt voor uw rekening."
    },
    {
      "q": "Kan ik een villa op afstand kopen, zonder naar Bali te komen?",
      "a": "Ja, transacties worden regelmatig via volmacht uitgevoerd: bezichtiging per video, documenten via de PPAT-notaris, betaling per bankoverschrijving. Eén punt is cruciaal — de juridische controle en oplevering moeten worden gedaan door uw onafhankelijke jurist of vertrouwenspersoon ter plaatse, niet door een vertegenwoordiger van de verkoper."
    }
  ]
}

export default copy
