// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/villas/ru.ts (Polish).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Ile kosztuje willa na Bali",
      "paragraphs": [
        "W katalogu jest 358 willi na sprzedaż od deweloperów i właścicieli. Mediana ceny to $350,000 i jest to uczciwy środek rynku, a nie liczba z witryny: osiem na dziesięć ofert mieści się w przedziale od $169,000 do $850,000. Dolna granica to około $80,000 za kompaktową willę z jedną sypialnią w głębi wyspy, górna — $6,5 mln za rezydencję w pierwszej linii od oceanu.",
        "Cenę kształtują trzy rzeczy: liczba sypialni, lokalizacja i etap gotowości. Sypialnie dają najbardziej przewidywalny skok — każda kolejna jest mniej więcej półtora raza droższa od poprzedniej, ponieważ wraz z nią rosną zarówno powierzchnia domu, jak i działki."
      ]
    },
    {
      "heading": "Budowa czy gotowy dom",
      "paragraphs": [
        "Spośród 358 willi 251 jest w budowie, a 101 zostało już oddanych. Nieruchomość w budowie kosztuje wyraźnie mniej niż gotowa: kupujący bierze na siebie ryzyko terminów i w zamian dostaje rabat, a także płatność ratalną na okres budowy — pierwsza wpłata najczęściej wynosi 30–50%, a reszta jest podzielona na etapy prac. Gotowa willa jest droższa, ale można ją obejrzeć na żywo, sprawdzić jakość wykończenia i od razu przeznaczyć na wynajem.",
        "Mediana ceny metra kwadratowego na wyspie wynosi od $2,000 do $3,300 w zależności od lokalizacji. Najtańszy metr jest w Ubud i na zachodnim wybrzeżu, najdroższy — na klifach Bukit i w Berawa. Oferty najlepiej porównywać właśnie po cenie za metr: dwa domy z taką samą ceną mogą różnić się powierzchnią dwukrotnie."
      ]
    },
    {
      "heading": "Gdzie kupić willę na Bali: lokalizacje i ceny",
      "paragraphs": [
        "Wyspa jest kompaktowa — z Canggu na Bukit jedzie się godzinę–półtorej — ale rynki w poszczególnych rejonach zachowują się różnie. Mediany cen w katalogu wyglądają tak:"
      ],
      "bullets": [
        "Canggu — Berawa, Batu Bolong, Pererenan. Wille z dwiema sypialniami $330,000–$390,000, z trzema sypialniami w Pererenan — od $649,000. Najgęstszy rynek najmu: surfing, kawiarnie i coworkingi, ale też najwyższa konkurencja o najemcę.",
        "Bukit — Uluwatu, Pandawa, Melasti, Ungasan. Mediana od $270,000 w Pandawa do $560,000 na klifach. Wille widokowe, segment premium, mocny wysoki sezon i wyraźny spadek w niskim.",
        "Ubud — mediana $310,000, wille z jedną sypialnią od $172,000. Dżungla i tarasy ryżowe, popyt na wynajem długoterminowy przez cały rok, do oceanu 30–40 minut.",
        "Nusa Dua i Jimbaran — mediana $248,500. Infrastruktura hotelowa, spokojne morze, rodzinny charakter i przewidywalne obłożenie.",
        "Zachodnie wybrzeże — Nyanyi, Seseh, Cemagi. Mediana $276,500: najtańsze wejście na rynek przy oceanie i najszybszy wzrost cen ziemi w ostatnich latach.",
        "Sanur i Umalas — $207,500 i $255,000. Spokojne rejony do życia, szkoły i kliniki w pobliżu; najem krótkoterminowy jest słabszy, za to miesięczny stabilny."
      ]
    },
    {
      "heading": "Jak cudzoziemiec może kupić willę na Bali",
      "paragraphs": [
        "Pełna prywatna własność gruntu (Hak Milik, freehold) jest dla cudzoziemca niedostępna zgodnie z prawem indonezyjskim. Są trzy praktyczne drogi. Leasehold (Hak Sewa) — prawo użytkowania na określony czas z opcją przedłużenia: w przypadku 161 willi w katalogu okres wynosi 26–30 lat, w przypadku 98 — do 25 lat, a w przypadku 85 — od 31 lat wzwyż. Hak Pakai — prawo użytkowania dla rezydenta z KITAS, cykl 30+30+20 lat. PT PMA z późniejszym HGB — rozwiązanie dla tych, dla których nieruchomość jest biznesem: kilka obiektów albo oficjalny wynajem.",
        "Sama transakcja przebiega według jednego schematu: wybór i rezerwacja z depozytem, następnie due diligence prawne (certyfikat gruntu, zoning, pozwolenia, obciążenia), umowa u notariusza PPAT, płatność według harmonogramu, rejestracja i odbiór nieruchomości. Transakcję można przeprowadzić także zdalnie — przez pełnomocnictwo, ale weryfikację warto zlecić swojemu prawnikowi, a nie prawnikowi sprzedającego.",
        "Obowiązkowe opłaty są następujące: PPh 2,5% od ceny transakcji płaci sprzedający, BPHTB do 5% — kupujący przy rejestracji praw, VAT w cenie nowej nieruchomości efektywnie wynosi 11%. Dokładne stawki zależą od kabupatenu i statusu sprzedającego, dlatego końcowy kosztorys warto potwierdzić u notariusza przed wpłatą depozytu."
      ]
    },
    {
      "heading": "Co sprawdzić przed zakupem",
      "paragraphs": [
        "Większość problemów na Bali wynika nie z ceny, lecz z dokumentów. Minimalna lista kontrolna:"
      ],
      "bullets": [
        "Zoning działki (RDTR i kolor gruntu) — na żółtym gruncie mieszkaniowym krótkoterminowy wynajem turystom jest nielegalny.",
        "Okres leaseholdu i warunki przedłużenia: czy cena drugiego cyklu jest zapisana w umowie, czy zostanie podana według rynku za 25 lat.",
        "Pozwolenia PBG i SLF — bez nich wybudowany dom nie jest zalegalizowany.",
        "Kto jest właścicielem gruntu, czy nie ma zastawu, sporu spadkowego albo drugiego najemcy.",
        "Historia dewelopera: oddane inwestycje, dotrzymywanie terminów i co dzieje się z pieniędzmi, jeśli budowa stanie.",
        "Harmonogram płatności i kary za opóźnienie oddania — po obu stronach.",
        "Podłączenie wody i prądu oraz rzeczywista moc — na Bukit to częściej problem niż formalność."
      ]
    },
    {
      "heading": "Wynajem, rentowność i koszty utrzymania",
      "paragraphs": [
        "Wynajem miesięczny daje jasny punkt odniesienia do kalkulacji: mediana w katalogu to $2,585 w Berawa, $2,113 w Canggu, $1,608 na Bukit i $1,300 w Ubud. Wynajem krótkoterminowy w wysokim sezonie jest wyższy, ale obłożenie też się waha: grudzień–marzec i lipiec–sierpień dają szczyt, kwiecień i październik — spadek.",
        "Realistyczna rentowność netto willi w zarządzaniu to 8–12% rocznie przy obłożeniu 70–80%. Deklarowane przez deweloperów 10–15% prawie zawsze liczy się od przychodu brutto w szczytowym miesiącu. Zanim zaczniesz liczyć zwrot, odejmij prowizję firmy zarządzającej 15–25%, utrzymanie (basen, ogród, prąd, sprzątanie) — 5–8% przychodu, podatek od najmu i amortyzację leaseholdu: im bliżej końca okresu, tym tańsza nieruchomość przy odsprzedaży."
      ]
    }
  ],
  "priceTable": {
    "caption": "Ceny willi na Bali według liczby sypialni",
    "columns": [
      "Sypialnie",
      "Powierzchnia domu",
      "Typowa cena",
      "Mediana"
    ],
    "rows": [
      [
        "1 sypialnia",
        "72 m²",
        "$127,000 – $285,000",
        "$188,000"
      ],
      [
        "2 sypialnie",
        "110 m²",
        "$185,000 – $510,000",
        "$320,000"
      ],
      [
        "3 sypialnie",
        "193 m²",
        "$300,000 – $781,000",
        "$473,700"
      ],
      [
        "4+ sypialnie",
        "310 m²",
        "$477,000 – $1,850,000",
        "$869,800"
      ]
    ],
    "note": "Przedział — 10. i 90. percentyl dla 357 willi z podaną ceną. Dane z katalogu, aktualizowane wraz z cennikami deweloperów."
  },
  "faqExtra": [
    {
      "q": "Co jest korzystniejsze — leasehold czy freehold?",
      "a": "Freehold (Hak Milik) jest niedostępny dla cudzoziemca, dlatego realny wybór dotyczy leaseholdu, Hak Pakai i posiadania przez PT PMA. Leasehold jest tańszy na wejściu i prostszy formalnie, ale nieruchomość amortyzuje się wraz z upływem okresu. PT PMA jest droższe w utrzymaniu (podatek korporacyjny, sprawozdawczość), za to prawa są dłuższe i nieruchomość można legalnie wynajmować jako biznes."
    },
    {
      "q": "Co stanie się z willą po zakończeniu leaseholdu?",
      "a": "Prawa do gruntu i wszystkiego, co zostało zbudowane, wracają do właściciela gruntu, jeśli okres nie zostanie przedłużony. Dlatego warunek przedłużenia to kluczowy punkt umowy: w dobrym wariancie cena i zasady drugiego cyklu są ustalone z góry, w słabym — właściciel poda cenę rynkową. Przedłużenie zwykle załatwia się z wyprzedzeniem, a nie w ostatnim roku."
    },
    {
      "q": "Czy można kupić willę na raty?",
      "a": "Na etapie budowy to standard: pierwsza wpłata zwykle wynosi 30–50%, a reszta jest dzielona na etapy do momentu oddania. Kredytu hipotecznego dla cudzoziemca w typowej formie na Bali nie ma — raty daje sam deweloper, z reguły bez odsetek na okres budowy. W przypadku gotowych obiektów raty spotyka się rzadziej i na krótszy okres."
    },
    {
      "q": "Ile kosztuje utrzymanie willi na Bali?",
      "a": "Punkt odniesienia to 5–8% przychodu z najmu, jeśli willa jest wynajmowana, albo $300–$700 miesięcznie dla domu z basenem przy użytkowaniu własnym: prąd, woda, serwis basenu, ogrodnik, sprzątanie, internet. Osobno liczy się podatek od gruntu i budynku PBB oraz prowizję firmy zarządzającej 15–25%, jeśli obiekt jest wynajmowany."
    },
    {
      "q": "Czym różni się willa w kompleksie od wolnostojącej?",
      "a": "Willa w kompleksie dzieli z sąsiadami teren, ochronę, serwis i często firmę zarządzającą — to obniża koszty utrzymania i ułatwia wynajem, ale pojawia się service charge i regulamin kompleksu. Wolnostojąca willa daje więcej prywatności i swobody przebudowy, ale całe utrzymanie i szukanie najemców spada na właściciela."
    },
    {
      "q": "Czy można kupić willę zdalnie, bez przyjazdu na Bali?",
      "a": "Tak, transakcje regularnie przeprowadza się przez pełnomocnictwo: prezentacja wideo, dokumenty przez notariusza PPAT, płatność przelewem bankowym. Kluczowa jest jedna rzecz — due diligence prawne i odbiór powinien zrobić Twój niezależny prawnik albo zaufana osoba na miejscu, a nie przedstawiciel sprzedającego."
    }
  ]
}

export default copy
