// «How we calculate» copy for the non-RU/EN locales. Same shape and numbers
// as the RU/EN copy in MethodologyView.tsx.

import Link from 'next/link'
import { A } from '../MarketShell'
import type { MethodCopy, MethodCtx } from '../MethodologyView'
import { IN_ENGLISH, type IntlLang } from './types'
import { plPlural, ukPlural } from './plural'

const en = (c: MethodCtx, l: IntlLang) => (c.guidesInEnglish ? IN_ENGLISH[l] : '')

export const METHOD_INTL: Record<IntlLang, (c: MethodCtx) => MethodCopy> = {
  id: c => ({
    metaTitle: 'Cara Kami Menghitung: Sumber & Metode Data Properti Bali',
    description: 'Dari mana Balinsky mendapatkan harga, tarif sewa, dan imbal hasil di Bali: sumber, definisi, model imbal hasil, batasan, dan cara kami memperbaiki kesalahan.',
    crumb: 'Cara kami menghitung',
    h1: 'Cara kami menghitung',
    lead: <>Setiap angka di situs ini — harga per m² dibanding kawasan, tarif sewa di sekitar, imbal hasil — dihitung dengan metode terbuka. Halaman ini menjelaskan asal data, arti setiap angka, dan di mana batas datanya.</>,
    updated: `Data diperbarui: ${c.when}.`,
    sourcesH2: 'Asal data',
    sourceCols: ['Sumber', 'Yang kami pakai', 'Jumlah'],
    sourceRows: [
      ['Katalog Balinsky', 'Harga penawaran, luas bangunan, kamar tidur, masa sewa, status pembangunan dan izin — sesuai keterangan pengembang', `${c.n(c.T.villas)} vila, ${c.n(c.T.apartments)} apartemen`],
      ['Basis data sewa harian (estatemarket.io)', 'Tarif per malam, tipe properti, kamar tidur, koordinat', `${c.n(c.T.rentals)} properti di sekitar kawasan katalog`],
      ['Listing sewa jangka panjang', 'Sewa bulanan, tipe, kamar tidur, kawasan', `${c.n(c.M.n)} listing, ${c.from} — ${c.to}`],
      ['Statistik resmi dan peraturan', 'Kedatangan wisatawan dan hunian hotel (BPS Bali), hak atas tanah (PP 18/2021), pajak', 'Ditautkan di setiap artikel'],
    ],
    defsH2: 'Arti angka-angka',
    defs: [
      ['Median', 'Nilai tengah: separuh properti lebih murah, separuh lebih mahal. Satu vila seharga jutaan dolar tidak menggesernya, karena itu kami memakai median, bukan rata-rata.'],
      ['Separuh tengah (persentil 25–75)', 'Rentang tempat separuh harga yang di tengah berada. Menunjukkan seberapa beragam harga di satu kawasan.'],
      ['Harga per m²', 'Harga penawaran dibagi luas bangunan di listing. Tanah, teras, dan kolam renang tidak termasuk.'],
      ['Indikatif (*)', `Kurang dari ${c.N} pengamatan. Angka seperti ini adalah pengamatan, bukan kesimpulan tentang kawasan.`],
      ['Kawasan properti sewa', 'Properti sewa harian dimasukkan ke kawasan listing katalog terdekat dalam radius 1,5 km. Yang lebih jauh tidak dihitung.'],
      ['Status PBG/SLF', 'Keterangan pengembang: persetujuan bangunan gedung (PBG), sertifikat laik fungsi (SLF), sedang diajukan, atau tidak ada data. Kami tidak mencocokkan nomornya dengan registri.'],
    ],
    yieldH2: 'Cara menghitung imbal hasil',
    yield: [
      'Ambil median tarif per malam vila serupa di sekitar (tipe dan jumlah kamar yang sama).',
      'Kalikan dengan 365 dan dengan tingkat hunian. Skenario dasar 65%, dengan 55% dan 75% di sampingnya. Data hunian di basis data tidak andal (tanggal kalender yang diblokir dihitung sebagai terisi), jadi kami memakai skenario, bukan “hunian aktual”.',
      'Kurangi biaya: komisi platform 15%, pengelolaan 20%, operasional 6%, pajak daerah atas akomodasi (PBJT) 10% — total 51% dari pendapatan kotor. Pajak penghasilan (10% untuk residen, hingga 20% untuk non-residen) dihitung terpisah karena bergantung pada status Anda.',
      'Bagi dengan harga beli. Hasilnya sebelum amortisasi leasehold: tanahnya disewa, dan haknya berakhir setelah 25–30 tahun.',
    ],
    yieldMore: <>Hasil per kawasan: <Link href={c.href.yield} className={A}>imbal hasil sewa vila di Bali per kawasan</Link>{en(c, 'id')}.</>,
    limitsH2: 'Yang tidak ditunjukkan data ini',
    limits: [
      'Harga transaksi. Harga ini tidak dipublikasikan di Bali; kami menampilkan harga penawaran.',
      'Seluruh pasar. Katalog berisi pengembang yang mendaftar di kami; properti bekas kurang terwakili.',
      'Keabsahan hukum. Kami menampilkan dokumen sesuai keterangan pengembang dan tidak mengesahkannya. Sebelum membayar, minta notaris PPAT atau pengacara memeriksa sertifikat dan izinnya.',
      'Masa depan. Harga dan sewa di masa lalu tidak menjamin masa depan.',
    ],
    updH2: 'Pembaruan dan koreksi',
    upd: [
      'Harga dan tarif dihitung ulang setiap bulan; tanggal perhitungan ada di setiap halaman data.',
      'Setiap listing dihitung dengan cara yang sama: pengembang tidak bisa memengaruhi angka untuk propertinya sendiri.',
      'Menemukan kesalahan pada harga, tanggal, atau status izin? Kirim pesan ke bot di Telegram — kesalahan yang terkonfirmasi kami perbaiki dan tanggalnya kami perbarui.',
    ],
    pagesH2: 'Di mana data ini ditampilkan',
    pages: [
      { t: 'Harga properti di Bali per kawasan', href: c.href.prices },
      { t: 'Berapa harga sewa di Bali', href: c.href.rent },
      { t: 'Investasi properti di Bali: imbal hasil per kawasan', href: c.href.invest },
      { t: 'Tentang Balinsky: apa yang kami periksa dan apa yang tidak', href: c.href.about },
    ],
    srcH2: 'Sumber eksternal',
    sources: [
      { label: 'estatemarket.io — data sewa harian di Bali', href: c.href.estatemarket },
      { label: 'BPS Bali: kedatangan wisatawan dan hunian hotel', href: c.href.bps },
      { label: 'BPS: kedatangan wisatawan mancanegara ke Bali per tahun', href: c.href.bpsArrivals },
      { label: 'Peraturan Pemerintah No. 18/2021 (hak atas tanah)', href: c.href.pp18 },
      { label: 'PwC Worldwide Tax Summaries: Indonesia', href: c.href.pwcTax },
    ],
  }),

  fr: c => ({
    metaTitle: 'Notre méthode : sources et calculs de nos données immobilières sur Bali',
    description: 'D’où viennent les prix, loyers et rendements de Balinsky pour Bali : sources, définitions, modèle de rendement, limites et correction des erreurs.',
    crumb: 'Notre méthode',
    h1: 'Notre méthode',
    lead: <>Chaque chiffre du site — prix au m² comparé au quartier, loyers des biens voisins, rendement — est calculé selon une méthode ouverte. Cette page explique d’où viennent les données, ce que signifie chaque indicateur et où se trouvent leurs limites.</>,
    updated: `Données mises à jour : ${c.when}.`,
    sourcesH2: 'D’où viennent les données',
    sourceCols: ['Source', 'Ce que nous utilisons', 'Volume'],
    sourceRows: [
      ['Catalogue Balinsky', 'Prix demandés, surface habitable, chambres, durée du bail, état d’avancement et permis — selon le promoteur', `${c.n(c.T.villas)} villas, ${c.n(c.T.apartments)} appartements`],
      ['Base de locations de vacances (estatemarket.io)', 'Tarifs à la nuit, type de bien, chambres, coordonnées', `${c.n(c.T.rentals)} biens près des quartiers du catalogue`],
      ['Annonces de location longue durée', 'Loyer mensuel, type, chambres, quartier', `${c.n(c.M.n)} annonces, ${c.from} — ${c.to}`],
      ['Statistiques officielles et lois', 'Arrivées et occupation hôtelière (BPS Bali), droits fonciers (PP 18/2021), fiscalité', 'Liens dans chaque article'],
    ],
    defsH2: 'Ce que signifient les indicateurs',
    defs: [
      ['Médiane', 'Le milieu de la série : la moitié des biens sont moins chers, l’autre moitié plus chers. Une villa à plusieurs millions ne la déplace pas, c’est pourquoi nous utilisons la médiane plutôt que la moyenne.'],
      ['Moitié centrale (25e–75e centile)', 'La fourchette qui contient la moitié centrale des prix. Elle montre à quel point les prix d’un quartier sont dispersés.'],
      ['Prix au m²', 'Prix demandé divisé par la surface habitable de l’annonce. Terrain, terrasse et piscine ne sont pas inclus.'],
      ['Indicatif (*)', `Moins de ${c.N} observations. Un tel chiffre est une observation, pas une conclusion sur le quartier.`],
      ['Quartier d’une location', 'Une location de vacances est rattachée au quartier du bien du catalogue le plus proche, dans un rayon de 1,5 km. Au-delà, elle n’est pas comptée.'],
      ['Statut PBG/SLF', 'Ce que déclare le promoteur : permis de construire (PBG), certificat de conformité (SLF), demande déposée ou aucune donnée. Nous ne vérifions pas les numéros dans le registre.'],
    ],
    yieldH2: 'Comment se calcule le rendement',
    yield: [
      'On prend le tarif médian à la nuit des villas similaires à proximité (même type, même nombre de chambres).',
      'On le multiplie par 365 et par le taux d’occupation. Le scénario de base est de 65 %, avec 55 % et 75 % en regard. Les données d’occupation de la base ne sont pas fiables (les dates bloquées du calendrier y comptent comme réservées), nous utilisons donc des scénarios plutôt qu’une « occupation réelle ».',
      'On déduit les coûts : commissions des plateformes 15 %, gestion 20 %, exploitation 6 %, taxe locale sur l’hébergement (PBJT) 10 % — soit 51 % du chiffre d’affaires brut. L’impôt sur le revenu (10 % pour un résident, jusqu’à 20 % pour un non-résident) s’y ajoute, car il dépend de votre statut.',
      'On divise par le prix d’achat. Le résultat s’entend avant amortissement du bail : le terrain est loué, et le droit prend fin au bout de 25 à 30 ans.',
    ],
    yieldMore: <>Résultats par quartier : <Link href={c.href.yield} className={A}>rendement locatif des villas à Bali par quartier</Link>{en(c, 'fr')}.</>,
    limitsH2: 'Ce que ces données ne montrent pas',
    limits: [
      'Les prix de transaction. Ils ne sont pas publiés à Bali ; nous montrons des prix demandés.',
      'Tout le marché. Le catalogue couvre les promoteurs qui publient chez nous ; la revente est sous-représentée.',
      'La validité juridique. Nous montrons les documents tels que déclarés par le promoteur, sans les certifier. Avant de payer, faites vérifier le titre et les permis par un notaire PPAT ou un avocat.',
      'L’avenir. Les loyers et prix passés ne garantissent pas ceux à venir.',
    ],
    updH2: 'Mises à jour et corrections',
    upd: [
      'Les prix et tarifs sont recalculés chaque mois ; la date de calcul figure sur chaque page de données.',
      'Tous les biens sont calculés de la même façon : un promoteur ne peut pas influencer les chiffres de son propre bien.',
      'Vous avez trouvé une erreur de prix, de date ou de statut de permis ? Écrivez au bot sur Telegram — les erreurs confirmées sont corrigées et la date mise à jour.',
    ],
    pagesH2: 'Où ces données apparaissent',
    pages: [
      { t: 'Prix de l’immobilier à Bali par quartier', href: c.href.prices },
      { t: 'Combien coûte un loyer à Bali', href: c.href.rent },
      { t: 'Investir dans l’immobilier à Bali : rendement par quartier', href: c.href.invest },
      { t: 'À propos de Balinsky : ce que nous vérifions et ce que nous ne vérifions pas', href: c.href.about },
    ],
    srcH2: 'Sources externes',
    sources: [
      { label: 'estatemarket.io — données de location de vacances à Bali', href: c.href.estatemarket },
      { label: 'BPS Bali : arrivées et occupation hôtelière', href: c.href.bps },
      { label: 'BPS : arrivées de touristes étrangers à Bali par année', href: c.href.bpsArrivals },
      { label: 'Règlement du gouvernement indonésien n° 18/2021 (droits fonciers)', href: c.href.pp18 },
      { label: 'PwC Worldwide Tax Summaries : Indonésie', href: c.href.pwcTax },
    ],
  }),

  de: c => ({
    metaTitle: 'So rechnen wir: Quellen und Methode unserer Bali-Immobiliendaten',
    description: 'Woher Balinskys Preise, Mieten und Renditen für Bali stammen: Quellen, Definitionen, Renditemodell, Grenzen und wie wir Fehler korrigieren.',
    crumb: 'So rechnen wir',
    h1: 'So rechnen wir',
    lead: <>Jede Zahl auf der Website — Preis pro m² im Vergleich zur Gegend, Mieten in der Nachbarschaft, Rendite — wird nach einer offenen Methode berechnet. Hier steht, woher die Daten kommen, was jede Kennzahl bedeutet und wo die Daten an Grenzen stoßen.</>,
    updated: `Daten aktualisiert: ${c.when}.`,
    sourcesH2: 'Woher die Daten kommen',
    sourceCols: ['Quelle', 'Was wir verwenden', 'Umfang'],
    sourceRows: [
      ['Balinsky-Katalog', 'Angebotspreise, Wohnfläche, Schlafzimmer, Pachtdauer, Bau- und Genehmigungsstatus — laut Bauträger', `${c.n(c.T.villas)} Villen, ${c.n(c.T.apartments)} Wohnungen`],
      ['Datenbank Ferienvermietung (estatemarket.io)', 'Nachtpreise, Objekttyp, Schlafzimmer, Koordinaten', `${c.n(c.T.rentals)} Objekte nahe den Katalog-Gegenden`],
      ['Langzeit-Mietangebote', 'Monatsmiete, Typ, Schlafzimmer, Gegend', `${c.n(c.M.n)} Angebote, ${c.from} — ${c.to}`],
      ['Amtliche Statistik und Gesetze', 'Ankünfte und Hotelauslastung (BPS Bali), Landrechte (PP 18/2021), Steuern', 'In jedem Artikel verlinkt'],
    ],
    defsH2: 'Was die Kennzahlen bedeuten',
    defs: [
      ['Median', 'Die Mitte der Reihe: Die Hälfte der Objekte ist günstiger, die Hälfte teurer. Eine einzelne Villa für mehrere Millionen verschiebt ihn nicht — deshalb verwenden wir den Median statt des Durchschnitts.'],
      ['Mittlere Hälfte (25.–75. Perzentil)', 'Die Spanne, in der die mittlere Hälfte der Preise liegt. Sie zeigt, wie unterschiedlich die Preise einer Gegend sind.'],
      ['Preis pro m²', 'Angebotspreis geteilt durch die Wohnfläche im Inserat. Grundstück, Terrasse und Pool zählen nicht mit.'],
      ['Richtwert (*)', `Weniger als ${c.N} Beobachtungen. Eine solche Zahl ist eine Beobachtung, keine Aussage über die Gegend.`],
      ['Gegend eines Mietobjekts', 'Ein Ferienobjekt wird der Gegend des nächstgelegenen Katalogobjekts im Umkreis von 1,5 km zugeordnet. Was weiter entfernt liegt, zählt nicht.'],
      ['Status PBG/SLF', 'Was der Bauträger angibt: Baugenehmigung (PBG), Nutzungsbescheinigung (SLF), Antrag gestellt oder keine Angabe. Die Nummern gleichen wir nicht mit dem Register ab.'],
    ],
    yieldH2: 'So wird die Rendite berechnet',
    yield: [
      'Wir nehmen den Median-Nachtpreis ähnlicher Villen in der Nähe (gleicher Typ, gleiche Zahl an Schlafzimmern).',
      'Wir multiplizieren ihn mit 365 und mit der Auslastung. Das Basisszenario sind 65 %, daneben 55 % und 75 %. Die Auslastungsdaten der Datenbank sind unzuverlässig (gesperrte Kalendertage zählen dort als gebucht), daher arbeiten wir mit Szenarien statt mit einer „tatsächlichen Auslastung“.',
      'Wir ziehen die Kosten ab: Plattformgebühren 15 %, Verwaltung 20 %, Betrieb 6 %, lokale Beherbergungssteuer (PBJT) 10 % — zusammen 51 % des Bruttoumsatzes. Die Einkommensteuer (10 % für Steuerinländer, bis zu 20 % für Steuerausländer) kommt hinzu, da sie von Ihrem Status abhängt.',
      'Wir teilen durch den Kaufpreis. Das Ergebnis gilt vor Abschreibung der Pacht: Das Land ist gepachtet, und das Recht endet nach 25–30 Jahren.',
    ],
    yieldMore: <>Ergebnisse nach Gegend: <Link href={c.href.yield} className={A}>Mietrendite von Villen auf Bali nach Gegend</Link>{en(c, 'de')}.</>,
    limitsH2: 'Was diese Daten nicht zeigen',
    limits: [
      'Kaufpreise. Sie werden auf Bali nicht veröffentlicht; wir zeigen Angebotspreise.',
      'Den ganzen Markt. Der Katalog umfasst Bauträger, die bei uns inserieren; Wiederverkäufe sind unterrepräsentiert.',
      'Die Rechtssicherheit. Wir zeigen Dokumente so, wie der Bauträger sie angibt, und beglaubigen sie nicht. Lassen Sie Titel und Genehmigungen vor der Zahlung von einem PPAT-Notar oder Anwalt prüfen.',
      'Die Zukunft. Vergangene Mieten und Preise garantieren keine künftigen.',
    ],
    updH2: 'Aktualisierungen und Korrekturen',
    upd: [
      'Preise und Mieten werden monatlich neu berechnet; das Berechnungsdatum steht auf jeder Datenseite.',
      'Jedes Objekt wird gleich berechnet: Ein Bauträger kann die Zahlen für sein eigenes Objekt nicht beeinflussen.',
      'Einen Fehler bei Preis, Datum oder Genehmigungsstatus gefunden? Schreiben Sie dem Bot auf Telegram — bestätigte Fehler korrigieren wir und aktualisieren das Datum.',
    ],
    pagesH2: 'Wo diese Daten erscheinen',
    pages: [
      { t: 'Immobilienpreise auf Bali nach Gegend', href: c.href.prices },
      { t: 'Was kostet Miete auf Bali', href: c.href.rent },
      { t: 'In Immobilien auf Bali investieren: Rendite nach Gegend', href: c.href.invest },
      { t: 'Über Balinsky: was wir prüfen und was nicht', href: c.href.about },
    ],
    srcH2: 'Externe Quellen',
    sources: [
      { label: 'estatemarket.io — Daten zur Ferienvermietung auf Bali', href: c.href.estatemarket },
      { label: 'BPS Bali: Ankünfte und Hotelauslastung', href: c.href.bps },
      { label: 'BPS: ausländische Ankünfte auf Bali nach Jahr', href: c.href.bpsArrivals },
      { label: 'Indonesische Regierungsverordnung Nr. 18/2021 (Landrechte)', href: c.href.pp18 },
      { label: 'PwC Worldwide Tax Summaries: Indonesien', href: c.href.pwcTax },
    ],
  }),

  zh: c => ({
    metaTitle: '我们如何计算：巴厘岛房产数据的来源与方法',
    description: 'Balinsky巴厘岛价格、租金和收益率数据的来源：数据来源、定义、收益率模型、局限，以及我们如何更正错误。',
    crumb: '我们如何计算',
    h1: '我们如何计算',
    lead: <>网站上的每个数字——与区域对比的每平方米价格、周边租金、收益率——都按公开的方法计算。本页说明数据从哪里来、每个指标是什么意思，以及数据的局限在哪里。</>,
    updated: `数据更新：${c.when}。`,
    sourcesH2: '数据从哪里来',
    sourceCols: ['来源', '我们使用什么', '数量'],
    sourceRows: [
      ['Balinsky目录', '挂牌价、居住面积、卧室、租赁年限、施工和许可证状态——以开发商提供的信息为准', `别墅${c.n(c.T.villas)}套，公寓${c.n(c.T.apartments)}套`],
      ['度假短租数据库（estatemarket.io）', '每晚价格、房产类型、卧室、坐标', `目录区域附近${c.n(c.T.rentals)}处房产`],
      ['长租房源', '月租、类型、卧室、区域', `${c.n(c.M.n)}条房源，${c.from} — ${c.to}`],
      ['官方统计和法规', '游客人数和酒店入住率（巴厘岛BPS）、土地权利（PP 18/2021）、税收', '每篇文章中附有链接'],
    ],
    defsH2: '指标的含义',
    defs: [
      ['中位数', '数列的中间值：一半房产更便宜，一半更贵。一套数百万美元的别墅不会让它变动，所以我们用中位数而不是平均数。'],
      ['中间一半（第25–75百分位）', '中间一半价格所在的区间，显示一个区域的价格差异有多大。'],
      ['每平方米价格', '挂牌价除以房源中的居住面积，不含土地、露台和泳池。'],
      ['仅供参考（*）', `观测值少于${c.N}个。这样的数字只是观察，不能作为对该区域的结论。`],
      ['短租房产所属区域', '短租房产归入1.5公里半径内最近的目录房源所在区域。更远的不计入。'],
      ['PBG/SLF状态', '开发商提供的信息：建筑许可（PBG）、使用合格证（SLF）、已提交申请或无数据。我们不与登记系统核对编号。'],
    ],
    yieldH2: '收益率如何计算',
    yield: [
      '取附近同类别墅（相同类型和卧室数量）的每晚中位价。',
      '乘以365和入住率。基准情景为65%，同时列出55%和75%。数据库中的入住率数据不可靠（会把日历上被屏蔽的日期算作已预订），所以我们使用情景，而不是“实际入住率”。',
      '扣除成本：平台佣金15%、管理费20%、运营6%、地方住宿税（PBJT）10%——合计占总收入的51%。所得税（居民10%，非居民最高20%）另算，因为取决于您的身份。',
      '除以购买价格。结果未计入租赁权摊销：土地是租来的，权利在25–30年后到期。',
    ],
    yieldMore: <>各区域结果见<Link href={c.href.yield} className={A}>巴厘岛各区域别墅租金收益率</Link>{en(c, 'zh')}。</>,
    limitsH2: '这些数据不能说明什么',
    limits: [
      '成交价格。巴厘岛不公开成交价；我们展示的是挂牌价。',
      '整个市场。目录中是在我们平台发布房源的开发商；二手房代表性不足。',
      '法律合规性。我们按开发商提供的信息展示文件，但不作认证。付款前请让PPAT公证人或律师核查产权证和许可证。',
      '未来。过去的租金和价格不能保证未来。',
    ],
    updH2: '更新与更正',
    upd: [
      '价格和租金每月重新计算；每个数据页面都注明计算日期。',
      '所有房源都用同样的方法计算：开发商无法影响自己房产的数字。',
      '发现价格、日期或许可证状态有误？请在Telegram上给机器人发消息——经确认的错误我们会更正并更新日期。',
    ],
    pagesH2: '这些数据出现在哪里',
    pages: [
      { t: '巴厘岛各区域房产价格', href: c.href.prices },
      { t: '巴厘岛租房多少钱', href: c.href.rent },
      { t: '巴厘岛房产投资：各区域收益率', href: c.href.invest },
      { t: '关于Balinsky：我们核查什么、不核查什么', href: c.href.about },
    ],
    srcH2: '外部来源',
    sources: [
      { label: 'estatemarket.io — 巴厘岛度假短租数据', href: c.href.estatemarket },
      { label: '巴厘岛BPS：游客人数和酒店入住率', href: c.href.bps },
      { label: 'BPS：历年赴巴厘岛外国游客人数', href: c.href.bpsArrivals },
      { label: '印度尼西亚政府条例2021年第18号（土地权利）', href: c.href.pp18 },
      { label: 'PwC Worldwide Tax Summaries：印度尼西亚', href: c.href.pwcTax },
    ],
  }),

  nl: c => ({
    metaTitle: 'Hoe we rekenen: bronnen en methode achter onze vastgoeddata over Bali',
    description: 'Waar de prijzen, huren en rendementen van Balinsky voor Bali vandaan komen: bronnen, definities, het rendementsmodel, beperkingen en hoe we fouten corrigeren.',
    crumb: 'Hoe we rekenen',
    h1: 'Hoe we rekenen',
    lead: <>Elk cijfer op de site — prijs per m² ten opzichte van het gebied, huren in de buurt, rendement — is berekend met een open methode. Hier leest u waar de data vandaan komt, wat elk cijfer betekent en waar de grenzen van de data liggen.</>,
    updated: `Data bijgewerkt: ${c.when}.`,
    sourcesH2: 'Waar de data vandaan komt',
    sourceCols: ['Bron', 'Wat we gebruiken', 'Omvang'],
    sourceRows: [
      ['Balinsky-catalogus', 'Vraagprijzen, woonoppervlakte, slaapkamers, pachttermijn, bouw- en vergunningsstatus — volgens de ontwikkelaar', `${c.n(c.T.villas)} villa’s, ${c.n(c.T.apartments)} appartementen`],
      ['Database vakantieverhuur (estatemarket.io)', 'Nachttarieven, type object, slaapkamers, coördinaten', `${c.n(c.T.rentals)} objecten rond de catalogusgebieden`],
      ['Advertenties langdurige verhuur', 'Maandhuur, type, slaapkamers, gebied', `${c.n(c.M.n)} advertenties, ${c.from} — ${c.to}`],
      ['Officiële statistiek en wetgeving', 'Aankomsten en hotelbezetting (BPS Bali), grondrechten (PP 18/2021), belastingen', 'Gelinkt in elk artikel'],
    ],
    defsH2: 'Wat de cijfers betekenen',
    defs: [
      ['Mediaan', 'Het midden van de reeks: de helft van de objecten is goedkoper, de helft duurder. Eén villa van enkele miljoenen verschuift hem niet, daarom gebruiken we de mediaan en niet het gemiddelde.'],
      ['Middelste helft (25e–75e percentiel)', 'Het bereik waarin de middelste helft van de prijzen valt. Het laat zien hoe uiteenlopend de prijzen in een gebied zijn.'],
      ['Prijs per m²', 'Vraagprijs gedeeld door de woonoppervlakte in de advertentie. Grond, terras en zwembad tellen niet mee.'],
      ['Indicatief (*)', `Minder dan ${c.N} waarnemingen. Zo’n cijfer is een waarneming, geen conclusie over het gebied.`],
      ['Gebied van een huurobject', 'Een vakantiewoning wordt ingedeeld bij het gebied van het dichtstbijzijnde catalogusobject binnen 1,5 km. Wat verder weg ligt, telt niet mee.'],
      ['Status PBG/SLF', 'Wat de ontwikkelaar opgeeft: bouwvergunning (PBG), gebruiksvergunning (SLF), aanvraag ingediend of geen gegevens. We controleren de nummers niet in het register.'],
    ],
    yieldH2: 'Hoe het rendement wordt berekend',
    yield: [
      'We nemen het mediane nachttarief van vergelijkbare villa’s in de buurt (zelfde type en aantal slaapkamers).',
      'Dat vermenigvuldigen we met 365 en met de bezetting. Het basisscenario is 65%, met 55% en 75% ernaast. De bezettingsdata in de database zijn onbetrouwbaar (geblokkeerde kalenderdagen tellen als geboekt), dus werken we met scenario’s in plaats van een ‘werkelijke bezetting’.',
      'We trekken de kosten af: platformcommissies 15%, beheer 20%, exploitatie 6%, lokale logiesbelasting (PBJT) 10% — samen 51% van de bruto-omzet. Inkomstenbelasting (10% voor een ingezetene, tot 20% voor een niet-ingezetene) komt daar nog bij, omdat die van uw status afhangt.',
      'We delen door de aankoopprijs. Het resultaat is vóór afschrijving van de pacht: de grond is gepacht en het recht eindigt na 25–30 jaar.',
    ],
    yieldMore: <>Resultaten per gebied: <Link href={c.href.yield} className={A}>huurrendement van villa’s op Bali per gebied</Link>{en(c, 'nl')}.</>,
    limitsH2: 'Wat deze data niet laat zien',
    limits: [
      'Transactieprijzen. Die worden op Bali niet gepubliceerd; we tonen vraagprijzen.',
      'De hele markt. De catalogus bevat ontwikkelaars die bij ons adverteren; doorverkoop is ondervertegenwoordigd.',
      'Juridische zekerheid. We tonen documenten zoals de ontwikkelaar ze opgeeft en certificeren ze niet. Laat vóór betaling het eigendomsbewijs en de vergunningen controleren door een PPAT-notaris of advocaat.',
      'De toekomst. Huren en prijzen uit het verleden bieden geen garantie voor de toekomst.',
    ],
    updH2: 'Updates en correcties',
    upd: [
      'Prijzen en tarieven worden maandelijks opnieuw berekend; de berekeningsdatum staat op elke datapagina.',
      'Elk object wordt op dezelfde manier berekend: een ontwikkelaar kan de cijfers voor zijn eigen object niet beïnvloeden.',
      'Een fout gevonden in een prijs, datum of vergunningsstatus? Stuur de bot een bericht op Telegram — bevestigde fouten corrigeren we en de datum wordt bijgewerkt.',
    ],
    pagesH2: 'Waar deze data te zien is',
    pages: [
      { t: 'Vastgoedprijzen op Bali per gebied', href: c.href.prices },
      { t: 'Wat kost huren op Bali', href: c.href.rent },
      { t: 'Investeren in vastgoed op Bali: rendement per gebied', href: c.href.invest },
      { t: 'Over Balinsky: wat we controleren en wat niet', href: c.href.about },
    ],
    srcH2: 'Externe bronnen',
    sources: [
      { label: 'estatemarket.io — data over vakantieverhuur op Bali', href: c.href.estatemarket },
      { label: 'BPS Bali: aankomsten en hotelbezetting', href: c.href.bps },
      { label: 'BPS: buitenlandse aankomsten op Bali per jaar', href: c.href.bpsArrivals },
      { label: 'Indonesische regeringsverordening nr. 18/2021 (grondrechten)', href: c.href.pp18 },
      { label: 'PwC Worldwide Tax Summaries: Indonesië', href: c.href.pwcTax },
    ],
  }),

  pl: c => ({
    metaTitle: 'Jak liczymy: źródła i metoda danych o nieruchomościach na Bali',
    description: 'Skąd Balinsky bierze ceny, stawki najmu i rentowność na Bali: źródła, definicje, model rentowności, ograniczenia i sposób poprawiania błędów.',
    crumb: 'Jak liczymy',
    h1: 'Jak liczymy',
    lead: <>Każda liczba na stronie — cena za m² na tle rejonu, stawki najmu sąsiadów, rentowność — jest liczona według jawnej metody. Tu opisujemy, skąd są dane, co oznacza każdy wskaźnik i gdzie dane mają swoje granice.</>,
    updated: `Dane zaktualizowane: ${c.when}.`,
    sourcesH2: 'Skąd są dane',
    sourceCols: ['Źródło', 'Co bierzemy', 'Wielkość'],
    sourceRows: [
      ['Katalog Balinsky', 'Ceny ofertowe, powierzchnia, sypialnie, okres dzierżawy, stan budowy i pozwoleń — według dewelopera', `${c.n(c.T.villas)} ${plPlural(c.T.villas, 'willa', 'wille', 'willi')}, ${c.n(c.T.apartments)} ${plPlural(c.T.apartments, 'apartament', 'apartamenty', 'apartamentów')}`],
      ['Baza najmu krótkoterminowego (estatemarket.io)', 'Stawki za noc, typ obiektu, liczba sypialni, współrzędne', `${c.n(c.T.rentals)} ${plPlural(c.T.rentals, 'obiekt', 'obiekty', 'obiektów')} w rejonach katalogu`],
      ['Ogłoszenia najmu długoterminowego', 'Czynsz miesięczny, typ, sypialnie, rejon', `${c.n(c.M.n)} ${plPlural(c.M.n, 'ogłoszenie', 'ogłoszenia', 'ogłoszeń')}, ${c.from} — ${c.to}`],
      ['Oficjalne statystyki i przepisy', 'Ruch turystyczny i obłożenie hoteli (BPS Bali), prawa do gruntu (PP 18/2021), podatki', 'Linki w każdym artykule'],
    ],
    defsH2: 'Co oznaczają wskaźniki',
    defs: [
      ['Mediana', 'Środek szeregu: połowa obiektów jest tańsza, połowa droższa. Jedna willa za kilka milionów jej nie przesuwa, dlatego używamy mediany, a nie średniej.'],
      ['Środkowa połowa (25.–75. percentyl)', 'Przedział, w którym mieści się środkowa połowa cen. Pokazuje, jak bardzo różnią się ceny w rejonie.'],
      ['Cena za m²', 'Cena ofertowa podzielona przez powierzchnię mieszkalną z ogłoszenia. Działka, taras i basen nie są wliczone.'],
      ['Orientacyjnie (*)', `Mniej niż ${c.N} obserwacji. Taka liczba to obserwacja, a nie wniosek o rejonie.`],
      ['Rejon obiektu na wynajem', 'Obiekt najmu krótkoterminowego przypisujemy do rejonu najbliższego obiektu z katalogu w promieniu 1,5 km. Dalszych nie liczymy.'],
      ['Status PBG/SLF', 'To, co podał deweloper: pozwolenie na budowę (PBG), zaświadczenie o przydatności do użytkowania (SLF), złożony wniosek lub brak danych. Nie sprawdzamy numerów w rejestrze.'],
    ],
    yieldH2: 'Jak liczymy rentowność',
    yield: [
      'Bierzemy medianę stawki za noc podobnych willi w pobliżu (ten sam typ i liczba sypialni).',
      'Mnożymy przez 365 i przez obłożenie. Scenariusz bazowy to 65%, obok pokazujemy 55% i 75%. Dane o obłożeniu w bazie są niewiarygodne (zablokowane daty w kalendarzu liczą jako zajęte), dlatego używamy scenariuszy, a nie „rzeczywistego obłożenia”.',
      'Odejmujemy koszty: prowizje platform 15%, zarządzanie 20%, eksploatacja 6%, lokalny podatek od zakwaterowania (PBJT) 10% — razem 51% przychodu brutto. Podatek dochodowy (10% dla rezydenta, do 20% dla nierezydenta) dochodzi osobno, bo zależy od twojego statusu.',
      'Dzielimy przez cenę zakupu. Wynik jest przed amortyzacją dzierżawy: grunt jest dzierżawiony, a prawo wygasa po 25–30 latach.',
    ],
    yieldMore: <>Wyniki według rejonów: <Link href={c.href.yield} className={A}>rentowność najmu willi na Bali według rejonów</Link>{en(c, 'pl')}.</>,
    limitsH2: 'Czego te dane nie pokazują',
    limits: [
      'Cen transakcyjnych. Na Bali się ich nie publikuje; pokazujemy ceny ofertowe.',
      'Całego rynku. Katalog to deweloperzy, którzy publikują u nas; rynek wtórny jest słabo reprezentowany.',
      'Czystości prawnej. Dokumenty pokazujemy według dewelopera i ich nie poświadczamy. Przed zapłatą zleć sprawdzenie tytułu i pozwoleń notariuszowi PPAT lub prawnikowi.',
      'Przyszłości. Dawne stawki najmu i ceny nie gwarantują przyszłych.',
    ],
    updH2: 'Aktualizacje i poprawki',
    upd: [
      'Ceny i stawki przeliczamy co miesiąc; data obliczeń jest podana na każdej stronie z danymi.',
      'Każdy obiekt liczymy tak samo: deweloper nie może wpłynąć na wyliczenia dla swojego obiektu.',
      'Znalazłeś błąd w cenie, dacie lub statusie pozwolenia? Napisz do bota na Telegramie — potwierdzone błędy poprawiamy i aktualizujemy datę.',
    ],
    pagesH2: 'Gdzie te dane są na stronie',
    pages: [
      { t: 'Ceny nieruchomości na Bali według rejonów', href: c.href.prices },
      { t: 'Ile kosztuje najem na Bali', href: c.href.rent },
      { t: 'Inwestycje w nieruchomości na Bali: rentowność według rejonów', href: c.href.invest },
      { t: 'O Balinsky: co sprawdzamy, a czego nie', href: c.href.about },
    ],
    srcH2: 'Źródła zewnętrzne',
    sources: [
      { label: 'estatemarket.io — dane o najmie krótkoterminowym na Bali', href: c.href.estatemarket },
      { label: 'BPS Bali: ruch turystyczny i obłożenie hoteli', href: c.href.bps },
      { label: 'BPS: liczba zagranicznych turystów na Bali według lat', href: c.href.bpsArrivals },
      { label: 'Rozporządzenie rządu Indonezji nr 18/2021 (prawa do gruntu)', href: c.href.pp18 },
      { label: 'PwC Worldwide Tax Summaries: Indonezja', href: c.href.pwcTax },
    ],
  }),

  uk: c => ({
    metaTitle: 'Як ми рахуємо: джерела і метод даних про нерухомість Балі',
    description: 'Звідки Balinsky бере ціни, ставки оренди і дохідність на Балі: джерела, визначення, модель дохідності, обмеження і порядок виправлення помилок.',
    crumb: 'Як ми рахуємо',
    h1: 'Як ми рахуємо',
    lead: <>Кожна цифра на сайті — ціна за м² проти району, ставки оренди сусідів, дохідність — рахується за відкритим методом. Тут описано, звідки дані, що означає кожен показник і де в даних межі.</>,
    updated: `Дані оновлено: ${c.when}`,
    sourcesH2: 'Звідки дані',
    sourceCols: ['Джерело', 'Що беремо', 'Обсяг'],
    sourceRows: [
      ['Каталог Balinsky', 'Ціни пропозиції, площа, спальні, строк лізхолду, статус будівництва і дозволів — зі слів забудовника', `${c.n(c.T.villas)} ${ukPlural(c.T.villas, 'вілла', 'вілли', 'вілл')}, ${c.n(c.T.apartments)} ${ukPlural(c.T.apartments, 'апартамент', 'апартаменти', 'апартаментів')}`],
      ['База подобової оренди (estatemarket.io)', 'Ставки за ніч, тип об’єкта, кількість спалень, координати', `${c.n(c.T.rentals)} ${ukPlural(c.T.rentals, 'об’єкт', 'об’єкти', 'об’єктів')} біля районів каталогу`],
      ['Оголошення про помісячну оренду', 'Ціна на місяць, тип, спальні, район', `${c.n(c.M.n)} ${ukPlural(c.M.n, 'оголошення', 'оголошення', 'оголошень')}, ${c.from} — ${c.to}`],
      ['Офіційна статистика і закони', 'Турпотік і завантаження готелів (BPS Балі), права на землю (PP 18/2021), податки', 'Посилання — у кожному матеріалі'],
    ],
    defsH2: 'Що означають показники',
    defs: [
      ['Медіана', 'Середина ряду: у половини об’єктів ціна нижча, у половини вища. Одна вілла за кілька мільйонів її не зсуває, тому ми використовуємо медіану, а не середнє.'],
      ['Половина об’єктів (25–75%)', 'Діапазон, у який потрапляє середня половина цін. Показує, наскільки ціни в районі різні.'],
      ['Ціна за м²', 'Ціна пропозиції, поділена на житлову площу з картки. Земля, тераса і басейн не входять.'],
      ['Орієнтовно (*)', `Менше ${c.N} спостережень. Така цифра — спостереження, а не висновок про район.`],
      ['Район об’єкта оренди', 'Об’єкт подобової оренди відносимо до району найближчого об’єкта каталогу в радіусі 1,5 км. Далі — не враховуємо.'],
      ['Статус PBG/SLF', 'Те, що вказав забудовник: дозвіл на будівництво (PBG), сертифікат придатності до експлуатації (SLF), подано заявку або даних немає. Ми не звіряємо номери з реєстром.'],
    ],
    yieldH2: 'Як рахується дохідність',
    yield: [
      'Беремо медіанну ставку за ніч схожих вілл поруч (той самий тип і кількість спалень).',
      'Множимо на 365 і на завантаження. Базовий сценарій — 65%, поруч показуємо 55% і 75%. Дані про фактичне завантаження в базі ненадійні (вони вважають закриті дати календаря зайнятими), тому ми використовуємо сценарії, а не «реальне завантаження».',
      'Віднімаємо витрати: комісії майданчиків 15%, управління 20%, експлуатація 6%, місцевий податок на розміщення (PBJT) 10% — усього 51% валового виторгу. Податок на дохід (10% для резидента, до 20% для нерезидента) йде зверху — він залежить від вашого статусу.',
      'Ділимо на ціну купівлі. Результат — до амортизації лізхолду: земля в оренді, і через 25–30 років право закінчується.',
    ],
    yieldMore: <>Розрахунок за районами — у статті <Link href={c.href.yield} className={A}>дохідність вілл на Балі за районами</Link>{en(c, 'uk')}.</>,
    limitsH2: 'Чого ці дані не показують',
    limits: [
      'Ціни угод. На Балі їх не публікують; ми показуємо ціни пропозиції.',
      'Увесь ринок. Каталог — це забудовники, які публікуються в нас; вторинний ринок представлений слабко.',
      'Юридичну чистоту. Документи ми показуємо зі слів забудовника і не засвідчуємо. Перед оплатою перевірте сертифікат і дозволи в нотаріуса PPAT або юриста.',
      'Майбутнє. Минулі ставки оренди і ціни не гарантують майбутніх.',
    ],
    updH2: 'Оновлення і виправлення',
    upd: [
      'Ціни і ставки перераховуються щомісяця; дата розрахунку вказана на кожній сторінці з даними.',
      'Усі об’єкти рахуються однаково: забудовник не може вплинути на розрахунок свого об’єкта.',
      'Знайшли помилку в ціні, строку чи статусі дозволу? Напишіть боту в Telegram — підтверджені помилки виправляємо й оновлюємо дату.',
    ],
    pagesH2: 'Де ці дані на сайті',
    pages: [
      { t: 'Ціни на нерухомість Балі за районами', href: c.href.prices },
      { t: 'Скільки коштує оренда на Балі', href: c.href.rent },
      { t: 'Інвестиції в нерухомість Балі: дохідність за районами', href: c.href.invest },
      { t: 'Про Balinsky: що ми перевіряємо і чого ні', href: c.href.about },
    ],
    srcH2: 'Зовнішні джерела',
    sources: [
      { label: 'estatemarket.io — дані подобової оренди на Балі', href: c.href.estatemarket },
      { label: 'BPS Балі: турпотік і завантаження готелів', href: c.href.bps },
      { label: 'BPS: кількість іноземних туристів на Балі за роками', href: c.href.bpsArrivals },
      { label: 'Постанова уряду Індонезії № 18/2021 (права на землю)', href: c.href.pp18 },
      { label: 'PwC Worldwide Tax Summaries: Індонезія', href: c.href.pwcTax },
    ],
  }),
}
