// «Bali property prices by area» copy for the non-RU/EN locales. Same shape
// and the same numbers as the RU/EN copy in PriceIndexView.tsx — every figure
// comes from the context, never from the text.

import Link from 'next/link'
import type { Faq } from '../MarketShell'
import { A } from '../MarketShell'
import type { PriceCopy, PriceCtx } from '../PriceIndexView'
import { IN_ENGLISH, type IntlLang } from './types'
import { plPlural, ukPlural } from './plural'

const en = (c: PriceCtx, l: IntlLang) => (c.guidesInEnglish ? IN_ENGLISH[l] : '')

export const PRICES_INTL: Record<IntlLang, (c: PriceCtx) => PriceCopy> = {
  id: c => ({
    title: `Harga properti di Bali per kawasan — ${c.when}`,
    metaTitle: 'Harga Vila & Apartemen di Bali per Kawasan (Data 2026)',
    description: `Median harga penawaran vila di Bali: ${c.$(c.V.median)} (${c.V.n} listing); apartemen: ${c.$(c.I.apartments.median)}. Harga per m², sebaran harga, masa sewa dan status izin per kawasan. Diperbarui ${c.when}.`,
    crumb: 'Harga properti',
    h1: 'Harga properti di Bali per kawasan',
    lead: <>Median harga vila di katalog kami adalah <strong>{c.$(c.V.median)}</strong>; separuh vila ditawarkan antara {c.$(c.V.p25)} dan {c.$(c.V.p75)}. Apartemen: <strong>{c.$(c.I.apartments.median)}</strong>. Di bawah ini ada harga per m², sebaran harga dan status kepemilikan per kawasan. Ini harga penawaran untuk {c.V.n} vila dan {c.I.apartments.n} apartemen, bukan harga transaksi.</>,
    updated: `Data: ${c.when}. Dihitung ulang setiap bulan.`,
    takeawaysH2: 'Angka utama',
    takeaways: [
      `Vila 2 kamar tidur punya median harga ${c.$(c.I.villaByBeds['2'].median)} (${c.I.villaByBeds['2'].n} listing); vila 3 kamar tidur ${c.$(c.I.villaByBeds['3'].median)}.`,
      c.cheapest && c.dearest ? `Di antara kawasan dengan lebih dari ${c.N} vila, yang paling terjangkau per m² adalah ${c.nm(c.cheapest[0])} (${c.$(c.cheapest[1].perM2)}/m²), yang paling mahal ${c.nm(c.dearest[0])} (${c.$(c.dearest[1].perM2)}/m²). Median seluruh pulau ${c.$(c.V.perM2)}/m².` : '',
      `${c.V.offPlanShare}% vila di katalog masih dibangun: Anda membeli proyek, bukan rumah jadi.`,
      `${c.V.permitShare}% vila mencantumkan izin PBG atau SLF. Sisanya tanpa data izin atau izin masih diajukan.`,
      c.V.leaseYears ? `Masa sewa yang umum adalah ${c.V.leaseYears} tahun. Bandingkan harga dengan memperhitungkan masa sewa: 30 tahun lebih bernilai daripada 25.` : '',
    ].filter(Boolean),
    bedsH2: 'Harga vila menurut jumlah kamar tidur',
    bedsCols: ['Kamar tidur', 'Listing', 'Median', 'Separuh tengah', 'Per m²'],
    bedLabel: b => b,
    villasH2: 'Vila: harga per kawasan',
    villasCols: ['Kawasan', 'Listing', 'Median', 'Separuh tengah', 'Per m²', '2 kamar', 'Sewa', 'Dibangun', 'PBG/SLF'],
    years: n => `${n} th`,
    aptsH2: 'Apartemen: harga per kawasan',
    aptsCols: ['Kawasan', 'Listing', 'Median', 'Separuh tengah', 'Per m²'],
    browse: 'Lihat',
    indicative: `* Kurang dari ${c.N} listing — angka indikatif, bukan kesimpulan tentang kawasan itu.`,
    columnsNote: '“Separuh tengah” adalah persentil ke-25 sampai ke-75: separuh harga yang di tengah ada di rentang ini. “Sewa” adalah median sisa masa sewa tanah (leasehold). “PBG/SLF” adalah porsi vila yang pengembangnya mencantumkan persetujuan bangunan gedung (PBG) atau sertifikat laik fungsi (SLF).',
    readH2: 'Cara membaca angka-angka ini',
    read: [
      'Ini harga penawaran, bukan harga jual. Harga transaksi di Bali tidak dipublikasikan, dan biasanya masih bisa ditawar, terutama untuk bangunan jadi.',
      'Katalog bukan seluruh pasar. Isinya pengembang yang mendaftar di kami; properti bekas dan penjualan pribadi hampir tidak ada.',
      'Median lebih stabil daripada rata-rata: satu vila seharga jutaan dolar tidak menggesernya.',
      'Harga per m² memakai luas bangunan di listing. Tanah dan kolam renang tidak termasuk, jadi vila di lahan luas terlihat lebih mahal.',
    ],
    moreRead: <>Berapa pendapatan sewa rumah-rumah ini ada di halaman <Link href={c.href.rent} className={A}>harga sewa di Bali</Link>. Cara menghitung imbal hasil: <Link href={c.href.yield} className={A}>imbal hasil sewa vila per kawasan</Link>{en(c, 'id')}.</>,
    faqH2: 'Pertanyaan yang sering diajukan',
    faq: [
      { q: 'Berapa harga vila di Bali pada 2026?', a: `Median harga penawaran adalah ${c.$(c.V.median)} dari ${c.V.n} vila di katalog kami. Separuhnya ditawarkan antara ${c.$(c.V.p25)} dan ${c.$(c.V.p75)}. Vila 2 kamar tidur sekitar ${c.$(c.I.villaByBeds['2'].median)}, vila 3 kamar tidur sekitar ${c.$(c.I.villaByBeds['3'].median)}.` },
      c.cheapest ? { q: 'Di mana properti paling murah di Bali?', a: `Di antara kawasan dengan listing yang cukup, vila paling murah per m² ada di ${c.nm(c.cheapest[0])}: ${c.$(c.cheapest[1].perM2)}/m² (${c.cheapest[1].n} listing). Apartemen jauh lebih murah daripada vila: median ${c.$(c.I.apartments.median)} per unit.` } : null,
      { q: 'Apakah ini harga jual sebenarnya?', a: 'Bukan. Ini harga yang diminta pengembang. Harga transaksi di Bali tidak dipublikasikan. Gunakan angka ini sebagai patokan untuk membandingkan dan menawar, bukan sebagai penilaian.' },
      { q: 'Leasehold atau freehold?', a: `Hampir semua vila di katalog dijual leasehold, yaitu sewa tanah jangka panjang. Median masa sewanya ${c.V.leaseYears ?? '—'} tahun. Warga asing tidak bisa memiliki tanah hak milik secara langsung.` },
    ].filter(Boolean) as Faq[],
    sourcesH2: 'Sumber dan metode',
    sources: [
      { label: `Katalog Balinsky: ${c.V.n} vila dan ${c.I.apartments.n} apartemen dijual, harga penawaran, ${c.when}`, href: c.href.catalog },
      { label: 'Cara kami menghitung: sumber, definisi, batasan', href: c.href.method },
      { label: `Masa leasehold di Bali dalam angka${en(c, 'id')}`, href: c.href.lease },
      { label: `Zonasi dan izin vila di Bali dalam angka${en(c, 'id')}`, href: c.href.zoning },
      { label: 'Peraturan Pemerintah No. 18/2021 (hak atas tanah)', href: c.href.pp18 },
    ],
    datasetName: 'Harga penawaran vila dan apartemen di Bali per kawasan',
  }),

  fr: c => ({
    title: `Prix de l’immobilier à Bali par quartier — ${c.when}`,
    metaTitle: 'Prix des villas et appartements à Bali par quartier (données 2026)',
    description: `Prix demandé médian d’une villa à Bali : ${c.$(c.V.median)} (${c.V.n} annonces) ; appartements : ${c.$(c.I.apartments.median)}. Prix au m², fourchette, durée du bail et permis par quartier. Mis à jour : ${c.when}.`,
    crumb: 'Prix de l’immobilier',
    h1: 'Prix de l’immobilier à Bali par quartier',
    lead: <>La villa médiane de notre catalogue est proposée à <strong>{c.$(c.V.median)}</strong> ; la moitié des villas se situent entre {c.$(c.V.p25)} et {c.$(c.V.p75)}. Appartements : <strong>{c.$(c.I.apartments.median)}</strong>. Ci-dessous : prix au m², fourchette et conditions de propriété par quartier. Ce sont les prix demandés pour {c.V.n} villas et {c.I.apartments.n} appartements, pas des prix de vente.</>,
    updated: `Données : ${c.when}. Recalculées chaque mois.`,
    takeawaysH2: 'Les chiffres clés',
    takeaways: [
      `Une villa de 2 chambres a un prix demandé médian de ${c.$(c.I.villaByBeds['2'].median)} (${c.I.villaByBeds['2'].n} annonces) ; une villa de 3 chambres, ${c.$(c.I.villaByBeds['3'].median)}.`,
      c.cheapest && c.dearest ? `Parmi les quartiers de plus de ${c.N} villas, le plus abordable au m² est ${c.nm(c.cheapest[0])} (${c.$(c.cheapest[1].perM2)}/m²), le plus cher ${c.nm(c.dearest[0])} (${c.$(c.dearest[1].perM2)}/m²). La médiane de l’île est de ${c.$(c.V.perM2)}/m².` : '',
      `${c.V.offPlanShare} % des villas du catalogue sont encore en construction : vous achetez un projet, pas une maison finie.`,
      `${c.V.permitShare} % des villas indiquent un permis PBG ou SLF. Les autres n’ont aucune donnée de permis ou une demande en cours.`,
      c.V.leaseYears ? `La durée de bail typique est de ${c.V.leaseYears} ans. Comparez les prix en tenant compte de la durée : 30 ans valent plus que 25.` : '',
    ].filter(Boolean),
    bedsH2: 'Prix des villas selon le nombre de chambres',
    bedsCols: ['Chambres', 'Annonces', 'Médiane', 'Moitié centrale', 'Au m²'],
    bedLabel: b => b,
    villasH2: 'Villas : prix par quartier',
    villasCols: ['Quartier', 'Annonces', 'Médiane', 'Moitié centrale', 'Au m²', '2 chambres', 'Bail', 'En construction', 'PBG/SLF'],
    years: n => `${n} ans`,
    aptsH2: 'Appartements : prix par quartier',
    aptsCols: ['Quartier', 'Annonces', 'Médiane', 'Moitié centrale', 'Au m²'],
    browse: 'Voir',
    indicative: `* Moins de ${c.N} annonces : un chiffre indicatif, pas une conclusion sur le quartier.`,
    columnsNote: '« Moitié centrale » va du 25e au 75e centile : la moitié centrale des prix se trouve dans cette fourchette. « Bail » est la durée restante médiane du bail foncier. « PBG/SLF » est la part des villas dont le promoteur indique un permis de construire (PBG) ou un certificat de conformité (SLF).',
    readH2: 'Comment lire ces chiffres',
    read: [
      'Ce sont des prix demandés, pas des prix de vente. Personne ne publie les prix des transactions à Bali, et il y a généralement une marge de négociation, surtout pour les biens achevés.',
      'Le catalogue n’est pas tout le marché. Il couvre les promoteurs qui publient chez nous ; la revente et les ventes entre particuliers y sont quasi absentes.',
      'La médiane est plus robuste que la moyenne : une villa à plusieurs millions ne la déplace pas.',
      'Le prix au m² se calcule sur la surface habitable de l’annonce. Terrain et piscine n’y entrent pas, donc les villas sur de grands terrains paraissent plus chères.',
    ],
    moreRead: <>Ce que rapportent ces biens en location : page <Link href={c.href.rent} className={A}>prix des locations à Bali</Link>. Comment se calcule le rendement : <Link href={c.href.yield} className={A}>rendement locatif des villas par quartier</Link>{en(c, 'fr')}.</>,
    faqH2: 'Questions fréquentes',
    faq: [
      { q: 'Combien coûte une villa à Bali en 2026 ?', a: `Le prix demandé médian est de ${c.$(c.V.median)} sur ${c.V.n} villas de notre catalogue. La moitié sont proposées entre ${c.$(c.V.p25)} et ${c.$(c.V.p75)}. Une villa de 2 chambres coûte environ ${c.$(c.I.villaByBeds['2'].median)}, une villa de 3 chambres environ ${c.$(c.I.villaByBeds['3'].median)}.` },
      c.cheapest ? { q: 'Où l’immobilier est-il le moins cher à Bali ?', a: `Parmi les quartiers ayant assez d’annonces, les villas sont les moins chères au m² à ${c.nm(c.cheapest[0])} : ${c.$(c.cheapest[1].perM2)}/m² (${c.cheapest[1].n} annonces). Les appartements coûtent bien moins que les villas : ${c.$(c.I.apartments.median)} en médiane.` } : null,
      { q: 'S’agit-il de prix de vente réels ?', a: 'Non. Ce sont les prix demandés par les promoteurs. Les prix des transactions ne sont pas publiés à Bali. Utilisez ces chiffres comme repère pour comparer et négocier, pas comme une estimation.' },
      { q: 'Leasehold ou pleine propriété ?', a: `Presque toutes les villas du catalogue sont vendues en leasehold, c’est-à-dire un bail de longue durée sur le terrain. La durée médiane est de ${c.V.leaseYears ?? '—'} ans. Un étranger ne peut pas détenir directement un terrain en pleine propriété.` },
    ].filter(Boolean) as Faq[],
    sourcesH2: 'Sources et méthode',
    sources: [
      { label: `Catalogue Balinsky : ${c.V.n} villas et ${c.I.apartments.n} appartements à vendre, prix demandés, ${c.when}`, href: c.href.catalog },
      { label: 'Notre méthode : sources, définitions, limites', href: c.href.method },
      { label: `La durée des baux à Bali en chiffres${en(c, 'fr')}`, href: c.href.lease },
      { label: `Zonage et permis des villas à Bali en chiffres${en(c, 'fr')}`, href: c.href.zoning },
      { label: 'Règlement du gouvernement indonésien n° 18/2021 (droits fonciers)', href: c.href.pp18 },
    ],
    datasetName: 'Prix demandés des villas et appartements à Bali par quartier',
  }),

  de: c => ({
    title: `Immobilienpreise auf Bali nach Gegend — ${c.when}`,
    metaTitle: 'Villen- und Wohnungspreise auf Bali nach Gegend (Daten 2026)',
    description: `Medianer Angebotspreis einer Villa auf Bali: ${c.$(c.V.median)} (${c.V.n} Angebote); Wohnungen: ${c.$(c.I.apartments.median)}. Preis pro m², Spanne, Pachtdauer und Genehmigungen nach Gegend. Stand: ${c.when}.`,
    crumb: 'Immobilienpreise',
    h1: 'Immobilienpreise auf Bali nach Gegend',
    lead: <>Die mittlere Villa in unserem Katalog wird für <strong>{c.$(c.V.median)}</strong> angeboten; die Hälfte aller Villen liegt zwischen {c.$(c.V.p25)} und {c.$(c.V.p75)}. Wohnungen: <strong>{c.$(c.I.apartments.median)}</strong>. Unten stehen Preis pro m², Spanne und Eigentumsbedingungen nach Gegend. Es sind Angebotspreise für {c.V.n} Villen und {c.I.apartments.n} Wohnungen, keine Verkaufspreise.</>,
    updated: `Daten: ${c.when}. Monatlich neu berechnet.`,
    takeawaysH2: 'Die wichtigsten Zahlen',
    takeaways: [
      `Eine Villa mit 2 Schlafzimmern kostet im Median ${c.$(c.I.villaByBeds['2'].median)} (${c.I.villaByBeds['2'].n} Angebote), mit 3 Schlafzimmern ${c.$(c.I.villaByBeds['3'].median)}.`,
      c.cheapest && c.dearest ? `Unter den Gegenden mit mehr als ${c.N} Villen ist ${c.nm(c.cheapest[0])} pro m² am günstigsten (${c.$(c.cheapest[1].perM2)}/m²), ${c.nm(c.dearest[0])} am teuersten (${c.$(c.dearest[1].perM2)}/m²). Der Median der Insel liegt bei ${c.$(c.V.perM2)}/m².` : '',
      `${c.V.offPlanShare} % der Villen im Katalog sind noch im Bau: Sie kaufen ein Projekt, kein fertiges Haus.`,
      `${c.V.permitShare} % der Villen geben eine PBG- oder SLF-Genehmigung an. Bei den übrigen fehlen Angaben oder der Antrag läuft noch.`,
      c.V.leaseYears ? `Die typische Pachtdauer beträgt ${c.V.leaseYears} Jahre. Vergleichen Sie Preise immer mit der Laufzeit: 30 Jahre sind mehr wert als 25.` : '',
    ].filter(Boolean),
    bedsH2: 'Villenpreise nach Zahl der Schlafzimmer',
    bedsCols: ['Schlafzimmer', 'Angebote', 'Median', 'Mittlere Hälfte', 'Pro m²'],
    bedLabel: b => b,
    villasH2: 'Villen: Preise nach Gegend',
    villasCols: ['Gegend', 'Angebote', 'Median', 'Mittlere Hälfte', 'Pro m²', '2 Schlafz.', 'Pacht', 'Im Bau', 'PBG/SLF'],
    years: n => `${n} J.`,
    aptsH2: 'Wohnungen: Preise nach Gegend',
    aptsCols: ['Gegend', 'Angebote', 'Median', 'Mittlere Hälfte', 'Pro m²'],
    browse: 'Ansehen',
    indicative: `* Weniger als ${c.N} Angebote: ein Richtwert, keine Aussage über die Gegend.`,
    columnsNote: '„Mittlere Hälfte“ reicht vom 25. bis zum 75. Perzentil: In dieser Spanne liegt die mittlere Hälfte der Preise. „Pacht“ ist die mediane Restlaufzeit der Landpacht. „PBG/SLF“ ist der Anteil der Villen, bei denen der Bauträger eine Baugenehmigung (PBG) oder eine Nutzungsbescheinigung (SLF) angibt.',
    readH2: 'So lesen Sie diese Zahlen',
    read: [
      'Das sind Angebotspreise, keine Verkaufspreise. Tatsächliche Kaufpreise werden auf Bali nicht veröffentlicht, und meist lässt sich verhandeln, vor allem bei fertigen Objekten.',
      'Der Katalog ist nicht der ganze Markt. Er umfasst Bauträger, die bei uns inserieren; Wiederverkäufe und Privatverkäufe fehlen weitgehend.',
      'Der Median ist robuster als der Durchschnitt: Eine einzelne Villa für mehrere Millionen verschiebt ihn nicht.',
      'Der Preis pro m² bezieht sich auf die Wohnfläche im Inserat. Grundstück und Pool zählen nicht mit, daher wirken Villen auf großen Grundstücken teurer.',
    ],
    moreRead: <>Was diese Häuser als Vermietung einbringen, steht auf der Seite <Link href={c.href.rent} className={A}>Mietpreise auf Bali</Link>. Wie die Rendite berechnet wird: <Link href={c.href.yield} className={A}>Mietrendite von Villen nach Gegend</Link>{en(c, 'de')}.</>,
    faqH2: 'Häufige Fragen',
    faq: [
      { q: 'Was kostet eine Villa auf Bali 2026?', a: `Der mediane Angebotspreis liegt bei ${c.$(c.V.median)} über ${c.V.n} Villen in unserem Katalog. Die Hälfte wird zwischen ${c.$(c.V.p25)} und ${c.$(c.V.p75)} angeboten. Eine Villa mit 2 Schlafzimmern kostet etwa ${c.$(c.I.villaByBeds['2'].median)}, mit 3 Schlafzimmern etwa ${c.$(c.I.villaByBeds['3'].median)}.` },
      c.cheapest ? { q: 'Wo sind Immobilien auf Bali am günstigsten?', a: `Unter den Gegenden mit genug Angeboten sind Villen pro m² in ${c.nm(c.cheapest[0])} am günstigsten: ${c.$(c.cheapest[1].perM2)}/m² (${c.cheapest[1].n} Angebote). Wohnungen kosten deutlich weniger als Villen: im Median ${c.$(c.I.apartments.median)} pro Einheit.` } : null,
      { q: 'Sind das tatsächliche Verkaufspreise?', a: 'Nein. Es sind die Preise, die Bauträger verlangen. Kaufpreise werden auf Bali nicht veröffentlicht. Nutzen Sie die Zahlen als Maßstab zum Vergleichen und Verhandeln, nicht als Bewertung.' },
      { q: 'Leasehold oder Freehold?', a: `Fast jede Villa im Katalog wird als Leasehold verkauft, also mit langfristiger Pacht des Grundstücks. Die mediane Laufzeit beträgt ${c.V.leaseYears ?? '—'} Jahre. Ausländer können Land nicht direkt als Eigentum (Freehold) besitzen.` },
    ].filter(Boolean) as Faq[],
    sourcesH2: 'Quellen und Methode',
    sources: [
      { label: `Balinsky-Katalog: ${c.V.n} Villen und ${c.I.apartments.n} Wohnungen zum Verkauf, Angebotspreise, ${c.when}`, href: c.href.catalog },
      { label: 'So rechnen wir: Quellen, Definitionen, Grenzen', href: c.href.method },
      { label: `Pachtlaufzeiten auf Bali in Zahlen${en(c, 'de')}`, href: c.href.lease },
      { label: `Zonierung und Genehmigungen von Villen auf Bali in Zahlen${en(c, 'de')}`, href: c.href.zoning },
      { label: 'Indonesische Regierungsverordnung Nr. 18/2021 (Landrechte)', href: c.href.pp18 },
    ],
    datasetName: 'Angebotspreise für Villen und Wohnungen auf Bali nach Gegend',
  }),

  zh: c => ({
    title: `巴厘岛各区域房产价格 — ${c.when}`,
    metaTitle: '巴厘岛各区域别墅与公寓价格（2026年数据）',
    description: `巴厘岛别墅挂牌价中位数：${c.$(c.V.median)}（${c.V.n}套）；公寓：${c.$(c.I.apartments.median)}。按区域列出每平方米价格、价格区间、租赁年限和许可证情况。更新时间：${c.when}。`,
    crumb: '房产价格',
    h1: '巴厘岛各区域房产价格',
    lead: <>我们目录中别墅挂牌价的中位数为<strong>{c.$(c.V.median)}</strong>，一半别墅的价格在{c.$(c.V.p25)}到{c.$(c.V.p75)}之间。公寓：<strong>{c.$(c.I.apartments.median)}</strong>。下方按区域列出每平方米价格、价格区间和产权条件。这些是{c.V.n}套别墅和{c.I.apartments.n}套公寓的挂牌价，不是成交价。</>,
    updated: `数据：${c.when}，每月重新计算。`,
    takeawaysH2: '关键数字',
    takeaways: [
      `两居室别墅挂牌价中位数为${c.$(c.I.villaByBeds['2'].median)}（${c.I.villaByBeds['2'].n}套），三居室为${c.$(c.I.villaByBeds['3'].median)}。`,
      c.cheapest && c.dearest ? `在别墅超过${c.N}套的区域中，每平方米最便宜的是${c.nm(c.cheapest[0])}（${c.$(c.cheapest[1].perM2)}/m²），最贵的是${c.nm(c.dearest[0])}（${c.$(c.dearest[1].perM2)}/m²）。全岛中位数为${c.$(c.V.perM2)}/m²。` : '',
      `目录中${c.V.offPlanShare}%的别墅仍在建设中：您买的是项目，而不是建好的房子。`,
      `${c.V.permitShare}%的别墅注明了PBG或SLF许可证。其余没有许可证信息，或申请仍在办理中。`,
      c.V.leaseYears ? `典型的租赁年限为${c.V.leaseYears}年。比较价格时要考虑年限：30年比25年更值钱。` : '',
    ].filter(Boolean),
    bedsH2: '按卧室数量划分的别墅价格',
    bedsCols: ['卧室', '房源数', '中位数', '中间一半', '每平方米'],
    bedLabel: b => b,
    villasH2: '别墅：各区域价格',
    villasCols: ['区域', '房源数', '中位数', '中间一半', '每平方米', '两居室', '租期', '在建', 'PBG/SLF'],
    years: n => `${n}年`,
    aptsH2: '公寓：各区域价格',
    aptsCols: ['区域', '房源数', '中位数', '中间一半', '每平方米'],
    browse: '查看',
    indicative: `* 房源少于${c.N}套：仅供参考，不能作为对该区域的结论。`,
    columnsNote: '“中间一半”指第25至第75百分位：中间一半的价格落在这个区间。“租期”是土地租赁的剩余年限中位数。“PBG/SLF”是开发商注明建筑许可（PBG）或使用合格证（SLF）的别墅比例。',
    readH2: '如何解读这些数字',
    read: [
      '这些是挂牌价，不是成交价。巴厘岛不公开实际成交价格，通常还有议价空间，现房尤其如此。',
      '目录并不代表整个市场。其中是在我们平台发布房源的开发商；二手房和私人出售几乎不在其中。',
      '中位数比平均数更稳定：一套数百万美元的别墅不会让它变动。',
      '每平方米价格按房源中的居住面积计算，不含土地和泳池，因此大地块上的别墅看起来更贵。',
    ],
    moreRead: <>这些房子出租能带来多少收入，请看<Link href={c.href.rent} className={A}>巴厘岛租金价格</Link>页面。收益率的计算方法见<Link href={c.href.yield} className={A}>各区域别墅租金收益率</Link>{en(c, 'zh')}。</>,
    faqH2: '常见问题',
    faq: [
      { q: '2026年在巴厘岛买一套别墅要多少钱？', a: `我们目录中${c.V.n}套别墅的挂牌价中位数为${c.$(c.V.median)}，一半在${c.$(c.V.p25)}到${c.$(c.V.p75)}之间。两居室别墅约${c.$(c.I.villaByBeds['2'].median)}，三居室约${c.$(c.I.villaByBeds['3'].median)}。` },
      c.cheapest ? { q: '巴厘岛哪里的房产最便宜？', a: `在房源足够多的区域中，${c.nm(c.cheapest[0])}的别墅每平方米最便宜：${c.$(c.cheapest[1].perM2)}/m²（${c.cheapest[1].n}套）。公寓比别墅便宜得多：每套中位数为${c.$(c.I.apartments.median)}。` } : null,
      { q: '这些是实际成交价吗？', a: '不是。这是开发商的要价。巴厘岛不公开成交价格。请把这些数字当作比较和议价的参考，而不是估值。' },
      { q: '租赁产权还是永久产权？', a: `目录中几乎所有别墅都以租赁产权（leasehold）出售，即长期租赁土地。租期中位数为${c.V.leaseYears ?? '—'}年。外国人不能直接持有永久产权的土地。` },
    ].filter(Boolean) as Faq[],
    sourcesH2: '来源与方法',
    sources: [
      { label: `Balinsky目录：在售别墅${c.V.n}套、公寓${c.I.apartments.n}套，挂牌价，${c.when}`, href: c.href.catalog },
      { label: '我们如何计算：来源、定义、局限', href: c.href.method },
      { label: `巴厘岛租赁年限数据${en(c, 'zh')}`, href: c.href.lease },
      { label: `巴厘岛别墅分区与许可证数据${en(c, 'zh')}`, href: c.href.zoning },
      { label: '印度尼西亚政府条例2021年第18号（土地权利）', href: c.href.pp18 },
    ],
    datasetName: '巴厘岛各区域别墅和公寓挂牌价',
  }),

  nl: c => ({
    title: `Vastgoedprijzen op Bali per gebied — ${c.when}`,
    metaTitle: 'Prijzen van villa’s en appartementen op Bali per gebied (data 2026)',
    description: `Mediane vraagprijs van een villa op Bali: ${c.$(c.V.median)} (${c.V.n} aanbiedingen); appartementen: ${c.$(c.I.apartments.median)}. Prijs per m², spreiding, pachttermijn en vergunningen per gebied. Bijgewerkt: ${c.when}.`,
    crumb: 'Vastgoedprijzen',
    h1: 'Vastgoedprijzen op Bali per gebied',
    lead: <>De mediane villa in onze catalogus staat te koop voor <strong>{c.$(c.V.median)}</strong>; de helft van alle villa’s zit tussen {c.$(c.V.p25)} en {c.$(c.V.p75)}. Appartementen: <strong>{c.$(c.I.apartments.median)}</strong>. Hieronder de prijs per m², de spreiding en de eigendomsvoorwaarden per gebied. Dit zijn vraagprijzen van {c.V.n} villa’s en {c.I.apartments.n} appartementen, geen verkoopprijzen.</>,
    updated: `Data: ${c.when}. Elke maand opnieuw berekend.`,
    takeawaysH2: 'De belangrijkste cijfers',
    takeaways: [
      `Een villa met 2 slaapkamers heeft een mediane vraagprijs van ${c.$(c.I.villaByBeds['2'].median)} (${c.I.villaByBeds['2'].n} aanbiedingen); met 3 slaapkamers ${c.$(c.I.villaByBeds['3'].median)}.`,
      c.cheapest && c.dearest ? `Van de gebieden met meer dan ${c.N} villa’s is ${c.nm(c.cheapest[0])} per m² het goedkoopst (${c.$(c.cheapest[1].perM2)}/m²) en ${c.nm(c.dearest[0])} het duurst (${c.$(c.dearest[1].perM2)}/m²). De mediaan voor het hele eiland is ${c.$(c.V.perM2)}/m².` : '',
      `${c.V.offPlanShare}% van de villa’s in de catalogus is nog in aanbouw: u koopt een project, geen afgebouwd huis.`,
      `${c.V.permitShare}% van de villa’s vermeldt een PBG- of SLF-vergunning. Bij de rest ontbreken gegevens of loopt de aanvraag nog.`,
      c.V.leaseYears ? `De gebruikelijke pachttermijn is ${c.V.leaseYears} jaar. Vergelijk prijzen altijd met de termijn erbij: 30 jaar is meer waard dan 25.` : '',
    ].filter(Boolean),
    bedsH2: 'Villaprijzen naar aantal slaapkamers',
    bedsCols: ['Slaapkamers', 'Aanbod', 'Mediaan', 'Middelste helft', 'Per m²'],
    bedLabel: b => b,
    villasH2: 'Villa’s: prijzen per gebied',
    villasCols: ['Gebied', 'Aanbod', 'Mediaan', 'Middelste helft', 'Per m²', '2 slaapk.', 'Pacht', 'In aanbouw', 'PBG/SLF'],
    years: n => `${n} jr`,
    aptsH2: 'Appartementen: prijzen per gebied',
    aptsCols: ['Gebied', 'Aanbod', 'Mediaan', 'Middelste helft', 'Per m²'],
    browse: 'Bekijken',
    indicative: `* Minder dan ${c.N} aanbiedingen: een indicatief cijfer, geen conclusie over het gebied.`,
    columnsNote: '‘Middelste helft’ loopt van het 25e tot het 75e percentiel: de middelste helft van de prijzen valt in dit bereik. ‘Pacht’ is de mediane resterende pachttermijn van de grond. ‘PBG/SLF’ is het aandeel villa’s waarvan de ontwikkelaar een bouwvergunning (PBG) of een gebruiksvergunning (SLF) vermeldt.',
    readH2: 'Zo leest u deze cijfers',
    read: [
      'Dit zijn vraagprijzen, geen verkoopprijzen. Werkelijke transactieprijzen worden op Bali niet gepubliceerd, en meestal valt er te onderhandelen, vooral bij opgeleverde woningen.',
      'De catalogus is niet de hele markt. Hij bevat ontwikkelaars die bij ons adverteren; doorverkoop en particuliere verkoop ontbreken grotendeels.',
      'De mediaan is robuuster dan het gemiddelde: één villa van enkele miljoenen verschuift hem niet.',
      'De prijs per m² gaat uit van de woonoppervlakte in de advertentie. Grond en zwembad tellen niet mee, dus villa’s op grote kavels lijken duurder.',
    ],
    moreRead: <>Wat deze woningen opbrengen bij verhuur staat op de pagina <Link href={c.href.rent} className={A}>huurprijzen op Bali</Link>. Hoe het rendement wordt berekend: <Link href={c.href.yield} className={A}>huurrendement van villa’s per gebied</Link>{en(c, 'nl')}.</>,
    faqH2: 'Veelgestelde vragen',
    faq: [
      { q: 'Wat kost een villa op Bali in 2026?', a: `De mediane vraagprijs is ${c.$(c.V.median)} over ${c.V.n} villa’s in onze catalogus. De helft staat te koop tussen ${c.$(c.V.p25)} en ${c.$(c.V.p75)}. Een villa met 2 slaapkamers kost ongeveer ${c.$(c.I.villaByBeds['2'].median)}, met 3 slaapkamers ongeveer ${c.$(c.I.villaByBeds['3'].median)}.` },
      c.cheapest ? { q: 'Waar is vastgoed op Bali het goedkoopst?', a: `Van de gebieden met genoeg aanbod zijn villa’s per m² het goedkoopst in ${c.nm(c.cheapest[0])}: ${c.$(c.cheapest[1].perM2)}/m² (${c.cheapest[1].n} aanbiedingen). Appartementen kosten veel minder dan villa’s: een mediaan van ${c.$(c.I.apartments.median)} per eenheid.` } : null,
      { q: 'Zijn dit echte verkoopprijzen?', a: 'Nee. Het zijn de prijzen die ontwikkelaars vragen. Transactieprijzen worden op Bali niet gepubliceerd. Gebruik deze cijfers als maatstaf om te vergelijken en te onderhandelen, niet als taxatie.' },
      { q: 'Leasehold of freehold?', a: `Bijna elke villa in de catalogus wordt als leasehold verkocht: een langdurige pacht van de grond. De mediane termijn is ${c.V.leaseYears ?? '—'} jaar. Buitenlanders kunnen grond niet rechtstreeks in volle eigendom (freehold) bezitten.` },
    ].filter(Boolean) as Faq[],
    sourcesH2: 'Bronnen en methode',
    sources: [
      { label: `Balinsky-catalogus: ${c.V.n} villa’s en ${c.I.apartments.n} appartementen te koop, vraagprijzen, ${c.when}`, href: c.href.catalog },
      { label: 'Hoe we rekenen: bronnen, definities, beperkingen', href: c.href.method },
      { label: `Pachttermijnen op Bali in cijfers${en(c, 'nl')}`, href: c.href.lease },
      { label: `Bestemming en vergunningen van villa’s op Bali in cijfers${en(c, 'nl')}`, href: c.href.zoning },
      { label: 'Indonesische regeringsverordening nr. 18/2021 (grondrechten)', href: c.href.pp18 },
    ],
    datasetName: 'Vraagprijzen van villa’s en appartementen op Bali per gebied',
  }),

  pl: c => ({
    title: `Ceny nieruchomości na Bali według rejonów — ${c.when}`,
    metaTitle: 'Ceny willi i apartamentów na Bali według rejonów (dane 2026)',
    description: `Mediana ceny ofertowej willi na Bali: ${c.$(c.V.median)} (${c.V.n} ${plPlural(c.V.n, 'oferta', 'oferty', 'ofert')}); apartamenty: ${c.$(c.I.apartments.median)}. Cena za m², rozrzut, okres dzierżawy i pozwolenia według rejonów. Aktualizacja: ${c.when}.`,
    crumb: 'Ceny nieruchomości',
    h1: 'Ceny nieruchomości na Bali według rejonów',
    lead: <>Mediana ceny willi w naszym katalogu to <strong>{c.$(c.V.median)}</strong>; połowa willi kosztuje od {c.$(c.V.p25)} do {c.$(c.V.p75)}. Apartamenty: <strong>{c.$(c.I.apartments.median)}</strong>. Poniżej cena za m², rozrzut i warunki własności według rejonów. To ceny ofertowe {c.V.n} willi i {c.I.apartments.n} apartamentów, a nie ceny transakcyjne.</>,
    updated: `Dane: ${c.when}. Przeliczane co miesiąc.`,
    takeawaysH2: 'Najważniejsze liczby',
    takeaways: [
      `Willa z 2 sypialniami ma medianę ceny ofertowej ${c.$(c.I.villaByBeds['2'].median)} (ofert: ${c.I.villaByBeds['2'].n}), z 3 sypialniami ${c.$(c.I.villaByBeds['3'].median)}.`,
      c.cheapest && c.dearest ? `Spośród rejonów z ponad ${c.N} willami najtańszy za m² jest ${c.nm(c.cheapest[0])} (${c.$(c.cheapest[1].perM2)}/m²), najdroższy ${c.nm(c.dearest[0])} (${c.$(c.dearest[1].perM2)}/m²). Mediana dla całej wyspy to ${c.$(c.V.perM2)}/m².` : '',
      `${c.V.offPlanShare}% willi w katalogu jest jeszcze w budowie: kupujesz projekt, a nie gotowy dom.`,
      `${c.V.permitShare}% willi ma podane pozwolenie PBG lub SLF. Przy pozostałych brak danych albo wniosek jest w toku.`,
      c.V.leaseYears ? `Typowy okres dzierżawy to ${c.V.leaseYears} ${plPlural(c.V.leaseYears, 'rok', 'lata', 'lat')}. Porównuj ceny z uwzględnieniem okresu: 30 lat jest warte więcej niż 25.` : '',
    ].filter(Boolean),
    bedsH2: 'Ceny willi według liczby sypialni',
    bedsCols: ['Sypialnie', 'Oferty', 'Mediana', 'Środkowa połowa', 'Za m²'],
    bedLabel: b => b,
    villasH2: 'Wille: ceny według rejonów',
    villasCols: ['Rejon', 'Oferty', 'Mediana', 'Środkowa połowa', 'Za m²', '2 sypialnie', 'Dzierżawa', 'W budowie', 'PBG/SLF'],
    years: n => `${n} ${plPlural(n, 'rok', 'lata', 'lat')}`,
    aptsH2: 'Apartamenty: ceny według rejonów',
    aptsCols: ['Rejon', 'Oferty', 'Mediana', 'Środkowa połowa', 'Za m²'],
    browse: 'Zobacz',
    indicative: `* Mniej niż ${c.N} ofert: liczba orientacyjna, a nie wniosek o rejonie.`,
    columnsNote: '„Środkowa połowa” to przedział od 25. do 75. percentyla: mieści się w nim środkowa połowa cen. „Dzierżawa” to mediana pozostałego okresu dzierżawy gruntu. „PBG/SLF” to odsetek willi, dla których deweloper podaje pozwolenie na budowę (PBG) lub zaświadczenie o przydatności do użytkowania (SLF).',
    readH2: 'Jak czytać te liczby',
    read: [
      'To ceny ofertowe, a nie ceny sprzedaży. Rzeczywistych cen transakcyjnych na Bali nikt nie publikuje, a negocjacje są zwykle możliwe, zwłaszcza przy gotowych obiektach.',
      'Katalog to nie cały rynek. Obejmuje deweloperów, którzy publikują u nas; rynek wtórny i sprzedaż prywatna prawie się w nim nie pojawiają.',
      'Mediana jest odporniejsza niż średnia: jedna willa za kilka milionów jej nie przesuwa.',
      'Cena za m² liczona jest od powierzchni mieszkalnej z ogłoszenia. Działka i basen nie są wliczone, więc wille na dużych działkach wyglądają na droższe.',
    ],
    moreRead: <>Ile te domy zarabiają na wynajmie — na stronie <Link href={c.href.rent} className={A}>ceny najmu na Bali</Link>. Jak liczymy rentowność: <Link href={c.href.yield} className={A}>rentowność najmu willi według rejonów</Link>{en(c, 'pl')}.</>,
    faqH2: 'Najczęstsze pytania',
    faq: [
      { q: 'Ile kosztuje willa na Bali w 2026 roku?', a: `Mediana ceny ofertowej to ${c.$(c.V.median)} dla ${c.V.n} willi z naszego katalogu. Połowa kosztuje od ${c.$(c.V.p25)} do ${c.$(c.V.p75)}. Willa z 2 sypialniami to około ${c.$(c.I.villaByBeds['2'].median)}, z 3 sypialniami około ${c.$(c.I.villaByBeds['3'].median)}.` },
      c.cheapest ? { q: 'Gdzie na Bali nieruchomości są najtańsze?', a: `Spośród rejonów z wystarczającą liczbą ofert wille są najtańsze za m² w rejonie ${c.nm(c.cheapest[0])}: ${c.$(c.cheapest[1].perM2)}/m² (ofert: ${c.cheapest[1].n}). Apartamenty są znacznie tańsze od willi: mediana ${c.$(c.I.apartments.median)} za lokal.` } : null,
      { q: 'Czy to rzeczywiste ceny sprzedaży?', a: 'Nie. To ceny, których żądają deweloperzy. Ceny transakcyjne na Bali nie są publikowane. Traktuj te liczby jako punkt odniesienia do porównań i negocjacji, a nie jako wycenę.' },
      { q: 'Leasehold czy freehold?', a: `Prawie wszystkie wille w katalogu są sprzedawane w leasehold, czyli w długoterminowej dzierżawie gruntu. Mediana okresu to ${c.V.leaseYears ? `${c.V.leaseYears} ${plPlural(c.V.leaseYears, 'rok', 'lata', 'lat')}` : '—'}. Cudzoziemiec nie może bezpośrednio posiadać gruntu na własność (freehold).` },
    ].filter(Boolean) as Faq[],
    sourcesH2: 'Źródła i metoda',
    sources: [
      { label: `Katalog Balinsky: ${c.V.n} ${plPlural(c.V.n, 'willa', 'wille', 'willi')} i ${c.I.apartments.n} ${plPlural(c.I.apartments.n, 'apartament', 'apartamenty', 'apartamentów')} na sprzedaż, ceny ofertowe, ${c.when}`, href: c.href.catalog },
      { label: 'Jak liczymy: źródła, definicje, ograniczenia', href: c.href.method },
      { label: `Okresy dzierżawy na Bali w liczbach${en(c, 'pl')}`, href: c.href.lease },
      { label: `Strefy i pozwolenia willi na Bali w liczbach${en(c, 'pl')}`, href: c.href.zoning },
      { label: 'Rozporządzenie rządu Indonezji nr 18/2021 (prawa do gruntu)', href: c.href.pp18 },
    ],
    datasetName: 'Ceny ofertowe willi i apartamentów na Bali według rejonów',
  }),

  uk: c => ({
    title: `Ціни на нерухомість на Балі за районами — ${c.when}`,
    metaTitle: 'Ціни на вілли та апартаменти на Балі за районами (дані 2026)',
    description: `Медіанна ціна вілли на Балі — ${c.$(c.V.median)} (${c.V.n} ${ukPlural(c.V.n, 'об’єкт', 'об’єкти', 'об’єктів')}), апартаментів — ${c.$(c.I.apartments.median)}. Ціни за м², розкид, строки лізхолду і дозволи за районами. Оновлено: ${c.when}.`,
    crumb: 'Ціни на нерухомість',
    h1: 'Ціни на нерухомість на Балі за районами',
    lead: <>Медіанна ціна вілли в нашому каталозі — <strong>{c.$(c.V.median)}</strong>, половина вілл коштує від {c.$(c.V.p25)} до {c.$(c.V.p75)}. Апартаменти — <strong>{c.$(c.I.apartments.median)}</strong>. Нижче — ціна за м², розкид і умови володіння за районами. Це ціни пропозиції {c.V.n} вілл і {c.I.apartments.n} апартаментів, а не ціни угод.</>,
    updated: `Дані: ${c.when}. Перераховуються щомісяця.`,
    takeawaysH2: 'Головне в цифрах',
    takeaways: [
      `Вілла з 2 спальнями — медіана ${c.$(c.I.villaByBeds['2'].median)} (об’єктів: ${c.I.villaByBeds['2'].n}), з 3 спальнями — ${c.$(c.I.villaByBeds['3'].median)}.`,
      c.cheapest && c.dearest ? `Серед районів, де понад ${c.N} вілл, найдоступніший за ціною за м² — ${c.nm(c.cheapest[0])} (${c.$(c.cheapest[1].perM2)}/м²), найдорожчий — ${c.nm(c.dearest[0])} (${c.$(c.dearest[1].perM2)}/м²). Медіана по острову — ${c.$(c.V.perM2)}/м².` : '',
      `${c.V.offPlanShare}% вілл у каталозі ще будуються: ви купуєте проєкт, а не готовий будинок.`,
      `Дозвіл PBG або SLF указано у ${c.V.permitShare}% вілл. В інших — «немає даних» або «подано заявку».`,
      c.V.leaseYears ? `Типовий строк лізхолду — ${c.V.leaseYears} ${ukPlural(c.V.leaseYears, 'рік', 'роки', 'років')}. Порівнюйте ціни з урахуванням строку: 30 років коштують більше, ніж 25.` : '',
    ].filter(Boolean),
    bedsH2: 'Скільки коштує вілла за кількістю спалень',
    bedsCols: ['Спальні', 'Об’єктів', 'Медіана', 'Половина вілл', 'За м²'],
    bedLabel: b => (b === '4+' ? '4 і більше' : b),
    villasH2: 'Вілли: ціни за районами',
    villasCols: ['Район', 'Об’єктів', 'Медіана', 'Половина вілл', 'За м²', '2 спальні', 'Лізхолд', 'Будуються', 'PBG/SLF'],
    years: n => `${n} ${ukPlural(n, 'рік', 'роки', 'років')}`,
    aptsH2: 'Апартаменти: ціни за районами',
    aptsCols: ['Район', 'Об’єктів', 'Медіана', 'Половина', 'За м²'],
    browse: 'Дивитися',
    indicative: `* Менше ${c.N} об’єктів — цифра орієнтовна, а не висновок про район.`,
    columnsNote: '«Половина вілл» — від 25-го до 75-го перцентиля: у цей діапазон потрапляє середня половина цін. «Лізхолд» — медіанний строк оренди землі. «PBG/SLF» — частка вілл, у яких забудовник указав дозвіл на будівництво (PBG) або сертифікат придатності до експлуатації (SLF).',
    readH2: 'Як читати ці цифри',
    read: [
      'Це ціни пропозиції, а не угод. Реальних цін продажу на Балі ніхто не публікує; торг зазвичай можливий, особливо на готові об’єкти.',
      'Каталог — не весь ринок. У ньому об’єкти забудовників, які публікуються в нас; вторинний ринок і приватні продажі сюди майже не потрапляють.',
      'Медіана стійкіша за середнє: одна вілла за кілька мільйонів її не зсуває.',
      'Ціна за м² рахується за житловою площею з картки. Земля і басейн до неї не входять, тому вілли на великих ділянках виглядають дорожчими.',
    ],
    moreRead: <>Скільки ці будинки приносять в оренді — на сторінці <Link href={c.href.rent} className={A}>ціни оренди на Балі</Link>. Як рахується дохідність — у <Link href={c.href.yield} className={A}>розборі дохідності вілл за районами</Link>{en(c, 'uk')}.</>,
    faqH2: 'Часті запитання',
    faq: [
      { q: 'Скільки коштує вілла на Балі у 2026 році?', a: `Медіанна ціна пропозиції — ${c.$(c.V.median)} за ${c.V.n} віллами нашого каталогу. Половина вілл коштує від ${c.$(c.V.p25)} до ${c.$(c.V.p75)}. Вілла з 2 спальнями — близько ${c.$(c.I.villaByBeds['2'].median)}, з 3 спальнями — близько ${c.$(c.I.villaByBeds['3'].median)}.` },
      c.cheapest ? { q: 'Де на Балі нерухомість дешевша?', a: `Серед районів із достатньою вибіркою вілли найдешевші за м² у районі ${c.nm(c.cheapest[0])} — ${c.$(c.cheapest[1].perM2)}/м² (об’єктів: ${c.cheapest[1].n}). Апартаменти помітно дешевші за вілли: медіана ${c.$(c.I.apartments.median)} за об’єкт.` } : null,
      { q: 'Це реальні ціни продажу?', a: 'Ні, це ціни, які забудовники вказують у пропозиції. Ціни угод на Балі не публікуються. Використовуйте ці цифри як орієнтир для торгу й порівняння, а не як оцінку.' },
      { q: 'Лізхолд чи фрихолд?', a: `Майже всі вілли в каталозі продаються в лізхолд — довгострокову оренду землі. Медіанний строк — ${c.V.leaseYears ? `${c.V.leaseYears} ${ukPlural(c.V.leaseYears, 'рік', 'роки', 'років')}` : '—'}. Іноземець не може володіти землею у фрихолд напряму.` },
    ].filter(Boolean) as Faq[],
    sourcesH2: 'Джерела і метод',
    sources: [
      { label: `Каталог Balinsky: ${c.V.n} ${ukPlural(c.V.n, 'вілла', 'вілли', 'вілл')} і ${c.I.apartments.n} ${ukPlural(c.I.apartments.n, 'апартамент', 'апартаменти', 'апартаментів')} у продажу, ціни пропозиції, ${c.when}`, href: c.href.catalog },
      { label: 'Як ми рахуємо: джерела, визначення, обмеження', href: c.href.method },
      { label: `Строки лізхолду на Балі в цифрах${en(c, 'uk')}`, href: c.href.lease },
      { label: `Зонування і дозволи вілл на Балі в цифрах${en(c, 'uk')}`, href: c.href.zoning },
      { label: 'Постанова уряду Індонезії № 18/2021 (права на землю)', href: c.href.pp18 },
    ],
    datasetName: 'Ціни пропозиції на вілли та апартаменти на Балі за районами',
  }),
}
