// «How much is rent in Bali» copy for the non-RU/EN locales. Same shape and
// numbers as the RU/EN copy in RentIndexView.tsx.

import Link from 'next/link'
import type { Faq } from '../MarketShell'
import { A } from '../MarketShell'
import type { RentCopy, RentCtx } from '../RentIndexView'
import { IN_ENGLISH, type IntlLang } from './types'
import { plPlural, ukPlural } from './plural'

const en = (c: RentCtx, l: IntlLang) => (c.guidesInEnglish ? IN_ENGLISH[l] : '')

export const RENT_INTL: Record<IntlLang, (c: RentCtx) => RentCopy> = {
  id: c => ({
    metaTitle: 'Berapa Harga Sewa di Bali? Harga Bulanan & per Malam per Kawasan',
    description: `Sewa vila 2 kamar tidur di Bali: median ${c.$(c.two.median)} per bulan (${c.two.n} listing) atau ${c.$(c.R['2br'].median)} per malam. Harga per kawasan dan jumlah kamar, data ${c.when}.`,
    crumb: 'Harga sewa',
    h1: 'Berapa harga sewa di Bali?',
    lead: <>Vila 2 kamar tidur dengan sewa jangka panjang punya median <strong>{c.$(c.two.median)} per bulan</strong>; separuh listing ada di antara {c.$(c.two.p25)} dan {c.$(c.two.p75)}. Sebagai sewa harian, vila yang sama sekitar <strong>{c.$(c.R['2br'].median)} per malam</strong>. Harga per kawasan dan jumlah kamar ada di bawah.</>,
    updated: `Bulanan: ${c.M.n} listing dari ${c.from} sampai ${c.to}. Harian: ${c.n(c.T.villaRentals)} vila, ${c.when}.`,
    takeawaysH2: 'Angka utama',
    takeaways: [
      `Vila 1 kamar tidur disewakan sekitar ${c.$(c.M.island.villa1br.median)} per bulan, vila 3 kamar ${c.$(c.M.island.villa3br.median)}. Apartemen: ${c.$(c.M.island.apartment.median)}.`,
      c.cheapM && c.dearM ? `Di antara kawasan dengan lebih dari ${c.N} listing, ${c.nm(c.cheapM[0])} paling murah (median ${c.$(c.cheapM[1].all.median)} per bulan) dan ${c.nm(c.dearM[0])} paling mahal (${c.$(c.dearM[1].all.median)}).` : '',
      c.monthEq ? `Tiga puluh malam dengan tarif median harian menjadi ${c.$(c.monthEq)}, ${c.ratio} kali sewa bulanan. Tetapi vila harian tidak terisi setiap malam, dan pemilik membayar komisi platform dan pengelolaan.` : '',
    ].filter(Boolean),
    monthlyH2: 'Sewa bulanan menurut jumlah kamar',
    monthlyCols: ['Tipe', 'Listing', 'Median per bulan', 'Separuh tengah'],
    types: { apartment: 'Apartemen', villa1br: 'Vila, 1 kamar', villa2br: 'Vila, 2 kamar', villa3br: 'Vila, 3 kamar', villa4br: 'Vila, 4+ kamar' },
    monthlyDistrictH2: 'Sewa bulanan per kawasan',
    monthlyDistrictCols: ['Kawasan', 'Listing', 'Median', 'Separuh tengah', 'Vila 1 kamar', 'Vila 2 kamar', 'Vila 3 kamar'],
    nightlyH2: 'Tarif per malam per kawasan',
    nightlyCols: ['Kawasan', 'Vila disewakan', 'Vila 1 kamar', 'Vila 2 kamar', 'Vila 3 kamar', 'Vila 4+ kamar', 'Apartemen'],
    nightlyNote: 'Angka per malam adalah median tarif yang dipasang di platform pemesanan. Ini tarif penawaran: pendapatan nyata bergantung pada tingkat hunian, dan data hunian yang andal tidak ada, jadi kami tidak menampilkannya.',
    indicative: `* Kurang dari ${c.N} listing — indikatif. Tanda strip berarti kurang dari 5 listing.`,
    monthlyNote: `Angka bulanan adalah harga sewa yang diminta di listing sewa jangka panjang yang terbit antara ${c.from} dan ${c.to}. Listing lebih dari 180 hari tidak dihitung. Listrik, air, dan kebersihan biasanya dibayar terpisah — tanyakan kepada pemilik.`,
    moreH2: 'Jika Anda membeli untuk disewakan',
    more: <>Tarif di atas adalah pesaing vila Anda. Bagaimana tarif itu menjadi imbal hasil dan berapa yang habis untuk biaya dijelaskan di <Link href={c.href.yield} className={A}>imbal hasil sewa vila di Bali per kawasan</Link>{en(c, 'id')}. Harga beli di kawasan yang sama ada di <Link href={c.href.prices} className={A}>harga properti di Bali</Link>.</>,
    catalogue: <>Listing sewa bulanan terbaru ada di <Link href={c.href.catalog} className={A}>katalog sewa</Link>.</>,
    faqH2: 'Pertanyaan yang sering diajukan',
    faq: [
      { q: 'Berapa harga sewa di Bali per bulan?', a: `Vila 2 kamar tidur punya median ${c.$(c.two.median)} per bulan; 1 kamar ${c.$(c.M.island.villa1br.median)}; 3 kamar ${c.$(c.M.island.villa3br.median)}. Apartemen sekitar ${c.$(c.M.island.apartment.median)}. Berdasarkan ${c.M.n} listing dari ${c.from} sampai ${c.to}.` },
      { q: 'Berapa harga vila di Bali per malam?', a: `Tarif median per malam adalah ${c.$(c.R['2br'].median)} untuk vila 2 kamar, ${c.$(c.R['1br'].median)} untuk 1 kamar dan ${c.$(c.R['3br'].median)} untuk 3 kamar, dari ${c.n(c.T.villaRentals)} vila di platform pemesanan.` },
      c.cheapM ? { q: 'Di mana sewa paling murah di Bali?', a: `Di antara kawasan dengan listing yang cukup, ${c.nm(c.cheapM[0])} paling murah dengan median ${c.$(c.cheapM[1].all.median)} per bulan. Pesisir barat daya (Canggu, Berawa, Pererenan) jelas lebih mahal.` } : null,
      { q: 'Lebih murah sewa bulanan atau harian?', a: `Bulanan. Tiga puluh malam dengan tarif median harian vila 2 kamar sekitar ${c.monthEq ? c.$(c.monthEq) : '—'}, sedangkan vila yang sama disewakan ${c.$(c.two.median)} per bulan.` },
    ].filter(Boolean) as Faq[],
    sourcesH2: 'Sumber dan metode',
    sources: [
      { label: `Katalog sewa Balinsky: ${c.M.n} listing sewa jangka panjang, ${c.from} — ${c.to}`, href: c.href.catalog },
      { label: `Basis data sewa harian Balinsky: ${c.n(c.T.rentals)} properti, bersumber dari estatemarket.io`, href: c.href.estatemarket },
      { label: 'Cara kami menghitung: sumber, definisi, batasan', href: c.href.method },
      { label: `Tarif sewa vila di Bali per kawasan${en(c, 'id')}`, href: c.href.rates },
      { label: 'Statistik pariwisata Bali (BPS)', href: c.href.bps },
    ],
    datasetName: 'Harga sewa di Bali: bulanan dan harian, per kawasan',
  }),

  fr: c => ({
    metaTitle: 'Combien coûte un loyer à Bali ? Prix au mois et à la nuit par quartier',
    description: `Louer une villa de 2 chambres à Bali : médiane de ${c.$(c.two.median)} par mois (${c.two.n} annonces) ou ${c.$(c.R['2br'].median)} la nuit. Prix par quartier et par nombre de chambres, données ${c.when}.`,
    crumb: 'Prix des locations',
    h1: 'Combien coûte un loyer à Bali ?',
    lead: <>Une villa de 2 chambres en location longue durée a un loyer médian de <strong>{c.$(c.two.median)} par mois</strong> ; la moitié des annonces se situent entre {c.$(c.two.p25)} et {c.$(c.two.p75)}. En location de vacances, la même villa se loue environ <strong>{c.$(c.R['2br'].median)} la nuit</strong>. Les prix par quartier et par nombre de chambres sont ci-dessous.</>,
    updated: `Au mois : ${c.M.n} annonces du ${c.from} au ${c.to}. À la nuit : ${c.n(c.T.villaRentals)} villas, ${c.when}.`,
    takeawaysH2: 'Les chiffres clés',
    takeaways: [
      `Une villa d’une chambre se loue environ ${c.$(c.M.island.villa1br.median)} par mois, une villa de 3 chambres ${c.$(c.M.island.villa3br.median)}. Appartements : ${c.$(c.M.island.apartment.median)}.`,
      c.cheapM && c.dearM ? `Parmi les quartiers de plus de ${c.N} annonces, ${c.nm(c.cheapM[0])} est le moins cher (médiane de ${c.$(c.cheapM[1].all.median)} par mois) et ${c.nm(c.dearM[0])} le plus cher (${c.$(c.dearM[1].all.median)}).` : '',
      c.monthEq ? `Trente nuits au tarif médian reviennent à ${c.$(c.monthEq)}, soit ${c.ratio} fois le loyer mensuel. Mais une villa de vacances n’est pas louée chaque nuit, et le propriétaire paie les commissions des plateformes et la gestion.` : '',
    ].filter(Boolean),
    monthlyH2: 'Loyer mensuel selon le nombre de chambres',
    monthlyCols: ['Type', 'Annonces', 'Médiane par mois', 'Moitié centrale'],
    types: { apartment: 'Appartement', villa1br: 'Villa, 1 chambre', villa2br: 'Villa, 2 chambres', villa3br: 'Villa, 3 chambres', villa4br: 'Villa, 4+ chambres' },
    monthlyDistrictH2: 'Loyer mensuel par quartier',
    monthlyDistrictCols: ['Quartier', 'Annonces', 'Médiane', 'Moitié centrale', 'Villa 1 ch.', 'Villa 2 ch.', 'Villa 3 ch.'],
    nightlyH2: 'Tarifs à la nuit par quartier',
    nightlyCols: ['Quartier', 'Villas en location', 'Villa 1 ch.', 'Villa 2 ch.', 'Villa 3 ch.', 'Villa 4+ ch.', 'Appartement'],
    nightlyNote: 'Les tarifs à la nuit sont les médianes des prix affichés sur les plateformes de réservation. Ce sont des prix demandés : le revenu réel dépend du taux d’occupation, et il n’existe pas de données fiables sur l’occupation, nous ne l’affichons donc pas.',
    indicative: `* Moins de ${c.N} annonces : indicatif. Un tiret signifie moins de 5 annonces.`,
    monthlyNote: `Les chiffres mensuels sont les loyers demandés dans les annonces de location longue durée publiées du ${c.from} au ${c.to}. Les annonces de plus de 180 jours sont exclues. Charges et ménage sont en général en plus — renseignez-vous auprès du propriétaire.`,
    moreH2: 'Si vous achetez pour louer',
    more: <>Les tarifs ci-dessus sont la concurrence de votre villa. Comment ils se traduisent en rendement, et ce que les coûts en retirent, est expliqué dans <Link href={c.href.yield} className={A}>rendement locatif des villas à Bali par quartier</Link>{en(c, 'fr')}. Les prix d’achat dans les mêmes quartiers sont sur la page <Link href={c.href.prices} className={A}>prix de l’immobilier à Bali</Link>.</>,
    catalogue: <>Les annonces de location au mois les plus récentes sont dans le <Link href={c.href.catalog} className={A}>catalogue des locations</Link>.</>,
    faqH2: 'Questions fréquentes',
    faq: [
      { q: 'Combien coûte un loyer à Bali par mois ?', a: `Une villa de 2 chambres a un loyer médian de ${c.$(c.two.median)} par mois ; une chambre, ${c.$(c.M.island.villa1br.median)} ; 3 chambres, ${c.$(c.M.island.villa3br.median)}. Les appartements tournent autour de ${c.$(c.M.island.apartment.median)}. Sur la base de ${c.M.n} annonces du ${c.from} au ${c.to}.` },
      { q: 'Combien coûte une villa à Bali la nuit ?', a: `Le tarif médian est de ${c.$(c.R['2br'].median)} la nuit pour une villa de 2 chambres, ${c.$(c.R['1br'].median)} pour une chambre et ${c.$(c.R['3br'].median)} pour 3 chambres, sur ${c.n(c.T.villaRentals)} villas des plateformes de réservation.` },
      c.cheapM ? { q: 'Où les loyers sont-ils les moins chers à Bali ?', a: `Parmi les quartiers ayant assez d’annonces, ${c.nm(c.cheapM[0])} est le moins cher, avec une médiane de ${c.$(c.cheapM[1].all.median)} par mois. La côte sud-ouest (Canggu, Berawa, Pererenan) est nettement plus chère.` } : null,
      { q: 'Vaut-il mieux louer au mois ou à la nuit ?', a: `Au mois. Trente nuits au tarif médian d’une villa de 2 chambres reviennent à environ ${c.monthEq ? c.$(c.monthEq) : '—'}, alors que la même villa se loue ${c.$(c.two.median)} par mois.` },
    ].filter(Boolean) as Faq[],
    sourcesH2: 'Sources et méthode',
    sources: [
      { label: `Catalogue des locations Balinsky : ${c.M.n} annonces longue durée, ${c.from} — ${c.to}`, href: c.href.catalog },
      { label: `Base de locations de vacances Balinsky : ${c.n(c.T.rentals)} biens, source estatemarket.io`, href: c.href.estatemarket },
      { label: 'Notre méthode : sources, définitions, limites', href: c.href.method },
      { label: `Tarifs de location des villas à Bali par quartier${en(c, 'fr')}`, href: c.href.rates },
      { label: 'Statistiques du tourisme à Bali (BPS)', href: c.href.bps },
    ],
    datasetName: 'Prix des locations à Bali : au mois et à la nuit, par quartier',
  }),

  de: c => ({
    metaTitle: 'Was kostet Miete auf Bali? Monats- und Nachtpreise nach Gegend',
    description: `Eine Villa mit 2 Schlafzimmern auf Bali mieten: Median ${c.$(c.two.median)} pro Monat (${c.two.n} Angebote) oder ${c.$(c.R['2br'].median)} pro Nacht. Preise nach Gegend und Schlafzimmern, Daten ${c.when}.`,
    crumb: 'Mietpreise',
    h1: 'Was kostet Miete auf Bali?',
    lead: <>Eine Villa mit 2 Schlafzimmern kostet bei Langzeitmiete im Median <strong>{c.$(c.two.median)} pro Monat</strong>; die Hälfte der Angebote liegt zwischen {c.$(c.two.p25)} und {c.$(c.two.p75)}. Als Ferienvilla kostet dieselbe Villa rund <strong>{c.$(c.R['2br'].median)} pro Nacht</strong>. Preise nach Gegend und Zahl der Schlafzimmer stehen unten.</>,
    updated: `Monatlich: ${c.M.n} Angebote vom ${c.from} bis ${c.to}. Pro Nacht: ${c.n(c.T.villaRentals)} Villen, ${c.when}.`,
    takeawaysH2: 'Die wichtigsten Zahlen',
    takeaways: [
      `Eine Villa mit 1 Schlafzimmer kostet rund ${c.$(c.M.island.villa1br.median)} im Monat, mit 3 Schlafzimmern ${c.$(c.M.island.villa3br.median)}. Wohnungen: ${c.$(c.M.island.apartment.median)}.`,
      c.cheapM && c.dearM ? `Unter den Gegenden mit mehr als ${c.N} Angeboten ist ${c.nm(c.cheapM[0])} am günstigsten (Median ${c.$(c.cheapM[1].all.median)} im Monat) und ${c.nm(c.dearM[0])} am teuersten (${c.$(c.dearM[1].all.median)}).` : '',
      c.monthEq ? `Dreißig Nächte zum Median-Nachtpreis ergeben ${c.$(c.monthEq)}, das ${c.ratio}-Fache der Monatsmiete. Aber eine Ferienvilla ist nicht jede Nacht belegt, und der Eigentümer zahlt Plattformgebühren und Verwaltung.` : '',
    ].filter(Boolean),
    monthlyH2: 'Monatsmiete nach Schlafzimmern',
    monthlyCols: ['Typ', 'Angebote', 'Median pro Monat', 'Mittlere Hälfte'],
    types: { apartment: 'Wohnung', villa1br: 'Villa, 1 Schlafzimmer', villa2br: 'Villa, 2 Schlafzimmer', villa3br: 'Villa, 3 Schlafzimmer', villa4br: 'Villa, 4+ Schlafzimmer' },
    monthlyDistrictH2: 'Monatsmiete nach Gegend',
    monthlyDistrictCols: ['Gegend', 'Angebote', 'Median', 'Mittlere Hälfte', 'Villa 1 SZ', 'Villa 2 SZ', 'Villa 3 SZ'],
    nightlyH2: 'Nachtpreise nach Gegend',
    nightlyCols: ['Gegend', 'Villen zur Miete', 'Villa 1 SZ', 'Villa 2 SZ', 'Villa 3 SZ', 'Villa 4+ SZ', 'Wohnung'],
    nightlyNote: 'Nachtpreise sind die Mediane der auf Buchungsplattformen angegebenen Preise. Es sind Angebotspreise: Der tatsächliche Umsatz hängt von der Auslastung ab, und verlässliche Auslastungsdaten gibt es nicht, deshalb zeigen wir sie nicht.',
    indicative: `* Weniger als ${c.N} Angebote: Richtwert. Ein Strich bedeutet weniger als 5 Angebote.`,
    monthlyNote: `Die Monatswerte sind geforderte Mieten aus Langzeit-Mietangeboten, die zwischen ${c.from} und ${c.to} veröffentlicht wurden. Ältere Angebote als 180 Tage bleiben außen vor. Nebenkosten und Reinigung kommen meist hinzu — fragen Sie den Vermieter.`,
    moreH2: 'Wenn Sie zum Vermieten kaufen',
    more: <>Mit diesen Preisen konkurriert Ihre Villa. Wie daraus eine Rendite wird und wie viel die Kosten aufzehren, steht in <Link href={c.href.yield} className={A}>Mietrendite von Villen auf Bali nach Gegend</Link>{en(c, 'de')}. Kaufpreise in denselben Gegenden finden Sie unter <Link href={c.href.prices} className={A}>Immobilienpreise auf Bali</Link>.</>,
    catalogue: <>Aktuelle Monatsmiet-Angebote stehen im <Link href={c.href.catalog} className={A}>Mietkatalog</Link>.</>,
    faqH2: 'Häufige Fragen',
    faq: [
      { q: 'Was kostet Miete auf Bali im Monat?', a: `Eine Villa mit 2 Schlafzimmern kostet im Median ${c.$(c.two.median)} im Monat, mit 1 Schlafzimmer ${c.$(c.M.island.villa1br.median)}, mit 3 Schlafzimmern ${c.$(c.M.island.villa3br.median)}. Wohnungen liegen bei etwa ${c.$(c.M.island.apartment.median)}. Grundlage: ${c.M.n} Angebote vom ${c.from} bis ${c.to}.` },
      { q: 'Was kostet eine Villa auf Bali pro Nacht?', a: `Der Median-Nachtpreis liegt bei ${c.$(c.R['2br'].median)} für eine Villa mit 2 Schlafzimmern, ${c.$(c.R['1br'].median)} mit 1 Schlafzimmer und ${c.$(c.R['3br'].median)} mit 3 Schlafzimmern, über ${c.n(c.T.villaRentals)} Villen auf Buchungsplattformen.` },
      c.cheapM ? { q: 'Wo ist Miete auf Bali am günstigsten?', a: `Unter den Gegenden mit genug Angeboten ist ${c.nm(c.cheapM[0])} am günstigsten, mit einem Median von ${c.$(c.cheapM[1].all.median)} im Monat. Die Südwestküste (Canggu, Berawa, Pererenan) ist deutlich teurer.` } : null,
      { q: 'Ist Monatsmiete oder Tagesmiete günstiger?', a: `Monatsmiete. Dreißig Nächte zum Median-Nachtpreis einer Villa mit 2 Schlafzimmern kosten etwa ${c.monthEq ? c.$(c.monthEq) : '—'}, dieselbe Villa kostet im Monat ${c.$(c.two.median)}.` },
    ].filter(Boolean) as Faq[],
    sourcesH2: 'Quellen und Methode',
    sources: [
      { label: `Balinsky-Mietkatalog: ${c.M.n} Langzeit-Mietangebote, ${c.from} — ${c.to}`, href: c.href.catalog },
      { label: `Balinsky-Datenbank für Ferienvermietung: ${c.n(c.T.rentals)} Objekte, Quelle estatemarket.io`, href: c.href.estatemarket },
      { label: 'So rechnen wir: Quellen, Definitionen, Grenzen', href: c.href.method },
      { label: `Mietpreise für Villen auf Bali nach Gegend${en(c, 'de')}`, href: c.href.rates },
      { label: 'Tourismusstatistik Bali (BPS)', href: c.href.bps },
    ],
    datasetName: 'Mietpreise auf Bali: monatlich und pro Nacht, nach Gegend',
  }),

  zh: c => ({
    metaTitle: '巴厘岛租房多少钱？各区域月租和每晚价格',
    description: `在巴厘岛租一套两居室别墅：月租中位数${c.$(c.two.median)}（${c.two.n}条房源），或每晚${c.$(c.R['2br'].median)}。按区域和卧室数量列出价格，数据时间${c.when}。`,
    crumb: '租金价格',
    h1: '巴厘岛租房多少钱？',
    lead: <>长租两居室别墅的月租中位数为<strong>{c.$(c.two.median)}</strong>，一半房源在{c.$(c.two.p25)}到{c.$(c.two.p75)}之间。作为度假短租，同样的别墅约<strong>每晚{c.$(c.R['2br'].median)}</strong>。各区域和不同卧室数量的价格见下方。</>,
    updated: `月租：${c.M.n}条房源，${c.from}至${c.to}。按晚：${c.n(c.T.villaRentals)}套别墅，${c.when}。`,
    takeawaysH2: '关键数字',
    takeaways: [
      `一居室别墅月租约${c.$(c.M.island.villa1br.median)}，三居室约${c.$(c.M.island.villa3br.median)}。公寓：${c.$(c.M.island.apartment.median)}。`,
      c.cheapM && c.dearM ? `在房源超过${c.N}条的区域中，${c.nm(c.cheapM[0])}最便宜（月租中位数${c.$(c.cheapM[1].all.median)}），${c.nm(c.dearM[0])}最贵（${c.$(c.dearM[1].all.median)}）。` : '',
      c.monthEq ? `按每晚中位价住三十晚共${c.$(c.monthEq)}，是月租的${c.ratio}倍。但度假别墅并非每晚都有人住，业主还要支付平台佣金和管理费。` : '',
    ].filter(Boolean),
    monthlyH2: '按卧室数量划分的月租',
    monthlyCols: ['类型', '房源数', '月租中位数', '中间一半'],
    types: { apartment: '公寓', villa1br: '别墅，一居室', villa2br: '别墅，两居室', villa3br: '别墅，三居室', villa4br: '别墅，四居室及以上' },
    monthlyDistrictH2: '各区域月租',
    monthlyDistrictCols: ['区域', '房源数', '中位数', '中间一半', '一居室别墅', '两居室别墅', '三居室别墅'],
    nightlyH2: '各区域每晚价格',
    nightlyCols: ['区域', '出租别墅数', '一居室别墅', '两居室别墅', '三居室别墅', '四居室+别墅', '公寓'],
    nightlyNote: '每晚价格是预订平台上标价的中位数。这是要价：实际收入取决于入住率，而可靠的入住率数据并不存在，因此我们不展示。',
    indicative: `* 房源少于${c.N}条：仅供参考。短横线表示少于5条房源。`,
    monthlyNote: `月租数字是${c.from}至${c.to}期间发布的长租房源的要价。超过180天的房源不计入。水电和清洁费通常另付，请向房东确认。`,
    moreH2: '如果您买房用于出租',
    more: <>上面的价格就是您的别墅将面对的竞争。这些价格如何转化为收益、成本占去多少，见<Link href={c.href.yield} className={A}>巴厘岛各区域别墅租金收益率</Link>{en(c, 'zh')}。同一区域的购买价格见<Link href={c.href.prices} className={A}>巴厘岛房产价格</Link>。</>,
    catalogue: <>最新的月租房源在<Link href={c.href.catalog} className={A}>租房目录</Link>中。</>,
    faqH2: '常见问题',
    faq: [
      { q: '巴厘岛每月租金多少？', a: `两居室别墅月租中位数为${c.$(c.two.median)}，一居室${c.$(c.M.island.villa1br.median)}，三居室${c.$(c.M.island.villa3br.median)}。公寓约${c.$(c.M.island.apartment.median)}。基于${c.from}至${c.to}的${c.M.n}条房源。` },
      { q: '巴厘岛别墅每晚多少钱？', a: `两居室别墅每晚中位价为${c.$(c.R['2br'].median)}，一居室${c.$(c.R['1br'].median)}，三居室${c.$(c.R['3br'].median)}，数据来自预订平台上的${c.n(c.T.villaRentals)}套别墅。` },
      c.cheapM ? { q: '巴厘岛哪里租金最便宜？', a: `在房源足够多的区域中，${c.nm(c.cheapM[0])}最便宜，月租中位数${c.$(c.cheapM[1].all.median)}。西南海岸（Canggu、Berawa、Pererenan）明显更贵。` } : null,
      { q: '按月租还是按晚租更划算？', a: `按月租。两居室别墅按每晚中位价住三十晚约${c.monthEq ? c.$(c.monthEq) : '—'}，而同样的别墅月租为${c.$(c.two.median)}。` },
    ].filter(Boolean) as Faq[],
    sourcesH2: '来源与方法',
    sources: [
      { label: `Balinsky租房目录：${c.M.n}条长租房源，${c.from} — ${c.to}`, href: c.href.catalog },
      { label: `Balinsky度假短租数据库：${c.n(c.T.rentals)}处房产，来源estatemarket.io`, href: c.href.estatemarket },
      { label: '我们如何计算：来源、定义、局限', href: c.href.method },
      { label: `巴厘岛各区域别墅租金${en(c, 'zh')}`, href: c.href.rates },
      { label: '巴厘岛旅游统计（BPS）', href: c.href.bps },
    ],
    datasetName: '巴厘岛租金：各区域月租和每晚价格',
  }),

  nl: c => ({
    metaTitle: 'Wat kost huren op Bali? Prijzen per maand en per nacht per gebied',
    description: `Een villa met 2 slaapkamers huren op Bali: mediaan ${c.$(c.two.median)} per maand (${c.two.n} advertenties) of ${c.$(c.R['2br'].median)} per nacht. Prijzen per gebied en aantal slaapkamers, data ${c.when}.`,
    crumb: 'Huurprijzen',
    h1: 'Wat kost huren op Bali?',
    lead: <>Een villa met 2 slaapkamers op een langlopend huurcontract heeft een mediane huur van <strong>{c.$(c.two.median)} per maand</strong>; de helft van de advertenties zit tussen {c.$(c.two.p25)} en {c.$(c.two.p75)}. Als vakantieverhuur kost dezelfde villa ongeveer <strong>{c.$(c.R['2br'].median)} per nacht</strong>. Prijzen per gebied en aantal slaapkamers staan hieronder.</>,
    updated: `Per maand: ${c.M.n} advertenties van ${c.from} tot ${c.to}. Per nacht: ${c.n(c.T.villaRentals)} villa’s, ${c.when}.`,
    takeawaysH2: 'De belangrijkste cijfers',
    takeaways: [
      `Een villa met 1 slaapkamer huurt voor ongeveer ${c.$(c.M.island.villa1br.median)} per maand, met 3 slaapkamers voor ${c.$(c.M.island.villa3br.median)}. Appartementen: ${c.$(c.M.island.apartment.median)}.`,
      c.cheapM && c.dearM ? `Van de gebieden met meer dan ${c.N} advertenties is ${c.nm(c.cheapM[0])} het goedkoopst (mediaan ${c.$(c.cheapM[1].all.median)} per maand) en ${c.nm(c.dearM[0])} het duurst (${c.$(c.dearM[1].all.median)}).` : '',
      c.monthEq ? `Dertig nachten tegen het mediane nachttarief kosten ${c.$(c.monthEq)}, ${c.ratio} keer de maandhuur. Maar een vakantievilla is niet elke nacht bezet, en de eigenaar betaalt platformcommissies en beheer.` : '',
    ].filter(Boolean),
    monthlyH2: 'Maandhuur naar aantal slaapkamers',
    monthlyCols: ['Type', 'Advertenties', 'Mediaan per maand', 'Middelste helft'],
    types: { apartment: 'Appartement', villa1br: 'Villa, 1 slaapkamer', villa2br: 'Villa, 2 slaapkamers', villa3br: 'Villa, 3 slaapkamers', villa4br: 'Villa, 4+ slaapkamers' },
    monthlyDistrictH2: 'Maandhuur per gebied',
    monthlyDistrictCols: ['Gebied', 'Advertenties', 'Mediaan', 'Middelste helft', 'Villa 1 slpk', 'Villa 2 slpk', 'Villa 3 slpk'],
    nightlyH2: 'Nachttarieven per gebied',
    nightlyCols: ['Gebied', 'Villa’s te huur', 'Villa 1 slpk', 'Villa 2 slpk', 'Villa 3 slpk', 'Villa 4+ slpk', 'Appartement'],
    nightlyNote: 'Nachttarieven zijn medianen van de tarieven op boekingsplatforms. Het zijn vraagprijzen: de werkelijke omzet hangt af van de bezetting, en betrouwbare bezettingsdata bestaat niet, dus die tonen we niet.',
    indicative: `* Minder dan ${c.N} advertenties: indicatief. Een streepje betekent minder dan 5 advertenties.`,
    monthlyNote: `De maandcijfers zijn gevraagde huren uit advertenties voor langdurige verhuur, geplaatst tussen ${c.from} en ${c.to}. Advertenties ouder dan 180 dagen tellen niet mee. Gas, water, licht en schoonmaak komen er meestal bij — vraag het de verhuurder.`,
    moreH2: 'Als u koopt om te verhuren',
    more: <>Met de tarieven hierboven concurreert uw villa. Hoe die tot rendement leiden en hoeveel de kosten opslokken, staat in <Link href={c.href.yield} className={A}>huurrendement van villa’s op Bali per gebied</Link>{en(c, 'nl')}. Koopprijzen in dezelfde gebieden vindt u op <Link href={c.href.prices} className={A}>vastgoedprijzen op Bali</Link>.</>,
    catalogue: <>Actuele advertenties voor maandhuur staan in de <Link href={c.href.catalog} className={A}>huurcatalogus</Link>.</>,
    faqH2: 'Veelgestelde vragen',
    faq: [
      { q: 'Wat kost huren op Bali per maand?', a: `Een villa met 2 slaapkamers heeft een mediane huur van ${c.$(c.two.median)} per maand; met 1 slaapkamer ${c.$(c.M.island.villa1br.median)}; met 3 slaapkamers ${c.$(c.M.island.villa3br.median)}. Appartementen zitten rond ${c.$(c.M.island.apartment.median)}. Op basis van ${c.M.n} advertenties van ${c.from} tot ${c.to}.` },
      { q: 'Wat kost een villa op Bali per nacht?', a: `Het mediane nachttarief is ${c.$(c.R['2br'].median)} voor een villa met 2 slaapkamers, ${c.$(c.R['1br'].median)} met 1 slaapkamer en ${c.$(c.R['3br'].median)} met 3 slaapkamers, over ${c.n(c.T.villaRentals)} villa’s op boekingsplatforms.` },
      c.cheapM ? { q: 'Waar is huren op Bali het goedkoopst?', a: `Van de gebieden met genoeg advertenties is ${c.nm(c.cheapM[0])} het goedkoopst, met een mediaan van ${c.$(c.cheapM[1].all.median)} per maand. De zuidwestkust (Canggu, Berawa, Pererenan) is duidelijk duurder.` } : null,
      { q: 'Is huren per maand of per nacht goedkoper?', a: `Per maand. Dertig nachten tegen het mediane nachttarief van een villa met 2 slaapkamers kosten ongeveer ${c.monthEq ? c.$(c.monthEq) : '—'}, terwijl dezelfde villa ${c.$(c.two.median)} per maand kost.` },
    ].filter(Boolean) as Faq[],
    sourcesH2: 'Bronnen en methode',
    sources: [
      { label: `Balinsky-huurcatalogus: ${c.M.n} advertenties voor langdurige verhuur, ${c.from} — ${c.to}`, href: c.href.catalog },
      { label: `Balinsky-database vakantieverhuur: ${c.n(c.T.rentals)} objecten, bron estatemarket.io`, href: c.href.estatemarket },
      { label: 'Hoe we rekenen: bronnen, definities, beperkingen', href: c.href.method },
      { label: `Huurtarieven van villa’s op Bali per gebied${en(c, 'nl')}`, href: c.href.rates },
      { label: 'Toerismestatistieken Bali (BPS)', href: c.href.bps },
    ],
    datasetName: 'Huurprijzen op Bali: per maand en per nacht, per gebied',
  }),

  pl: c => ({
    metaTitle: 'Ile kosztuje najem na Bali? Ceny miesięczne i za noc według rejonów',
    description: `Najem willi z 2 sypialniami na Bali: mediana ${c.$(c.two.median)} miesięcznie (ogłoszeń: ${c.two.n}) lub ${c.$(c.R['2br'].median)} za noc. Ceny według rejonów i liczby sypialni, dane: ${c.when}.`,
    crumb: 'Ceny najmu',
    h1: 'Ile kosztuje najem na Bali?',
    lead: <>Willa z 2 sypialniami w najmie długoterminowym ma medianę czynszu <strong>{c.$(c.two.median)} miesięcznie</strong>; połowa ogłoszeń mieści się między {c.$(c.two.p25)} a {c.$(c.two.p75)}. W najmie krótkoterminowym ta sama willa kosztuje około <strong>{c.$(c.R['2br'].median)} za noc</strong>. Ceny według rejonów i liczby sypialni są poniżej.</>,
    updated: `Miesięcznie: ${c.M.n} ${plPlural(c.M.n, 'ogłoszenie', 'ogłoszenia', 'ogłoszeń')} od ${c.from} do ${c.to}. Za noc: ${c.n(c.T.villaRentals)} ${plPlural(c.T.villaRentals, 'willa', 'wille', 'willi')}, ${c.when}.`,
    takeawaysH2: 'Najważniejsze liczby',
    takeaways: [
      `Willa z 1 sypialnią kosztuje około ${c.$(c.M.island.villa1br.median)} miesięcznie, z 3 sypialniami ${c.$(c.M.island.villa3br.median)}. Apartamenty: ${c.$(c.M.island.apartment.median)}.`,
      c.cheapM && c.dearM ? `Spośród rejonów z ponad ${c.N} ogłoszeniami najtańszy jest ${c.nm(c.cheapM[0])} (mediana ${c.$(c.cheapM[1].all.median)} miesięcznie), najdroższy ${c.nm(c.dearM[0])} (${c.$(c.dearM[1].all.median)}).` : '',
      c.monthEq ? `Trzydzieści nocy po medianowej stawce to ${c.$(c.monthEq)}, czyli ${c.ratio} raza więcej niż czynsz miesięczny. Ale willa na doby nie jest zajęta każdej nocy, a właściciel płaci prowizje platform i za zarządzanie.` : '',
    ].filter(Boolean),
    monthlyH2: 'Czynsz miesięczny według liczby sypialni',
    monthlyCols: ['Typ', 'Ogłoszenia', 'Mediana miesięcznie', 'Środkowa połowa'],
    types: { apartment: 'Apartament', villa1br: 'Willa, 1 sypialnia', villa2br: 'Willa, 2 sypialnie', villa3br: 'Willa, 3 sypialnie', villa4br: 'Willa, 4+ sypialnie' },
    monthlyDistrictH2: 'Czynsz miesięczny według rejonów',
    monthlyDistrictCols: ['Rejon', 'Ogłoszenia', 'Mediana', 'Środkowa połowa', 'Willa 1 syp.', 'Willa 2 syp.', 'Willa 3 syp.'],
    nightlyH2: 'Stawki za noc według rejonów',
    nightlyCols: ['Rejon', 'Wille na wynajem', 'Willa 1 syp.', 'Willa 2 syp.', 'Willa 3 syp.', 'Willa 4+ syp.', 'Apartament'],
    nightlyNote: 'Stawki za noc to mediany cen wystawionych na platformach rezerwacyjnych. To ceny ofertowe: rzeczywisty przychód zależy od obłożenia, a wiarygodnych danych o obłożeniu nie ma, więc go nie pokazujemy.',
    indicative: `* Mniej niż ${c.N} ogłoszeń: wartość orientacyjna. Kreska oznacza mniej niż 5 ogłoszeń.`,
    monthlyNote: `Wartości miesięczne to czynsze z ogłoszeń najmu długoterminowego opublikowanych od ${c.from} do ${c.to}. Ogłoszenia starsze niż 180 dni nie są liczone. Media i sprzątanie są zwykle płatne osobno — zapytaj wynajmującego.`,
    moreH2: 'Jeśli kupujesz pod wynajem',
    more: <>Z tymi stawkami będzie konkurować twoja willa. Jak przekładają się na rentowność i ile zjadają koszty, opisujemy w artykule <Link href={c.href.yield} className={A}>rentowność najmu willi na Bali według rejonów</Link>{en(c, 'pl')}. Ceny zakupu w tych samych rejonach są na stronie <Link href={c.href.prices} className={A}>ceny nieruchomości na Bali</Link>.</>,
    catalogue: <>Aktualne ogłoszenia najmu miesięcznego są w <Link href={c.href.catalog} className={A}>katalogu najmu</Link>.</>,
    faqH2: 'Najczęstsze pytania',
    faq: [
      { q: 'Ile kosztuje najem na Bali miesięcznie?', a: `Willa z 2 sypialniami ma medianę ${c.$(c.two.median)} miesięcznie, z 1 sypialnią ${c.$(c.M.island.villa1br.median)}, z 3 sypialniami ${c.$(c.M.island.villa3br.median)}. Apartamenty to około ${c.$(c.M.island.apartment.median)}. Na podstawie ${c.M.n} ogłoszeń od ${c.from} do ${c.to}.` },
      { q: 'Ile kosztuje willa na Bali za noc?', a: `Medianowa stawka to ${c.$(c.R['2br'].median)} za noc za willę z 2 sypialniami, ${c.$(c.R['1br'].median)} z 1 sypialnią i ${c.$(c.R['3br'].median)} z 3 sypialniami, według ${c.n(c.T.villaRentals)} willi na platformach rezerwacyjnych.` },
      c.cheapM ? { q: 'Gdzie na Bali najem jest najtańszy?', a: `Spośród rejonów z wystarczającą liczbą ogłoszeń najtańszy jest ${c.nm(c.cheapM[0])}: mediana ${c.$(c.cheapM[1].all.median)} miesięcznie. Południowo-zachodnie wybrzeże (Canggu, Berawa, Pererenan) jest wyraźnie droższe.` } : null,
      { q: 'Taniej wynająć na miesiąc czy na doby?', a: `Na miesiąc. Trzydzieści nocy po medianowej stawce willi z 2 sypialniami to około ${c.monthEq ? c.$(c.monthEq) : '—'}, a ta sama willa na miesiąc kosztuje ${c.$(c.two.median)}.` },
    ].filter(Boolean) as Faq[],
    sourcesH2: 'Źródła i metoda',
    sources: [
      { label: `Katalog najmu Balinsky: ${c.M.n} ${plPlural(c.M.n, 'ogłoszenie', 'ogłoszenia', 'ogłoszeń')} najmu długoterminowego, ${c.from} — ${c.to}`, href: c.href.catalog },
      { label: `Baza najmu krótkoterminowego Balinsky: ${c.n(c.T.rentals)} ${plPlural(c.T.rentals, 'obiekt', 'obiekty', 'obiektów')}, źródło estatemarket.io`, href: c.href.estatemarket },
      { label: 'Jak liczymy: źródła, definicje, ograniczenia', href: c.href.method },
      { label: `Stawki najmu willi na Bali według rejonów${en(c, 'pl')}`, href: c.href.rates },
      { label: 'Statystyki turystyki Bali (BPS)', href: c.href.bps },
    ],
    datasetName: 'Ceny najmu na Bali: miesięcznie i za noc, według rejonów',
  }),

  uk: c => ({
    metaTitle: 'Скільки коштує оренда на Балі: ціни за місяць і за ніч за районами',
    description: `Оренда вілли з 2 спальнями на Балі — медіана ${c.$(c.two.median)} на місяць (оголошень: ${c.two.n}), за ніч — ${c.$(c.R['2br'].median)}. Ціни за районами і кількістю спалень, дані: ${c.when}.`,
    crumb: 'Ціни оренди',
    h1: 'Скільки коштує оренда на Балі',
    lead: <>Вілла з 2 спальнями в довгострокову оренду — медіана <strong>{c.$(c.two.median)} на місяць</strong>, половина оголошень від {c.$(c.two.p25)} до {c.$(c.two.p75)}. Подобово така вілла коштує близько <strong>{c.$(c.R['2br'].median)} за ніч</strong>. Нижче — ціни за районами і кількістю спалень.</>,
    updated: `Помісячна оренда — ${c.M.n} ${ukPlural(c.M.n, 'оголошення', 'оголошення', 'оголошень')} з ${c.from} по ${c.to}; подобова — ${c.n(c.T.villaRentals)} ${ukPlural(c.T.villaRentals, 'вілла', 'вілли', 'вілл')}, дані: ${c.when}`,
    takeawaysH2: 'Головне в цифрах',
    takeaways: [
      `Вілла з 1 спальнею — близько ${c.$(c.M.island.villa1br.median)} на місяць, з 3 спальнями — ${c.$(c.M.island.villa3br.median)}. Апартаменти — ${c.$(c.M.island.apartment.median)}.`,
      c.cheapM && c.dearM ? `Серед районів, де понад ${c.N} оголошень, найдешевший — ${c.nm(c.cheapM[0])} (медіана ${c.$(c.cheapM[1].all.median)} на місяць), найдорожчий — ${c.nm(c.dearM[0])} (${c.$(c.dearM[1].all.median)}).` : '',
      c.monthEq ? `30 ночей подобово за медіанною ставкою — ${c.$(c.monthEq)}, це в ${c.ratio} раза більше за місячну ціну. Але подобова вілла зайнята не щодня, а власник платить комісії та за управління.` : '',
    ].filter(Boolean),
    monthlyH2: 'Помісячна оренда за кількістю спалень',
    monthlyCols: ['Тип', 'Оголошень', 'Медіана на місяць', 'Половина оголошень'],
    types: { apartment: 'Апартаменти', villa1br: 'Вілла, 1 спальня', villa2br: 'Вілла, 2 спальні', villa3br: 'Вілла, 3 спальні', villa4br: 'Вілла, 4+ спальні' },
    monthlyDistrictH2: 'Помісячна оренда за районами',
    monthlyDistrictCols: ['Район', 'Оголошень', 'Медіана', 'Половина оголошень', 'Вілла 1 сп.', 'Вілла 2 сп.', 'Вілла 3 сп.'],
    nightlyH2: 'Подобова оренда за районами',
    nightlyCols: ['Район', 'Вілл в оренді', 'Вілла 1 сп.', 'Вілла 2 сп.', 'Вілла 3 сп.', 'Вілла 4+ сп.', 'Апартаменти'],
    nightlyNote: 'Ціни за ніч — медіани ставок, які об’єкти виставляють на майданчиках бронювання. Це ціна пропозиції: реальний виторг залежить від завантаження, а надійних даних про завантаження немає, тому ми його не показуємо.',
    indicative: `* Менше ${c.N} оголошень — цифра орієнтовна. Прочерк — менше 5 оголошень.`,
    monthlyNote: `Помісячні ціни — це ціни з оголошень про довгострокову оренду, опублікованих з ${c.from} по ${c.to}; старші за 180 днів у розрахунок не потрапляють. Комунальні платежі й прибирання зазвичай оплачуються окремо — уточнюйте в орендодавця.`,
    moreH2: 'Якщо ви купуєте під оренду',
    more: <>Ставки вище — це те, з чим конкуруватиме ваша вілла. Як із них виходить дохідність і скільки з’їдають витрати, розібрано в статті <Link href={c.href.yield} className={A}>дохідність вілл на Балі за районами</Link>{en(c, 'uk')}. Ціни купівлі в тих самих районах — на сторінці <Link href={c.href.prices} className={A}>ціни на нерухомість Балі</Link>.</>,
    catalogue: <>Свіжі оголошення про помісячну оренду — в <Link href={c.href.catalog} className={A}>каталозі оренди</Link>.</>,
    faqH2: 'Часті запитання',
    faq: [
      { q: 'Скільки коштує оренда на Балі на місяць?', a: `Вілла з 2 спальнями — медіана ${c.$(c.two.median)} на місяць, з 1 спальнею — ${c.$(c.M.island.villa1br.median)}, з 3 спальнями — ${c.$(c.M.island.villa3br.median)}. Апартаменти — близько ${c.$(c.M.island.apartment.median)}. Це ціни з ${c.M.n} оголошень з ${c.from} по ${c.to}.` },
      { q: 'Скільки коштує вілла на Балі за ніч?', a: `Медіанна ставка вілли з 2 спальнями — ${c.$(c.R['2br'].median)} за ніч, з 1 спальнею — ${c.$(c.R['1br'].median)}, з 3 спальнями — ${c.$(c.R['3br'].median)}. Дані за ${c.n(c.T.villaRentals)} віллами на майданчиках бронювання.` },
      c.cheapM ? { q: 'Де на Балі оренда дешевша?', a: `Серед районів із достатньою кількістю оголошень найдешевший — ${c.nm(c.cheapM[0])}: медіана ${c.$(c.cheapM[1].all.median)} на місяць. У районах біля океану на південному заході (Чангу, Берава, Переренан) оренда помітно дорожча.` } : null,
      { q: 'Вигідніше знімати помісячно чи подобово?', a: `Помісячно. 30 ночей за медіанною подобовою ставкою вілли з 2 спальнями — близько ${c.monthEq ? c.$(c.monthEq) : '—'}, а місячна оренда такої вілли — ${c.$(c.two.median)}.` },
    ].filter(Boolean) as Faq[],
    sourcesH2: 'Джерела і метод',
    sources: [
      { label: `Каталог оренди Balinsky: ${c.M.n} ${ukPlural(c.M.n, 'оголошення', 'оголошення', 'оголошень')} про помісячну оренду, ${c.from} — ${c.to}`, href: c.href.catalog },
      { label: `База подобової оренди Balinsky: ${c.n(c.T.rentals)} ${ukPlural(c.T.rentals, 'об’єкт', 'об’єкти', 'об’єктів')}, джерело — estatemarket.io`, href: c.href.estatemarket },
      { label: 'Як ми рахуємо: джерела, визначення, обмеження', href: c.href.method },
      { label: `Ставки оренди вілл на Балі за районами${en(c, 'uk')}`, href: c.href.rates },
      { label: 'Статистика туризму Балі (BPS)', href: c.href.bps },
    ],
    datasetName: 'Ціни оренди на Балі: помісячно й подобово за районами',
  }),
}
