export type MeetingLang = 'ru' | 'en'

export const MEETING_COPY = {
  ru: {
    metaTitle: 'Записаться на онлайн-встречу | Balinsky',
    metaDescription: 'Онлайн-встреча в Google Meet: выберите день и время.',
    eyebrow: 'Balinsky · встреча',
    h1: 'Записаться на онлайн-встречу',
    lead: 'Разговор в Google Meet о том, как устроен рынок и как читать документы по объекту. Это консультация по информации с сайта — не продажа и не сопровождение сделки.',
    step1: 'Формат',
    offline: 'Живая встреча',
    offlineMeta: 'на Бали',
    online: 'Онлайн',
    min: 'мин',
    step2: 'День',
    tz: 'Время Бали, UTC+8',
    daysHint: 'Если район у дня не указан, его можно выбрать — остальные встречи этого дня я соберу там же.',
    anyDistrict: 'есть время',
    full: 'занято',
    noDays: 'Свободных дней пока нет. Напишите в Telegram @BalinskyBot — подберём время.',
    pickDayFirst: 'Выберите день — здесь появится свободное время.',
    dayIn: 'В этот день я в районе',
    dayInTail: 'Встреча — там же.',
    pickDistrict: 'Район на этот день ещё не выбран. Где вам удобнее встретиться?',
    district: 'Район',
    step3: 'Время',
    noTimes: 'На этот день свободного времени не осталось.',
    name: 'Имя',
    email: 'Email',
    emailHint: 'Сюда придёт приглашение из Google Календаря.',
    contact: 'Telegram или телефон',
    comment: 'Что хотите обсудить',
    commentOffline: 'Что обсудить и где удобно встретиться',
    submit: 'Записаться',
    submitting: 'Записываем…',
    doneTitle: 'Встреча назначена',
    doneText: 'Приглашение отправлено на ваш email — добавьте его в календарь. Если планы изменятся, просто ответьте на письмо.',
    when: 'Когда',
    where: 'Где',
    onlineWhere: 'Онлайн, Google Meet',
    bali: 'Бали',
    retry: 'Попробовать снова',
    errLoad: 'Не удалось загрузить расписание.',
    errClosed: 'Онлайн-запись временно закрыта. Напишите в Telegram @BalinskyBot — подберём время.',
    errTaken: 'Это время только что заняли. Выберите другое — расписание обновлено.',
    errEmail: 'Проверьте email — в нём ошибка.',
    errRate: 'Слишком много попыток. Попробуйте через несколько минут.',
    errSubmit: 'Не получилось записаться. Попробуйте ещё раз или напишите в Telegram @BalinskyBot.',
  },
  en: {
    metaTitle: 'Book an online meeting | Balinsky',
    metaDescription: 'An online meeting on Google Meet: pick a day and a time.',
    eyebrow: 'Balinsky · meeting',
    h1: 'Book an online meeting',
    lead: 'A Google Meet conversation about how the market works and how to read a project’s documents. It is a walkthrough of what is on the site — not a sale, and not deal support.',
    step1: 'Format',
    offline: 'In person',
    offlineMeta: 'in Bali',
    online: 'Online',
    min: 'min',
    step2: 'Day',
    tz: 'Bali time, UTC+8',
    daysHint: 'If a day has no area yet, you can pick one — I’ll plan the rest of that day’s meetings around it.',
    anyDistrict: 'slots open',
    full: 'full',
    noDays: 'No free days right now. Message @BalinskyBot on Telegram and we’ll find a time.',
    pickDayFirst: 'Pick a day — the free times will show up here.',
    dayIn: 'That day I’m in',
    dayInTail: 'We’ll meet there.',
    pickDistrict: 'No area is set for this day yet. Where would you like to meet?',
    district: 'Area',
    step3: 'Time',
    noTimes: 'No free time left on this day.',
    name: 'Name',
    email: 'Email',
    emailHint: 'The Google Calendar invite will be sent here.',
    contact: 'Telegram or phone',
    comment: 'What would you like to discuss',
    commentOffline: 'What to discuss and where you’d like to meet',
    submit: 'Book',
    submitting: 'Booking…',
    doneTitle: 'Meeting booked',
    doneText: 'The invite is on its way to your email — add it to your calendar. If plans change, just reply to it.',
    when: 'When',
    where: 'Where',
    onlineWhere: 'Online, Google Meet',
    bali: 'Bali',
    retry: 'Try again',
    errLoad: 'Couldn’t load the schedule.',
    errClosed: 'Online booking is temporarily closed. Message @BalinskyBot on Telegram and we’ll find a time.',
    errTaken: 'That time was just taken. Please pick another — the schedule has been refreshed.',
    errEmail: 'Please check your email address.',
    errRate: 'Too many attempts. Please try again in a few minutes.',
    errSubmit: 'Booking failed. Please try again or message @BalinskyBot on Telegram.',
  },
} as const
