-- Track each PDF presentation generated by a visitor.
--
-- Two flavours of presentation, distinguished by `kind`:
--   'object'    — single-listing PDF triggered from villa / apartment
--                 / complex detail page. Fills `object_kind`,
--                 `object_id`, `slug`.
--   'shortlist' — multi-listing PDF triggered from /izbrannoe.
--                 Fills `item_count` and `items[]` (Airtable record
--                 ids in shortlist order, capped to 30 to keep rows
--                 small).
--
-- Insert path is `/api/track/presentation`, fire-and-forget from the
-- client right after the blob is generated. Aggregations live in
-- /admin/presentations.

create table if not exists public.presentation_events (
  id            bigserial primary key,
  created_at    timestamptz not null default now(),
  kind          text not null check (kind in ('object', 'shortlist')),
  -- Per-object fields. Null for shortlist events.
  object_kind   text,                       -- villa | apartment | complex
  object_id     text,                       -- airtable record id
  slug          text,
  title         text,
  -- Per-shortlist fields. Null for object events.
  item_count    integer,
  items         text[],                      -- airtable ids, capped to 30
  -- Render context — useful when slicing the report later.
  orientation   text,                        -- portrait | landscape
  has_agent     boolean not null default false,
  lang          text                         -- ru | en
);

create index if not exists presentation_events_created_at_idx
  on public.presentation_events (created_at desc);

create index if not exists presentation_events_kind_created_at_idx
  on public.presentation_events (kind, created_at desc);

create index if not exists presentation_events_object_id_idx
  on public.presentation_events (object_id)
  where object_id is not null;

grant select, insert on table public.presentation_events to service_role;
grant usage, select on sequence public.presentation_events_id_seq to service_role;
