-- On-page, reader-facing content for catalog/developer pages, generated by
-- Azure and stored alongside the existing assistant_kb row (one per listing,
-- keyed by kind+ref_id=airtable_id). The detail pages currently render the
-- generic Airtable "SEO Text" plus a TEMPLATED FAQ that is identical across
-- listings — thin/duplicate content that hurts SEO. These columns hold a
-- unique investor write-up + a listing-specific FAQ (RU + EN), grounded in
-- the same clean facts the summary uses.
--
-- Separate from `summary` (which is an internal retrieval note for the
-- assistant): page_body is buyer-facing prose; faq is structured Q&A used
-- both on-page and for FAQPage JSON-LD.

ALTER TABLE public.assistant_kb ADD COLUMN IF NOT EXISTS page_body     text;
ALTER TABLE public.assistant_kb ADD COLUMN IF NOT EXISTS page_body_en  text;
ALTER TABLE public.assistant_kb ADD COLUMN IF NOT EXISTS faq           jsonb;   -- [{q,a}]
ALTER TABLE public.assistant_kb ADD COLUMN IF NOT EXISTS faq_en        jsonb;   -- [{q,a}]
ALTER TABLE public.assistant_kb ADD COLUMN IF NOT EXISTS page_built_at timestamptz;
