// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/apartments/ru.ts (Balinese (Basa Bali, polite register)).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Pidan rega apartemen ring Bali",
      "paragraphs": [
        "Ring katalog wenten 423 apartemen sane kaadol ring 197 kompleks hunian. Rega medianne — $160,000, delapan saking sapuluh lot wenten ring rentang $105,000 ngantos $502,500. Mlebet pasar kawiwitan kira-kira saking $65,000 antuk studio ring kompleks sane durung prasida rampung, wates paling duur — $1,28 juta antuk penthouse ring pasisi sagara.",
        "Pasar apartemen ring Bali kabentukne béda saking pasar villa: puniki pinaka unit kompak. Delapan saking sapuluh lot inggih punika studio lan one-bedroom antuk lega median 41 m². Apartemen two-bedroom sampun kalebet langka (72 lot), three-bedroom dados produk premium sane terbatas."
      ]
    },
    {
      "heading": "Proyek durung rampung utawi kompleks sane sampun dados",
      "paragraphs": [
        "Saking 423 apartemen, 366 kantun ring proses pembangunan lan 53 kemanten sane sampun kaserahang — pasar puniki meh sadayané pasar primer. Saking punika, skema pamesuan dados jelas: pamesuan ring tahap pembangunan lumrahne nganggen cicilan saking developer (DP pisan biasane 30–50%, sisane manut tahap), tur wenten diskon dibanding rega unit sane sampun dados, nanging wenten risiko molih geser ring tenggat waktu.",
        "Rega median per meter — saking $3,300 ngantos $4,700 manut wilayah, tur langkung inggil ketimbang villa. Punika normal: ring rega per meter apartemen sampun kalebet kolam renang bersama, lobi, kaamanan, lift, lan perusahaan pengelola. Ngebandingang lot antarkompleks langkung trep manut rega per meter, nenten manut total rega — amargi lega studio prasida béda ngantos kaping kalih."
      ]
    },
    {
      "heading": "Ring dija meli apartemen ring Bali: wilayah lan rega",
      "paragraphs": [
        "Kompleks apartemen ngumpul ring sawatara zona, tur béda rega antarzona saged ngantos kaping tiga. Median apartemen one-bedroom manut katalog:"
      ],
      "bullets": [
        "Ubud — $121,500, mlebet pasar sane paling kajangkau tur pilihanne paling akéh (45 lot). Panuntut sewa jangka panjang ajeg sajeroning warsa, audiens yoga lan wellness kuat.",
        "Pandawa lan kidul Bukit — $135,000. Kompleks anyar ring cedek pasih, lot antuk pemandangan, fokus ring sewa harian ring musim rame.",
        "Pererenan — $147,500 lan Cemagi — $149,000. Sisih kulon Canggu: langkung tenang ketimbang Batu Bolong, rega langkung andap, infrastruktur terus ngiring ngembang.",
        "Batu Bolong — $175,000, 31 lot. Pusat Canggu, kapadatan kafe lan coworking paling inggil, profil penyewa paling prasida katebak.",
        "Uluwatu — $220,000 lan Berawa — $235,000. Kompleks premium, tarif per wengi inggil, nanging modal mlebet pasar taler langkung ageng.",
        "Nusa Dua — $157,900 lan Sanur — $468,000. Kidul gaya hotel lan wetan sane tenang: kulawarga, tinggal jangka panjang, okupansi ajeg tanpa puncak tajam."
      ]
    },
    {
      "heading": "Cara warga asing meli apartemen ring Bali",
      "paragraphs": [
        "Skemane sami sakadi villa: freehold penuh (Hak Milik) nenten kabuka ring warga asing. Apartemen lumrah kaambil nganggén leasehold (Hak Sewa) — ring 255 lot ring katalog, jangka waktuné 26–30 warsa, ring 114 lot — saking 31 warsa, ring 40 lot — ngantos 25 warsa. Warga sane dados residen antuk KITAS prasida ngurus Hak Pakai, tur sane nganggen puniki dados usaha prasida nguwasayang liwat PT PMA antuk hak HGB.",
        "Urutan transaksi: booking antuk deposit, pengecekan legal kompleks lan developer, perjanjian ring notaris PPAT, pambayaran manut jadwal, serah terima unit, lan penandatanganan berita acara. Ring kompleks, sane perlu taler kapariksa inggih punika anggaran dasar, ukuran service charge, lan sinten sane ngelola gedong sasampun serah terima.",
        "Pambayaran ring transaksi: PPh 2,5% saking rega kabayar olih penjual, BPHTB ngantos 5% — olih pembeli rikala ngurus hak, PPN ring rega proyek anyar efektif 11%. Tarif manut kabupaten lan status penjual, prasida dados total itungan final wajib kakonfirmasi olih notaris satekané deposit kabayar."
      ]
    },
    {
      "heading": "Sane patut kapariksa sadurung meli",
      "paragraphs": [
        "Ring apartemen wenten risiko sane khas: panjenengan nenten semeton meli unit kemanten, nanging taler mutu pengelolaan gedong. Check-list:"
      ],
      "bullets": [
        "Zonasi lahan kompleks — ring tanah hunian (kuning), sewa harian ring wisatawan nenten sah, padahal punika biasane dados dasar hitungan hasil investasi.",
        "Izin PBG lan SLF antuk sadurungé kompleks sampun utuh, nenten proyek dokumen kemanten.",
        "Jangka leasehold, syarat lan rega perpanjangan — lan napi jangka unit panjenengan sami sareng masa sewa tanah ring kompleks punika.",
        "Ukuran service charge lan napi kemanten sane kalebet ring jeroné: puniki ngurangin hasil investasi saben sasih.",
        "Sinten sane ngelola gedong sasampun serah terima, napi wenten kontrak sareng pengelola, lan ring syarat napi kontrak punika prasida kaputus.",
        "Riwayat developer: kompleks sane sampun kaserahang, katertiban ring tenggat waktu, lan kadi napi nasib dana yening pembangunan mandeg.",
        "Okupansi nyata ring kompleks tetangga, nenten mung proyeksi saking presentasi."
      ]
    },
    {
      "heading": "Sewa, hasil investasi, lan biaya pangreksan",
      "paragraphs": [
        "Patokan sewa bulanan: median $2,585 ring Berawa, $2,113 ring Canggu, $1,608 ring Bukit, $1,300 ring Ubud. Ring rerata, apartemen kasewa langkung murah ketimbang villa, nanging okupansiné langkung ajeg — unit kompak antuk kolam renang kompleks langkung gampang kaséwa ring luar musim rame.",
        "Hasil bersih sane realistis — 8–12% saben warsa antuk okupansi 70–80%. Sadurung ngandelang angka ring presentasi, kurangi komisi perusahaan pengelola 15–25%, service charge kompleks, biaya pangreksan lan pajak sewa, miwah amortisasi leasehold. Tur cek taler kanthi misah, napi ring wilayah panjenengan sampun rauh malih sapuluh kompleks sane sami: ring Canggu, kaluwihan studio sane mirib sampun ngamargiang tarif sewa mudun."
      ]
    }
  ],
  "priceTable": {
    "caption": "Rega apartemen ring Bali manut jumlah kamar tidur",
    "columns": [
      "Kamar tidur",
      "Lega",
      "Rega umum",
      "Median"
    ],
    "rows": [
      [
        "Studio / 1 kamar tidur",
        "41 m²",
        "$101,500 – $302,400",
        "$145,700"
      ],
      [
        "2 kamar tidur",
        "99 m²",
        "$200,000 – $673,000",
        "$389,000"
      ],
      [
        "3 kamar tidur",
        "125 m²",
        "$544,000 – $1,125,000",
        "$884,000"
      ],
      [
        "Sakancan pasar",
        "—",
        "$105,000 – $502,500",
        "$160,000"
      ]
    ],
    "note": "Rentang punika persentil ka-10 lan ka-90 saking 423 apartemen sane wenten reganipun. Data katalog, kaanyarang sesarengan sareng pricelist developer."
  },
  "faqExtra": [
    {
      "q": "Sane langkung nguntungang — apartemen utawi villa?",
      "a": "Apartemen langkung enteng ring modal awal (median $160,000 nglawan $350,000 ring villa), langkung prasida kaurus, lan langkung gampang kaséwa ring luar musim amargi fasilitas kompleks. Villa maringi privasi, tanah, lan tarif per wengi langkung inggil, nanging mresidayang pengelolaan pribadi lan biaya pangreksan sane langkung ageng. Kanggen objek kaping pisan ring Bali, akéh sane milih apartemen; kanggen tinggal sareng kulawarga — villa."
    },
    {
      "q": "Napi punika service charge lan pidan biayané?",
      "a": "Service charge inggih punika pambayaran bulanan kanggen pangreksan area bersama: kolam renang, lift, kaamanan, kebersihan, angkut sampah, resepsionis. Itungané lumrah manut lega unit lan ring anggaran ngelaksanayang fungsi sami sareng biaya utilitas. Ukuranipun patut kasuunin sadurung transaksi: puniki langsung ngurangin hasil bersih, tur ring sawatara kompleks prasida naek saben warsa."
    },
    {
      "q": "Napi sane kadadosang ring apartemen sasampun leasehold béak?",
      "a": "Hak punika malih ring pemilik tanah yening jangka waktuné nenten kaperpanjang. Antuk punika, ring kontrak wenten kalih pasal sane pinaka penting: syarat perpanjangan (napi rega siklus kapindoné sampun kaiket) lan kesamaan jangka unit panjenengan sareng masa sewa tanah ring sakancan kompleks — kadang béda, lan punika risiko sane kasingsal."
    },
    {
      "q": "Napi prasida meli apartemen antuk cicilan?",
      "a": "Ring tahap pembangunan, punika skema standar: DP pisan 30–50%, sisane kabayar manut tahap ngantos serah terima, lumrahne tanpa bunga. KPR kanggen warga asing ring Bali praktis pisan langka, dados cicilan punika lumrahne kaatur langsung olih developer. Kanggen unit sane sampun dados, cicilan biasane langkung cendek lan langkung jarang kapanggih."
    },
    {
      "q": "Sinten sane ngurus nyewayang apartemen?",
      "a": "Lumrahne perusahaan pengelola kompleks: ipun nanggung pemasangan listing ring platform, check-in tamu, kebersihan, lan pangreksan antuk komisi 15–25% saking pendapatan. Pemilik prasida nyewayang piyambak, nanging ring akéh kompleks wenten aturan sewa tunggal — syarat puniki patut kabaca sadurung meli."
    },
    {
      "q": "Napi prasida meli apartemen saking kejauhan?",
      "a": "Prasida, transaksi rutin kalaksanayang nganggén surat kuasa: video showing, dokumen liwat notaris PPAT, pambayaran antuk transfer. Syarat sane wajib inggih punika pengecekan legal independen ring kompleks lan serah terima unit olih wakil panjenengan ring lokasi, nenten olih staf sales."
    }
  ]
}

export default copy
