// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/apartments/ru.ts (German).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Wie viel kosten Apartments auf Bali",
      "paragraphs": [
        "Im Katalog stehen 423 Apartments zum Verkauf in 197 Wohnanlagen. Der Medianpreis liegt bei $160.000, acht von zehn Objekten bewegen sich in einer Spanne von $105.000 bis $502.500. Der Markteinstieg beginnt bei etwa $65.000 für ein Studio in einer Anlage in früher Bauphase, die Obergrenze liegt bei $1,28 Mio. für ein Penthouse am Ozean.",
        "Der Apartmentmarkt auf Bali funktioniert anders als der Villenmarkt: Es handelt sich überwiegend um kompakte Einheiten. Acht von zehn Objekten sind Studios und Einheiten mit 1 Schlafzimmer, mit einer Medianfläche von 41 m². Apartments mit 2 Schlafzimmern sind bereits selten (72 Objekte), mit 3 Schlafzimmern ein einzelnes Premiumprodukt."
      ]
    },
    {
      "heading": "Im Bau oder fertige Anlage",
      "paragraphs": [
        "Von 423 Apartments befinden sich 366 im Bau und nur 53 sind fertiggestellt — der Markt ist fast vollständig Primärmarkt. Daraus ergeben sich die Spielregeln: Der Kauf in der Bauphase erfolgt mit Ratenzahlung des Bauträgers (erste Anzahlung meist 30–50%, der Rest nach Baufortschritt) und mit Abschlag gegenüber dem Preis einer fertigen Einheit, allerdings mit dem Risiko von Terminverschiebungen.",
        "Der Medianpreis pro Quadratmeter liegt je nach Lage zwischen $3.300 und $4.700 und damit deutlich höher als bei Villen. Das ist normal: Im Quadratmeterpreis von Apartments sind Gemeinschaftspool, Lobby, Sicherheitsdienst, Aufzug und Verwaltung bereits enthalten. Objekte zwischen verschiedenen Anlagen vergleicht man sinnvoller über den Preis pro Quadratmeter und nicht über die Gesamtsumme — die Flächen von Studios unterscheiden sich um das Doppelte."
      ]
    },
    {
      "heading": "Wo man auf Bali Apartments kaufen kann: Lagen und Preise",
      "paragraphs": [
        "Die Anlagen konzentrieren sich auf einige wenige Zonen, und die Preisspanne zwischen ihnen beträgt das Dreifache. Der Median für Apartments mit 1 Schlafzimmer im Katalog:"
      ],
      "bullets": [
        "Ubud — $121.500, der günstigste Einstieg und die größte Auswahl (45 Objekte). Nachfrage nach Langzeitmiete das ganze Jahr über, starke Yoga- und Wellness-Zielgruppe.",
        "Pandawa und der Süden von Bukit — $135.000. Neue Anlagen nahe den Stränden, Objekte mit Aussicht, Fokus auf Kurzzeitvermietung in der Hochsaison.",
        "Pererenan — $147.500 und Cemagi — $149.000. Der westliche Teil von Canggu: ruhiger als Batu Bolong, niedrigere Preise, die Infrastruktur zieht nach.",
        "Batu Bolong — $175.000, 31 Objekte. Das Zentrum von Canggu, höchste Dichte an Cafés und Coworking-Spaces, der berechenbarste Mietermarkt.",
        "Uluwatu — $220.000 und Berawa — $235.000. Premiumanlagen, hoher Übernachtungspreis, aber auch ein teurerer Markteinstieg.",
        "Nusa Dua — $157.900 und Sanur — $468.000. Der Hotel-Süden und der ruhige Osten: Familien, längere Aufenthalte, gleichmäßige Auslastung ohne starke Spitzen."
      ]
    },
    {
      "heading": "Wie Ausländer Apartments auf Bali kaufen",
      "paragraphs": [
        "Das Modell ist dasselbe wie bei Villen: Volles freehold (Hak Milik) ist für Ausländer nicht zugänglich. Apartments werden über leasehold (Hak Sewa) gekauft — bei 255 Objekten im Katalog beträgt die Laufzeit 26–30 Jahre, bei 114 ab 31 Jahren, bei 40 bis 25 Jahre. Ein Resident mit KITAS kann Hak Pakai erhalten, und wer dies geschäftlich betreibt, kann über eine PT PMA mit HGB halten.",
        "Der Ablauf der Transaktion: Reservierung mit Anzahlung, rechtliche Prüfung der Anlage und des Bauträgers, Vertrag beim Notar PPAT, Zahlung nach Plan, Abnahme der Einheit und Unterzeichnung des Übergabeprotokolls. In einer Anlage prüft man zusätzlich die Satzung, die Höhe des service charge und wer das Gebäude nach Fertigstellung verwaltet.",
        "Zahlungen bei der Transaktion: PPh 2,5% des Kaufpreises zahlt der Verkäufer, BPHTB bis 5% der Käufer bei der Eintragung der Rechte, die Mehrwertsteuer im Preis eines Neubaus beträgt effektiv 11%. Die Sätze hängen vom Kabupaten und vom Status des Verkäufers ab, daher bestätigt der Notar die endgültige Kostenkalkulation vor Zahlung der Anzahlung."
      ]
    },
    {
      "heading": "Was man vor dem Kauf prüfen sollte",
      "paragraphs": [
        "Bei Apartments gibt es eigene Risiken: Sie kaufen nicht nur die Einheit, sondern auch die Qualität der Gebäudeverwaltung. Checkliste:"
      ],
      "bullets": [
        "Zonierung des Grundstücks der Anlage — auf Wohnland (gelbe Zone) ist die tägliche Vermietung an Touristen unzulässig, obwohl genau diese meist in die Renditerechnung einfließt.",
        "Genehmigungen PBG und SLF für die gesamte Anlage, nicht nur die Projektdokumentation.",
        "Leasehold-Laufzeit, Bedingungen und Preis der Verlängerung — und ob die Laufzeit Ihrer Einheit mit der Laufzeit des Landpachtvertrags der gesamten Anlage übereinstimmt.",
        "Höhe des service charge und was darin enthalten ist: Er reduziert die Rendite jeden Monat.",
        "Wer das Gebäude nach Fertigstellung verwaltet, ob ein Vertrag mit der Verwaltungsgesellschaft besteht und zu welchen Bedingungen er kündbar ist.",
        "Historie des Bauträgers: fertiggestellte Anlagen, Einhaltung von Fristen, Schicksal der Gelder bei Baustopp.",
        "Tatsächliche Auslastung benachbarter Anlagen und nicht die Prognose aus der Präsentation."
      ]
    },
    {
      "heading": "Miete, Rendite und laufende Kosten",
      "paragraphs": [
        "Orientierungswerte für die Monatsmiete: Median $2.585 in Berawa, $2.113 in Canggu, $1.608 in Bukit, $1.300 in Ubud. Apartments werden im Durchschnitt günstiger vermietet als Villen, sind aber gleichmäßiger ausgelastet — eine kompakte Einheit mit Gemeinschaftspool lässt sich außerhalb der Saison leichter vermieten.",
        "Eine realistische Nettorendite liegt bei 8–12% p.a. bei einer Auslastung von 70–80%. Bevor Sie einer Zahl aus der Präsentation glauben, ziehen Sie die Provision der Verwaltungsgesellschaft von 15–25%, den service charge der Anlage, Instandhaltung und Mietsteuer sowie die Abschreibung des leasehold ab. Prüfen Sie außerdem gesondert, ob in Ihrer Lage nicht noch ein weiteres Dutzend ähnlicher Anlagen auf den Markt kommt: In Canggu drückt ein Überangebot identischer Studios die Miete bereits nach unten."
      ]
    }
  ],
  "priceTable": {
    "caption": "Preise für Apartments auf Bali nach Anzahl der Schlafzimmer",
    "columns": [
      "Schlafzimmer",
      "Fläche",
      "Typischer Preis",
      "Median"
    ],
    "rows": [
      [
        "Studio / 1 Schlafzimmer",
        "41 m²",
        "$101.500 – $302.400",
        "$145.700"
      ],
      [
        "2 Schlafzimmer",
        "99 m²",
        "$200.000 – $673.000",
        "$389.000"
      ],
      [
        "3 Schlafzimmer",
        "125 m²",
        "$544.000 – $1.125.000",
        "$884.000"
      ],
      [
        "Gesamter Markt",
        "—",
        "$105.000 – $502.500",
        "$160.000"
      ]
    ],
    "note": "Die Spanne entspricht dem 10. und 90. Perzentil auf Basis von 423 Apartments mit ausgewiesenem Preis. Katalogdaten, werden zusammen mit den Preislisten der Bauträger aktualisiert."
  },
  "faqExtra": [
    {
      "q": "Was ist vorteilhafter — Apartment oder Villa?",
      "a": "Apartments sind beim Einstieg günstiger (Median $160.000 gegenüber $350.000 bei Villen), einfacher im Unterhalt und außerhalb der Saison leichter zu vermieten, weil die Infrastruktur der Anlage mitspielt. Eine Villa bietet Privatsphäre, Grundstück und einen höheren Übernachtungspreis, erfordert aber eigenes Management und deutlich höhere Unterhaltskosten. Für das erste Objekt auf Bali wird häufiger ein Apartment gekauft, für das Leben mit Familie eher eine Villa."
    },
    {
      "q": "Was ist der service charge und wie hoch ist er?",
      "a": "Service charge ist die monatliche Zahlung für den Unterhalt der Gemeinschaftsflächen: Pool, Aufzüge, Sicherheitsdienst, Reinigung, Müllabfuhr, Rezeption. Er wird nach der Fläche der Einheit berechnet und spielt im Budget dieselbe Rolle wie Nebenkosten. Seine Höhe muss vor dem Kauf geklärt werden: Er mindert die Nettorendite direkt, und in manchen Anlagen wird er jährlich indexiert."
    },
    {
      "q": "Was passiert mit dem Apartment nach Ablauf des leasehold?",
      "a": "Die Rechte fallen an den Grundstückseigentümer zurück, wenn die Laufzeit nicht verlängert wird. Deshalb sind im Vertrag zwei Punkte entscheidend: die Bedingungen der Verlängerung (ist der Preis für den zweiten Zyklus festgelegt) und die Übereinstimmung der Laufzeit Ihrer Einheit mit der Laufzeit des Landpachtvertrags der gesamten Anlage — manchmal weichen sie voneinander ab, und das ist ein verstecktes Risiko."
    },
    {
      "q": "Kann man Apartments in Raten kaufen?",
      "a": "In der Bauphase ist das das Standardschema: erste Anzahlung 30–50%, der Rest nach Baufortschritt bis zur Fertigstellung, in der Regel zinsfrei. Eine Hypothek ist für Ausländer auf Bali praktisch nicht verfügbar, deshalb gewährt der Bauträger selbst die Ratenzahlung. Bei fertigen Einheiten ist die Laufzeit kürzer und dieses Modell seltener."
    },
    {
      "q": "Wer kümmert sich um die Vermietung der Apartments?",
      "a": "In der Regel die Verwaltungsgesellschaft der Anlage: Sie übernimmt die Platzierung auf Plattformen, Check-in, Reinigung und Betrieb für 15–25% des Umsatzes. Der Eigentümer kann auch selbst vermieten, aber in den meisten Anlagen gilt ein einheitliches Vermietungsreglement — diese Bedingung sollte vor dem Kauf geprüft werden."
    },
    {
      "q": "Kann man Apartments aus der Ferne kaufen?",
      "a": "Ja, Transaktionen werden regelmäßig per Vollmacht durchgeführt: Videobesichtigung, Unterlagen über den Notar PPAT, Zahlung per Überweisung. Voraussetzung ist eine unabhängige rechtliche Prüfung der Anlage und die Abnahme der Einheit durch Ihren Vertreter vor Ort, nicht durch einen Mitarbeiter des Vertriebsteams."
    }
  ]
}

export default copy
