// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/apartments/ru.ts (English).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "How much do apartments in Bali cost",
      "paragraphs": [
        "The catalogue lists 423 apartments for sale across 197 residential complexes. The median price is $160,000, and eight out of ten listings fall in the range from $105,000 to $502,500. Entry starts at around $65,000 for a studio in a project at an early construction stage, while the top end reaches $1.28 million for an oceanfront penthouse.",
        "The apartment market in Bali works differently from the villa market: these are mostly compact units. Eight out of ten listings are studios and one-bedroom units with a median size of 41 m². Two-bedroom apartments are already relatively rare (72 listings), while three-bedroom units are a niche premium product."
      ]
    },
    {
      "heading": "Off-plan or completed complex",
      "paragraphs": [
        "Out of 423 apartments, 366 are under construction and only 53 have been completed, so the market is almost entirely primary. That sets the rules: buying at the construction stage usually comes with developer instalments (typically a 30–50% down payment, with the balance paid by stages) and a discount versus a completed unit, but also with the risk of delays.",
        "The median price per square metre ranges from $3,300 to $4,700 depending on the area, noticeably higher than for villas. That is normal: the apartment price per metre includes the shared pool, lobby, security, lift, and management company. When comparing listings across complexes, price per square metre is more accurate than total price, as studio sizes can vary twofold."
      ]
    },
    {
      "heading": "Where to buy apartments in Bali: areas and prices",
      "paragraphs": [
        "Complexes are concentrated in a few key areas, and the price spread between them is threefold. Median price for one-bedroom apartments in the catalogue:"
      ],
      "bullets": [
        "Ubud — $121,500, the most affordable entry point and the largest sample (45 listings). Year-round demand for long-term rentals, with a strong yoga and wellness audience.",
        "Pandawa and South Bukit — $135,000. New complexes near the beaches, view units, with a focus on short-term rental in high season.",
        "Pererenan — $147,500 and Cemagi — $149,000. The western side of Canggu: quieter than Batu Bolong, lower prices, and infrastructure is catching up.",
        "Batu Bolong — $175,000, 31 listings. The heart of Canggu, with the highest concentration of cafés and coworking spaces, and the most predictable tenant profile.",
        "Uluwatu — $220,000 and Berawa — $235,000. Premium complexes, higher nightly rates, but also a more expensive entry point.",
        "Nusa Dua — $157,900 and Sanur — $468,000. The resort south and the calmer east: families, longer stays, and steadier occupancy without sharp peaks."
      ]
    },
    {
      "heading": "How a foreigner can buy an apartment in Bali",
      "paragraphs": [
        "The structure is the same as for villas: full freehold (Hak Milik) is not available to foreigners. Apartments are bought on a leasehold basis (Hak Sewa) — in the catalogue, 255 listings have a term of 26–30 years, 114 have 31 years or more, and 40 have up to 25 years. A resident with KITAS can register Hak Pakai, while those buying for business purposes can hold through a PT PMA with HGB rights.",
        "The transaction process is standard: reservation with a deposit, legal due diligence on the complex and developer, contract with a PPAT notary, payment according to schedule, unit handover, and signing of the acceptance act. In a complex, you should also review the bylaws, the service charge amount, and who will manage the building after completion.",
        "Transaction costs: PPh 2.5% of the price is paid by the seller, BPHTB up to 5% is paid by the buyer when registering rights, and VAT in the price of a new-build is effectively 11%. Rates depend on the kabupaten and the seller’s status, so the final cost estimate should be confirmed by the notary before any deposit is paid."
      ]
    },
    {
      "heading": "What to check before buying",
      "paragraphs": [
        "Apartments have their own risks: you are buying not only the unit, but also the quality of the building’s management. Checklist:"
      ],
      "bullets": [
        "Zoning of the complex plot — on residential (yellow) land, daily tourist rental is illegal, and that is usually what projected returns are based on.",
        "PBG and SLF permits for the entire complex, not just project documentation.",
        "Leasehold term, extension terms and cost — and whether the term of your unit matches the land lease term for the entire complex.",
        "Service charge amount and what it includes: it reduces yield every month.",
        "Who manages the building after completion, whether there is a contract with the management company, and on what terms it can be terminated.",
        "Developer track record: completed projects, delivery discipline, and what happens to funds if construction stops.",
        "Actual occupancy of neighbouring complexes, not just the forecast shown in the presentation."
      ]
    },
    {
      "heading": "Rental income, yield, and running costs",
      "paragraphs": [
        "A guide to monthly rent: median $2,585 in Berawa, $2,113 in Canggu, $1,608 in Bukit, and $1,300 in Ubud. Apartments generally rent for less than villas, but occupancy is more stable — a compact unit with a shared complex pool is easier to let outside the high season.",
        "A realistic net yield is 8–12% per year at 70–80% occupancy. Before relying on a number from a presentation, deduct the management company fee of 15–25%, the complex service charge, maintenance and rental tax, as well as leasehold amortisation. Also check separately whether another ten similar complexes are about to enter the market in your area: in Canggu, an oversupply of identical studios is already putting pressure on rates."
      ]
    }
  ],
  "priceTable": {
    "caption": "Apartment prices in Bali by number of bedrooms",
    "columns": [
      "Bedrooms",
      "Area",
      "Typical price",
      "Median"
    ],
    "rows": [
      [
        "Studio / 1 bedroom",
        "41 m²",
        "$101,500 – $302,400",
        "$145,700"
      ],
      [
        "2 bedrooms",
        "99 m²",
        "$200,000 – $673,000",
        "$389,000"
      ],
      [
        "3 bedrooms",
        "125 m²",
        "$544,000 – $1,125,000",
        "$884,000"
      ],
      [
        "Whole market",
        "—",
        "$105,000 – $502,500",
        "$160,000"
      ]
    ],
    "note": "The range shows the 10th and 90th percentiles across 423 apartments with a listed price. Catalogue data, updated together with developer price lists."
  },
  "faqExtra": [
    {
      "q": "Which is better value: an apartment or a villa?",
      "a": "Apartments have a lower entry point (median $160,000 versus $350,000 for villas), are easier to maintain, and are easier to rent out outside the high season thanks to complex infrastructure. A villa gives you privacy, land, and a higher nightly rate, but it also requires hands-on management and noticeably higher maintenance costs. For a first property in Bali, buyers more often choose an apartment; for family living, a villa."
    },
    {
      "q": "What is the service charge and how much is it?",
      "a": "Service charge is the monthly fee for maintaining shared areas: pool, lifts, security, cleaning, waste collection, reception. It is calculated based on the unit size and plays the same role in the budget as utilities. The amount should be checked before the deal: it directly reduces net yield, and in some complexes it is indexed annually."
    },
    {
      "q": "What happens to the apartment when the leasehold ends?",
      "a": "The rights return to the landowner if the term is not extended. That is why two points in the contract are critical: the extension terms (including whether the second-term price is fixed) and whether the term of your unit matches the land lease term under the whole complex — sometimes they differ, and that is a hidden risk."
    },
    {
      "q": "Can you buy an apartment in instalments?",
      "a": "At the construction stage, this is the standard structure: 30–50% down payment, with the balance paid in stages until completion, usually without interest. Mortgage financing for foreigners in Bali is practically unavailable, so instalments are provided by the developer. For completed units, instalment plans are shorter and less common."
    },
    {
      "q": "Who handles apartment rentals?",
      "a": "Usually the complex management company: it handles listings on platforms, guest check-in, cleaning, and maintenance for 15–25% of revenue. An owner can also rent out independently, but in most complexes there is a unified rental policy — that condition should be reviewed before purchase."
    },
    {
      "q": "Can you buy an apartment remotely?",
      "a": "Yes, transactions are regularly completed by power of attorney: video viewing, documents through a PPAT notary, and payment by transfer. The key condition is independent legal due diligence on the complex and handover inspection by your representative on site, not by a sales department employee."
    }
  ]
}

export default copy
