// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/apartments/ru.ts (French).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Prix des appartements à Bali",
      "paragraphs": [
        "Le catalogue propose 423 appartements à vendre dans 197 résidences. Le prix médian est de $160 000, et huit lots sur dix se situent dans une fourchette de $105 000 à $502 500. L’entrée de marché commence autour de $65 000 pour un studio dans une résidence en phase initiale de construction, tandis que le haut de gamme atteint $1,28 млн pour un penthouse en bord d’océan.",
        "Le marché des appartements à Bali fonctionne différemment de celui des villas : il s’agit principalement d’unités compactes. Huit lots sur dix sont des studios et des appartements 1 chambre, avec une surface médiane de 41 m². Les appartements 2 chambres sont déjà plus rares (72 lots), et les 3 chambres relèvent d’une offre premium très limitée."
      ]
    },
    {
      "heading": "Acheter sur plan ou dans une résidence livrée",
      "paragraphs": [
        "Sur 423 appartements, 366 sont en construction et seulement 53 sont déjà livrés : le marché est presque entièrement primaire. Les règles en découlent : un achat en cours de construction se fait avec un paiement échelonné par le promoteur (acompte initial généralement de 30–50%, puis solde selon l’avancement) et avec une décote par rapport au prix d’une unité livrée, mais avec un risque de retard sur les délais.",
        "Le prix médian au mètre carré va de $3 300 à $4 700 selon la zone, sensiblement plus élevé que pour les villas. C’est normal : le prix au mètre inclut la piscine commune, le lobby, la sécurité, l’ascenseur et la société de gestion. Pour comparer des lots entre résidences, il est plus juste de regarder le prix au mètre que le montant total, car la surface des studios peut varier du simple au double."
      ]
    },
    {
      "heading": "Où acheter un appartement à Bali : zones et prix",
      "paragraphs": [
        "Les résidences sont concentrées dans quelques secteurs, avec un écart de prix pouvant aller du simple au triple. Médiane des appartements 1 chambre dans le catalogue :"
      ],
      "bullets": [
        "Ubud — $121 500, entrée de marché la plus accessible et l’échantillon le plus large (45 lots). Demande soutenue en location longue durée toute l’année, avec une clientèle forte liée au yoga et au bien-être.",
        "Pandawa et le sud du Bukit — $135 000. Nouvelles résidences près des plages, lots avec vue, positionnement sur la location courte durée en haute saison.",
        "Pererenan — $147 500 et Cemagi — $149 000. Partie ouest de Canggu : plus calme que Batu Bolong, prix plus bas, infrastructures en rattrapage.",
        "Batu Bolong — $175 000, 31 lots. Le cœur de Canggu, densité maximale de cafés et de coworkings, avec le profil de locataire le plus prévisible.",
        "Uluwatu — $220 000 et Berawa — $235 000. Résidences premium, revenu par nuit élevé, mais ticket d’entrée plus important.",
        "Nusa Dua — $157 900 et Sanur — $468 000. Le sud hôtelier et l’est résidentiel calme : familles, séjours longue durée, taux d’occupation régulier sans pics."
      ]
    },
    {
      "heading": "Comment un étranger peut acheter un appartement à Bali",
      "paragraphs": [
        "Le schéma est le même que pour les villas : le freehold complet (Hak Milik) n’est pas accessible à un étranger. Les appartements s’achètent en leasehold (Hak Sewa) — dans le catalogue, 255 lots ont une durée de 26–30 ans, 114 de 31 ans et plus, et 40 jusqu’à 25 ans. Un résident avec KITAS peut obtenir un Hak Pakai, et celui qui en fait une activité professionnelle peut détenir via une PT PMA avec droit HGB.",
        "Ordre habituel de la transaction : réservation avec dépôt, vérification juridique de la résidence et du promoteur, signature chez le notaire PPAT, paiement selon l’échéancier, réception de l’unité et signature du procès-verbal. Dans une résidence, il faut aussi vérifier les statuts, le montant du service charge et l’identité du gestionnaire après livraison.",
        "Frais liés à la transaction : le PPh de 2,5% du prix est payé par le vendeur, le BPHTB jusqu’à 5% par l’acheteur lors de l’enregistrement des droits, et la TVA incluse dans le prix du neuf est effectivement de 11%. Les taux dépendent du kabupaten et du statut du vendeur ; le budget final doit donc être confirmé par le notaire avant le versement du dépôt."
      ]
    },
    {
      "heading": "Points à vérifier avant l’achat",
      "paragraphs": [
        "Les appartements ont leurs propres risques : vous n’achetez pas seulement une unité, mais aussi la qualité de gestion de l’immeuble. Check-list :"
      ],
      "bullets": [
        "Le zonage du terrain de la résidence — sur un terrain résidentiel (jaune), la location touristique courte durée est illégale, alors que c’est souvent elle qui est retenue dans le calcul de rentabilité.",
        "Les autorisations PBG et SLF pour l’ensemble de la résidence, et pas seulement la documentation de projet.",
        "La durée du leasehold, les conditions et le prix de prolongation — et si la durée de votre unité correspond bien à celle du bail foncier de toute la résidence.",
        "Le montant du service charge et ce qu’il couvre : il réduit la rentabilité chaque mois.",
        "Qui gère l’immeuble après la livraison, s’il existe un contrat avec la société de gestion et dans quelles conditions il peut être résilié.",
        "L’historique du promoteur : résidences livrées, respect des délais, sort des fonds en cas d’arrêt du chantier.",
        "Le taux d’occupation réel des résidences voisines, et non la projection de la plaquette commerciale."
      ]
    },
    {
      "heading": "Location, rentabilité et charges",
      "paragraphs": [
        "Repères pour la location mensuelle : médiane de $2 585 à Berawa, $2 113 à Canggu, $1 608 dans le Bukit, $1 300 à Ubud. Les appartements se louent en moyenne moins cher que les villas, mais avec un taux d’occupation plus régulier — une unité compacte avec piscine de résidence se loue plus facilement hors saison.",
        "Une rentabilité nette réaliste se situe entre 8–12% par an avec un taux d’occupation de 70–80%. Avant de croire aux chiffres d’une présentation, déduisez la commission de la société de gestion de 15–25%, le service charge de la résidence, l’entretien et la taxe sur les loyers, ainsi que l’amortissement du leasehold. Vérifiez aussi séparément qu’une dizaine de résidences similaires n’arrivent pas en même temps sur le marché dans votre zone : à Canggu, la surabondance de studios identiques pèse déjà sur les loyers."
      ]
    }
  ],
  "priceTable": {
    "caption": "Prix des appartements à Bali selon le nombre de chambres",
    "columns": [
      "Chambres",
      "Surface",
      "Prix typique",
      "Médiane"
    ],
    "rows": [
      [
        "Studio / 1 chambre",
        "41 m²",
        "$101 500 – $302 400",
        "$145 700"
      ],
      [
        "2 chambres",
        "99 m²",
        "$200 000 – $673 000",
        "$389 000"
      ],
      [
        "3 chambres",
        "125 m²",
        "$544 000 – $1 125 000",
        "$884 000"
      ],
      [
        "Tout le marché",
        "—",
        "$105 000 – $502 500",
        "$160 000"
      ]
    ],
    "note": "La fourchette correspond aux 10e et 90e percentiles sur 423 appartements avec prix renseigné. Données du catalogue, mises à jour avec les tarifs des promoteurs."
  },
  "faqExtra": [
    {
      "q": "Qu’est-ce qui est le plus intéressant : un appartement ou une villa ?",
      "a": "L’appartement demande un ticket d’entrée plus faible (médiane de $160 000 contre $350 000 pour les villas), il est plus simple à entretenir et se loue plus facilement hors saison grâce aux infrastructures de la résidence. La villa offre plus d’intimité, un terrain et un revenu par nuit plus élevé, mais exige une gestion plus active et des frais d’entretien nettement supérieurs. Pour un premier achat à Bali, on choisit plus souvent un appartement ; pour vivre en famille, plutôt une villa."
    },
    {
      "q": "Qu’est-ce que le service charge et combien cela coûte ?",
      "a": "Le service charge est le paiement mensuel pour l’entretien des parties communes : piscine, ascenseurs, sécurité, nettoyage, enlèvement des déchets, réception. Il est calculé selon la surface de l’unité et joue dans le budget le même rôle que les charges de copropriété. Son montant doit être connu avant la transaction : il réduit directement la rentabilité nette, et dans certaines résidences il est indexé chaque année."
    },
    {
      "q": "Que devient l’appartement à la fin du leasehold ?",
      "a": "Les droits reviennent au propriétaire du terrain si la durée n’est pas prolongée. Deux points du contrat sont donc essentiels : les conditions de prolongation (le prix du second cycle est-il fixé) et la concordance entre la durée de votre unité et celle du bail foncier de toute la résidence — il arrive qu’elles diffèrent, et c’est un risque caché."
    },
    {
      "q": "Peut-on acheter un appartement en paiement échelonné ?",
      "a": "Pendant la construction, c’est le schéma standard : acompte de 30–50%, puis solde par étapes jusqu’à la livraison, en règle générale sans intérêts. Le crédit hypothécaire pour un étranger à Bali est pratiquement inaccessible, donc c’est le promoteur lui-même qui accorde l’échelonnement. Pour les unités déjà livrées, les facilités de paiement sont plus courtes et plus rares."
    },
    {
      "q": "Qui s’occupe de la mise en location de l’appartement ?",
      "a": "Le plus souvent, c’est la société de gestion de la résidence : elle prend en charge la diffusion sur les plateformes, les check-in, le ménage et l’entretien contre 15–25% du chiffre d’affaires. Le propriétaire peut aussi louer lui-même, mais dans la plupart des résidences il existe un règlement locatif unique — cette clause doit être lue avant l’achat."
    },
    {
      "q": "Peut-on acheter un appartement à distance ?",
      "a": "Oui, les transactions se font régulièrement par procuration : visite vidéo, documents via le notaire PPAT, paiement par virement. Condition impérative : une vérification juridique indépendante de la résidence et une réception de l’unité par votre représentant sur place, et non par un employé du service commercial."
    }
  ]
}

export default copy
