// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/apartments/ru.ts (Indonesian).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Berapa harga apartemen di Bali",
      "paragraphs": [
        "Di katalog terdapat 423 apartemen dijual di 197 kompleks hunian. Harga median — $160.000, delapan dari sepuluh unit berada dalam kisaran $105.000 hingga $502.500. Titik masuk pasar mulai sekitar $65.000 untuk studio di kompleks tahap awal pembangunan, sedangkan batas atas mencapai $1,28 juta untuk penthouse dekat laut.",
        "Pasar apartemen di Bali berbeda dari pasar vila: mayoritas berupa unit kompak. Delapan dari sepuluh listing adalah studio dan 1 kamar tidur dengan luas median 41 m². Apartemen 2 kamar tidur sudah lebih jarang (72 unit), sedangkan 3 kamar tidur adalah produk premium yang sangat terbatas."
      ]
    },
    {
      "heading": "Beli saat pembangunan atau di kompleks siap huni",
      "paragraphs": [
        "Dari 423 apartemen, 366 masih dalam pembangunan dan hanya 53 yang sudah selesai — pasar hampir sepenuhnya primer. Konsekuensinya jelas: pembelian pada tahap konstruksi biasanya disertai cicilan dari developer (uang muka umumnya 30–50%, sisanya dibayar per tahap) dan harga lebih rendah dibanding unit siap huni, tetapi ada risiko keterlambatan penyelesaian.",
        "Harga median per meter — dari $3.300 hingga $4.700 tergantung area, dan jelas lebih tinggi daripada vila. Ini wajar: dalam harga per meter apartemen sudah termasuk kolam renang bersama, lobi, keamanan, lift, dan perusahaan pengelola. Membandingkan unit antar-kompleks lebih tepat berdasarkan harga per meter, bukan total harga — luas studio bisa berbeda sampai dua kali lipat."
      ]
    },
    {
      "heading": "Di mana beli apartemen di Bali: area dan harga",
      "paragraphs": [
        "Kompleks apartemen terkonsentrasi di beberapa zona, dan selisih harga antar-zona bisa mencapai tiga kali lipat. Median apartemen 1 kamar tidur di katalog:"
      ],
      "bullets": [
        "Ubud — $121.500, titik masuk paling terjangkau dan pilihan terbesar (45 unit). Permintaan sewa jangka panjang stabil sepanjang tahun, dengan audiens yoga dan wellness yang kuat.",
        "Pandawa dan selatan Bukit — $135.000. Kompleks baru dekat pantai, unit dengan view, fokus pada sewa harian di musim ramai.",
        "Pererenan — $147.500 dan Cemagi — $149.000. Bagian barat Canggu: lebih tenang daripada Batu Bolong, harga lebih rendah, infrastruktur terus berkembang.",
        "Batu Bolong — $175.000, 31 unit. Pusat Canggu, konsentrasi kafe dan coworking tertinggi, tipe penyewa paling mudah diprediksi.",
        "Uluwatu — $220.000 dan Berawa — $235.000. Kompleks premium, tarif per malam tinggi, tetapi biaya masuk pasar juga lebih mahal.",
        "Nusa Dua — $157.900 dan Sanur — $468.000. Kawasan selatan bergaya resor dan timur yang lebih tenang: cocok untuk keluarga, tinggal jangka panjang, okupansi lebih stabil tanpa lonjakan musiman."
      ]
    },
    {
      "heading": "Cara orang asing membeli apartemen di Bali",
      "paragraphs": [
        "Skemanya sama seperti vila: freehold penuh (Hak Milik) tidak tersedia untuk orang asing. Apartemen dibeli dengan leasehold (Hak Sewa) — di katalog, 255 unit memiliki sisa masa 26–30 tahun, 114 unit — dari 31 tahun, dan 40 unit — hingga 25 tahun. Pemegang KITAS dapat menggunakan Hak Pakai, sedangkan untuk tujuan bisnis kepemilikan bisa dilakukan melalui PT PMA dengan hak HGB.",
        "Urutan transaksi: reservasi dengan deposit, legal check kompleks dan developer, penandatanganan perjanjian di hadapan notaris PPAT, pembayaran sesuai jadwal, serah terima unit, lalu penandatanganan berita acara. Pada kompleks apartemen, perlu juga memeriksa anggaran dasar, besaran service charge, dan siapa yang akan mengelola bangunan setelah serah terima.",
        "Biaya transaksi: PPh 2,5% dari harga dibayar penjual, BPHTB hingga 5% — pembeli saat pengurusan hak, PPN dalam harga properti baru efektif 11%. Tarif bergantung pada kabupaten dan status penjual, поэтому estimasi akhir harus dikonfirmasi notaris sebelum deposit dibayarkan."
      ]
    },
    {
      "heading": "Apa yang harus dicek sebelum membeli",
      "paragraphs": [
        "Apartemen memiliki risiko tersendiri: Anda membeli bukan hanya unit, tetapi juga kualitas pengelolaan gedung. Checklist:"
      ],
      "bullets": [
        "Zonasi lahan kompleks — di lahan hunian (zona kuning), sewa harian untuk wisatawan tidak legal, padahal biasanya justru itu yang dipakai dalam proyeksi imbal hasil.",
        "Izin PBG dan SLF untuk seluruh kompleks, bukan hanya dokumen perencanaan proyek.",
        "Sisa masa leasehold, syarat dan harga perpanjangan — serta apakah masa berlaku unit Anda sama dengan masa sewa tanah untuk seluruh kompleks.",
        "Besaran service charge dan apa saja yang termasuk di dalamnya: biaya ini mengurangi imbal hasil setiap bulan.",
        "Siapa yang mengelola gedung setelah serah terima, apakah ada perjanjian dengan perusahaan pengelola, dan bagaimana syarat pemutusannya.",
        "Rekam jejak developer: proyek yang sudah selesai, kepatuhan terhadap jadwal, dan bagaimana nasib dana jika pembangunan berhenti.",
        "Tingkat okupansi nyata di kompleks sekitar, bukan proyeksi dari presentasi."
      ]
    },
    {
      "heading": "Sewa, imbal hasil, dan biaya operasional",
      "paragraphs": [
        "Patokan sewa bulanan: median $2.585 di Berawa, $2.113 di Canggu, $1.608 di Bukit, $1.300 di Ubud. Apartemen rata-rata disewakan lebih murah daripada vila, tetapi okupansinya lebih stabil — unit kompak dengan kolam renang kompleks lebih mudah disewakan di luar musim ramai.",
        "Imbal hasil bersih yang realistis — 8–12% per tahun dengan okupansi 70–80%. Sebelum percaya angka dalam presentasi, kurangi dulu komisi perusahaan pengelola 15–25%, service charge kompleks, biaya perawatan dan pajak sewa, serta amortisasi leasehold. Periksa juga secara terpisah apakah di area Anda akan masuk lagi belasan kompleks serupa ke pasar: di Canggu, kelebihan pasokan studio yang mirip sudah mulai menekan tarif sewa."
      ]
    }
  ],
  "priceTable": {
    "caption": "Harga apartemen di Bali berdasarkan jumlah kamar tidur",
    "columns": [
      "Kamar tidur",
      "Luas",
      "Harga tipikal",
      "Median"
    ],
    "rows": [
      [
        "Studio / 1 kamar tidur",
        "41 m²",
        "$101.500 – $302.400",
        "$145.700"
      ],
      [
        "2 kamar tidur",
        "99 m²",
        "$200.000 – $673.000",
        "$389.000"
      ],
      [
        "3 kamar tidur",
        "125 m²",
        "$544.000 – $1.125.000",
        "$884.000"
      ],
      [
        "Seluruh pasar",
        "—",
        "$105.000 – $502.500",
        "$160.000"
      ]
    ],
    "note": "Rentang — persentil ke-10 dan ke-90 untuk 423 apartemen dengan harga yang tercantum. Data katalog, diperbarui mengikuti pricelist developer."
  },
  "faqExtra": [
    {
      "q": "Mana yang lebih menguntungkan — apartemen atau vila?",
      "a": "Apartemen lebih murah untuk masuk pasar (median $160.000 dibanding $350.000 untuk vila), lebih mudah dirawat, dan lebih gampang disewakan di luar musim ramai berkat fasilitas kompleks. Vila memberi privasi, tanah, dan tarif sewa per malam yang lebih tinggi, tetapi memerlukan pengelolaan pribadi dan biaya perawatan yang jauh lebih besar. Untuk properti pertama di Bali, pembeli lebih sering memilih apartemen; untuk tinggal bersama keluarga, biasanya vila."
    },
    {
      "q": "Apa itu service charge dan berapa biayanya?",
      "a": "Service charge adalah pembayaran bulanan untuk pemeliharaan area bersama: kolam renang, lift, keamanan, kebersihan, pengangkutan sampah, resepsionis. Perhitungannya berdasarkan luas unit dan dalam anggaran fungsinya mirip biaya utilitas. Besarannya harus diketahui sebelum transaksi: biaya ini langsung mengurangi imbal hasil bersih, dan di beberapa kompleks nilainya diindeks setiap tahun."
    },
    {
      "q": "Apa yang terjadi dengan apartemen setelah leasehold berakhir?",
      "a": "Hak kembali kepada pemilik tanah jika masa berlakunya tidak diperpanjang. Karena itu, ada dua poin penting dalam perjanjian: syarat perpanjangan (apakah harga untuk periode kedua sudah ditetapkan) dan apakah masa berlaku unit Anda sama dengan masa sewa tanah untuk seluruh kompleks — kadang berbeda, dan itu merupakan risiko tersembunyi."
    },
    {
      "q": "Apakah apartemen bisa dibeli dengan cicilan?",
      "a": "Pada tahap pembangunan ini adalah skema standar: uang muka 30–50%, sisanya dibayar per tahap sampai serah terima, umumnya tanpa bunga. KPR untuk orang asing di Bali praktis tidak tersedia, sehingga cicilan biasanya diberikan langsung oleh developer. Untuk unit siap huni, tenor cicilan lebih pendek dan lebih jarang ditawarkan."
    },
    {
      "q": "Siapa yang mengurus penyewaan apartemen?",
      "a": "Biasanya perusahaan pengelola kompleks: mereka menangani listing di platform, check-in tamu, kebersihan, dan perawatan dengan komisi 15–25% dari pendapatan. Pemilik bisa menyewakan sendiri, tetapi di sebagian besar kompleks berlaku aturan sewa terpadu — syarat ini perlu dibaca sebelum membeli."
    },
    {
      "q": "Apakah apartemen bisa dibeli dari jarak jauh?",
      "a": "Ya, transaksi seperti ini rutin dilakukan dengan surat kuasa: penayangan via video, dokumen melalui notaris PPAT, pembayaran lewat transfer. Syarat wajibnya adalah legal check independen atas kompleks dan serah terima unit oleh perwakilan Anda di lokasi, bukan oleh staf sales."
    }
  ]
}

export default copy
