// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/apartments/ru.ts (Dutch).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Wat kosten appartementen op Bali",
      "paragraphs": [
        "In de catalogus staan 423 appartementen te koop in 197 wooncomplexen. De mediaanprijs is $160.000, acht op de tien objecten vallen in de bandbreedte van $105.000 tot $502.500. Instappen in de markt begint rond $65.000 voor een studio in een complex in een vroege bouwfase, de bovenkant ligt op $1,28 mln voor een penthouse aan zee.",
        "De markt voor appartementen op Bali werkt anders dan de villamarkt: het gaat vooral om compacte units. Acht op de tien objecten zijn studio's en appartementen met 1 slaapkamer met een mediane oppervlakte van 41 m². Appartementen met 2 slaapkamers zijn al zeldzamer (72 objecten), 3-slaapkamerappartementen zijn een schaars premiumproduct."
      ]
    },
    {
      "heading": "Nieuwbouw of een opgeleverd complex",
      "paragraphs": [
        "Van de 423 appartementen zijn er 366 in aanbouw en slechts 53 opgeleverd — de markt is vrijwel volledig primair. Daar horen ook de spelregels bij: kopen in de bouwfase gaat met een betalingsregeling van de ontwikkelaar (eerste aanbetaling meestal 30–50%, het restant in termijnen per bouwfase) en met korting ten opzichte van de prijs van een opgeleverde unit, maar met het risico op uitloop van de oplevering.",
        "De mediane prijs per meter ligt tussen $3.300 en $4.700 afhankelijk van het gebied, merkbaar hoger dan bij villa's. Dat is normaal: in de meterprijs van appartementen zitten het gemeenschappelijke zwembad, de lobby, beveiliging, lift en beheermaatschappij inbegrepen. Objecten tussen complexen vergelijk je daarom beter op prijs per meter dan op de totale koopsom — de oppervlakte van studio's verschilt soms met een factor twee."
      ]
    },
    {
      "heading": "Waar appartementen kopen op Bali: wijken en prijzen",
      "paragraphs": [
        "Complexen zijn geconcentreerd in een paar zones, en het prijsverschil ertussen loopt op tot een factor drie. De mediaanprijs van appartementen met 1 slaapkamer in de catalogus:"
      ],
      "bullets": [
        "Ubud — $121.500, de laagste instap en de grootste steekproef (45 objecten). Vraag naar langetermijnverhuur het hele jaar door, met een sterke yoga- en wellnessdoelgroep.",
        "Pandawa en het zuiden van Bukit — $135.000. Nieuwe complexen bij de stranden, units met uitzicht, focus op kortetermijnverhuur in het hoogseizoen.",
        "Pererenan — $147.500 en Cemagi — $149.000. Het westelijke deel van Canggu: rustiger dan Batu Bolong, prijzen liggen lager, infrastructuur is bezig met inhalen.",
        "Batu Bolong — $175.000, 31 objecten. Het hart van Canggu, de hoogste dichtheid aan cafés en coworkings, de meest voorspelbare huurder.",
        "Uluwatu — $220.000 en Berawa — $235.000. Premiumcomplexen, hoge prijs per nacht, maar ook een duurdere instap.",
        "Nusa Dua — $157.900 en Sanur — $468.000. Het hotelgerichte zuiden en het rustige oosten: gezinnen, lang verblijf, stabiele bezetting zonder pieken."
      ]
    },
    {
      "heading": "Hoe een buitenlander appartementen koopt op Bali",
      "paragraphs": [
        "De structuur is dezelfde als bij villa's: volledige freehold (Hak Milik) is niet beschikbaar voor buitenlanders. Appartementen worden gekocht op leasehold-basis (Hak Sewa) — bij 255 objecten in de catalogus is de looptijd 26–30 jaar, bij 114 vanaf 31 jaar, bij 40 tot 25 jaar. Een resident met KITAS kan Hak Pakai registreren, en wie het als bedrijf aanhoudt kan bezitten via PT PMA met recht op HGB.",
        "De volgorde van de transactie: reservering met een aanbetaling, juridische controle van het complex en de ontwikkelaar, overeenkomst bij de notaris PPAT, betaling volgens schema, oplevering van de unit en ondertekening van het proces-verbaal. In een complex kijk je daarnaast naar de statuten, de hoogte van de service charge en wie het gebouw na oplevering beheert.",
        "Kosten bij de transactie: PPh 2,5% van de prijs betaalt de verkoper, BPHTB tot 5% betaalt de koper bij registratie van de rechten, btw in de prijs van nieuwbouw is effectief 11%. De tarieven hangen af van het kabupaten en de status van de verkoper, daarom bevestigt de notaris de definitieve kostenraming vóórdat de aanbetaling wordt gedaan."
      ]
    },
    {
      "heading": "Wat u vóór aankoop moet controleren",
      "paragraphs": [
        "Bij appartementen horen eigen risico's: u koopt niet alleen een unit, maar ook de kwaliteit van het gebouwbeheer. Checklist:"
      ],
      "bullets": [
        "De zonering van de grond van het complex — op residentiële (gele) grond is kortetermijnverhuur aan toeristen niet toegestaan, terwijl juist dat meestal in de rendementsberekening is opgenomen.",
        "Vergunningen PBG en SLF voor het volledige complex, niet alleen de projectdocumentatie.",
        "De duur van de leasehold, de voorwaarden en prijs van verlenging — en of de looptijd van uw unit overeenkomt met de looptijd van de grondhuur onder het hele complex.",
        "De hoogte van de service charge en wat daarin is inbegrepen: die drukt elke maand op het rendement.",
        "Wie het gebouw na oplevering beheert, of er een overeenkomst met de beheermaatschappij is en onder welke voorwaarden die kan worden beëindigd.",
        "De geschiedenis van de ontwikkelaar: opgeleverde complexen, naleving van termijnen, en wat er met het geld gebeurt als de bouw stilvalt.",
        "De werkelijke bezetting van vergelijkbare naburige complexen, niet alleen de prognose uit de presentatie."
      ]
    },
    {
      "heading": "Verhuur, rendement en kosten van eigendom",
      "paragraphs": [
        "Richtlijn voor maandelijkse huur: de mediaan is $2.585 in Berawa, $2.113 in Canggu, $1.608 in Bukit, $1.300 in Ubud. Appartementen worden gemiddeld goedkoper verhuurd dan villa's, maar kennen een stabielere bezetting — een compacte unit met zwembad in het complex is buiten het seizoen makkelijker te verhuren.",
        "Een realistisch netto rendement ligt op 8–12% per jaar bij een bezetting van 70–80%. Voordat u een cijfer uit een presentatie gelooft, trek eerst de commissie van de beheermaatschappij van 15–25%, de service charge van het complex, onderhoud en huurbelasting af, plus de afschrijving van de leasehold. Controleer daarnaast apart of er in uw gebied niet nog een tiental vergelijkbare complexen op de markt komt: in Canggu drukt een overaanbod van identieke studio's de huurprijs al naar beneden."
      ]
    }
  ],
  "priceTable": {
    "caption": "Appartementprijzen op Bali naar aantal slaapkamers",
    "columns": [
      "Slaapkamers",
      "Oppervlakte",
      "Typische prijs",
      "Mediaan"
    ],
    "rows": [
      [
        "Studio / 1 slaapkamer",
        "41 m²",
        "$101.500 – $302.400",
        "$145.700"
      ],
      [
        "2 slaapkamers",
        "99 m²",
        "$200.000 – $673.000",
        "$389.000"
      ],
      [
        "3 slaapkamers",
        "125 m²",
        "$544.000 – $1.125.000",
        "$884.000"
      ],
      [
        "Hele markt",
        "—",
        "$105.000 – $502.500",
        "$160.000"
      ]
    ],
    "note": "De bandbreedte is het 10e en 90e percentiel voor 423 appartementen met vermelde prijs. Catalogusdata, bijgewerkt samen met de prijslijsten van ontwikkelaars."
  },
  "faqExtra": [
    {
      "q": "Wat is voordeliger — een appartement of een villa?",
      "a": "Appartementen zijn goedkoper in de instap (mediaan $160.000 tegenover $350.000 voor villa's), eenvoudiger in onderhoud en buiten het seizoen makkelijker te verhuren dankzij de infrastructuur van het complex. Een villa biedt privacy, een perceel en een hogere prijs per nacht, maar vraagt om eigen beheer en duidelijk hogere onderhoudskosten. Voor een eerste object op Bali kiezen kopers vaker voor een appartement, voor gezinsbewoning eerder voor een villa."
    },
    {
      "q": "Wat is service charge en hoeveel kost het?",
      "a": "Service charge is de maandelijkse bijdrage voor het onderhoud van de gemeenschappelijke delen: zwembad, liften, beveiliging, schoonmaak, afvalverwerking, receptie. Die wordt berekend op basis van de oppervlakte van de unit en speelt in het budget dezelfde rol als servicekosten. De hoogte moet u vóór de transactie opvragen: die verlaagt rechtstreeks het netto rendement, en in sommige complexen wordt die jaarlijks geïndexeerd."
    },
    {
      "q": "Wat gebeurt er met appartementen na afloop van de leasehold?",
      "a": "De rechten vallen terug aan de grondeigenaar als de termijn niet wordt verlengd. Daarom zijn twee punten in het contract cruciaal: de voorwaarden voor verlenging (of de prijs van de tweede termijn is vastgelegd) en of de looptijd van uw unit gelijk loopt met de looptijd van de grondhuur onder het hele complex — soms verschilt dat, en dat is een verborgen risico."
    },
    {
      "q": "Kun je appartementen in termijnen kopen?",
      "a": "In de bouwfase is dat de standaardstructuur: eerste aanbetaling 30–50%, het restant in termijnen tot oplevering, doorgaans zonder rente. Een hypotheek voor buitenlanders op Bali is praktisch niet beschikbaar, daarom biedt de ontwikkelaar zelf de betalingsregeling aan. Voor opgeleverde units is een betalingsregeling korter en komt die minder vaak voor."
    },
    {
      "q": "Wie verzorgt de verhuur van appartementen?",
      "a": "Meestal de beheermaatschappij van het complex: die neemt plaatsing op platforms, check-in, schoonmaak en onderhoud op zich voor 15–25% van de omzet. De eigenaar kan ook zelf verhuren, maar in de meeste complexen geldt één uniform verhuurreglement — die voorwaarde moet u vóór aankoop lezen."
    },
    {
      "q": "Kun je appartementen op afstand kopen?",
      "a": "Ja, transacties worden regelmatig via volmacht gedaan: videobezichtiging, documenten via de notaris PPAT, betaling per overboeking. Voorwaarde is wel een onafhankelijke juridische controle van het complex en opleveringsinspectie van de unit door uw vertegenwoordiger ter plaatse, niet door een medewerker van de verkoopafdeling."
    }
  ]
}

export default copy
