// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/apartments/ru.ts (Polish).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Ile kosztują apartamenty na Bali",
      "paragraphs": [
        "W katalogu jest 423 apartamentów na sprzedaż w 197 kompleksach mieszkaniowych. Mediana ceny wynosi $160,000, osiem na dziesięć ofert mieści się w przedziale od $105,000 do $502,500. Wejście na rynek zaczyna się od około $65,000 za studio w kompleksie na wczesnym etapie budowy, a górny pułap to $1,28 mln za penthouse przy oceanie.",
        "Rynek apartamentów na Bali działa inaczej niż rynek willi: to głównie kompaktowe lokale. Osiem na dziesięć ofert to studia i apartamenty z 1 sypialnią o medianie powierzchni 41 m². Apartamenty z 2 sypialniami są już rzadkością (72 oferty), a 3 sypialnie to pojedynczy produkt premium."
      ]
    },
    {
      "heading": "Budowa czy gotowy kompleks",
      "paragraphs": [
        "Spośród 423 apartamentów 366 jest w budowie, a tylko 53 zostały oddane — rynek jest niemal w całości pierwotny. Z tego wynikają zasady gry: zakup na etapie budowy odbywa się w systemie rat od dewelopera (pierwsza wpłata zwykle 30–50%, reszta według etapów) i z dyskontem względem ceny gotowego lokalu, ale z ryzykiem przesunięcia terminów.",
        "Mediana ceny za metr wynosi od $3,300 do $4,700 w zależności od lokalizacji, wyraźnie więcej niż w przypadku willi. To normalne: w cenie metra apartamentu zawarte są wspólny basen, lobby, ochrona, winda i firma zarządzająca. Porównywanie ofert między kompleksami jest bardziej miarodajne według ceny za metr niż według łącznej kwoty — powierzchnie studiów różnią się nawet dwukrotnie."
      ]
    },
    {
      "heading": "Gdzie kupić apartament na Bali: lokalizacje i ceny",
      "paragraphs": [
        "Kompleksy koncentrują się w kilku strefach, a rozpiętość cen między nimi jest trzykrotna. Mediana apartamentów z 1 sypialnią w katalogu:"
      ],
      "bullets": [
        "Ubud — $121,500, najniższy próg wejścia i największa próba (45 ofert). Popyt na najem długoterminowy przez cały rok, silna grupa odbiorców związanych z yogą i wellness.",
        "Pandawa i południe Bukit — $135,000. Nowe kompleksy przy plażach, lokale z widokiem, nacisk na najem krótkoterminowy w wysokim sezonie.",
        "Pererenan — $147,500 i Cemagi — $149,000. Zachodnia część Canggu: ciszej niż w Batu Bolong, ceny niższe, infrastruktura szybko nadrabia.",
        "Batu Bolong — $175,000, 31 ofert. Serce Canggu, najwyższe zagęszczenie kawiarni i coworkingów, najbardziej przewidywalny najemca.",
        "Uluwatu — $220,000 i Berawa — $235,000. Kompleksy premium, wysoka stawka za noc, ale też droższe wejście na rynek.",
        "Nusa Dua — $157,900 i Sanur — $468,000. Hotelowe południe i spokojny wschód: rodziny, dłuższe pobyty, równe obłożenie bez wyraźnych pików."
      ]
    },
    {
      "heading": "Jak cudzoziemiec może kupić apartament na Bali",
      "paragraphs": [
        "Schemat jest taki sam jak przy willach: pełny freehold (Hak Milik) nie jest dostępny dla cudzoziemca. Apartamenty kupuje się w formule leasehold (Hak Sewa) — dla 255 ofert w katalogu okres wynosi 26–30 lat, dla 114 — od 31 lat, a dla 40 — do 25 lat. Rezydent z KITAS może uzyskać Hak Pakai, a osoba kupująca w celach biznesowych — posiadać nieruchomość przez PT PMA z prawem HGB.",
        "Kolejność transakcji: rezerwacja z depozytem, kontrola prawna kompleksu i dewelopera, umowa u notariusza PPAT, płatność zgodnie z harmonogramem, odbiór lokalu i podpisanie protokołu. W kompleksie dodatkowo sprawdza się statut, wysokość service charge oraz to, kto zarządza budynkiem po oddaniu.",
        "Płatności w transakcji: PPh 2,5% od ceny płaci sprzedający, BPHTB do 5% — kupujący przy rejestracji praw, VAT w cenie nowego lokalu efektywnie wynosi 11%. Stawki zależą od kabupatenu i statusu sprzedającego, dlatego ostateczny kosztorys potwierdza notariusz przed wpłatą depozytu."
      ]
    },
    {
      "heading": "Co sprawdzić przed zakupem",
      "paragraphs": [
        "Przy apartamentach ryzyka są inne: kupujesz nie tylko lokal, ale też jakość zarządzania budynkiem. Check-lista:"
      ],
      "bullets": [
        "Przeznaczenie gruntu pod kompleksem — na ziemi mieszkaniowej (żółtej) najem krótkoterminowy dla turystów jest nielegalny, a to właśnie on zwykle jest wpisany w kalkulację rentowności.",
        "Pozwolenia PBG i SLF dla całego kompleksu, a nie tylko dokumentacja projektowa.",
        "Okres leasehold, warunki i cena przedłużenia — oraz czy okres twojego lokalu pokrywa się z okresem dzierżawy gruntu pod całym kompleksem.",
        "Wysokość service charge i co obejmuje: co miesiąc obniża rentowność.",
        "Kto zarządza budynkiem po oddaniu, czy istnieje umowa z zarządcą i na jakich warunkach można ją rozwiązać.",
        "Historia dewelopera: oddane kompleksy, dotrzymywanie terminów, los środków w razie wstrzymania budowy.",
        "Rzeczywiste obłożenie sąsiednich kompleksów, a nie prognoza z prezentacji."
      ]
    },
    {
      "heading": "Najem, rentowność i koszty utrzymania",
      "paragraphs": [
        "Punkt odniesienia dla najmu miesięcznego: mediana to $2,585 w Berawa, $2,113 w Canggu, $1,608 na Bukit, $1,300 w Ubud. Apartamenty średnio wynajmują się taniej niż wille, ale mają bardziej stabilne obłożenie — kompaktowy lokal z basenem w kompleksie łatwiej wynająć poza sezonem.",
        "Realistyczna rentowność netto to 8–12% rocznie przy obłożeniu 70–80%. Zanim uwierzysz w liczbę z prezentacji, odejmij prowizję firmy zarządzającej 15–25%, service charge kompleksu, utrzymanie i podatek od najmu, a także amortyzację leasehold. Osobno sprawdź też, czy w twojej lokalizacji nie wchodzi na rynek kolejnych kilkanaście podobnych kompleksów: w Canggu nadpodaż identycznych studiów już obniża stawki."
      ]
    }
  ],
  "priceTable": {
    "caption": "Ceny apartamentów na Bali według liczby sypialni",
    "columns": [
      "Sypialnie",
      "Powierzchnia",
      "Typowa cena",
      "Mediana"
    ],
    "rows": [
      [
        "Studio / 1 sypialnia",
        "41 m²",
        "$101,500 – $302,400",
        "$145,700"
      ],
      [
        "2 sypialnie",
        "99 m²",
        "$200,000 – $673,000",
        "$389,000"
      ],
      [
        "3 sypialnie",
        "125 m²",
        "$544,000 – $1,125,000",
        "$884,000"
      ],
      [
        "Cały rynek",
        "—",
        "$105,000 – $502,500",
        "$160,000"
      ]
    ],
    "note": "Przedział — 10. i 90. percentyl dla 423 apartamentów z podaną ceną. Dane katalogowe, aktualizowane razem z cennikami deweloperów."
  },
  "faqExtra": [
    {
      "q": "Co bardziej się opłaca — apartament czy willa?",
      "a": "Apartament wymaga niższego kapitału na wejściu (mediana $160,000 wobec $350,000 dla willi), jest prostszy w utrzymaniu i łatwiej wynajmuje się poza sezonem dzięki infrastrukturze kompleksu. Willa daje prywatność, działkę i wyższą stawkę za noc, ale wymaga osobistego zarządzania i wyraźnie większych kosztów utrzymania. Na pierwszą nieruchomość na Bali częściej wybiera się apartament, do życia z rodziną — willę."
    },
    {
      "q": "Czym jest service charge i ile wynosi?",
      "a": "Service charge to miesięczna opłata za utrzymanie części wspólnych: basenu, wind, ochrony, sprzątania, wywozu śmieci, recepcji. Liczy się ją od powierzchni lokalu i w budżecie pełni podobną rolę jak opłaty eksploatacyjne. Jej wysokość trzeba sprawdzić przed transakcją: bezpośrednio obniża rentowność netto, a w niektórych kompleksach jest indeksowana co roku."
    },
    {
      "q": "Co stanie się z apartamentem po zakończeniu leasehold?",
      "a": "Prawa wracają do właściciela gruntu, jeśli okres nie zostanie przedłużony. Dlatego w umowie kluczowe są dwa punkty: warunki przedłużenia (czy cena drugiego okresu jest z góry ustalona) oraz zgodność okresu twojego lokalu z okresem dzierżawy gruntu pod całym kompleksem — czasem się różnią i to ukryte ryzyko."
    },
    {
      "q": "Czy można kupić apartament w systemie ratalnym?",
      "a": "Na etapie budowy to standardowy model: pierwsza wpłata 30–50%, reszta według etapów do oddania, z reguły bez odsetek. Hipoteka dla cudzoziemca na Bali jest praktycznie niedostępna, dlatego raty zapewnia sam deweloper. Przy gotowych lokalach raty są krótsze i spotyka się je rzadziej."
    },
    {
      "q": "Kto zajmuje się wynajmem apartamentu?",
      "a": "Zwykle firma zarządzająca kompleksem: odpowiada za publikację ofert na platformach, zameldowanie gości, sprzątanie i obsługę za 15–25% przychodu. Właściciel może wynajmować także samodzielnie, ale w większości kompleksów obowiązuje jednolity regulamin najmu — ten warunek trzeba przeczytać przed zakupem."
    },
    {
      "q": "Czy można kupić apartament zdalnie?",
      "a": "Tak, transakcje są regularnie prowadzone na podstawie pełnomocnictwa: prezentacja wideo, dokumenty przez notariusza PPAT, płatność przelewem. Warunek obowiązkowy — niezależna kontrola prawna kompleksu i odbiór lokalu przez twojego przedstawiciela na miejscu, a nie przez pracownika działu sprzedaży."
    }
  ]
}

export default copy
