// Reader-facing on-page content (unique write-up + listing-specific FAQ)
// generated into assistant_kb (migrations 040 + 042) by
// scripts/kb-page-content.mjs. Detail pages prefer this over the thin/
// duplicate Airtable "SEO Text" + templated FAQ.

import { createClient } from '@supabase/supabase-js'
import type { Lang } from '@/lib/i18n'

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_KEY!,
)

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL

// Per-language KB body translations (EN → de/zh/nl…) generated by
// scripts/kb-translate-body.mjs into feeds/_kb-body-<lang>.json = { ref_id:
// { body } }. Loaded once per lang and cached in-memory so a listing whose
// only long-form copy is the EN-only KB write-up still renders natively.
type KbBodyCache = Record<string, { body?: string }>
const _bodyCache = new Map<string, { ts: number; data: KbBodyCache }>()
const BODY_TTL_MS = 5 * 60 * 1000

async function loadKbBodyCache(lang: Lang): Promise<KbBodyCache> {
  if (lang === 'ru' || lang === 'en') return {}
  const cached = _bodyCache.get(lang)
  if (cached && Date.now() - cached.ts < BODY_TTL_MS) return cached.data
  try {
    const url = `${SUPABASE_URL}/storage/v1/object/public/feeds/_kb-body-${lang}.json`
    const r = await fetch(url, { next: { revalidate: 300 } })
    if (!r.ok) { _bodyCache.set(lang, { ts: Date.now(), data: {} }); return {} }
    const data = (await r.json()) as KbBodyCache
    _bodyCache.set(lang, { ts: Date.now(), data })
    return data
  } catch {
    return _bodyCache.get(lang)?.data ?? {}
  }
}

export type KbFaq = { q: string; a: string }
export type KbPageContent = { body: string | null; faq: KbFaq[] }

// kind: villa | apartment | complex | developer. airtableId = the row's
// airtable_id (= assistant_kb.ref_id). Returns null when nothing generated yet
// so callers fall back to their existing content.
export async function loadKbPageContent(
  kind: string,
  airtableId: string | null | undefined,
  lang: Lang,
): Promise<KbPageContent | null> {
  if (!airtableId) return null
  const { data, error } = await sb
    .from('assistant_kb')
    .select('page_body, page_body_en, faq, faq_en')
    .eq('kind', kind)
    .eq('ref_id', airtableId)
    .maybeSingle()
  if (error || !data) return null
  let body = ((lang === 'ru' ? data.page_body : data.page_body_en) as string | null) ?? null
  // Non-RU: prefer the native KB body translation when one has been generated.
  if (lang !== 'ru' && lang !== 'en') {
    const translated = (await loadKbBodyCache(lang))[airtableId]?.body
    if (translated && translated.trim()) body = translated
  }
  const faqRaw = (lang === 'ru' ? data.faq : data.faq_en) as unknown
  const faq: KbFaq[] = Array.isArray(faqRaw)
    ? faqRaw
        .filter((x): x is { q: unknown; a: unknown } => !!x && typeof x === 'object' && 'q' in x && 'a' in x)
        .map(x => ({ q: String(x.q), a: String(x.a) }))
        .filter(x => x.q && x.a)
    : []
  if (!body && faq.length === 0) return null
  return { body, faq }
}
