// Per-language AI knowledge-base summaries (RU → en/de/id/fr/zh/nl) generated by
// scripts/kb-translate-summary.mjs into feeds/_kb-summary-<lang>.json =
// { ref_id: { title, summary } }. Read by /api/llm/search and /llms-full.txt so
// the AI-facing corpus is native per language. Falls back to the RU value
// (which callers de-Cyrillic) when a translation isn't generated yet.
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL

export type KbSummaryTr = { title?: string; summary?: string }
type Cache = Record<string, KbSummaryTr>

const _cache = new Map<string, { ts: number; data: Cache }>()
const TTL_MS = 5 * 60 * 1000

// Which langs have their own generated cache. RU is the source (assistant_kb).
// ban has no listing-content translation (shell scope) → serve en.
const SUPPORTED = new Set(['en', 'de', 'id', 'fr', 'zh', 'nl', 'pl', 'uk'])

export function kbSummaryLang(lang: string): string | null {
  if (lang === 'ban') return 'en'
  return SUPPORTED.has(lang) ? lang : null
}

export async function loadKbSummaryCache(lang: string): Promise<Cache> {
  const key = kbSummaryLang(lang)
  if (!key) return {}
  const hit = _cache.get(key)
  if (hit && Date.now() - hit.ts < TTL_MS) return hit.data
  try {
    const r = await fetch(`${SUPABASE_URL}/storage/v1/object/public/feeds/_kb-summary-${key}.json`, { next: { revalidate: 300 } })
    if (!r.ok) { _cache.set(key, { ts: Date.now(), data: {} }); return {} }
    const data = (await r.json()) as Cache
    _cache.set(key, { ts: Date.now(), data })
    return data
  } catch {
    return _cache.get(key)?.data ?? {}
  }
}
