// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/rental/ru.ts (Balinese (Basa Bali, polite register)).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Pira regane nyewa papan tinggal ring Bali",
      "paragraphs": [
        "Ring basis data wenten 1485 tawaran sewa bulanan. Tarif median ring sakancan pulo puniki — $2.138 sasih, miwah walu saking sapuluh pilihan kasengguh ring rentang $620 ngantos $5.200. Beda rega sane ageng puniki nenten kebetulan: “papan tinggal ring Bali” punika prasida dados studio ring Ubud regane $400, miwah villa sareng kolam ring Berawa regane $8.000.",
        "Faktor utama sane nentuin rega inggih punika jumlah kamar turu, kaping kalih wilayah, kaping tiga masa kontrak. Sewa bulanan prasida wantah langkung mirah timbang harian: kontrak taunan ring villa sane sami dados 2–3 kali langkung nguntungang timbang nyewa per wengi ring mangsa ramai."
      ]
    },
    {
      "heading": "Bulanan utawi harian",
      "paragraphs": [
        "Sewa harian mrasidayang ring minggu-minggu awal duk nyarengin wilayah, nanging antuk nginep ajeg punika mawit mahal. Kontrak bulanan 6 ngantos 12 sasih maring tarif sane langkung becik, miwah kontrak taunan maring tarif sane paling becik sane prasida kauningin: pamilik ring Bali lumrahnyane nyuun pembayaran setahun di muka miwah antuk punika regane kasuda cukup nyata.",
        "Praktik pasar: deposit biasane sami sareng pembayaran 1–2 sasih, utilitas (listrik, toya, internet) paling asiki nenten kalebet ring tarif, nanging perawatan kolam miwah taman pinaka lumrah sampun kalebet. Listrik ring villa sareng AC miwah kolam nambah anggaran $100–250 sasih."
      ]
    },
    {
      "heading": "Ring dija nyewa papan tinggal ring Bali: wilayah miwah tarif",
      "paragraphs": [
        "Tarif median ring basis data titiang béda langkung saking 2 kali antuk wilayah:"
      ],
      "bullets": [
        "Ubud — $1.300 sasih, 250 tawaran. Punika wilayah populer sane paling kajangkau: alas, sawah terasering, yoga miwah coworking, ka sagara 30–40 menit.",
        "Nusa Dua — $1.433 miwah Bukit — $1.625. Sisih kidul sane tenang, infrastruktur hotel, pasih sane becik, langkung kirang rame miwah macet timbang ring Canggu.",
        "Canggu — $2.113, 253 tawaran. Pilihan paling akéh miwah kahuripan sane paling padet: surfing, kafe, coworking. Ring genah puniki taler kompetisi kanggen griya sane becik pinaka paling ketat.",
        "Uluwatu — $2.442 miwah Seminyak — $2.380. Villa sareng pemandangan ring tebing miwah format urban sareng restoran sacara silih.",
        "Berawa — $2.600, Umalas — $2.750, Pererenan — $2.822. Bagian premium Canggu: villa anyar, langkung tenang timbang ring pusat, nanging langkung mahal.",
        "Batu Bolong — $3.100, wilayah paling mahal ring sampel puniki. Puseh Canggu sane cedek ka sagara antuk mlampah."
      ]
    },
    {
      "heading": "Papan sane nyata prasida kaséwa manut anggaran ragane",
      "paragraphs": [
        "Patokan manut kamar turu: villa miwah apartemen 1 kamar turu — median $960 sasih (bagian 10% pasar sane paling asor ngamargiang saking $385), 2 kamar turu — $2.000, 3 kamar turu — $2.880, 4 kamar turu — $5.670. Justru unit 2 kamar turu sane ngawangun pasar: ring basis data wenten 655 saking 1479, punika standar antuk pasangan utawi kulawarga alit.",
        "Ring basis data wenten 1.333 villa miwah 146 apartemen. Villa ring Bali ampir setata dados griya sareng kolam miwah halaman pribadi sané ring segmen anggaran taler, dados antuk biaya sane sami sareng apartemen ring kota ageng, ring genah puniki sane kaséwa malah griya."
      ]
    },
    {
      "heading": "Cara nyewa papan tinggal miwah indik sane patut kauningin",
      "paragraphs": [
        "Pilihan sane becik biasane nenten tedun ring platform langkung saking sababaraha dina, dados katalog puniki wantah nunasang iklan sane anyar — tarif lawas malah nyasarin. Mriksa papan tinggal saking tebih prasida ngalanturang video, nanging nandatangan kontrak beciknyane sasampun kunjungan pribadi utawi ngalanturang wakil sane kapracayan."
      ],
      "bullets": [
        "Sane kalebet ring tarif: beberes, perawatan kolam miwah taman, internet — prasida taler kauningin pisah, nenten wenten standar tunggal.",
        "Listrik ampir setata kabayar manut meteran ring jaba tarif — ring villa sareng AC punika dados jumlah sane kerasa.",
        "Deposit, syarat pengembalianné miwah tata cara ngentegang kontrak — becik kacatet sacara tulis.",
        "Sira pamilikne miwah nenten wenten haknyane nyewayang: yening villa ring leasehold, masa sewa nenten prasida nglangkungi masa hak pamiliknyane.",
        "Saking April 2025 berlaku aturan pencatatan penyewa (APOA) — pamilik wajib ngedaftarin penyewa.",
        "Musiman: ring Desember–Maret miwah Juli–Agustus, papan kosong langkung setata alit, miwah tarif langkung tegeh — becik rundingan saking dini."
      ]
    },
    {
      "heading": "Sewa dados cara milih wilayah sadurung meli",
      "paragraphs": [
        "Skenario sane paling praktis antuk indik sane nimbang meli: nyewa sababaraha sasih ring 2–3 wilayah tur ngraosang ring dija sane saestu nyaman antuk rauh nginep. Canggu miwah Ubud raosné pateh pisan béda, miwah saking foto bédané puniki asiki nenten kabaca.",
        "Tarif sewa taler nunasang sisi investasi: wilayah sane mahal antuk kaséwa — punika wilayah sane prasida wenten pamargin antuk villa ragane ring mangkin. Median saking basis data puniki prasida kabandingang langsung sareng rega pamesuan ring katalog."
      ]
    }
  ],
  "priceTable": {
    "caption": "Biaya sewa ring Bali manut jumlah kamar turu",
    "columns": [
      "Kamar turu",
      "Tawaran",
      "Tarif tipikal",
      "Median"
    ],
    "rows": [
      [
        "1 kamar turu",
        "302",
        "$385 – $2.113/sasih",
        "$960/sasih"
      ],
      [
        "2 kamar turu",
        "655",
        "$780 – $3.363/sasih",
        "$2.000/sasih"
      ],
      [
        "3 kamar turu",
        "377",
        "$1.042 – $5.272/sasih",
        "$2.880/sasih"
      ],
      [
        "4 kamar turu",
        "106",
        "$2.966 – $11.800/sasih",
        "$5.670/sasih"
      ]
    ],
    "note": "Rentang punika persentil ka-10 miwah ka-90 saking 1479 iklan sane regane leres. Data kaanyarin sareng basis data sewa."
  },
  "faqExtra": [
    {
      "q": "Pira regane nyewa papan tinggal ring Bali sasih?",
      "a": "Median ring basis data — $2.138 sasih, nanging rentangné jembar: pilihan 1 kamar turu ngawit kira-kira saking $400, villa 2 kamar turu sareng kolam ring Canggu nginehang kirang langkung $2.000, miwah griya 4 kamar turu ring wilayah premium ngawit saking $5.000. Ring Ubud, antuk biaya sane sami, ragane prasida rauh ruang sane langkung lega timbang ring Berawa."
    },
    {
      "q": "Masa sewa sane pinaka nguntungang punika pira?",
      "a": "Sane langkung lintang masa kontrakné, langkung asor tarifné. Sewa bulanan langkung mirah pisan timbang harian, miwah kontrak taunan sareng pembayaran di muka punika pilihan sane paling nguntungang ring pasar: pamilik lumrahnyane maring potongan sane cukup ageng. Kompromi sane masuk akal antuk rauh kapertama punika 3–6 sasih."
    },
    {
      "q": "Ape sane kalebet ring biaya sewa?",
      "a": "Lumrahnyane perawatan kolam miwah taman, asering taler internet miwah beberes. Listrik ampir setata kabayar pisah manut meteran — ring villa sareng AC miwah kolam punika $100–250 sasih. Toya miwah pangangkutan sampah becik kauningin manut objekné: nenten wenten standar tunggal."
    },
    {
      "q": "Deposit sane kabutuhin pira?",
      "a": "Biasane pembayaran 1–2 sasih. Deposit kabalikang duk medal sesampun kakirangin kerusakan miwah tagihan sane durung kabayar, dados syarat pengembalian miwah kaadaan griya duk mlebet becik kacatet tulis sareng foto."
    },
    {
      "q": "Napi prasida nyewa papan tinggal ring Bali saking tebih?",
      "a": "Inggih, punika sampun lumrah kalaksanayang: viewing ngalanturang video, kontrak miwah pembayaran ngalanturang transfer. Risikonyane, foto miwah kaadaan nyata prasida nenten sami, dados becik nyiapang minggu-minggu awal antuk sewa harian tur mriksa langsung, utawi nganggen wakil sane kapracayan ring lokasi."
    },
    {
      "q": "Ape bédané nyewa villa miwah apartemen?",
      "a": "Villa punika griya nyiri sareng kolam miwah halaman pribadi, miwah ring Bali punika format sane masif: ring basis data wenten 1.333 villa ngalawan 146 apartemen. Apartemen langkung irit ring perawatan miwah lumrahnyane maring infrastruktur kompleks, nanging privasi miwah lega arep langkung alit."
    }
  ]
}

export default copy
