// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/rental/ru.ts (German).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Was kostet es, Wohnraum auf Bali zu mieten",
      "paragraphs": [
        "In der Datenbank gibt es 1485 Angebote zur Monatsmiete. Die Medianmiete auf der Insel liegt bei $2.138 pro Monat, und acht von zehn Optionen liegen im Bereich von $620 bis $5.200. Die große Spanne ist kein Zufall: „Wohnraum auf Bali“ bedeutet sowohl ein Studio in Ubud für $400 als auch eine Villa mit Pool in Berawa für $8.000.",
        "Der wichtigste Preisfaktor ist die Anzahl der Schlafzimmer, der zweite die Lage, der dritte die Mietdauer. Monatsmiete ist fast immer günstiger als Tagesmiete: Ein Jahresvertrag für dieselbe Villa ist zwei- bis dreimal vorteilhafter als dieselbe Immobilie nachts in der Hochsaison."
      ]
    },
    {
      "heading": "Monatsmiete oder Tagesmiete",
      "paragraphs": [
        "Tagesmiete ist für die ersten Wochen praktisch, während Sie sich die Gegenden ansehen, aber zum Wohnen ist sie teuer. Ein Monatsvertrag über 6 bis 12 Monate bietet einen besseren Preis, ein Jahresvertrag den bestmöglichen: Eigentümer auf Bali verlangen traditionell die Zahlung für ein Jahr im Voraus und senken dafür den Preis spürbar.",
        "Marktpraxis: Die Kaution entspricht in der Regel einer bis zwei Monatsmieten, Nebenkosten (Strom, Wasser, Internet) sind meist nicht in der Miete enthalten, die Pflege von Pool und Garten dagegen schon. Strom in einer Villa mit Klimaanlagen und Pool erhöht das Budget um $100–250 pro Monat."
      ]
    },
    {
      "heading": "Wo man auf Bali Wohnraum mietet: Gegenden und Mietpreise",
      "paragraphs": [
        "Die Medianmieten in unserer Datenbank unterscheiden sich je nach Gegend um mehr als das Doppelte:"
      ],
      "bullets": [
        "Ubud — $1.300 pro Monat, 250 Angebote. Die günstigste der beliebten Gegenden: Dschungel, Reisterrassen, Yoga und Coworking, 30–40 Minuten bis zum Ozean.",
        "Nusa Dua — $1.433 und Bukit — $1.625. Ruhiger Süden, Hotelinfrastruktur, gute Strände, weniger Trubel und Staus als in Canggu.",
        "Canggu — $2.113, 253 Angebote. Die größte Auswahl und das dichteste Leben: Surfen, Cafés, Coworking. Hier ist auch der Wettbewerb um gute Häuser am höchsten.",
        "Uluwatu — $2.442 und Seminyak — $2.380. Einerseits Villen mit Aussicht auf den Klippen, andererseits urbanes Wohnen mit Restaurants.",
        "Berawa — $2.600, Umalas — $2.750, Pererenan — $2.822. Der Premium-Teil von Canggu: neue Villen, ruhiger als im Zentrum, aber teurer.",
        "Batu Bolong — $3.100, die teuerste Gegend in der Auswahl. Das Herz von Canggu in fußläufiger Nähe zum Ozean."
      ]
    },
    {
      "heading": "Was sich mit Ihrem Budget realistisch mieten lässt",
      "paragraphs": [
        "Orientierung nach Schlafzimmern: Villen und Apartments mit 1 Schlafzimmer — Median $960 pro Monat (das untere Zehntel des Marktes beginnt bei $385), mit 2 Schlafzimmern — $2.000, mit 3 Schlafzimmern — $2.880, mit 4 Schlafzimmern — $5.670. Gerade 2-Schlafzimmer-Objekte prägen den Markt: In der Datenbank sind es 655 von 1479, das ist der Standard für Paare oder kleine Familien.",
        "In der Datenbank sind 1.333 Villen und 146 Apartments. Eine Villa auf Bali bedeutet fast immer einen eigenen Pool und Hof, selbst im Budgetsegment, deshalb mietet man hier für das Geld einer Stadtwohnung oft ein Haus."
      ]
    },
    {
      "heading": "Wie man Wohnraum mietet und worauf man achten sollte",
      "paragraphs": [
        "Gute Angebote bleiben auf Plattformen nicht länger als ein paar Tage online, deshalb zeigt der Katalog nur aktuelle Inserate — veraltete Preise führen nur in die Irre. Eine Besichtigung aus der Ferne ist per Video möglich, den Vertrag unterschreibt man aber besser nach einem persönlichen Besuch oder über eine Vertrauensperson."
      ],
      "bullets": [
        "Was in der Miete enthalten ist: Reinigung, Pool- und Gartenpflege, Internet — separat nachfragen, einen einheitlichen Standard gibt es nicht.",
        "Strom wird fast immer nach Zähler zusätzlich zur Miete berechnet — in einer Villa mit Klimaanlagen ist das ein spürbarer Betrag.",
        "Kaution, Bedingungen für die Rückzahlung und Regeln zur Vertragsauflösung sollten schriftlich festgehalten werden.",
        "Wer ist der Eigentümer und hat er das Recht zu vermieten: Bei einer Villa im leasehold kann die Mietdauer nicht länger sein als die Laufzeit der Rechte des Eigentümers selbst.",
        "Seit April 2025 gelten Regeln zur Registrierung von Mietern (APOA) — der Eigentümer muss den Bewohner anmelden.",
        "Saisonalität: Von Dezember bis März und von Juli bis August gibt es weniger freie Objekte und höhere Preise — verhandeln Sie frühzeitig."
      ]
    },
    {
      "heading": "Miete als Weg, die richtige Gegend für den Kauf zu wählen",
      "paragraphs": [
        "Das praktischste Szenario für alle, die einen Kauf prüfen: für mehrere Monate in zwei bis drei Gegenden mieten und verstehen, wo es sich tatsächlich angenehm lebt. Canggu und Ubud fühlen sich völlig unterschiedlich an, und auf Fotos ist dieser Unterschied nicht erkennbar.",
        "Die Mietpreise zeigen zugleich die Investmentseite: Eine Gegend, in der das Mieten teuer ist, ist auch eine Gegend, in der Nachfrage nach Ihrer künftigen Villa bestehen wird. Die Medianwerte aus dieser Datenbank lassen sich direkt mit den Kaufpreisen im Katalog vergleichen."
      ]
    }
  ],
  "priceTable": {
    "caption": "Mietpreise auf Bali nach Anzahl der Schlafzimmer",
    "columns": [
      "Schlafzimmer",
      "Angebote",
      "Typische Miete",
      "Median"
    ],
    "rows": [
      [
        "1 Schlafzimmer",
        "302",
        "$385 – 2.113/Monat",
        "$960/Monat"
      ],
      [
        "2 Schlafzimmer",
        "655",
        "$780 – 3.363/Monat",
        "$2.000/Monat"
      ],
      [
        "3 Schlafzimmer",
        "377",
        "$1.042 – 5.272/Monat",
        "$2.880/Monat"
      ],
      [
        "4 Schlafzimmer",
        "106",
        "$2.966 – 11.800/Monat",
        "$5.670/Monat"
      ]
    ],
    "note": "Die Spanne zeigt den 10. und 90. Perzentilwert für 1479 Anzeigen mit korrekt angegebenem Preis. Die Daten werden zusammen mit der Mietdatenbank aktualisiert."
  },
  "faqExtra": [
    {
      "q": "Was kostet es, auf Bali Wohnraum für einen Monat zu mieten?",
      "a": "Der Median in der Datenbank liegt bei $2.138 pro Monat, die Spanne ist jedoch groß: Optionen mit 1 Schlafzimmer beginnen bei etwa $400, eine Villa mit 2 Schlafzimmern und Pool in Canggu kostet rund $2.000, und ein Haus mit 4 Schlafzimmern in einer Premium-Gegend beginnt bei $5.000. In Ubud bekommen Sie für dasselbe Geld deutlich mehr Fläche als in Berawa."
    },
    {
      "q": "Für welche Laufzeit lohnt sich die Miete am meisten?",
      "a": "Je länger der Vertrag, desto niedriger die Miete. Monatsmiete ist um ein Vielfaches günstiger als Tagesmiete, und ein Jahresvertrag mit Vorauszahlung ist die attraktivste Option am Markt: Eigentümer gewähren dafür traditionell einen deutlichen Nachlass. Ein vernünftiger Kompromiss für den ersten Aufenthalt sind 3–6 Monate."
    },
    {
      "q": "Was ist in der Miete enthalten?",
      "a": "Üblicherweise Pool- und Gartenpflege, oft auch Internet und Reinigung. Strom wird fast immer separat nach Zähler bezahlt — in einer Villa mit Klimaanlagen und Pool sind das $100–250 pro Monat. Wasser und Müllabfuhr bitte separat klären: Einen einheitlichen Standard gibt es nicht."
    },
    {
      "q": "Welche Kaution ist üblich?",
      "a": "In der Regel die Miete für ein bis zwei Monate. Die Kaution wird beim Auszug abzüglich von Schäden und offenen Rechnungen zurückerstattet, deshalb sollten Rückgabebedingungen und der Zustand des Hauses beim Einzug schriftlich und mit Fotos festgehalten werden."
    },
    {
      "q": "Kann man auf Bali Wohnraum aus der Ferne mieten?",
      "a": "Ja, das ist gängige Praxis: Besichtigung per Video, Vertrag und Zahlung per Überweisung. Das Risiko besteht darin, dass Fotos und Realität voneinander abweichen, deshalb sollte man entweder für die ersten Wochen Tagesmiete einplanen und vor Ort besichtigen oder eine Vertrauensperson vor Ort einschalten."
    },
    {
      "q": "Worin unterscheidet sich die Miete einer Villa von einem Apartment?",
      "a": "Eine Villa ist ein freistehendes Haus mit eigenem Pool und Hof, und auf Bali ist das ein Massenformat: In der Datenbank stehen 1.333 Villen gegenüber 146 Apartments. Apartments sind im Unterhalt günstiger und bieten meist die Infrastruktur einer Anlage, dafür sind Privatsphäre und Fläche geringer."
    }
  ]
}

export default copy
