// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/rental/ru.ts (English).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "How much it costs to rent property in Bali",
      "paragraphs": [
        "The database contains 1485 monthly rental listings. The median asking rate across the island is $2,138 per month, and eight out of ten listings fall in the $620 to $5,200 range. The spread is wide for a reason: “property in Bali” includes both a studio in Ubud for $400 and a pool villa in Berawa for $8,000.",
        "The main pricing factor is the number of bedrooms, the second is the area, and the third is the lease term. Monthly rent is almost always cheaper than daily rent: a yearly contract for the same villa is two to three times better value than renting it by the night in high season."
      ]
    },
    {
      "heading": "Monthly or daily rent",
      "paragraphs": [
        "Daily rent works for the first few weeks while you explore areas, but it is expensive for living. A monthly contract for 6 to 12 months gives a better rate, and a yearly contract gives the best rate available: in Bali, owners traditionally ask for a year paid upfront and reduce the price noticeably in return.",
        "Standard market practice: the deposit is usually equal to one or two months of rent, utilities (electricity, water, internet) are usually not included, while pool and garden maintenance usually are. Electricity for a villa with air conditioning and a pool adds $100–250 per month to the budget."
      ]
    },
    {
      "heading": "Where to rent in Bali: areas and rates",
      "paragraphs": [
        "Median asking rates in our database differ by more than two times between areas:"
      ],
      "bullets": [
        "Ubud — $1,300 per month, 250 listings. The most affordable of the popular areas: jungle, rice terraces, yoga, and coworking spaces, 30–40 minutes to the ocean.",
        "Nusa Dua — $1,433 and Bukit — $1,625. A quiet south, hotel infrastructure, good beaches, less bustle and traffic than in Canggu.",
        "Canggu — $2,113, 253 listings. The widest choice and the busiest lifestyle: surf, cafés, coworking. This is also where competition for good houses is highest.",
        "Uluwatu — $2,442 and Seminyak — $2,380. Cliffside view villas in one case, and a more urban format with restaurants in the other.",
        "Berawa — $2,600, Umalas — $2,750, Pererenan — $2,822. The premium side of Canggu: newer villas, quieter than the center, but more expensive.",
        "Batu Bolong — $3,100, the most expensive area in the sample. The heart of Canggu within walking distance of the ocean."
      ]
    },
    {
      "heading": "What you can realistically rent on your budget",
      "paragraphs": [
        "A bedroom-based guide: 1-bedroom villas and apartments have a median of $960 per month (the bottom tenth of the market starts from $385), 2-bedroom units — $2,000, 3-bedroom units — $2,880, 4-bedroom units — $5,670. The market is driven by 2-bedroom homes: there are 655 of them in the database out of 1479, which is the standard setup for a couple or a small family.",
        "The database includes 1 333 villas and 146 apartments. A villa in Bali almost always means a private pool and yard even in the budget segment, so for the same money as an apartment in a major city, here you rent a house."
      ]
    },
    {
      "heading": "How to rent and what to check",
      "paragraphs": [
        "Good listings do not stay on platforms for more than a few days, so the catalogue shows only fresh listings — outdated rates only mislead. You can view property remotely by video, but it is better to sign a contract after a personal visit or through a trusted representative."
      ],
      "bullets": [
        "What is included in the rent: cleaning, pool and garden maintenance, internet — check separately, there is no single standard.",
        "Electricity is almost always paid by meter on top of the rent — in a villa with air conditioning, this is a noticeable amount.",
        "The deposit, refund terms, and termination procedure should be recorded in writing.",
        "Who the owner is and whether they have the right to rent it out: for a leasehold villa, the lease term cannot exceed the term of the owner’s own rights.",
        "From April 2025, tenant registration rules (APOA) apply — the owner must register the tenant.",
        "Seasonality: in December–March and July–August, there is less available housing and rates are higher — negotiate in advance."
      ]
    },
    {
      "heading": "Renting as a way to choose an area before buying",
      "paragraphs": [
        "The most practical scenario for anyone considering a purchase is to rent for a few months in two or three areas and understand where you are actually comfortable living. Canggu and Ubud feel completely different, and you cannot see that difference from photos.",
        "Rental rates also show the investment side: an area that is expensive to rent in is an area where your future villa will be in demand. The medians from this database can be compared directly with purchase prices in the catalogue."
      ]
    }
  ],
  "priceTable": {
    "caption": "Rental prices in Bali by number of bedrooms",
    "columns": [
      "Bedrooms",
      "Listings",
      "Typical rate",
      "Median"
    ],
    "rows": [
      [
        "1 bedroom",
        "302",
        "$385–2,113/month",
        "$960/month"
      ],
      [
        "2 bedrooms",
        "655",
        "$780–3,363/month",
        "$2,000/month"
      ],
      [
        "3 bedrooms",
        "377",
        "$1,042–5,272/month",
        "$2,880/month"
      ],
      [
        "4 bedrooms",
        "106",
        "$2,966–11,800/month",
        "$5,670/month"
      ]
    ],
    "note": "The range is the 10th and 90th percentiles across 1479 listings with a valid price. Data is updated together with the rental database."
  },
  "faqExtra": [
    {
      "q": "How much does it cost to rent property in Bali for a month?",
      "a": "The median across the database is $2,138 per month, but the spread is wide: 1-bedroom options start from around $400, a 2-bedroom pool villa in Canggu will cost about $2,000, and a 4-bedroom house in a premium area starts from $5,000. In Ubud, the same budget gets you noticeably more space than in Berawa."
    },
    {
      "q": "What rental term gives the best value?",
      "a": "The longer the contract, the lower the rate. Monthly rent is several times cheaper than daily rent, and a yearly contract paid upfront is the best-value option on the market: owners traditionally give a substantial discount for that. A reasonable compromise for a first stay is 3–6 months."
    },
    {
      "q": "What is included in the rental price?",
      "a": "Usually pool and garden maintenance, often internet and cleaning. Electricity is almost always paid separately by meter — for a villa with air conditioning and a pool, that is $100–250 per month. Ask separately about water and garbage collection: there is no single standard."
    },
    {
      "q": "What deposit is required?",
      "a": "Usually one or two months of rent. The deposit is returned at move-out minus damage and unpaid bills, so it is worth recording the refund terms and the condition of the house at check-in in writing and with photos."
    },
    {
      "q": "Can you rent property in Bali remotely?",
      "a": "Yes, this is common: video viewing, contract, and payment by transfer. The risk is that photos and reality may differ, so either allow for the first weeks in daily accommodation and view in person, or use a trusted representative on the ground."
    },
    {
      "q": "How is renting a villa different from renting an apartment?",
      "a": "A villa is a detached house with its own pool and yard, and in Bali this is the mainstream format: the database has 1 333 villas versus 146 apartments. Apartments are cheaper to maintain and usually come with complex amenities, but they offer less privacy and space."
    }
  ]
}

export default copy
