// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/rental/ru.ts (French).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Combien coûte une location à Bali",
      "paragraphs": [
        "La base comprend 1485 offres de location au mois. Le loyer médian sur l’île est de 2 138 $ par mois, et huit biens sur dix se situent dans une fourchette de 620 à 5 200 $. Cet écart n’a rien d’inhabituel : « logement à Bali » peut désigner aussi bien un studio à Ubud à 400 $ qu’une villa avec piscine à Berawa à 8 000 $.",
        "Le principal facteur de prix est le nombre de chambres, le deuxième est le quartier, le troisième la durée. La location au mois est presque toujours moins chère que la location à la nuitée : un contrat annuel pour la même villa revient deux à trois fois plus avantageux que la même maison louée à la nuit en haute saison."
      ]
    },
    {
      "heading": "Location au mois ou à la nuitée",
      "paragraphs": [
        "La location à la nuitée est pratique pour les premières semaines, le temps de découvrir les quartiers, mais elle coûte cher pour y vivre. Un contrat mensuel de 6 à 12 mois donne un meilleur tarif, et un contrat annuel le meilleur possible : à Bali, les propriétaires demandent traditionnellement un paiement d’un an d’avance et baissent nettement le prix en échange.",
        "En pratique sur le marché : le dépôt de garantie correspond généralement à un à deux mois de loyer, les charges (électricité, eau, internet) sont le plus souvent exclues, tandis que l’entretien de la piscine et du jardin est généralement inclus. L’électricité d’une villa avec climatisation et piscine ajoute 100–250 $ par mois au budget."
      ]
    },
    {
      "heading": "Où louer à Bali : quartiers et niveaux de loyer",
      "paragraphs": [
        "Les loyers médians de notre base varient de plus du simple au double selon les quartiers :"
      ],
      "bullets": [
        "Ubud — 1 300 $ par mois, 250 offres. Le plus abordable des secteurs recherchés : jungle, rizières, yoga et coworkings, à 30–40 minutes de l’océan.",
        "Nusa Dua — 1 433 $ et Bukit — 1 625 $. Un sud plus calme, avec infrastructure hôtelière, bonnes plages, moins d’agitation et d’embouteillages qu’à Canggu.",
        "Canggu — 2 113 $, 253 offres. Le plus grand choix et la vie la plus dense : surf, cafés, coworkings. C’est aussi là que la concurrence est la plus forte pour les bonnes maisons.",
        "Uluwatu — 2 442 $ et Seminyak — 2 380 $. Respectivement des villas avec vue sur les falaises et un format plus urbain avec restaurants.",
        "Berawa — 2 600 $, Umalas — 2 750 $, Pererenan — 2 822 $. La partie premium de Canggu : villas récentes, plus calme que le centre, mais plus cher.",
        "Batu Bolong — 3 100 $, le quartier le plus cher de l’échantillon. Le cœur de Canggu à distance de marche de l’océan."
      ]
    },
    {
      "heading": "Ce qu’on peut réellement louer selon votre budget",
      "paragraphs": [
        "Repère par nombre de chambres : villas et appartements d’1 chambre — médiane de 960 $ par mois (les 10 % les moins chers du marché commencent à 385 $), 2 chambres — 2 000 $, 3 chambres — 2 880 $, 4 chambres — 5 670 $. Ce sont les biens de 2 chambres qui structurent le marché : 655 sur 1479 dans la base, un format standard pour un couple ou une petite famille.",
        "La base comprend 1 333 villas et 146 appartements. À Bali, une villa signifie presque toujours piscine privée et cour, même dans le segment économique ; pour le prix d’un appartement dans une grande ville, on loue ici une maison."
      ]
    },
    {
      "heading": "Comment louer et quels points vérifier",
      "paragraphs": [
        "Les bons biens ne restent pas en ligne plus de quelques jours, c’est pourquoi le catalogue n’affiche que des annonces récentes — les anciens prix faussent la lecture du marché. Il est possible de visiter à distance par vidéo, mais il vaut mieux signer le contrat après une visite sur place ou via une personne de confiance."
      ],
      "bullets": [
        "Ce qui est inclus dans le loyer : ménage, entretien de la piscine et du jardin, internet — à vérifier au cas par cas, il n’existe pas de standard unique.",
        "L’électricité est presque toujours facturée au compteur en plus du loyer — dans une villa avec climatisation, cela représente une somme sensible.",
        "Le dépôt de garantie, ses conditions de restitution et les modalités de résiliation doivent être formalisés par écrit.",
        "Qui est le propriétaire et a-t-il le droit de louer : pour une villa en leasehold, la durée de location ne peut pas dépasser la durée des droits du propriétaire lui-même.",
        "Depuis avril 2025, les règles d’enregistrement des locataires (APOA) s’appliquent — le propriétaire doit enregistrer l’occupant.",
        "Saisonnalité : de décembre à mars et de juillet à août, il y a moins de logements disponibles et les loyers sont plus élevés — mieux vaut s’y prendre à l’avance."
      ]
    },
    {
      "heading": "Louer pour choisir un quartier avant d’acheter",
      "paragraphs": [
        "Le scénario le plus pratique pour ceux qui envisagent un achat consiste à louer quelques mois dans deux ou trois quartiers afin de comprendre où il est réellement confortable de vivre. Canggu et Ubud offrent des cadres de vie très différents, et cette différence ne se lit pas sur des photos.",
        "Les loyers donnent aussi un indicateur de l’aspect investissement : un quartier où il est cher de louer est un quartier où votre future villa aura de la demande. Les médianes de cette base peuvent être comparées directement aux prix d’achat du catalogue."
      ]
    }
  ],
  "priceTable": {
    "caption": "Coût de location à Bali selon le nombre de chambres",
    "columns": [
      "Chambres",
      "Offres",
      "Fourchette typique",
      "Médiane"
    ],
    "rows": [
      [
        "1 chambre",
        "302",
        "385 – 2 113 $/mois",
        "960 $/mois"
      ],
      [
        "2 chambres",
        "655",
        "780 – 3 363 $/mois",
        "2 000 $/mois"
      ],
      [
        "3 chambres",
        "377",
        "1 042 – 5 272 $/mois",
        "2 880 $/mois"
      ],
      [
        "4 chambres",
        "106",
        "2 966 – 11 800 $/mois",
        "5 670 $/mois"
      ]
    ],
    "note": "La fourchette correspond aux 10e et 90e percentiles sur 1479 annonces avec un prix valide. Les données sont mises à jour avec la base locative."
  },
  "faqExtra": [
    {
      "q": "Combien coûte une location à Bali pour un mois ?",
      "a": "La médiane de la base est de 2 138 $ par mois, mais l’écart est important : les biens d’1 chambre commencent autour de 400 $, une villa de 2 chambres avec piscine à Canggu coûte environ 2 000 $, et une maison de 4 chambres dans un quartier premium démarre à partir de 5 000 $. À Ubud, pour le même budget, vous obtiendrez sensiblement plus de surface qu’à Berawa."
    },
    {
      "q": "Quelle durée de location est la plus avantageuse ?",
      "a": "Plus le contrat est long, plus le tarif baisse. La location au mois est nettement moins chère que la nuitée, et un contrat annuel payé d’avance est l’option la plus avantageuse du marché : les propriétaires accordent traditionnellement une remise substantielle dans ce cas. Un compromis raisonnable pour une première arrivée est de 3–6 mois."
    },
    {
      "q": "Qu’est-ce qui est inclus dans le loyer ?",
      "a": "En général, l’entretien de la piscine et du jardin, souvent internet et le ménage. L’électricité est presque toujours facturée séparément au compteur — dans une villa avec climatisation et piscine, cela représente 100–250 $ par mois. Pour l’eau et l’enlèvement des déchets, il faut vérifier : il n’existe pas de standard unique."
    },
    {
      "q": "Quel dépôt de garantie faut-il prévoir ?",
      "a": "En règle générale, l’équivalent d’un à deux mois de loyer. Le dépôt est restitué au départ, déduction faite des dommages et des factures impayées ; il est donc préférable de fixer par écrit les conditions de restitution et l’état du logement à l’entrée, avec photos."
    },
    {
      "q": "Peut-on louer un logement à Bali à distance ?",
      "a": "Oui, c’est une pratique courante : visite vidéo, contrat et paiement par virement. Le risque est que les photos et la réalité diffèrent ; soit vous prévoyez les premières semaines en location à la nuitée pour visiter sur place, soit vous mandatez une personne de confiance sur place."
    },
    {
      "q": "Quelle est la différence entre louer une villa et un appartement ?",
      "a": "Une villa est une maison indépendante avec piscine privée et cour, et à Bali c’est le format dominant : 1 333 villas dans la base contre 146 appartements. Les appartements coûtent moins cher à entretenir et donnent généralement accès aux équipements de la résidence, mais offrent moins d’intimité et moins d’espace."
    }
  ]
}

export default copy
