// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/rental/ru.ts (Indonesian).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Berapa biaya sewa hunian di Bali",
      "paragraphs": [
        "Di database kami ada 1485 listing sewa bulanan. Tarif median di seluruh pulau adalah $2.138 per bulan, dan delapan dari sepuluh opsi berada di kisaran $620 hingga $5.200. Selisihnya besar karena “hunian di Bali” mencakup studio di Ubud seharga $400 dan vila dengan kolam renang di Berawa seharga $8.000.",
        "Faktor utama harga adalah jumlah kamar tidur, faktor kedua adalah area, dan faktor ketiga adalah durasi sewa. Sewa bulanan hampir selalu lebih murah daripada harian: kontrak tahunan untuk vila yang sama biasanya 2–3 kali lebih menguntungkan dibanding disewa per malam saat high season."
      ]
    },
    {
      "heading": "Sewa bulanan atau harian",
      "paragraphs": [
        "Sewa harian praktis untuk minggu-minggu pertama saat Anda masih melihat area, tetapi biayanya mahal untuk ditinggali. Kontrak bulanan 6 hingga 12 bulan memberi tarif yang lebih baik, dan kontrak tahunan memberi tarif terbaik: pemilik di Bali secara tradisional meminta pembayaran setahun di muka dan karena itu menurunkan harga cukup signifikan.",
        "Praktik pasar: deposit biasanya setara pembayaran 1–2 bulan, utilitas (listrik, air, internet) paling sering tidak termasuk dalam tarif, sedangkan perawatan kolam renang dan taman biasanya sudah termasuk. Listrik untuk vila dengan AC dan kolam renang menambah anggaran sekitar $100–250 per bulan."
      ]
    },
    {
      "heading": "Di mana menyewa hunian di Bali: area dan tarif",
      "paragraphs": [
        "Tarif median di database kami berbeda lebih dari dua kali lipat antar area:"
      ],
      "bullets": [
        "Ubud — $1.300 per bulan, 250 listing. Paling terjangkau di antara area populer: hutan, sawah terasering, yoga, dan coworking, ke laut 30–40 menit.",
        "Nusa Dua — $1.433 dan Bukit — $1.625. Selatan yang tenang, infrastruktur hotel, pantai yang bagus, lebih sedikit hiruk-pikuk dan macet dibanding Canggu.",
        "Canggu — $2.113, 253 listing. Pilihan paling banyak dan kehidupan paling padat: surfing, kafe, coworking. Di sini juga persaingan untuk rumah yang bagus paling tinggi.",
        "Uluwatu — $2.442 dan Seminyak — $2.380. Masing-masing menawarkan vila dengan view di atas tebing dan format area urban dengan restoran.",
        "Berawa — $2.600, Umalas — $2.750, Pererenan — $2.822. Bagian premium Canggu: vila baru, lebih tenang daripada pusat, tetapi lebih mahal.",
        "Batu Bolong — $3.100, area termahal dalam sampel. Jantung Canggu dalam jarak jalan kaki ke laut."
      ]
    },
    {
      "heading": "Hunian yang realistis untuk budget Anda",
      "paragraphs": [
        "Patokan berdasarkan kamar tidur: vila dan apartemen 1 kamar tidur — median $960 per bulan (10% terbawah pasar mulai dari $385), 2 kamar tidur — $2.000, 3 kamar tidur — $2.880, 4 kamar tidur — $5.670. Justru unit 2 kamar tidur yang membentuk pasar: ada 655 dari 1479 listing di database, ini standar untuk pasangan atau keluarga kecil.",
        "Di database ada 1 333 vila dan 146 apartemen. Vila di Bali hampir selalu berarti kolam renang dan halaman pribadi bahkan di segmen budget, jadi dengan uang yang setara harga apartemen di kota besar, di sini orang menyewa rumah."
      ]
    },
    {
      "heading": "Cara menyewa hunian dan hal yang perlu diperiksa",
      "paragraphs": [
        "Opsi yang bagus biasanya tidak bertahan di platform lebih dari beberapa hari, поэтому katalog menampilkan hanya listing terbaru — tarif lama hanya menyesatkan. Melihat properti dari jarak jauh bisa lewat video, tetapi menandatangani kontrak sebaiknya setelah kunjungan langsung atau melalui orang kepercayaan."
      ],
      "bullets": [
        "Apa yang termasuk dalam tarif: kebersihan, perawatan kolam renang dan taman, internet — konfirmasi satu per satu, tidak ada standar tunggal.",
        "Listrik hampir selalu dibayar berdasarkan meteran di luar tarif — untuk vila dengan AC jumlahnya terasa signifikan.",
        "Deposit, syarat pengembaliannya, dan prosedur penghentian kontrak — tetapkan secara tertulis.",
        "Siapa pemiliknya dan apakah ia berhak menyewakan: untuk vila leasehold, masa sewa tidak bisa melebihi masa hak yang dimiliki pemilik itu sendiri.",
        "Sejak April 2025 berlaku aturan pencatatan penyewa (APOA) — pemilik wajib mendaftarkan penghuni.",
        "Musiman: pada Desember–Maret dan Juli–Agustus, unit kosong lebih sedikit dan tarif lebih tinggi — negosiasikan lebih awal."
      ]
    },
    {
      "heading": "Sewa sebagai cara memilih area sebelum membeli",
      "paragraphs": [
        "Skenario paling praktis bagi yang sedang mempertimbangkan pembelian: sewa beberapa bulan di dua–tiga area lalu pahami di mana Anda benar-benar nyaman tinggal. Canggu dan Ubud terasa sangat berbeda, dan perbedaan itu tidak terbaca dari foto.",
        "Tarif sewa sekaligus menunjukkan sisi investasi: area yang mahal untuk disewa adalah area yang kemungkinan punya permintaan untuk vila Anda di masa depan. Median dari database ini bisa langsung dibandingkan dengan harga beli di katalog."
      ]
    }
  ],
  "priceTable": {
    "caption": "Biaya sewa di Bali berdasarkan jumlah kamar tidur",
    "columns": [
      "Kamar tidur",
      "Listing",
      "Tarif tipikal",
      "Median"
    ],
    "rows": [
      [
        "1 kamar tidur",
        "302",
        "$385 – $2.113/bulan",
        "$960/bulan"
      ],
      [
        "2 kamar tidur",
        "655",
        "$780 – $3.363/bulan",
        "$2.000/bulan"
      ],
      [
        "3 kamar tidur",
        "377",
        "$1.042 – $5.272/bulan",
        "$2.880/bulan"
      ],
      [
        "4 kamar tidur",
        "106",
        "$2.966 – $11.800/bulan",
        "$5.670/bulan"
      ]
    ],
    "note": "Rentang adalah persentil ke-10 dan ke-90 dari 1479 listing dengan harga yang valid. Data diperbarui bersama database sewa."
  },
  "faqExtra": [
    {
      "q": "Berapa biaya sewa hunian di Bali per bulan?",
      "a": "Median di database adalah $2.138 per bulan, tetapi rentangnya besar: opsi 1 kamar tidur mulai sekitar $400, vila 2 kamar tidur dengan kolam renang di Canggu sekitar $2.000, dan rumah 4 kamar tidur di area premium mulai dari $5.000. Di Ubud, dengan anggaran yang sama Anda akan mendapat luas bangunan yang jauh lebih besar dibanding di Berawa."
    },
    {
      "q": "Durasi sewa berapa yang paling menguntungkan?",
      "a": "Semakin panjang kontrak, semakin rendah tarifnya. Sewa bulanan jauh lebih murah daripada harian, dan kontrak tahunan dengan pembayaran di muka adalah opsi paling menguntungkan di pasar: pemilik secara tradisional memberi diskon besar untuk itu. Kompromi yang masuk akal untuk kedatangan pertama adalah 3–6 bulan."
    },
    {
      "q": "Apa saja yang termasuk dalam biaya sewa?",
      "a": "Biasanya perawatan kolam renang dan taman, sering juga internet dan kebersihan. Listrik hampir selalu dibayar terpisah berdasarkan meteran — untuk vila dengan AC dan kolam renang sekitar $100–250 per bulan. Air dan pengangkutan sampah perlu ditanyakan terpisah: tidak ada standar tunggal."
    },
    {
      "q": "Berapa deposit yang dibutuhkan?",
      "a": "Umumnya setara pembayaran 1–2 bulan. Deposit dikembalikan saat check-out setelah dikurangi kerusakan dan tagihan yang belum dibayar, jadi syarat pengembalian dan kondisi rumah saat check-in sebaiknya dicatat tertulis dan difoto."
    },
    {
      "q": "Apakah bisa menyewa hunian di Bali dari jarak jauh?",
      "a": "Ya, ini cukup umum dilakukan: viewing lewat video, kontrak dan pembayaran lewat transfer. Risikonya, foto dan kondisi nyata bisa berbeda, jadi sebaiknya siapkan minggu-minggu pertama untuk sewa harian sambil survei langsung, atau gunakan orang kepercayaan di lokasi."
    },
    {
      "q": "Apa perbedaan sewa vila dan apartemen?",
      "a": "Vila adalah rumah terpisah dengan kolam renang dan halaman pribadi, dan di Bali ini format yang umum: di database ada 1 333 vila dibanding 146 apartemen. Apartemen lebih murah dalam biaya operasional dan biasanya memberi fasilitas kompleks, tetapi privasi dan luasnya lebih terbatas."
    }
  ]
}

export default copy
