// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/rental/ru.ts (Dutch).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Wat kost het om woonruimte te huren op Bali",
      "paragraphs": [
        "In de database staan 1485 aanbiedingen voor maandelijkse huur. De mediane huurprijs op het eiland is $2.138 per maand, en acht van de tien opties vallen in de bandbreedte van $620 tot $5.200. Die grote spreiding is logisch: ‘woonruimte op Bali’ betekent zowel een studio in Ubud voor $400 als een villa met zwembad in Berawa voor $8.000.",
        "De belangrijkste prijsfactor is het aantal slaapkamers, daarna de wijk en vervolgens de huurtermijn. Per maand huren is vrijwel altijd goedkoper dan per dag: een jaarcontract voor dezelfde villa is twee tot drie keer voordeliger dan diezelfde villa per nacht in het hoogseizoen."
      ]
    },
    {
      "heading": "Per maand of per dag huren",
      "paragraphs": [
        "Daghuur is handig voor de eerste weken terwijl u verschillende wijken bekijkt, maar om er te wonen is het duur. Een maandcontract van 6 tot 12 maanden geeft een beter tarief, en een jaarcontract het best mogelijke tarief: eigenaren op Bali vragen traditioneel betaling voor een jaar vooruit en verlagen daarvoor de prijs merkbaar.",
        "Gangbare marktpraktijk: de borg is meestal gelijk aan de huur van één tot twee maanden, nutsvoorzieningen (elektriciteit, water, internet) zijn meestal niet inbegrepen, terwijl onderhoud van zwembad en tuin meestal wel inbegrepen is. Elektriciteit voor een villa met airco's en zwembad voegt $100–250 per maand toe aan het budget."
      ]
    },
    {
      "heading": "Waar woonruimte huren op Bali: wijken en huurprijzen",
      "paragraphs": [
        "De mediane huurprijzen in onze database verschillen per wijk met meer dan een factor twee:"
      ],
      "bullets": [
        "Ubud — $1.300 per maand, 250 aanbiedingen. De meest betaalbare van de populaire gebieden: jungle, rijstterrassen, yoga en coworkings, 30–40 minuten van de oceaan.",
        "Nusa Dua — $1.433 en Bukit — $1.625. Rustig zuiden, hotelinfrastructuur, goede stranden, minder drukte en verkeer dan in Canggu.",
        "Canggu — $2.113, 253 aanbiedingen. De grootste keuze en het drukste leven: surfen, cafés, coworkings. Hier is ook de sterkste concurrentie om goede woningen.",
        "Uluwatu — $2.442 en Seminyak — $2.380. Respectievelijk villa's met uitzicht op kliffen en een stedelijk woonformaat met restaurants.",
        "Berawa — $2.600, Umalas — $2.750, Pererenan — $2.822. Het premium deel van Canggu: nieuwe villa's, rustiger dan het centrum, maar duurder.",
        "Batu Bolong — $3.100, de duurste wijk in de selectie. Het hart van Canggu op loopafstand van de oceaan."
      ]
    },
    {
      "heading": "Wat u werkelijk kunt huren binnen uw budget",
      "paragraphs": [
        "Richtlijn per aantal slaapkamers: villa's en appartementen met 1 slaapkamer — mediaan $960 per maand (de onderste 10% van de markt begint vanaf $385), 2 slaapkamers — $2.000, 3 slaapkamers — $2.880, 4 slaapkamers — $5.670. Juist woningen met 2 slaapkamers bepalen de markt: daarvan staan er 655 van 1479 in de database, de standaard voor een stel of een klein gezin.",
        "In de database staan 1 333 villa's en 146 appartementen. Een villa op Bali betekent vrijwel altijd een privézwembad en eigen terrein, zelfs in het budgetsegment, waardoor men hier voor hetzelfde geld als een appartement in een grote stad een huis huurt."
      ]
    },
    {
      "heading": "Hoe u woonruimte huurt en waar u op moet letten",
      "paragraphs": [
        "Goede opties blijven meestal niet langer dan enkele dagen op platforms staan, daarom toont de catalogus alleen actuele advertenties — verouderde prijzen geven een verkeerd beeld. Op afstand bezichtigen kan via video, maar een contract tekent u het best na een persoonlijke bezichtiging of via een vertrouwenspersoon."
      ],
      "bullets": [
        "Wat in de huurprijs is inbegrepen: schoonmaak, onderhoud van zwembad en tuin, internet — altijd apart navragen, er is geen vaste standaard.",
        "Elektriciteit wordt vrijwel altijd op basis van meterstanden boven op de huurprijs betaald — in een villa met airco's is dat een merkbaar bedrag.",
        "Borg, voorwaarden voor terugbetaling en de regeling bij beëindiging van het contract — leg dit schriftelijk vast.",
        "Wie de eigenaar is en of hij het recht heeft om te verhuren: bij een villa in leasehold kan de huurtermijn niet langer zijn dan de looptijd van de rechten van de eigenaar zelf.",
        "Sinds april 2025 gelden regels voor registratie van huurders (APOA) — de eigenaar is verplicht de bewoner te registreren.",
        "Seizoensinvloed: in december–maart en juli–augustus is er minder vrije woonruimte en liggen de tarieven hoger — regel dit vooraf."
      ]
    },
    {
      "heading": "Huren als manier om een wijk voor aankoop te kiezen",
      "paragraphs": [
        "Het meest praktische scenario voor wie een aankoop overweegt: huur enkele maanden in twee of drie verschillende wijken en ontdek waar het echt prettig wonen is. Canggu en Ubud voelen totaal anders aan, en op foto's is dat verschil niet zichtbaar.",
        "Huurprijzen laten tegelijk ook de investeringskant zien: een wijk waar huren duur is, is een wijk waar vraag zal zijn naar uw toekomstige villa. De medianen uit deze database kunt u direct vergelijken met aankoopprijzen in de catalogus."
      ]
    }
  ],
  "priceTable": {
    "caption": "Huurprijzen op Bali per aantal slaapkamers",
    "columns": [
      "Slaapkamers",
      "Aanbiedingen",
      "Gebruikelijk tarief",
      "Mediaan"
    ],
    "rows": [
      [
        "1 slaapkamer",
        "302",
        "$385 – $2.113/maand",
        "$960/maand"
      ],
      [
        "2 slaapkamers",
        "655",
        "$780 – $3.363/maand",
        "$2.000/maand"
      ],
      [
        "3 slaapkamers",
        "377",
        "$1.042 – $5.272/maand",
        "$2.880/maand"
      ],
      [
        "4 slaapkamers",
        "106",
        "$2.966 – $11.800/maand",
        "$5.670/maand"
      ]
    ],
    "note": "De bandbreedte is het 10e en 90e percentiel op basis van 1479 advertenties met een correcte prijs. De gegevens worden samen met de huurdatabase bijgewerkt."
  },
  "faqExtra": [
    {
      "q": "Wat kost het om woonruimte op Bali voor een maand te huren?",
      "a": "De mediaan in de database is $2.138 per maand, maar de spreiding is groot: opties met 1 slaapkamer beginnen rond $400, een villa met 2 slaapkamers en zwembad in Canggu kost ongeveer $2.000, en een huis met 4 slaapkamers in een premium wijk begint vanaf $5.000. In Ubud krijgt u voor hetzelfde geld merkbaar meer woonoppervlak dan in Berawa."
    },
    {
      "q": "Voor welke termijn is huren het voordeligst?",
      "a": "Hoe langer het contract, hoe lager het tarief. Per maand huren is vele malen goedkoper dan per dag, en een jaarcontract met vooruitbetaling is de voordeligste optie op de markt: eigenaren geven daar traditioneel een aanzienlijke korting voor. Een redelijk compromis voor een eerste verblijf is 3–6 maanden."
    },
    {
      "q": "Wat is inbegrepen in de huurprijs?",
      "a": "Meestal onderhoud van zwembad en tuin, vaak ook internet en schoonmaak. Elektriciteit wordt vrijwel altijd apart op basis van meterstanden betaald — voor een villa met airco's en zwembad is dat $100–250 per maand. Vraag water en afvalafvoer altijd na: er is geen vaste standaard."
    },
    {
      "q": "Welke borg is gebruikelijk?",
      "a": "Meestal de huur van één tot twee maanden. De borg wordt bij vertrek terugbetaald minus schade en onbetaalde rekeningen, daarom is het verstandig de voorwaarden voor terugbetaling en de staat van de woning bij intrek schriftelijk en met foto's vast te leggen."
    },
    {
      "q": "Kan ik woonruimte op Bali op afstand huren?",
      "a": "Ja, dat gebeurt regelmatig: bezichtiging via video, contract en betaling per overboeking. Het risico is dat foto's en werkelijkheid uiteenlopen, dus reserveer ofwel de eerste weken voor daghuur en ga zelf kijken, of werk met een vertrouwenspersoon ter plaatse."
    },
    {
      "q": "Wat is het verschil tussen het huren van een villa en een appartement?",
      "a": "Een villa is een vrijstaand huis met privézwembad en eigen terrein, en op Bali is dat een massaal format: in de database staan 1 333 villa's tegenover 146 appartementen. Appartementen zijn goedkoper in onderhoud en bieden meestal complexvoorzieningen, maar hebben minder privacy en minder ruimte."
    }
  ]
}

export default copy
