// AUTO-GENERATED by scripts/translate-hub-seo.mjs — do not edit by hand.
// Source: lib/hub-seo/rental/ru.ts (Polish).
import type { HubLongCopy } from '../types'

const copy: HubLongCopy = {
  "sections": [
    {
      "heading": "Ile kosztuje wynajem mieszkania lub willi na Bali",
      "paragraphs": [
        "W bazie jest 1485 ofert wynajmu miesięcznego. Mediana stawki na wyspie to 2 138 $ miesięcznie, a osiem na dziesięć ofert mieści się w przedziale od 620 do 5 200 $. Tak duży rozrzut nie jest przypadkowy: „nieruchomość do wynajęcia na Bali” to zarówno studio w Ubud za 400 $, jak i willa z basenem w Berawa za 8 000 $.",
        "Głównym czynnikiem ceny jest liczba sypialni, drugim lokalizacja, trzecim długość najmu. Wynajem miesięczny prawie zawsze jest tańszy niż dobowy: roczny kontrakt na tę samą willę wypada dwa-trzy razy korzystniej niż najem za noc w wysokim sezonie."
      ]
    },
    {
      "heading": "Wynajem miesięczny czy dobowy",
      "paragraphs": [
        "Wynajem dobowy jest wygodny na pierwsze tygodnie, kiedy poznajecie dzielnice, ale do mieszkania na dłużej jest drogi. Kontrakt miesięczny na 6 do 12 miesięcy daje lepszą stawkę, a roczny — najlepszą z możliwych: właściciele na Bali tradycyjnie oczekują płatności za rok z góry i w zamian wyraźnie obniżają cenę.",
        "Praktyka rynkowa jest taka: kaucja zwykle odpowiada opłacie za jeden-dwa miesiące, media (prąd, woda, internet) najczęściej nie są wliczone w stawkę, a serwis basenu i ogrodu — tak. Prąd w willi z klimatyzacją i basenem zwiększa budżet o 100–250 $ miesięcznie."
      ]
    },
    {
      "heading": "Gdzie wynająć nieruchomość na Bali: lokalizacje i stawki",
      "paragraphs": [
        "Mediany stawek w naszej bazie różnią się między lokalizacjami ponad dwukrotnie:"
      ],
      "bullets": [
        "Ubud — 1 300 $ miesięcznie, 250 ofert. Najbardziej przystępna cenowo z popularnych lokalizacji: dżungla, tarasy ryżowe, joga i coworkingi, do oceanu 30–40 minut.",
        "Nusa Dua — 1 433 $ i Bukit — 1 625 $. Spokojne południe, infrastruktura hotelowa, dobre plaże, mniej zgiełku i korków niż w Canggu.",
        "Canggu — 2 113 $, 253 oferty. Największy wybór i najbardziej intensywne życie: surfing, kawiarnie, coworkingi. Tu też konkurencja o dobre domy jest najwyższa.",
        "Uluwatu — 2 442 $ i Seminyak — 2 380 $. Odpowiednio wille widokowe na klifach oraz miejski format z restauracjami.",
        "Berawa — 2 600 $, Umalas — 2 750 $, Pererenan — 2 822 $. Bardziej premium część Canggu: nowe wille, ciszej niż w centrum, ale drożej.",
        "Batu Bolong — 3 100 $, najdroższa lokalizacja w zestawieniu. Serce Canggu, w odległości spaceru od oceanu."
      ]
    },
    {
      "heading": "Co realnie wynajmiesz w swoim budżecie",
      "paragraphs": [
        "Punkt odniesienia według liczby sypialni: wille i apartamenty z 1 sypialnią — mediana 960 $ miesięcznie (dolne 10% rynku zaczyna się od 385 $), z 2 sypialniami — 2 000 $, z 3 sypialniami — 2 880 $, z 4 sypialniami — 5 670 $. To właśnie segment 2 sypialni tworzy rynek: w bazie jest ich 655 z 1479, to standard dla pary lub małej rodziny.",
        "W bazie jest 1 333 willi i 146 apartamentów. Willa na Bali to prawie zawsze prywatny basen i własne patio nawet w segmencie budżetowym, dlatego za kwotę porównywalną z mieszkaniem w dużym mieście tutaj wynajmuje się dom."
      ]
    },
    {
      "heading": "Jak wynająć nieruchomość i na co zwrócić uwagę",
      "paragraphs": [
        "Dobre oferty nie utrzymują się na portalach dłużej niż kilka dni, dlatego katalog pokazuje tylko świeże ogłoszenia — nieaktualne stawki tylko wprowadzają w błąd. Nieruchomość można oglądać zdalnie na wideo, ale umowę najlepiej podpisywać po osobistej wizycie albo przez zaufaną osobę na miejscu."
      ],
      "bullets": [
        "Co jest wliczone w stawkę: sprzątanie, serwis basenu i ogrodu, internet — trzeba to doprecyzować osobno, nie ma jednego standardu.",
        "Prąd prawie zawsze jest płatny według licznika ponad stawkę — w willi z klimatyzacją to odczuwalny koszt.",
        "Kaucję, warunki jej zwrotu i zasady rozwiązania umowy warto zapisać na piśmie.",
        "Kto jest właścicielem i czy ma prawo wynajmować: w przypadku willi w leasehold okres najmu nie może przekraczać okresu praw samego właściciela.",
        "Od kwietnia 2025 obowiązują zasady rejestracji najemców (APOA) — właściciel ma obowiązek zgłosić lokatora.",
        "Sezonowość: w grudniu–marcu oraz lipcu–sierpniu wolnych nieruchomości jest mniej, a stawki są wyższe — warto ustalać warunki z wyprzedzeniem."
      ]
    },
    {
      "heading": "Wynajem jako sposób na wybór lokalizacji pod zakup",
      "paragraphs": [
        "Najbardziej praktyczny scenariusz dla osób rozważających zakup: wynająć na kilka miesięcy w dwóch-trzech lokalizacjach i sprawdzić, gdzie naprawdę wygodnie się mieszka. Canggu i Ubud odczuwa się zupełnie inaczej, a ze zdjęć tej różnicy nie widać.",
        "Stawki najmu pokazują przy okazji stronę inwestycyjną: lokalizacja, w której drogo się wynajmuje, to lokalizacja, w której będzie popyt na waszą przyszłą willę. Mediany z tej bazy można bezpośrednio porównywać z cenami zakupu w katalogu."
      ]
    }
  ],
  "priceTable": {
    "caption": "Koszt wynajmu na Bali według liczby sypialni",
    "columns": [
      "Sypialnie",
      "Ofert",
      "Typowa stawka",
      "Mediana"
    ],
    "rows": [
      [
        "1 sypialnia",
        "302",
        "385 – 2 113 $/mies.",
        "960 $/mies."
      ],
      [
        "2 sypialnie",
        "655",
        "780 – 3 363 $/mies.",
        "2 000 $/mies."
      ],
      [
        "3 sypialnie",
        "377",
        "1 042 – 5 272 $/mies.",
        "2 880 $/mies."
      ],
      [
        "4 sypialnie",
        "106",
        "2 966 – 11 800 $/mies.",
        "5 670 $/mies."
      ]
    ],
    "note": "Przedział to 10. i 90. percentyl dla 1479 ogłoszeń z poprawnie podaną ceną. Dane są aktualizowane razem z bazą wynajmu."
  },
  "faqExtra": [
    {
      "q": "Ile kosztuje wynajem nieruchomości na Bali na miesiąc?",
      "a": "Mediana w bazie to 2 138 $ miesięcznie, ale rozrzut jest duży: warianty z 1 sypialnią zaczynają się mniej więcej od 400 $, willa z 2 sypialniami i basenem w Canggu kosztuje około 2 000 $, a dom z 4 sypialniami w lokalizacji premium — od 5 000 $. W Ubud za tę samą kwotę dostaniecie wyraźnie większy metraż niż w Berawa."
    },
    {
      "q": "Na jaki okres najbardziej opłaca się wynajmować?",
      "a": "Im dłuższy kontrakt, tym niższa stawka. Wynajem miesięczny jest wielokrotnie tańszy od dobowego, a roczny kontrakt z płatnością z góry to najkorzystniejszy wariant na rynku: właściciele tradycyjnie dają za to istotny rabat. Rozsądny kompromis przy pierwszym przyjeździe to 3–6 miesięcy."
    },
    {
      "q": "Co wchodzi w koszt wynajmu?",
      "a": "Zwykle serwis basenu i ogrodu, często internet i sprzątanie. Prąd prawie zawsze jest rozliczany osobno według licznika — w willi z klimatyzacją i basenem to 100–250 $ miesięcznie. Wodę i wywóz śmieci trzeba doprecyzować: nie ma jednego standardu."
    },
    {
      "q": "Jaka kaucja jest wymagana?",
      "a": "Z reguły równowartość opłaty za jeden-dwa miesiące. Kaucja jest zwracana przy wyjeździe po potrąceniu szkód i nieopłaconych rachunków, dlatego warunki zwrotu i stan domu przy wprowadzeniu warto utrwalić na piśmie i na zdjęciach."
    },
    {
      "q": "Czy można wynająć nieruchomość na Bali zdalnie?",
      "a": "Tak, to powszechna praktyka: oglądanie na wideo, umowa i płatność przelewem. Ryzyko polega na tym, że zdjęcia i rzeczywistość mogą się różnić, dlatego albo warto założyć pierwsze tygodnie na wynajem dobowy i oglądać na żywo, albo zaangażować zaufaną osobę na miejscu."
    },
    {
      "q": "Czym różni się wynajem willi od apartamentu?",
      "a": "Willa to osobny dom z prywatnym basenem i własnym patio, a na Bali to format masowy: w bazie jest 1 333 willi wobec 146 apartamentów. Apartamenty są tańsze w utrzymaniu i zwykle dają infrastrukturę kompleksu, ale oferują mniej prywatności i mniejszą powierzchnię."
    }
  ]
}

export default copy
