import type { InvestmentGuideCopy } from './types'
import { SRC } from './data'

export const de: InvestmentGuideCopy = {
  meta: {
    title: 'Immobilien auf Bali 2026 als Investment — Renditen aus eigenen Daten, Leasehold, Steuern | Balinsky',
    description: 'Leitfaden für ausländische Käufer: Mietrenditen berechnet aus 6.305 Mietvillen und 359 Verkaufspreisen, Leasehold oder PT PMA, Steuern, Zonierung und Genehmigungen — jede Zahl mit Quelle.',
    ogTitle: 'Bali-Immobilien 2026 — was die Daten zeigen',
    ogDescription: 'Renditen aus eigenen Daten, Leasehold oder PT PMA, Steuern, Zonierung und Genehmigungen. Jede Zahl mit Quelle.',
  },
  crumbHome: 'Startseite',
  crumb: 'Immobilien-Investment auf Bali',
  h1: 'In Immobilien auf Bali investieren — Leitfaden 2026',
  intro: 'Mietrenditen aus unseren eigenen Daten, Eigentumsstrukturen (Leasehold und PT PMA), Steuern für ausländische Eigentümer, Zonierung und Genehmigungen. Jede Zahl auf dieser Seite verweist auf ihre Quelle.',
  updated: 'Aktualisiert: September 2026',
  stats: {
    yield: 'Bruttorendite einer mittleren Villa mit 2 Schlafzimmern bei 65 % Auslastung',
    catalogue: 'Villen und Apartments im Katalog',
    permits: 'der Villen haben PBG oder SLF',
    rentals: 'Mietvillen ausgewertet',
  },
  why: {
    h2: 'Warum ausländische Investoren auf Bali schauen',
    p1: 'Bali ist einer der wenigen Resortmärkte Südostasiens, auf dem Ausländer trotz des indonesischen Verbots von Volleigentum für Ausländer rechtmäßig über eine Immobilie verfügen können — per Pachtvertrag, per Nutzungsrecht (Hak Pakai) mit Aufenthaltstitel oder über eine Gesellschaft mit ausländischem Kapital (PT PMA), die ein Baurecht hält.',
    p2: 'Die Nachfrage ist stark: 2025 kamen 6.948.754 ausländische Besucher nach Bali, ein Rekord (BPS Bali). Sternehotels sind zu etwa 57–65 % ausgelastet, in der Nebensaison weniger (BPS Bali). Balinsky verfolgt den Markt für Kurzzeitvermietung täglich — über 6.300 Villen mit ihren Übernachtungspreisen, über estatemarket.io — und vergleicht jede Villa im Verkauf mit ihren Nachbarn.',
    p3: 'Die Kehrseite ist ebenso real: Die meisten Villen sind Leasehold und verlieren mit ablaufender Laufzeit an Wert, Bauträger sind sehr unterschiedlich, ein Drittel der Villen im Verkauf steht auf Wohnland, auf dem Übernachtungsvermietung nicht erlaubt ist, und nur etwa ein Viertel hat eine Baugenehmigung.',
    p3Link: 'Zonierung und Genehmigungen in Zahlen (auf Englisch)',
  },
  yields: {
    h2: 'Renditen nach Gebiet — unsere Berechnung 2026',
    method: 'Villen mit zwei Schlafzimmern: Medianpreis im Balinsky-Katalog und medianer Übernachtungspreis vermieteter Villen mit zwei Schlafzimmern im selben Gebiet, bei 65 % Auslastung. Netto = nach 15 % Plattformprovision, 20 % Verwaltung, 6 % Betriebskosten und 10 % Mietsteuer; vor Abschreibung des Leasehold. Vollständige Methode (auf Englisch):',
    methodLink: 'Villenrenditen auf Bali nach Gebiet',
    colArea: 'Gebiet',
    colPrice: 'Preis 2 SZ, Median',
    colRate: 'Pro Nacht, Median',
    colYield: 'Brutto / netto',
    indicative: '* weniger als 30 Verkaufspreise — Richtwert',
    browse: 'ansehen',
    areas: {
      canggu: 'Groß-Canggu (Canggu, Berawa, Batu Bolong, Pererenan, Umalas, Seminyak)',
      bukit: 'Bukit (Uluwatu, Melasti, Pandawa, Ungasan)',
      ubud: 'Ubud',
      nyanyi: 'Nyanyi und Tabanan',
      nusaDua: 'Nusa Dua',
      island: 'Ganz Bali',
    },
  },
  legal: {
    h2: 'Eigentumsstrukturen — Leasehold oder PT PMA',
    leaseTitle: 'Leasehold',
    leaseLead: 'Ein vertraglicher Pachtvertrag mit einem lokalen Eigentümer — meist 25–30 Jahre; eine Verlängerung gibt es nur, wenn sie im Vertrag steht.',
    lease: [
      'Keine Gesellschaft nötig',
      'Abschluss als notarielle Urkunde',
      'Keine jährlichen Gesellschaftsberichte',
      'Passt für ein Eigenheim oder ein bis zwei Mietvillen',
      'Das Land gehört Ihnen nicht — nur das Nutzungsrecht auf Zeit',
    ],
    pmaTitle: 'PT PMA',
    pmaLead: 'Eine indonesische Gesellschaft mit ausländischen Gesellschaftern. Sie hält ein Baurecht (HGB) — kein Volleigentum, das Ausländern und Gesellschaften mit ausländischem Kapital verwehrt ist.',
    pma: [
      'Baurecht (HGB): 30 + 20 + 30 Jahre (PP 18/2021)',
      'Passt für ein Vermietungsgeschäft oder ein Portfolio',
      'Eingezahltes Kapital von 2,5 Mrd. Rupiah (Verordnung des Investitionsministeriums Nr. 5/2025)',
      'Jährliche Steuer- und Investitionsberichte',
      '22 % Körperschaftsteuer',
    ],
    more: 'Den gesamten Kaufablauf finden Sie auf der Seite',
    moreLink: '„Immobilie auf Bali kaufen“',
  },
  roi: {
    h2: 'Renditerechnung — eine mittlere Villa',
    title: 'Villa mit 2 Schlafzimmern zum Katalog-Median, 322.500 $, 30 Jahre Leasehold',
    lines: [
      'Übernachtungspreis: 135 $ (Median von 1.966 vermieteten Villen mit 2 Schlafzimmern) × 65 % Auslastung × 365 = etwa 32.000 $ brutto im Jahr',
      'Plattformprovision 15 %, Verwaltung 20 %, Betriebskosten 6 %, Mietsteuer 10 %: etwa −16.300 $',
      'Netto: etwa 15.700 $ im Jahr — 4,9 % des Preises',
      'Abschreibung des Leasehold: 322.500 $ ÷ 30 Jahre = 10.750 $ im Jahr; über die Rückgewinnung des eigenen Kapitals hinaus bleiben also etwa 4.950 $ im Jahr',
    ],
    top: 'Eine Villa im obersten Marktviertel (190 $ pro Nacht) bei 75 % Auslastung: etwa 52.000 $ brutto und 25.500 $ netto — 7,9 % desselben Preises.',
    note: 'Jede Villenseite im Katalog zeigt eine Schätzung auf Basis ihrer eigenen Nachbarn. Methode (auf Englisch):',
    noteLink: 'Villenrenditen auf Bali nach Gebiet',
  },
  risks: {
    h3: 'Risiken, über die Verkäufer selten sprechen',
    items: [
      { t: 'Die Laufzeit schrumpft.', d: 'Ein 25-jähriger Leasehold verbraucht jedes Jahr etwa 4 % des Preises. Vergleichen Sie Villen nach Preis pro verbleibendem Jahr.' },
      { t: 'Keine Baugenehmigung oder kein SLF.', d: 'Ohne sie ist eine Vermietungslizenz schwer zu bekommen. Nur etwa 27 % der Villen in unserem Katalog haben ein PBG oder SLF.' },
      { t: 'Wohn- oder Agrarland.', d: 'Ein Drittel der Villen in unserem Katalog steht auf Wohnland (gelb), auf dem Übernachtungsvermietung nicht erlaubt ist. Prüfen Sie die RDTR-Zone des Grundstücks.' },
      { t: 'Prognosen über dem Markt.', d: 'Im Median bringt eine Villa mit zwei Schlafzimmern etwa 5 % netto. Prognosen von 10–15 % setzen Spitzenpreise und Spitzenauslastung voraus.' },
      { t: 'Bauträgerrisiko bei Off-plan.', d: 'Zahlen Sie nach Bauabschnitten, behalten Sie die größte Rate für die Übergabe und zahlen Sie nichts vor Erteilung des PBG.' },
    ],
  },
  check: {
    h2: 'Was wir zu jedem Inserat zeigen',
    p: 'Für jede Immobilie erfassen wir den Genehmigungsstatus (PBG, SLF), die Grundstückszone und den Bauträger und zeigen sie im Inserat. Wurde ein Dokument nicht vorgelegt, steht das im Inserat — im September 2026 betraf das 57 % der Villen. Prüfen Sie Dokumente vor der Zahlung immer selbst oder über Ihren eigenen Anwalt.',
    cards: [
      { t: 'Dokumente', d: 'PBG, SLF und Grundstücksstatus wie erfasst — fordern Sie vor der Zahlung Kopien an.' },
      { t: 'Bauträger', d: 'Gesellschaft, fertiggestellte Projekte und weitere Inserate desselben Bauträgers.' },
      { t: 'Lage', d: 'Karte, Zonenfarbe, Orte in der Nähe und Mietkonkurrenz rund um die Immobilie.' },
    ],
    more: 'Mehr dazu auf der Seite',
    moreLink: '„Über Balinsky“',
  },
  next: {
    h2: 'Nächste Schritte',
    villas: ['Villenkatalog', 'Villen mit Fotos, Preisen, Genehmigungsstatus und Ertragsschätzung.'],
    apartments: ['Apartmentkatalog', 'Einheiten in verwalteten Anlagen — der niedrigste Einstiegspreis.'],
    complexes: ['Wohnanlagen', 'Anlagen im Bau und fertiggestellt, mit Übergabeterminen.'],
    howTo: ['Kaufen — Schritt für Schritt', 'Eigentumsstrukturen, Kaufablauf, reale Kosten und Fallstricke.'],
  },
  faqH2: 'Häufige Fragen',
  faq: [
    { q: 'Welche Mietrendite ist 2026 für eine Villa auf Bali realistisch?',
      a: 'Nach Berechnung von Balinsky (September 2026: 359 Villen im Verkauf, 6.305 Villen in der Vermietung) erzielt eine mittlere Villa mit zwei Schlafzimmern bei 65 % Auslastung etwa 10 % brutto und etwa 5 % netto im Jahr, eine Villa mit einem Schlafzimmer etwa 14 % brutto und 7 % netto. Villen im obersten Viertel nach Übernachtungspreis erreichen etwa 7–10 % netto. Netto heißt nach Plattformprovision, Verwaltung, Betriebskosten und Mietsteuer, vor Abschreibung des Leasehold. Sternehotels auf Bali sind zu etwa 57–65 % ausgelastet (BPS Bali).' },
    { q: 'Leasehold oder PT PMA — welche Struktur passt für ausländische Investoren?',
      a: 'Ein Leasehold (vertraglicher Pachtvertrag, meist 25–30 Jahre) passt für ein Eigenheim oder ein bis zwei Mietvillen: ohne Gesellschaft und ohne Jahresberichte. Eine PT PMA hält ein Baurecht (HGB, 30 + 20 + 30 Jahre nach PP 18/2021) — kein Volleigentum, das Ausländern verwehrt ist. Sie passt für ein Vermietungsgeschäft; das geforderte eingezahlte Kapital beträgt 2,5 Mrd. Rupiah (Verordnung des Investitionsministeriums Nr. 5/2025), dazu Jahresberichte und 22 % Körperschaftsteuer.' },
    { q: 'Welche Steuern zahlt ein Ausländer beim Kauf und Besitz einer Immobilie auf Bali?',
      a: 'Beim Kauf: Mehrwertsteuer beim Kauf vom Bauträger (effektiv 11 %), Erwerbsteuer BPHTB bis 5 % beim Erwerb eines eingetragenen Grundstücksrechts und Notargebühr (PPAT) von 0,5–1 %. Im Besitz: Grund- und Gebäudesteuer PBB bis 0,5 % der Bemessungsgrundlage. Auf Mieteinnahmen: 10 % Abgeltungsteuer auf die Bruttomiete für Steueransässige; bei Nichtansässigen meist 20 % Quellensteuer, reduzierbar per Doppelbesteuerungsabkommen. Beim Verkauf: 2,5 % Abgeltungsteuer auf den Preis der Übertragung von Grundstück und Gebäude. Quellen: DJP, PwC Indonesia Tax Summaries.' },
    { q: 'Nach wie vielen Jahren amortisiert sich eine Villa auf Bali?',
      a: 'Das hängt von der Nettorendite ab: bei 5 % netto etwa 20 Jahre, bei 7 % etwa 14, bei 10 % etwa 10. Bei einem Leasehold von 25–30 Jahren bleibt im Median wenig Spielraum — deshalb zählen Preis, der real erzielbare Übernachtungspreis und die Laufzeit mehr als die Rendite aus der Broschüre.' },
    { q: 'Was sind PBG und SLF, und warum sind sie wichtig?',
      a: 'PBG (Persetujuan Bangunan Gedung) ist die Baugenehmigung, erteilt vor Baubeginn. SLF (Sertifikat Laik Fungsi) ist die Nutzungsbescheinigung, erteilt nach Fertigstellung. Ohne sie ist eine Vermietungslizenz schwer zu bekommen. Im Balinsky-Katalog haben 27 % der Villen ein PBG oder SLF und 16 % einen laufenden Antrag (September 2026) — fordern Sie die Dokumente vor der Zahlung an.' },
    { q: 'Bekomme ich über eine Immobilieninvestition einen indonesischen Aufenthaltstitel?',
      a: 'Der Kauf einer Villa allein verschafft keinen Aufenthaltstitel. Möglich sind unter anderem ein Investoren-KITAS über eine PT PMA, das Second Home Visa (2 Mrd. Rupiah auf einem indonesischen Bankkonto) und das Golden Visa für größere Investitionen. Die Bedingungen ändern sich — prüfen Sie sie bei der Generaldirektion für Einwanderung.' },
  ],
  sourcesH2: 'Quellen',
  sources: [
    { label: 'BPS Bali — Ankünfte ausländischer Touristen 1969–2025', href: SRC.bpsArrivals },
    { label: 'BPS Bali — Tourismusstatistik, Hotelauslastung (Veröffentlichung November 2025)', href: SRC.bpsOccupancy },
    { label: 'estatemarket.io — Inserate der Kurzzeitvermietung (Quelle der Mietdatenbank)', href: SRC.estatemarket },
    { label: 'Balinsky — Villenrenditen auf Bali nach Gebiet: Methode und Daten (auf Englisch)', href: SRC.yieldEn },
    { label: 'Balinsky — Zonierung und Genehmigungen der Villen im Verkauf in Zahlen (auf Englisch)', href: SRC.zoningEn },
    { label: 'PP Nr. 18/2021 über Grundstücksrechte (JDIH BPK)', href: SRC.pp18 },
    { label: 'PwC Indonesia — Tax Summaries', href: SRC.pwcTax },
    { label: 'DJP — indonesische Steuerverwaltung', href: SRC.djp },
    { label: 'Generaldirektion für Einwanderung Indonesiens', href: SRC.immigration },
  ],
  district: {
    metaTitle: n => `Investieren in ${n}, Bali — Übernachtungspreise und Renditen aus unseren Daten | Balinsky`,
    metaDescription: n => `${n}, Bali: medianer Übernachtungspreis einer Villa, Mieteinnahmen bei 65 % Auslastung und Vergleich mit der ganzen Insel — aus Balinsky-Katalog und Mietdatenbank, mit Quellen.`,
    h1: n => `In Immobilien in ${n}, Bali investieren — 2026`,
    caseTitle: n => `Villa mit zwei Schlafzimmern in ${n} — was die Daten zeigen`,
    rate: (r, n) => `Medianer Übernachtungspreis: ${r} (${n} vermietete Villen mit zwei Schlafzimmern)`,
    revenue: a => `Bruttoeinnahmen bei 65 % Auslastung: etwa ${a} im Jahr`,
    net: a => `Nach Plattformprovision, Verwaltung, Betriebskosten und Mietsteuer (etwa 51 %): etwa ${a} im Jahr`,
    price: (p, n) => `Medianer Angebotspreis der Villen im Gebiet: ${p} (${n} Inserate)`,
    island: 'Zum Vergleich: Auf ganz Bali erzielt eine mittlere Villa mit zwei Schlafzimmern bei 65 % Auslastung etwa 10 % brutto und 5 % netto im Jahr, vor Abschreibung des Leasehold.',
    noRentals: 'In diesem Gebiet werden zu wenige Villen mit zwei Schlafzimmern vermietet, um einen verlässlichen Preis zu nennen — vergleichen Sie mit Nachbargebieten.',
    risksH3: 'Was hier zu prüfen ist',
    bestFor: 'Geeignet für',
    next: 'Nächster Schritt',
    villas: n => [`Villen in ${n}`, 'Inserate mit Fotos, Preisen, Genehmigungsstatus und Ertragsschätzung.'],
    apartments: n => [`Apartments in ${n}`, 'Einheiten in verwalteten Anlagen.'],
    complexes: n => [`Wohnanlagen in ${n}`, 'Projekte im Bau und fertiggestellt.'],
    guide: ['Vollständiger Bali-Investmentguide', 'Renditen, Leasehold, PT PMA und Steuern — mit Quellen.'],
    map: 'Das Gebiet auf der Karte —',
    mapLink: 'Villenkarte',
  },
}
