import type { InvestmentGuideCopy } from './types'
import { SRC } from './data'

export const en: InvestmentGuideCopy = {
  meta: {
    title: 'Bali Property Investment 2026 — Yields From Our Own Data, Leasehold, Taxes | Balinsky',
    description: 'Bali property investment guide for foreigners: rental yields calculated from 6,305 villa rentals and 359 villa prices, leasehold vs PT PMA, taxes, zoning and permits — every figure with its source.',
    ogTitle: 'Bali Property Investment 2026 — What the Data Shows',
    ogDescription: 'Yields from our own data, leasehold vs PT PMA, taxes, zoning and permits. Every figure with its source.',
  },
  crumbHome: 'Home',
  crumb: 'Bali property investment',
  h1: 'Bali Property Investment — 2026 Guide',
  intro: 'Rental yields calculated from our own data, legal structures (leasehold and PT PMA), taxes for foreign owners, zoning and permits. Every figure on this page links to its source.',
  updated: 'Updated: September 2026',
  stats: {
    yield: 'gross yield, median 2-bed villa at 65% occupancy',
    catalogue: 'villas and apartments in the catalogue',
    permits: 'of villas have a PBG or SLF on record',
    rentals: 'villa rentals analysed',
  },
  why: {
    h2: 'Why Foreign Investors Look at Bali',
    p1: 'Bali is one of the few resort markets in Southeast Asia where a foreigner can legally control property despite Indonesia’s ban on foreign freehold — through a lease, a Right to Use (Hak Pakai) with a residence permit, or a foreign-owned company (PT PMA) holding a Right to Build.',
    p2: 'Demand is strong: Bali received 6,948,754 foreign visitors in 2025, a record (BPS Bali). Star-hotel occupancy runs at roughly 57–65% and dips in the low months (BPS Bali). Balinsky tracks the short-term rental market daily — over 6,300 villas with their listed nightly rates, via estatemarket.io — and compares every villa for sale with its neighbours.',
    p3: 'The trade-offs are just as real: most villas are leasehold and lose value as the term runs down, developers are uneven, a third of villas for sale sit on residential land where nightly rental is not permitted, and only about a quarter have a building permit on record.',
    p3Link: 'Zoning and permits in numbers',
  },
  yields: {
    h2: 'Yields by Area — Our 2026 Calculation',
    method: 'Two-bedroom villas: median asking price in the Balinsky catalogue and median listed nightly rate of two-bedroom villas for rent in the same area, at 65% occupancy. Net = after 15% booking-platform commissions, 20% management, 6% running costs and 10% rental tax; before leasehold amortisation. Full method:',
    methodLink: 'Bali villa rental yield by area',
    colArea: 'Area',
    colPrice: '2-bed price, median',
    colRate: 'Per night, median',
    colYield: 'Gross / net',
    indicative: '* fewer than 30 sale prices — indicative',
    browse: 'browse',
    areas: {
      canggu: 'Greater Canggu (Canggu, Berawa, Batu Bolong, Pererenan, Umalas, Seminyak)',
      bukit: 'Bukit (Uluwatu, Melasti, Pandawa, Ungasan)',
      ubud: 'Ubud',
      nyanyi: 'Nyanyi and Tabanan',
      nusaDua: 'Nusa Dua',
      island: 'All of Bali',
    },
  },
  legal: {
    h2: 'Legal Structures — Leasehold vs PT PMA',
    leaseTitle: 'Leasehold',
    leaseLead: 'A contractual lease from a local owner — usually 25–30 years; an extension exists only if it is written into the contract.',
    lease: [
      'No company needed',
      'Signed as a notarial deed',
      'No annual corporate reporting',
      'Fits a home or one or two rental villas',
      'You do not own the land — only the right to use it, for a fixed term',
    ],
    pmaTitle: 'PT PMA',
    pmaLead: 'An Indonesian company with foreign shareholders. It holds a Right to Build (HGB) — not freehold, which foreigners and foreign-owned companies cannot hold.',
    pma: [
      'Right to Build (HGB): 30 + 20 + 30 years (PP 18/2021)',
      'Suits a rental business or a portfolio',
      'Paid-up capital of IDR 2.5 billion (Ministry of Investment Regulation 5/2025)',
      'Annual tax and investment reporting',
      '22% corporate income tax',
    ],
    more: 'The full transaction process is on the',
    moreLink: '«How to buy property in Bali»',
  },
  roi: {
    h2: 'Return Calculation — a Median Villa',
    title: '2-bed villa at the catalogue median, $322,500, 30-year leasehold',
    lines: [
      'Nightly rate: $135 (median of 1,966 two-bedroom villas for rent) × 65% occupancy × 365 = about $32,000 a year gross',
      'Platform commissions 15%, management 20%, running costs 6%, rental tax 10%: about −$16,300',
      'Net: about $15,700 a year — 4.9% of the price',
      'Leasehold amortisation: $322,500 ÷ 30 years = $10,750 a year, so about $4,950 a year is return above getting your own money back',
    ],
    top: 'A villa in the top quarter of the market ($190 a night) at 75% occupancy: about $52,000 gross and $25,500 net — 7.9% of the same price.',
    note: 'Each villa page in the catalogue shows an estimate based on its own neighbours. Method:',
    noteLink: 'Bali villa rental yield by area',
  },
  risks: {
    h3: 'Risks Sellers Rarely Mention',
    items: [
      { t: 'The lease runs down.', d: 'A 25-year lease uses up about 4% of the price every year. Compare villas by price per remaining year.' },
      { t: 'No building permit or SLF.', d: 'Without them, licensing a rental is difficult. Only about 27% of villas in our catalogue have a PBG or SLF on record.' },
      { t: 'Residential or agricultural land.', d: 'A third of villas in our catalogue sit on residential (yellow) land where nightly rental is not permitted. Check the RDTR zone of the exact plot.' },
      { t: 'Projections above the market.', d: 'At the median, a two-bedroom villa earns about 5% net. Projections of 10–15% assume top-of-market rates and occupancy.' },
      { t: 'Developer risk on off-plan.', d: 'Pay by construction milestone, keep the largest payment for handover, and do not pay before the PBG exists.' },
    ],
  },
  check: {
    h2: 'What We Show for Each Listing',
    p: 'For every property we record the permit status (PBG, SLF), the land zone and the developer, and show them on the listing. Where a document has not been provided, the listing says so — in September 2026 that was 57% of villas. Always verify documents yourself or through your own lawyer before paying.',
    cards: [
      { t: 'Documents', d: 'PBG, SLF and land status as recorded — ask for copies before paying.' },
      { t: 'Developer', d: 'Company, completed projects and other listings by the same developer.' },
      { t: 'Location', d: 'Map, land zone colour, nearby places and rental competition around the property.' },
    ],
    more: 'More on the',
    moreLink: '«About Balinsky»',
  },
  next: {
    h2: 'Next Steps',
    villas: ['Villa catalogue', 'Villas with photos, prices, permit status and an income estimate.'],
    apartments: ['Apartment catalogue', 'Units in managed complexes — the lowest entry price.'],
    complexes: ['Residential complexes', 'Off-plan and completed complexes with completion dates.'],
    howTo: ['How to buy — step by step', 'Ownership structures, the transaction, real costs and pitfalls.'],
  },
  faqH2: 'Frequently Asked Questions',
  faq: [
    { q: 'What is the realistic rental yield for a Bali villa in 2026?',
      a: 'By Balinsky’s calculation (September 2026: 359 villas for sale, 6,305 villas listed for rent), a median two-bedroom villa earns about 10% a year gross and about 5% net at 65% occupancy; a one-bedroom villa about 14% gross and 7% net. Villas in the top quarter by nightly rate reach about 7–10% net. Net means after platform commissions, management, running costs and rental tax, before leasehold amortisation. Star-hotel occupancy on Bali is roughly 57–65% (BPS Bali).' },
    { q: 'Leasehold or PT PMA — which structure should a foreign investor pick?',
      a: 'A leasehold (a contractual lease, usually 25–30 years) suits a home or one or two rental villas: no company and no annual reporting. A PT PMA holds a Right to Build (HGB, 30 + 20 + 30 years under PP 18/2021) — not freehold, which foreigners cannot hold. It suits a rental business; the paid-up capital requirement is IDR 2.5 billion (Ministry of Investment Regulation 5/2025), plus annual reporting and 22% corporate income tax.' },
    { q: 'What taxes does a foreigner pay when buying and owning property in Bali?',
      a: 'On purchase: VAT when buying from a developer (effectively 11%), acquisition duty (BPHTB) up to 5% when a registered land right is acquired, and a notary (PPAT) fee of 0.5–1%. On ownership: land and building tax (PBB) up to 0.5% of the assessed base. On rental income: a 10% final tax on gross rent for tax residents; non-residents are generally withheld at 20%, reducible under a tax treaty. On sale: a 2.5% final tax on the price of a land-and-building transfer. Sources: DJP, PwC Indonesia Tax Summaries.' },
    { q: 'How many years until a Bali villa pays back?',
      a: 'It depends on the net yield: at 5% net about 20 years, at 7% about 14 years, at 10% about 10 years. On a 25–30-year leasehold that leaves little margin at the median, which is why the price, the nightly rate a villa can really achieve and the lease term matter more than the brochure yield.' },
    { q: 'What are PBG and SLF, and why do they matter?',
      a: 'PBG (Persetujuan Bangunan Gedung) is the building permit, issued before construction. SLF (Sertifikat Laik Fungsi) is the certificate of functional feasibility, issued on completion. Without them, licensing a rental is difficult. In the Balinsky catalogue, 27% of villas have a PBG or SLF on record and 16% have an application in progress (September 2026) — ask for the documents before paying.' },
    { q: 'Can I get an Indonesian residence permit through property investment?',
      a: 'Buying a villa alone does not grant residency. Options include an investor KITAS linked to a PT PMA, the Second Home Visa (funds of IDR 2 billion placed in an Indonesian bank) and the Golden Visa for larger investments. Conditions change — check them with the Directorate General of Immigration.' },
  ],
  sourcesH2: 'Sources',
  sources: [
    { label: 'BPS Bali — foreign tourist arrivals 1969–2025', href: SRC.bpsArrivals },
    { label: 'BPS Bali — tourism statistics, hotel occupancy (November 2025 release)', href: SRC.bpsOccupancy },
    { label: 'estatemarket.io — short-term rental listings (source of the rental database)', href: SRC.estatemarket },
    { label: 'Balinsky — Bali villa rental yield by area: method and data', href: SRC.yieldEn },
    { label: 'Balinsky — zoning and permits of villas for sale, in numbers', href: SRC.zoningEn },
    { label: 'PP No. 18/2021 on land rights (JDIH BPK)', href: SRC.pp18 },
    { label: 'PwC Indonesia — Tax Summaries', href: SRC.pwcTax },
    { label: 'DJP — Indonesian Tax Authority', href: SRC.djp },
    { label: 'Directorate General of Immigration', href: SRC.immigration },
  ],
  district: {
    metaTitle: n => `Investing in ${n}, Bali: Rental Rates & Yields | Balinsky`,
    metaDescription: n => `${n}, Bali: median nightly villa rate, rental revenue at 65% occupancy and how it compares with the island — from Balinsky's catalogue and rental database, with sources.`,
    h1: n => `Investing in property in ${n}, Bali — 2026`,
    caseTitle: n => `Two-bedroom villa in ${n} — what the data shows`,
    rate: (r, n) => `Median listed nightly rate: ${r} (${n} two-bedroom villas for rent)`,
    revenue: a => `Gross revenue at 65% occupancy: about ${a} a year`,
    net: a => `After platform commissions, management, running costs and rental tax (about 51%): about ${a} a year`,
    price: (p, n) => `Median asking price of villas in the area: ${p} (${n} listings)`,
    island: 'For comparison, across Bali a median two-bedroom villa earns about 10% gross and 5% net a year at 65% occupancy, before leasehold amortisation.',
    noRentals: 'There are too few two-bedroom villas for rent in this area to state a reliable nightly rate — compare with neighbouring areas.',
    risksH3: 'Risks to check here',
    bestFor: 'Best for',
    next: 'Next step',
    villas: n => [`Villas in ${n}`, 'Listings with photos, prices, permit status and an income estimate.'],
    apartments: n => [`Apartments in ${n}`, 'Units in managed complexes.'],
    complexes: n => [`Residential complexes in ${n}`, 'Off-plan and completed projects.'],
    guide: ['Full Bali investment guide', 'Yields, leasehold, PT PMA and taxes — with sources.'],
    map: 'See the area on the map —',
    mapLink: 'villa map',
  },
}
