import type { InvestmentGuideCopy } from './types'
import { SRC } from './data'

export const fr: InvestmentGuideCopy = {
  meta: {
    title: 'Investir dans l’immobilier à Bali en 2026 — rendements selon nos données, leasehold, impôts | Balinsky',
    description: 'Guide de l’investissement immobilier à Bali pour les étrangers : rendements calculés sur 6 305 villas en location et 359 prix de vente, leasehold ou PT PMA, impôts, zonage et permis — chaque chiffre avec sa source.',
    ogTitle: 'Investir à Bali en 2026 — ce que montrent les données',
    ogDescription: 'Rendements calculés sur nos propres données, leasehold ou PT PMA, impôts, zonage et permis. Chaque chiffre avec sa source.',
  },
  crumbHome: 'Accueil',
  crumb: 'Investissement immobilier à Bali',
  h1: 'Investir dans l’immobilier à Bali — guide 2026',
  intro: 'Des rendements calculés sur nos propres données, les structures de détention (leasehold et PT PMA), les impôts pour un propriétaire étranger, le zonage et les permis. Chaque chiffre de cette page renvoie à sa source.',
  updated: 'Mis à jour : septembre 2026',
  stats: {
    yield: 'rendement brut d’une villa médiane de 2 chambres à 65 % d’occupation',
    catalogue: 'villas et appartements au catalogue',
    permits: 'des villas ont un PBG ou un SLF',
    rentals: 'villas en location analysées',
  },
  why: {
    h2: 'Pourquoi les investisseurs étrangers regardent Bali',
    p1: 'Bali est l’un des rares marchés balnéaires d’Asie du Sud-Est où un étranger peut légalement contrôler un bien malgré l’interdiction indonésienne de la pleine propriété pour les étrangers : par un bail, par un droit d’usage (Hak Pakai) avec un titre de séjour, ou par une société à capitaux étrangers (PT PMA) détenant un droit de construire.',
    p2: 'La demande est forte : Bali a accueilli 6 948 754 visiteurs étrangers en 2025, un record (BPS Bali). L’occupation des hôtels étoilés tourne autour de 57–65 % et baisse en basse saison (BPS Bali). Balinsky suit chaque jour le marché de la location courte durée — plus de 6 300 villas avec leur prix à la nuit, via estatemarket.io — et compare chaque villa à vendre avec ses voisines.',
    p3: 'Les contreparties sont tout aussi réelles : la plupart des villas sont en leasehold et perdent de la valeur à mesure que le bail s’écoule, les promoteurs sont inégaux, un tiers des villas à vendre se trouvent sur un terrain résidentiel où la location à la nuit n’est pas autorisée, et seul un quart environ a un permis de construire enregistré.',
    p3Link: 'Zonage et permis en chiffres (en anglais)',
  },
  yields: {
    h2: 'Rendements par secteur — notre calcul 2026',
    method: 'Villas de deux chambres : prix médian au catalogue Balinsky et prix médian à la nuit des villas de deux chambres en location dans le même secteur, à 65 % d’occupation. Net = après 15 % de commissions des plateformes, 20 % de gestion, 6 % de frais d’exploitation et 10 % d’impôt sur les loyers ; avant amortissement du leasehold. Méthode complète (en anglais) :',
    methodLink: 'rendement des villas à Bali par secteur',
    colArea: 'Secteur',
    colPrice: 'Prix 2 ch., médiane',
    colRate: 'Par nuit, médiane',
    colYield: 'Brut / net',
    indicative: '* moins de 30 prix de vente — indicatif',
    browse: 'voir',
    areas: {
      canggu: 'Grand Canggu (Canggu, Berawa, Batu Bolong, Pererenan, Umalas, Seminyak)',
      bukit: 'Bukit (Uluwatu, Melasti, Pandawa, Ungasan)',
      ubud: 'Ubud',
      nyanyi: 'Nyanyi et Tabanan',
      nusaDua: 'Nusa Dua',
      island: 'Tout Bali',
    },
  },
  legal: {
    h2: 'Structures de détention — leasehold ou PT PMA',
    leaseTitle: 'Leasehold',
    leaseLead: 'Un bail contractuel consenti par un propriétaire local — généralement 25–30 ans ; une prolongation n’existe que si elle est écrite dans le contrat.',
    lease: [
      'Pas besoin de société',
      'Signé par acte notarié',
      'Pas de comptes annuels de société',
      'Convient à une résidence ou à une ou deux villas locatives',
      'Le terrain ne vous appartient pas — seulement le droit de l’utiliser pour une durée fixe',
    ],
    pmaTitle: 'PT PMA',
    pmaLead: 'Une société indonésienne à actionnaires étrangers. Elle détient un droit de construire (HGB) — pas la pleine propriété, interdite aux étrangers et aux sociétés à capitaux étrangers.',
    pma: [
      'Droit de construire (HGB) : 30 + 20 + 30 ans (PP 18/2021)',
      'Convient à une activité locative ou à un portefeuille',
      'Capital libéré de 2,5 milliards de roupies (règlement du ministère de l’Investissement n° 5/2025)',
      'Déclarations fiscales et d’investissement annuelles',
      'Impôt sur les sociétés de 22 %',
    ],
    more: 'Tout le processus de transaction est sur la page',
    moreLink: '« Comment acheter un bien à Bali »',
  },
  roi: {
    h2: 'Calcul du rendement — une villa médiane',
    title: 'Villa de 2 chambres à la médiane du catalogue, 322 500 $, leasehold de 30 ans',
    lines: [
      'Prix à la nuit : 135 $ (médiane de 1 966 villas de 2 chambres en location) × 65 % d’occupation × 365 = environ 32 000 $ par an brut',
      'Commissions des plateformes 15 %, gestion 20 %, frais d’exploitation 6 %, impôt sur les loyers 10 % : environ −16 300 $',
      'Net : environ 15 700 $ par an — 4,9 % du prix',
      'Amortissement du leasehold : 322 500 $ ÷ 30 ans = 10 750 $ par an, soit environ 4 950 $ par an de rendement au-delà de la récupération de votre propre capital',
    ],
    top: 'Une villa du quart supérieur du marché (190 $ la nuit) à 75 % d’occupation : environ 52 000 $ brut et 25 500 $ net — 7,9 % du même prix.',
    note: 'Chaque page de villa du catalogue affiche une estimation fondée sur ses propres voisines. Méthode (en anglais) :',
    noteLink: 'rendement des villas à Bali par secteur',
  },
  risks: {
    h3: 'Les risques dont les vendeurs parlent peu',
    items: [
      { t: 'Le bail s’épuise.', d: 'Un bail de 25 ans consomme environ 4 % du prix chaque année. Comparez les villas par prix par année restante.' },
      { t: 'Pas de permis de construire ni de SLF.', d: 'Sans eux, obtenir une licence de location est difficile. Seules 27 % environ des villas de notre catalogue ont un PBG ou un SLF enregistré.' },
      { t: 'Terrain résidentiel ou agricole.', d: 'Un tiers des villas de notre catalogue se trouvent sur un terrain résidentiel (jaune) où la location à la nuit n’est pas autorisée. Vérifiez la zone RDTR de la parcelle.' },
      { t: 'Projections au-dessus du marché.', d: 'À la médiane, une villa de deux chambres rapporte environ 5 % net. Des projections de 10–15 % supposent des tarifs et une occupation de haut de marché.' },
      { t: 'Risque promoteur sur l’off-plan.', d: 'Payez par étape de construction, gardez le plus gros paiement pour la livraison et ne payez rien avant l’obtention du PBG.' },
    ],
  },
  check: {
    h2: 'Ce que nous affichons pour chaque annonce',
    p: 'Pour chaque bien, nous enregistrons le statut des permis (PBG, SLF), la zone du terrain et le promoteur, et nous les affichons sur l’annonce. Lorsqu’un document n’a pas été fourni, l’annonce l’indique — en septembre 2026, c’était le cas de 57 % des villas. Vérifiez toujours les documents vous-même ou avec votre propre avocat avant de payer.',
    cards: [
      { t: 'Documents', d: 'PBG, SLF et statut du terrain tels qu’enregistrés — demandez-en des copies avant de payer.' },
      { t: 'Promoteur', d: 'Société, projets livrés et autres annonces du même promoteur.' },
      { t: 'Emplacement', d: 'Carte, couleur de zone, lieux à proximité et concurrence locative autour du bien.' },
    ],
    more: 'En savoir plus sur la page',
    moreLink: '« À propos de Balinsky »',
  },
  next: {
    h2: 'Prochaines étapes',
    villas: ['Catalogue de villas', 'Villas avec photos, prix, statut des permis et estimation des revenus.'],
    apartments: ['Catalogue d’appartements', 'Lots dans des résidences gérées — le ticket d’entrée le plus bas.'],
    complexes: ['Résidences', 'Résidences sur plan et livrées, avec dates de livraison.'],
    howTo: ['Comment acheter — étape par étape', 'Structures de détention, transaction, coûts réels et pièges.'],
  },
  faqH2: 'Questions fréquentes',
  faq: [
    { q: 'Quel est le rendement locatif réaliste d’une villa à Bali en 2026 ?',
      a: 'Selon le calcul de Balinsky (septembre 2026 : 359 villas à vendre, 6 305 villas en location), une villa médiane de deux chambres rapporte environ 10 % brut par an et environ 5 % net à 65 % d’occupation ; une villa d’une chambre environ 14 % brut et 7 % net. Les villas du quart supérieur par prix à la nuit atteignent environ 7–10 % net. Net signifie après commissions des plateformes, gestion, frais d’exploitation et impôt sur les loyers, avant amortissement du leasehold. L’occupation des hôtels étoilés de Bali est d’environ 57–65 % (BPS Bali).' },
    { q: 'Leasehold ou PT PMA — quelle structure choisir pour un investisseur étranger ?',
      a: 'Le leasehold (bail contractuel, généralement 25–30 ans) convient à une résidence ou à une ou deux villas locatives : pas de société ni de comptes annuels. Une PT PMA détient un droit de construire (HGB, 30 + 20 + 30 ans selon le PP 18/2021) — pas la pleine propriété, interdite aux étrangers. Elle convient à une activité locative ; le capital libéré requis est de 2,5 milliards de roupies (règlement du ministère de l’Investissement n° 5/2025), plus des déclarations annuelles et 22 % d’impôt sur les sociétés.' },
    { q: 'Quels impôts paie un étranger à l’achat et pendant la détention d’un bien à Bali ?',
      a: 'À l’achat : TVA en cas d’achat auprès d’un promoteur (11 % en pratique), droit d’acquisition BPHTB jusqu’à 5 % lors de l’acquisition d’un droit foncier enregistré, et frais de notaire (PPAT) de 0,5–1 %. Pendant la détention : taxe foncière PBB jusqu’à 0,5 % de la base imposable. Sur les loyers : impôt libératoire de 10 % sur les loyers bruts pour les résidents fiscaux ; retenue généralement de 20 % pour les non-résidents, réductible par convention fiscale. À la vente : impôt libératoire de 2,5 % sur le prix de cession du terrain et de la construction. Sources : DJP, PwC Indonesia Tax Summaries.' },
    { q: 'En combien d’années une villa à Bali est-elle rentabilisée ?',
      a: 'Cela dépend du rendement net : à 5 % net, environ 20 ans ; à 7 %, environ 14 ans ; à 10 %, environ 10 ans. Sur un leasehold de 25–30 ans, la marge est faible à la médiane — c’est pourquoi le prix, le tarif à la nuit réellement atteignable et la durée du bail comptent plus que le rendement de la brochure.' },
    { q: 'Que sont le PBG et le SLF, et pourquoi sont-ils importants ?',
      a: 'Le PBG (Persetujuan Bangunan Gedung) est le permis de construire, délivré avant les travaux. Le SLF (Sertifikat Laik Fungsi) est le certificat de conformité d’usage, délivré à l’achèvement. Sans eux, obtenir une licence de location est difficile. Dans le catalogue Balinsky, 27 % des villas ont un PBG ou un SLF enregistré et 16 % ont une demande en cours (septembre 2026) — demandez les documents avant de payer.' },
    { q: 'Peut-on obtenir un titre de séjour indonésien en investissant dans l’immobilier ?',
      a: 'L’achat d’une villa seul ne donne pas de titre de séjour. Les options incluent un KITAS investisseur lié à une PT PMA, le Second Home Visa (2 milliards de roupies déposés dans une banque indonésienne) et le Golden Visa pour des investissements plus importants. Les conditions évoluent — vérifiez-les auprès de la Direction générale de l’immigration.' },
  ],
  sourcesH2: 'Sources',
  sources: [
    { label: 'BPS Bali — arrivées de touristes étrangers 1969–2025', href: SRC.bpsArrivals },
    { label: 'BPS Bali — statistiques du tourisme, occupation hôtelière (publication de novembre 2025)', href: SRC.bpsOccupancy },
    { label: 'estatemarket.io — annonces de location courte durée (source de la base de location)', href: SRC.estatemarket },
    { label: 'Balinsky — rendement des villas à Bali par secteur : méthode et données (en anglais)', href: SRC.yieldEn },
    { label: 'Balinsky — zonage et permis des villas à vendre en chiffres (en anglais)', href: SRC.zoningEn },
    { label: 'PP n° 18/2021 sur les droits fonciers (JDIH BPK)', href: SRC.pp18 },
    { label: 'PwC Indonesia — Tax Summaries', href: SRC.pwcTax },
    { label: 'DJP — administration fiscale indonésienne', href: SRC.djp },
    { label: 'Direction générale de l’immigration d’Indonésie', href: SRC.immigration },
  ],
  district: {
    metaTitle: n => `Investir à ${n}, Bali — prix à la nuit et rendements selon nos données | Balinsky`,
    metaDescription: n => `${n}, Bali : prix médian d’une villa à la nuit, revenus locatifs à 65 % d’occupation et comparaison avec l’île — d’après le catalogue et la base de location Balinsky, avec sources.`,
    h1: n => `Investir dans l’immobilier à ${n}, Bali — 2026`,
    caseTitle: n => `Villa de deux chambres à ${n} — ce que montrent les données`,
    rate: (r, n) => `Prix médian à la nuit : ${r} (${n} villas de deux chambres en location)`,
    revenue: a => `Revenu brut à 65 % d’occupation : environ ${a} par an`,
    net: a => `Après commissions des plateformes, gestion, frais d’exploitation et impôt sur les loyers (environ 51 %) : environ ${a} par an`,
    price: (p, n) => `Prix médian des villas du secteur : ${p} (${n} annonces)`,
    island: 'À titre de comparaison, sur l’ensemble de Bali une villa médiane de deux chambres rapporte environ 10 % brut et 5 % net par an à 65 % d’occupation, avant amortissement du leasehold.',
    noRentals: 'Trop peu de villas de deux chambres sont en location dans ce secteur pour donner un prix fiable — comparez avec les secteurs voisins.',
    risksH3: 'À vérifier ici',
    bestFor: 'Pour qui',
    next: 'Prochaine étape',
    villas: n => [`Villas à ${n}`, 'Annonces avec photos, prix, statut des permis et estimation des revenus.'],
    apartments: n => [`Appartements à ${n}`, 'Lots dans des résidences gérées.'],
    complexes: n => [`Résidences à ${n}`, 'Projets sur plan et livrés.'],
    guide: ['Guide complet de l’investissement à Bali', 'Rendements, leasehold, PT PMA et impôts — avec sources.'],
    map: 'Voir le secteur sur la carte —',
    mapLink: 'carte des villas',
  },
}
