import type { InvestmentGuideCopy } from './types'
import { SRC } from './data'

export const id: InvestmentGuideCopy = {
  meta: {
    title: 'Investasi Properti Bali 2026 — Imbal Hasil dari Data Kami, Leasehold, Pajak | Balinsky',
    description: 'Panduan investasi properti Bali untuk orang asing: imbal hasil dihitung dari 6.305 vila sewa dan 359 harga jual vila, leasehold vs PT PMA, pajak, zonasi dan izin — setiap angka dengan sumbernya.',
    ogTitle: 'Investasi Properti Bali 2026 — Apa Kata Data',
    ogDescription: 'Imbal hasil dari data kami sendiri, leasehold vs PT PMA, pajak, zonasi dan izin. Setiap angka dengan sumbernya.',
  },
  crumbHome: 'Beranda',
  crumb: 'Investasi properti Bali',
  h1: 'Investasi Properti Bali — Panduan 2026',
  intro: 'Imbal hasil yang dihitung dari data kami sendiri, struktur kepemilikan (leasehold dan PT PMA), pajak bagi pemilik asing, zonasi dan izin. Setiap angka di halaman ini memiliki tautan ke sumbernya.',
  updated: 'Diperbarui: September 2026',
  stats: {
    yield: 'imbal hasil kotor vila 2 kamar median pada okupansi 65%',
    catalogue: 'vila dan apartemen di katalog',
    permits: 'vila memiliki PBG atau SLF',
    rentals: 'vila sewa dianalisis',
  },
  why: {
    h2: 'Mengapa Investor Asing Melirik Bali',
    p1: 'Bali adalah salah satu dari sedikit pasar resor di Asia Tenggara tempat orang asing dapat menguasai properti secara sah meskipun Indonesia melarang hak milik bagi orang asing — melalui sewa, Hak Pakai dengan izin tinggal, atau perusahaan berpemilik asing (PT PMA) yang memegang Hak Guna Bangunan.',
    p2: 'Permintaannya kuat: Bali menerima 6.948.754 wisatawan asing pada 2025, sebuah rekor (BPS Bali). Okupansi hotel berbintang sekitar 57–65% dan turun pada bulan sepi (BPS Bali). Balinsky memantau pasar sewa jangka pendek setiap hari — lebih dari 6.300 vila dengan tarif per malamnya, melalui estatemarket.io — dan membandingkan setiap vila yang dijual dengan tetangganya.',
    p3: 'Sisi lainnya sama nyata: sebagian besar vila berstatus leasehold dan nilainya turun seiring berjalannya masa sewa, kualitas pengembang tidak merata, sepertiga vila yang dijual berada di lahan hunian tempat sewa harian tidak diizinkan, dan hanya sekitar seperempat yang memiliki izin bangunan.',
    p3Link: 'Zonasi dan izin dalam angka (bahasa Inggris)',
  },
  yields: {
    h2: 'Imbal Hasil per Kawasan — Perhitungan Kami 2026',
    method: 'Vila 2 kamar tidur: harga median di katalog Balinsky dan tarif median per malam vila 2 kamar yang disewakan di kawasan yang sama, pada okupansi 65%. Bersih = setelah komisi platform 15%, manajemen 20%, biaya operasional 6% dan pajak sewa 10%; sebelum amortisasi leasehold. Metode lengkap (bahasa Inggris):',
    methodLink: 'imbal hasil vila Bali per kawasan',
    colArea: 'Kawasan',
    colPrice: 'Harga 2 kamar, median',
    colRate: 'Per malam, median',
    colYield: 'Kotor / bersih',
    indicative: '* kurang dari 30 harga jual — indikatif',
    browse: 'lihat',
    areas: {
      canggu: 'Canggu Raya (Canggu, Berawa, Batu Bolong, Pererenan, Umalas, Seminyak)',
      bukit: 'Bukit (Uluwatu, Melasti, Pandawa, Ungasan)',
      ubud: 'Ubud',
      nyanyi: 'Nyanyi dan Tabanan',
      nusaDua: 'Nusa Dua',
      island: 'Seluruh Bali',
    },
  },
  legal: {
    h2: 'Struktur Kepemilikan — Leasehold vs PT PMA',
    leaseTitle: 'Leasehold',
    leaseLead: 'Sewa berdasarkan kontrak dari pemilik lokal — biasanya 25–30 tahun; perpanjangan hanya ada jika tertulis dalam kontrak.',
    lease: [
      'Tidak perlu perusahaan',
      'Ditandatangani sebagai akta notaris',
      'Tanpa laporan perusahaan tahunan',
      'Cocok untuk rumah atau satu-dua vila sewa',
      'Tanah bukan milik Anda — hanya hak pakai untuk jangka waktu tertentu',
    ],
    pmaTitle: 'PT PMA',
    pmaLead: 'Perusahaan Indonesia dengan pemegang saham asing. Memegang Hak Guna Bangunan (HGB) — bukan hak milik, yang tidak bisa dimiliki orang asing maupun perusahaan berpemilik asing.',
    pma: [
      'Hak Guna Bangunan: 30 + 20 + 30 tahun (PP 18/2021)',
      'Cocok untuk bisnis sewa atau portofolio',
      'Modal disetor Rp2,5 miliar (Peraturan Kementerian Investasi No. 5/2025)',
      'Laporan pajak dan investasi tahunan',
      'Pajak penghasilan badan 22%',
    ],
    more: 'Proses transaksi lengkap ada di halaman',
    moreLink: '«Cara membeli properti di Bali»',
  },
  roi: {
    h2: 'Perhitungan Imbal Hasil — Vila Median',
    title: 'Vila 2 kamar pada median katalog, $322.500, leasehold 30 tahun',
    lines: [
      'Tarif: $135 per malam (median 1.966 vila 2 kamar yang disewakan) × okupansi 65% × 365 = sekitar $32.000 per tahun kotor',
      'Komisi platform 15%, manajemen 20%, biaya operasional 6%, pajak sewa 10%: sekitar −$16.300',
      'Bersih: sekitar $15.700 per tahun — 4,9% dari harga',
      'Amortisasi leasehold: $322.500 ÷ 30 tahun = $10.750 per tahun, jadi sekitar $4.950 per tahun adalah hasil di atas pengembalian modal Anda sendiri',
    ],
    top: 'Vila di kuartil teratas pasar ($190 per malam) pada okupansi 75%: sekitar $52.000 kotor dan $25.500 bersih — 7,9% dari harga yang sama.',
    note: 'Setiap halaman vila di katalog menampilkan estimasi berdasarkan tetangganya sendiri. Metode (bahasa Inggris):',
    noteLink: 'imbal hasil vila Bali per kawasan',
  },
  risks: {
    h3: 'Risiko yang Jarang Disebut Penjual',
    items: [
      { t: 'Masa sewa terus berkurang.', d: 'Sewa 25 tahun menghabiskan sekitar 4% harga setiap tahun. Bandingkan vila berdasarkan harga per sisa tahun.' },
      { t: 'Tanpa izin bangunan atau SLF.', d: 'Tanpa keduanya, perizinan sewa sulit. Hanya sekitar 27% vila di katalog kami yang memiliki PBG atau SLF.' },
      { t: 'Lahan hunian atau pertanian.', d: 'Sepertiga vila di katalog kami berada di lahan hunian (kuning) tempat sewa harian tidak diizinkan. Periksa zona RDTR bidang tanahnya.' },
      { t: 'Proyeksi di atas pasar.', d: 'Pada median, vila 2 kamar menghasilkan sekitar 5% bersih. Proyeksi 10–15% mengasumsikan tarif dan okupansi puncak pasar.' },
      { t: 'Risiko pengembang pada off-plan.', d: 'Bayar sesuai tahap pembangunan, simpan pembayaran terbesar untuk serah terima, dan jangan membayar sebelum PBG terbit.' },
    ],
  },
  check: {
    h2: 'Apa yang Kami Tampilkan untuk Setiap Listing',
    p: 'Untuk setiap properti kami mencatat status izin (PBG, SLF), zona tanah dan pengembangnya, lalu menampilkannya di listing. Jika dokumen belum diberikan, listing menyebutkannya — pada September 2026 itu berlaku untuk 57% vila. Selalu periksa dokumen sendiri atau melalui pengacara Anda sebelum membayar.',
    cards: [
      { t: 'Dokumen', d: 'PBG, SLF dan status tanah sebagaimana tercatat — minta salinannya sebelum membayar.' },
      { t: 'Pengembang', d: 'Perusahaan, proyek yang sudah selesai dan listing lain dari pengembang yang sama.' },
      { t: 'Lokasi', d: 'Peta, warna zona, tempat di sekitar dan persaingan sewa di sekitar properti.' },
    ],
    more: 'Selengkapnya di halaman',
    moreLink: '«Tentang Balinsky»',
  },
  next: {
    h2: 'Langkah Berikutnya',
    villas: ['Katalog vila', 'Vila dengan foto, harga, status izin dan estimasi pendapatan.'],
    apartments: ['Katalog apartemen', 'Unit di kompleks terkelola — harga masuk terendah.'],
    complexes: ['Kompleks hunian', 'Kompleks off-plan dan yang sudah selesai dengan jadwal serah terima.'],
    howTo: ['Cara membeli — langkah demi langkah', 'Struktur kepemilikan, transaksi, biaya nyata dan jebakannya.'],
  },
  faqH2: 'Pertanyaan yang Sering Diajukan',
  faq: [
    { q: 'Berapa imbal hasil sewa yang realistis untuk vila di Bali pada 2026?',
      a: 'Menurut perhitungan Balinsky (September 2026: 359 vila dijual, 6.305 vila disewakan), vila 2 kamar median menghasilkan sekitar 10% per tahun kotor dan sekitar 5% bersih pada okupansi 65%; vila 1 kamar sekitar 14% kotor dan 7% bersih. Vila di kuartil teratas berdasarkan tarif per malam mencapai sekitar 7–10% bersih. Bersih berarti setelah komisi platform, manajemen, biaya operasional dan pajak sewa, sebelum amortisasi leasehold. Okupansi hotel berbintang di Bali sekitar 57–65% (BPS Bali).' },
    { q: 'Leasehold atau PT PMA — struktur mana yang sebaiknya dipilih investor asing?',
      a: 'Leasehold (sewa berdasarkan kontrak, biasanya 25–30 tahun) cocok untuk rumah atau satu-dua vila sewa: tanpa perusahaan dan tanpa laporan tahunan. PT PMA memegang Hak Guna Bangunan (HGB, 30 + 20 + 30 tahun menurut PP 18/2021) — bukan hak milik, yang tidak bisa dimiliki orang asing. Cocok untuk bisnis sewa; modal disetor yang disyaratkan Rp2,5 miliar (Peraturan Kementerian Investasi No. 5/2025), ditambah laporan tahunan dan pajak badan 22%.' },
    { q: 'Pajak apa yang dibayar orang asing saat membeli dan memiliki properti di Bali?',
      a: 'Saat membeli: PPN jika membeli dari pengembang (efektif 11%), BPHTB hingga 5% saat memperoleh hak atas tanah yang terdaftar, dan biaya notaris (PPAT) 0,5–1%. Saat memiliki: PBB hingga 0,5% dari dasar pengenaan. Atas penghasilan sewa: pajak final 10% dari sewa bruto bagi wajib pajak dalam negeri; bagi nonresiden umumnya dipotong 20%, dapat dikurangi melalui perjanjian pajak. Saat menjual: pajak final 2,5% dari harga pengalihan tanah dan bangunan. Sumber: DJP, PwC Indonesia Tax Summaries.' },
    { q: 'Berapa tahun vila di Bali balik modal?',
      a: 'Tergantung imbal hasil bersih: pada 5% bersih sekitar 20 tahun, pada 7% sekitar 14 tahun, pada 10% sekitar 10 tahun. Pada leasehold 25–30 tahun, marginnya tipis untuk vila median — karena itu harga, tarif per malam yang benar-benar bisa dicapai dan masa sewa lebih penting daripada angka di brosur.' },
    { q: 'Apa itu PBG dan SLF, dan mengapa penting?',
      a: 'PBG (Persetujuan Bangunan Gedung) adalah izin bangunan yang terbit sebelum pembangunan. SLF (Sertifikat Laik Fungsi) terbit setelah bangunan selesai. Tanpa keduanya, perizinan sewa sulit. Di katalog Balinsky, 27% vila memiliki PBG atau SLF dan 16% sedang dalam proses pengajuan (September 2026) — minta dokumennya sebelum membayar.' },
    { q: 'Bisakah saya mendapatkan izin tinggal di Indonesia melalui investasi properti?',
      a: 'Membeli vila saja tidak memberikan izin tinggal. Pilihannya antara lain KITAS investor melalui PT PMA, Second Home Visa (dana Rp2 miliar di bank Indonesia) dan Golden Visa untuk investasi yang lebih besar. Ketentuan berubah — periksa di Direktorat Jenderal Imigrasi.' },
  ],
  sourcesH2: 'Sumber',
  sources: [
    { label: 'BPS Bali — kedatangan wisatawan mancanegara 1969–2025', href: SRC.bpsArrivals },
    { label: 'BPS Bali — statistik pariwisata, okupansi hotel (rilis November 2025)', href: SRC.bpsOccupancy },
    { label: 'estatemarket.io — listing sewa jangka pendek (sumber basis data sewa)', href: SRC.estatemarket },
    { label: 'Balinsky — imbal hasil vila Bali per kawasan: metode dan data (bahasa Inggris)', href: SRC.yieldEn },
    { label: 'Balinsky — zonasi dan izin vila yang dijual dalam angka (bahasa Inggris)', href: SRC.zoningEn },
    { label: 'PP No. 18/2021 tentang hak atas tanah (JDIH BPK)', href: SRC.pp18 },
    { label: 'PwC Indonesia — Tax Summaries', href: SRC.pwcTax },
    { label: 'DJP — Direktorat Jenderal Pajak', href: SRC.djp },
    { label: 'Direktorat Jenderal Imigrasi', href: SRC.immigration },
  ],
  district: {
    metaTitle: n => `Investasi properti di ${n}, Bali — tarif per malam dan imbal hasil dari data kami | Balinsky`,
    metaDescription: n => `${n}, Bali: tarif median vila per malam, pendapatan sewa pada okupansi 65% dan perbandingannya dengan seluruh pulau — dari katalog dan basis data sewa Balinsky, dengan sumber.`,
    h1: n => `Investasi properti di ${n}, Bali — 2026`,
    caseTitle: n => `Vila 2 kamar di ${n} — apa kata data`,
    rate: (r, n) => `Tarif median per malam: ${r} (${n} vila 2 kamar disewakan)`,
    revenue: a => `Pendapatan kotor pada okupansi 65%: sekitar ${a} per tahun`,
    net: a => `Setelah komisi platform, manajemen, biaya operasional dan pajak sewa (sekitar 51%): sekitar ${a} per tahun`,
    price: (p, n) => `Harga median vila di kawasan ini: ${p} (${n} listing)`,
    island: 'Sebagai perbandingan, di seluruh Bali vila 2 kamar median menghasilkan sekitar 10% kotor dan 5% bersih per tahun pada okupansi 65%, sebelum amortisasi leasehold.',
    noRentals: 'Vila 2 kamar yang disewakan di kawasan ini terlalu sedikit untuk tarif yang andal — bandingkan dengan kawasan tetangga.',
    risksH3: 'Yang perlu diperiksa di sini',
    bestFor: 'Cocok untuk',
    next: 'Langkah berikutnya',
    villas: n => [`Vila di ${n}`, 'Listing dengan foto, harga, status izin dan estimasi pendapatan.'],
    apartments: n => [`Apartemen di ${n}`, 'Unit di kompleks terkelola.'],
    complexes: n => [`Kompleks hunian di ${n}`, 'Proyek off-plan dan yang sudah selesai.'],
    guide: ['Panduan lengkap investasi Bali', 'Imbal hasil, leasehold, PT PMA dan pajak — dengan sumber.'],
    map: 'Lihat kawasan di peta —',
    mapLink: 'peta vila',
  },
}
