import type { InvestmentGuideCopy } from './types'
import { SRC } from './data'

export const nl: InvestmentGuideCopy = {
  meta: {
    title: 'Beleggen in vastgoed op Bali 2026 — rendementen uit eigen data, leasehold, belastingen | Balinsky',
    description: 'Gids voor buitenlandse kopers: huurrendementen berekend uit 6.305 huurvilla’s en 359 verkoopprijzen, leasehold of PT PMA, belastingen, bestemming en vergunningen — elk cijfer met bron.',
    ogTitle: 'Vastgoed op Bali 2026 — wat de data laat zien',
    ogDescription: 'Rendementen uit eigen data, leasehold of PT PMA, belastingen, bestemming en vergunningen. Elk cijfer met bron.',
  },
  crumbHome: 'Home',
  crumb: 'Vastgoedbelegging op Bali',
  h1: 'Beleggen in vastgoed op Bali — gids 2026',
  intro: 'Huurrendementen berekend uit onze eigen data, eigendomsstructuren (leasehold en PT PMA), belastingen voor buitenlandse eigenaren, bestemming en vergunningen. Elk cijfer op deze pagina verwijst naar zijn bron.',
  updated: 'Bijgewerkt: september 2026',
  stats: {
    yield: 'brutorendement van een mediane villa met 2 slaapkamers bij 65% bezetting',
    catalogue: "villa's en appartementen in de catalogus",
    permits: "van de villa's heeft een PBG of SLF",
    rentals: "huurvilla's geanalyseerd",
  },
  why: {
    h2: 'Waarom buitenlandse beleggers naar Bali kijken',
    p1: 'Bali is een van de weinige resortmarkten in Zuidoost-Azië waar een buitenlander ondanks het Indonesische verbod op volle eigendom voor buitenlanders legaal over vastgoed kan beschikken — via een huurovereenkomst, een gebruiksrecht (Hak Pakai) met verblijfsvergunning, of een vennootschap met buitenlands kapitaal (PT PMA) die een opstalrecht houdt.',
    p2: 'De vraag is sterk: Bali ontving in 2025 6.948.754 buitenlandse bezoekers, een record (BPS Bali). Sterrenhotels draaien op ongeveer 57–65% bezetting, lager in het laagseizoen (BPS Bali). Balinsky volgt de markt voor kortetermijnverhuur dagelijks — meer dan 6.300 villa’s met hun prijs per nacht, via estatemarket.io — en vergelijkt elke villa te koop met haar buren.',
    p3: 'De keerzijde is net zo echt: de meeste villa’s zijn leasehold en verliezen waarde naarmate de looptijd afneemt, ontwikkelaars verschillen sterk, een derde van de villa’s te koop staat op woongrond waar verhuur per nacht niet is toegestaan, en slechts ongeveer een kwart heeft een bouwvergunning.',
    p3Link: 'Bestemming en vergunningen in cijfers (in het Engels)',
  },
  yields: {
    h2: 'Rendementen per gebied — onze berekening 2026',
    method: "Villa's met twee slaapkamers: mediane vraagprijs in de Balinsky-catalogus en mediane prijs per nacht van verhuurde villa's met twee slaapkamers in hetzelfde gebied, bij 65% bezetting. Netto = na 15% platformcommissie, 20% beheer, 6% exploitatiekosten en 10% huurbelasting; vóór afschrijving van de leasehold. Volledige methode (in het Engels):",
    methodLink: "rendement van villa's op Bali per gebied",
    colArea: 'Gebied',
    colPrice: 'Prijs 2 slk, mediaan',
    colRate: 'Per nacht, mediaan',
    colYield: 'Bruto / netto',
    indicative: '* minder dan 30 verkoopprijzen — indicatief',
    browse: 'bekijken',
    areas: {
      canggu: 'Groot-Canggu (Canggu, Berawa, Batu Bolong, Pererenan, Umalas, Seminyak)',
      bukit: 'Bukit (Uluwatu, Melasti, Pandawa, Ungasan)',
      ubud: 'Ubud',
      nyanyi: 'Nyanyi en Tabanan',
      nusaDua: 'Nusa Dua',
      island: 'Heel Bali',
    },
  },
  legal: {
    h2: 'Eigendomsstructuren — leasehold of PT PMA',
    leaseTitle: 'Leasehold',
    leaseLead: 'Een contractuele huur van een lokale eigenaar — meestal 25–30 jaar; verlenging bestaat alleen als die in het contract staat.',
    lease: [
      'Geen vennootschap nodig',
      'Getekend als notariële akte',
      'Geen jaarlijkse vennootschapsrapportage',
      "Past bij een eigen woning of één à twee huurvilla's",
      'De grond is niet van u — alleen het gebruiksrecht voor een vaste termijn',
    ],
    pmaTitle: 'PT PMA',
    pmaLead: 'Een Indonesische vennootschap met buitenlandse aandeelhouders. Zij houdt een opstalrecht (HGB) — geen volle eigendom, die voor buitenlanders en vennootschappen met buitenlands kapitaal niet mogelijk is.',
    pma: [
      'Opstalrecht (HGB): 30 + 20 + 30 jaar (PP 18/2021)',
      'Past bij een verhuurbedrijf of portefeuille',
      'Gestort kapitaal van IDR 2,5 miljard (verordening van het ministerie van Investeringen nr. 5/2025)',
      'Jaarlijkse belasting- en investeringsrapportage',
      '22% vennootschapsbelasting',
    ],
    more: 'Het volledige aankoopproces staat op de pagina',
    moreLink: '„Vastgoed kopen op Bali”',
  },
  roi: {
    h2: 'Rendementsberekening — een mediane villa',
    title: 'Villa met 2 slaapkamers op de catalogusmediaan, $322.500, leasehold van 30 jaar',
    lines: [
      "Prijs per nacht: $135 (mediaan van 1.966 verhuurde villa's met 2 slaapkamers) × 65% bezetting × 365 = ongeveer $32.000 bruto per jaar",
      'Platformcommissie 15%, beheer 20%, exploitatiekosten 6%, huurbelasting 10%: ongeveer −$16.300',
      'Netto: ongeveer $15.700 per jaar — 4,9% van de prijs',
      'Afschrijving van de leasehold: $322.500 ÷ 30 jaar = $10.750 per jaar; boven het terugverdienen van uw eigen geld blijft dus ongeveer $4.950 per jaar over',
    ],
    top: 'Een villa in het bovenste kwart van de markt ($190 per nacht) bij 75% bezetting: ongeveer $52.000 bruto en $25.500 netto — 7,9% van dezelfde prijs.',
    note: 'Elke villapagina in de catalogus toont een schatting op basis van haar eigen buren. Methode (in het Engels):',
    noteLink: "rendement van villa's op Bali per gebied",
  },
  risks: {
    h3: 'Risico’s waar verkopers zelden over praten',
    items: [
      { t: 'De looptijd slinkt.', d: 'Een leasehold van 25 jaar verbruikt elk jaar ongeveer 4% van de prijs. Vergelijk villa’s op prijs per resterend jaar.' },
      { t: 'Geen bouwvergunning of SLF.', d: 'Zonder die documenten is een verhuurvergunning lastig. Slechts ongeveer 27% van de villa’s in onze catalogus heeft een PBG of SLF.' },
      { t: 'Woon- of landbouwgrond.', d: 'Een derde van de villa’s in onze catalogus staat op woongrond (geel) waar verhuur per nacht niet is toegestaan. Controleer de RDTR-zone van het perceel.' },
      { t: 'Prognoses boven de markt.', d: 'Mediaan levert een villa met twee slaapkamers ongeveer 5% netto op. Prognoses van 10–15% gaan uit van topprijzen en topbezetting.' },
      { t: 'Ontwikkelaarsrisico bij off-plan.', d: 'Betaal per bouwfase, houd de grootste betaling voor de oplevering en betaal niets voordat de PBG er is.' },
    ],
  },
  check: {
    h2: 'Wat we bij elke aanbieding tonen',
    p: 'Voor elk object leggen we de vergunningstatus (PBG, SLF), de grondzone en de ontwikkelaar vast en tonen die in de aanbieding. Is een document niet aangeleverd, dan staat dat erbij — in september 2026 gold dat voor 57% van de villa’s. Controleer documenten altijd zelf of via uw eigen advocaat voordat u betaalt.',
    cards: [
      { t: 'Documenten', d: 'PBG, SLF en grondstatus zoals vastgelegd — vraag kopieën op voordat u betaalt.' },
      { t: 'Ontwikkelaar', d: 'Vennootschap, opgeleverde projecten en andere aanbiedingen van dezelfde ontwikkelaar.' },
      { t: 'Locatie', d: 'Kaart, zonekleur, plekken in de buurt en huurconcurrentie rond het object.' },
    ],
    more: 'Meer op de pagina',
    moreLink: '„Over Balinsky”',
  },
  next: {
    h2: 'Volgende stappen',
    villas: ['Villacatalogus', "Villa's met foto's, prijzen, vergunningstatus en een inkomensschatting."],
    apartments: ['Appartementencatalogus', 'Units in beheerde complexen — de laagste instapprijs.'],
    complexes: ['Wooncomplexen', 'Complexen in aanbouw en opgeleverd, met opleverdata.'],
    howTo: ['Kopen — stap voor stap', 'Eigendomsstructuren, de transactie, echte kosten en valkuilen.'],
  },
  faqH2: 'Veelgestelde vragen',
  faq: [
    { q: 'Wat is in 2026 een realistisch huurrendement voor een villa op Bali?',
      a: "Volgens de berekening van Balinsky (september 2026: 359 villa's te koop, 6.305 villa's te huur) levert een mediane villa met twee slaapkamers bij 65% bezetting ongeveer 10% bruto en ongeveer 5% netto per jaar op, een villa met één slaapkamer ongeveer 14% bruto en 7% netto. Villa's in het bovenste kwart qua prijs per nacht halen ongeveer 7–10% netto. Netto betekent na platformcommissie, beheer, exploitatiekosten en huurbelasting, vóór afschrijving van de leasehold. Sterrenhotels op Bali draaien op ongeveer 57–65% bezetting (BPS Bali)." },
    { q: 'Leasehold of PT PMA — welke structuur past bij een buitenlandse belegger?',
      a: "Een leasehold (contractuele huur, meestal 25–30 jaar) past bij een eigen woning of één à twee huurvilla's: zonder vennootschap en zonder jaarrapportage. Een PT PMA houdt een opstalrecht (HGB, 30 + 20 + 30 jaar volgens PP 18/2021) — geen volle eigendom, die voor buitenlanders niet mogelijk is. Zij past bij een verhuurbedrijf; het vereiste gestorte kapitaal is IDR 2,5 miljard (verordening van het ministerie van Investeringen nr. 5/2025), plus jaarrapportage en 22% vennootschapsbelasting." },
    { q: 'Welke belastingen betaalt een buitenlander bij aankoop en bezit van vastgoed op Bali?',
      a: 'Bij aankoop: btw bij aankoop van een ontwikkelaar (effectief 11%), overdrachtsbelasting BPHTB tot 5% bij verwerving van een geregistreerd grondrecht, en notariskosten (PPAT) van 0,5–1%. Tijdens bezit: grond- en gebouwenbelasting PBB tot 0,5% van de heffingsgrondslag. Op huurinkomsten: 10% eindheffing op de brutohuur voor fiscaal inwoners; voor niet-inwoners meestal 20% inhouding, te verlagen via een belastingverdrag. Bij verkoop: 2,5% eindheffing op de prijs van de overdracht van grond en gebouw. Bronnen: DJP, PwC Indonesia Tax Summaries.' },
    { q: 'In hoeveel jaar verdient een villa op Bali zichzelf terug?',
      a: 'Dat hangt af van het nettorendement: bij 5% netto ongeveer 20 jaar, bij 7% ongeveer 14, bij 10% ongeveer 10. Op een leasehold van 25–30 jaar blijft er bij de mediaan weinig marge over — daarom tellen de prijs, de werkelijk haalbare prijs per nacht en de looptijd zwaarder dan het rendement uit de brochure.' },
    { q: 'Wat zijn PBG en SLF, en waarom zijn ze belangrijk?',
      a: 'PBG (Persetujuan Bangunan Gedung) is de bouwvergunning, afgegeven vóór de bouw. SLF (Sertifikat Laik Fungsi) is het gebruikscertificaat, afgegeven na oplevering. Zonder deze documenten is een verhuurvergunning lastig. In de Balinsky-catalogus heeft 27% van de villa’s een PBG of SLF en heeft 16% een lopende aanvraag (september 2026) — vraag de documenten op voordat u betaalt.' },
    { q: 'Kan ik via een vastgoedbelegging een Indonesische verblijfsvergunning krijgen?',
      a: 'Alleen een villa kopen geeft geen verblijfsrecht. Mogelijkheden zijn onder meer een investeerders-KITAS via een PT PMA, het Second Home Visa (IDR 2 miljard op een Indonesische bankrekening) en het Golden Visa voor grotere investeringen. De voorwaarden veranderen — controleer ze bij het Directoraat-Generaal Immigratie.' },
  ],
  sourcesH2: 'Bronnen',
  sources: [
    { label: 'BPS Bali — aankomsten van buitenlandse toeristen 1969–2025', href: SRC.bpsArrivals },
    { label: 'BPS Bali — toerismestatistiek, hotelbezetting (publicatie november 2025)', href: SRC.bpsOccupancy },
    { label: 'estatemarket.io — aanbiedingen kortetermijnverhuur (bron van de huurdatabase)', href: SRC.estatemarket },
    { label: "Balinsky — rendement van villa's op Bali per gebied: methode en data (in het Engels)", href: SRC.yieldEn },
    { label: "Balinsky — bestemming en vergunningen van villa's te koop in cijfers (in het Engels)", href: SRC.zoningEn },
    { label: 'PP nr. 18/2021 over grondrechten (JDIH BPK)', href: SRC.pp18 },
    { label: 'PwC Indonesia — Tax Summaries', href: SRC.pwcTax },
    { label: 'DJP — Indonesische belastingdienst', href: SRC.djp },
    { label: 'Directoraat-Generaal Immigratie van Indonesië', href: SRC.immigration },
  ],
  district: {
    metaTitle: n => `Beleggen in ${n}, Bali — prijzen per nacht en rendementen uit onze data | Balinsky`,
    metaDescription: n => `${n}, Bali: mediane villaprijs per nacht, huuropbrengst bij 65% bezetting en de vergelijking met het hele eiland — uit de Balinsky-catalogus en huurdatabase, met bronnen.`,
    h1: n => `Beleggen in vastgoed in ${n}, Bali — 2026`,
    caseTitle: n => `Villa met twee slaapkamers in ${n} — wat de data laat zien`,
    rate: (r, n) => `Mediane prijs per nacht: ${r} (${n} verhuurde villa's met twee slaapkamers)`,
    revenue: a => `Bruto-opbrengst bij 65% bezetting: ongeveer ${a} per jaar`,
    net: a => `Na platformcommissie, beheer, exploitatiekosten en huurbelasting (ongeveer 51%): ongeveer ${a} per jaar`,
    price: (p, n) => `Mediane vraagprijs van villa's in het gebied: ${p} (${n} aanbiedingen)`,
    island: 'Ter vergelijking: op heel Bali levert een mediane villa met twee slaapkamers bij 65% bezetting ongeveer 10% bruto en 5% netto per jaar op, vóór afschrijving van de leasehold.',
    noRentals: "In dit gebied worden te weinig villa's met twee slaapkamers verhuurd voor een betrouwbare prijs — vergelijk met naburige gebieden.",
    risksH3: 'Wat u hier moet controleren',
    bestFor: 'Geschikt voor',
    next: 'Volgende stap',
    villas: n => [`Villa's in ${n}`, "Aanbiedingen met foto's, prijzen, vergunningstatus en een inkomensschatting."],
    apartments: n => [`Appartementen in ${n}`, 'Units in beheerde complexen.'],
    complexes: n => [`Wooncomplexen in ${n}`, 'Projecten in aanbouw en opgeleverd.'],
    guide: ['Volledige Bali-beleggingsgids', 'Rendementen, leasehold, PT PMA en belastingen — met bronnen.'],
    map: 'Bekijk het gebied op de kaart —',
    mapLink: 'villakaart',
  },
}
