import type { InvestmentGuideCopy } from './types'
import { SRC } from './data'

export const pl: InvestmentGuideCopy = {
  meta: {
    title: 'Inwestycje w nieruchomości na Bali 2026 — rentowność z własnych danych, leasehold, podatki | Balinsky',
    description: 'Przewodnik dla kupujących z zagranicy: rentowność policzona na 6305 willach na wynajem i 359 cenach sprzedaży, leasehold czy PT PMA, podatki, strefy i pozwolenia — każda liczba ze źródłem.',
    ogTitle: 'Nieruchomości na Bali 2026 — co pokazują dane',
    ogDescription: 'Rentowność z własnych danych, leasehold czy PT PMA, podatki, strefy i pozwolenia. Każda liczba ze źródłem.',
  },
  crumbHome: 'Strona główna',
  crumb: 'Inwestycje w nieruchomości na Bali',
  h1: 'Inwestycje w nieruchomości na Bali — przewodnik 2026',
  intro: 'Rentowność policzona na naszych własnych danych, struktury własności (leasehold i PT PMA), podatki dla zagranicznego właściciela, strefy i pozwolenia. Każda liczba na tej stronie ma link do źródła.',
  updated: 'Aktualizacja: wrzesień 2026',
  stats: {
    yield: 'rentowność brutto mediany willi z 2 sypialniami przy obłożeniu 65%',
    catalogue: 'willi i apartamentów w katalogu',
    permits: 'willi ma PBG lub SLF',
    rentals: 'willi na wynajem przeanalizowanych',
  },
  why: {
    h2: 'Dlaczego zagraniczni inwestorzy patrzą na Bali',
    p1: 'Bali to jeden z niewielu kurortów Azji Południowo-Wschodniej, gdzie cudzoziemiec może legalnie dysponować nieruchomością mimo indonezyjskiego zakazu pełnej własności dla cudzoziemców — przez umowę dzierżawy, prawo użytkowania (Hak Pakai) z zezwoleniem na pobyt albo spółkę z kapitałem zagranicznym (PT PMA) z prawem zabudowy.',
    p2: 'Popyt jest silny: w 2025 roku Bali przyjęło 6 948 754 zagranicznych turystów — rekord (BPS Bali). Obłożenie hoteli z gwiazdkami wynosi około 57–65% i spada poza sezonem (BPS Bali). Balinsky codziennie śledzi rynek najmu krótkoterminowego — ponad 6300 willi z cenami za noc, przez estatemarket.io — i porównuje każdą willę na sprzedaż z sąsiadami.',
    p3: 'Druga strona jest równie realna: większość willi to leasehold, który traci wartość wraz z upływem okresu, deweloperzy są nierówni, jedna trzecia willi na sprzedaż stoi na gruncie mieszkaniowym, gdzie najem na doby nie jest dozwolony, a tylko około jednej czwartej ma pozwolenie na budowę.',
    p3Link: 'Strefy i pozwolenia w liczbach (po angielsku)',
  },
  yields: {
    h2: 'Rentowność według okolic — nasze wyliczenie 2026',
    method: 'Wille z dwiema sypialniami: mediana ceny w katalogu Balinsky i mediana ceny za noc willi z dwiema sypialniami na wynajem w tej samej okolicy, przy obłożeniu 65%. Netto = po 15% prowizji platform, 20% zarządzania, 6% kosztów utrzymania i 10% lokalnego podatku od zakwaterowania (PBJT); przed podatkiem dochodowym; przed amortyzacją leasehold. Pełna metodologia (po angielsku):',
    methodLink: 'rentowność willi na Bali według okolic',
    colArea: 'Okolica',
    colPrice: 'Cena 2 syp., mediana',
    colRate: 'Za noc, mediana',
    colYield: 'Brutto / netto',
    indicative: '* mniej niż 30 cen sprzedaży — wartość orientacyjna',
    browse: 'zobacz',
    areas: {
      canggu: 'Wielkie Canggu (Canggu, Berawa, Batu Bolong, Pererenan, Umalas, Seminyak)',
      bukit: 'Bukit (Uluwatu, Melasti, Pandawa, Ungasan)',
      ubud: 'Ubud',
      nyanyi: 'Nyanyi i Tabanan',
      nusaDua: 'Nusa Dua',
      island: 'Całe Bali',
    },
  },
  legal: {
    h2: 'Struktury własności — leasehold czy PT PMA',
    leaseTitle: 'Leasehold',
    leaseLead: 'Umowna dzierżawa od lokalnego właściciela — zwykle 25–30 lat; przedłużenie istnieje tylko wtedy, gdy jest zapisane w umowie.',
    lease: [
      'Spółka niepotrzebna',
      'Podpisywana jako akt notarialny',
      'Bez corocznej sprawozdawczości spółki',
      'Pasuje do domu lub jednej-dwóch willi na wynajem',
      'Grunt nie jest twój — tylko prawo do korzystania przez określony czas',
    ],
    pmaTitle: 'PT PMA',
    pmaLead: 'Indonezyjska spółka z zagranicznymi udziałowcami. Posiada prawo zabudowy (HGB) — nie pełną własność, niedostępną dla cudzoziemców i spółek z kapitałem zagranicznym.',
    pma: [
      'Prawo zabudowy (HGB): 30 + 20 + 30 lat (PP 18/2021)',
      'Pasuje do biznesu najmu lub portfela',
      'Kapitał wpłacony 2,5 mld rupii (rozporządzenie Ministerstwa Inwestycji nr 5/2025)',
      'Coroczne sprawozdania podatkowe i inwestycyjne',
      'Podatek dochodowy od osób prawnych 22%',
    ],
    more: 'Cały proces transakcji opisuje strona',
    moreLink: '„Jak kupić nieruchomość na Bali”',
  },
  roi: {
    h2: 'Wyliczenie rentowności — mediana willi',
    title: 'Willa z 2 sypialniami według mediany katalogu, 322 500 $, leasehold 30 lat',
    lines: [
      'Stawka: 135 $ za noc (mediana 1966 willi z 2 sypialniami na wynajem) × obłożenie 65% × 365 = około 32 000 $ brutto rocznie',
      'Prowizje platform 15%, zarządzanie 20%, utrzymanie 6%, lokalny podatek od zakwaterowania (PBJT) 10%: około −16 300 $ (przed podatkiem dochodowym)',
      'Netto: około 15 700 $ rocznie — 4,9% ceny',
      'Amortyzacja leasehold: 322 500 $ ÷ 30 lat = 10 750 $ rocznie, więc ponad zwrot własnych pieniędzy zostaje około 4950 $ rocznie',
    ],
    top: 'Willa z górnej ćwiartki rynku (190 $ za noc) przy obłożeniu 75%: około 52 000 $ brutto i 25 500 $ netto — 7,9% tej samej ceny.',
    note: 'Strona każdej willi w katalogu pokazuje szacunek na podstawie jej własnych sąsiadów. Metodologia (po angielsku):',
    noteLink: 'rentowność willi na Bali według okolic',
  },
  risks: {
    h3: 'Ryzyka, o których sprzedawcy rzadko mówią',
    items: [
      { t: 'Okres dzierżawy maleje.', d: 'Leasehold na 25 lat zużywa co roku około 4% ceny. Porównuj wille według ceny za pozostały rok.' },
      { t: 'Brak pozwolenia na budowę lub SLF.', d: 'Bez nich trudno o licencję na najem. Tylko około 27% willi w naszym katalogu ma PBG lub SLF.' },
      { t: 'Grunt mieszkaniowy lub rolny.', d: 'Jedna trzecia willi w naszym katalogu stoi na gruncie mieszkaniowym (żółtym), gdzie najem na doby nie jest dozwolony. Sprawdź strefę RDTR działki.' },
      { t: 'Prognozy powyżej rynku.', d: 'Mediana willi z dwiema sypialniami daje około 5% netto. Prognozy 10–15% zakładają stawki i obłożenie ze szczytu rynku.' },
      { t: 'Ryzyko dewelopera w off-plan.', d: 'Płać według etapów budowy, zostaw największą płatność na odbiór i nie płać przed wydaniem PBG.' },
    ],
  },
  check: {
    h2: 'Co pokazujemy przy każdej ofercie',
    p: 'Dla każdej nieruchomości zapisujemy status pozwoleń (PBG, SLF), strefę gruntu i dewelopera i pokazujemy je w ofercie. Jeśli dokument nie został dostarczony, oferta to zaznacza — we wrześniu 2026 dotyczyło to 57% willi. Zawsze sprawdzaj dokumenty sam lub przez własnego prawnika przed zapłatą.',
    cards: [
      { t: 'Dokumenty', d: 'PBG, SLF i status gruntu w zapisanej postaci — poproś o kopie przed zapłatą.' },
      { t: 'Deweloper', d: 'Spółka, ukończone projekty i inne oferty tego samego dewelopera.' },
      { t: 'Lokalizacja', d: 'Mapa, kolor strefy, miejsca w pobliżu i konkurencja najmu wokół nieruchomości.' },
    ],
    more: 'Więcej na stronie',
    moreLink: '„O Balinsky”',
  },
  next: {
    h2: 'Kolejne kroki',
    villas: ['Katalog willi', 'Wille ze zdjęciami, cenami, statusem pozwoleń i szacunkiem dochodu.'],
    apartments: ['Katalog apartamentów', 'Lokale w zarządzanych kompleksach — najniższy próg wejścia.'],
    complexes: ['Kompleksy mieszkaniowe', 'Kompleksy w budowie i oddane, z terminami oddania.'],
    howTo: ['Jak kupić — krok po kroku', 'Struktury własności, transakcja, realne koszty i pułapki.'],
  },
  faqH2: 'Najczęstsze pytania',
  faq: [
    { q: 'Jaka jest realna rentowność najmu willi na Bali w 2026 roku?',
      a: 'Według wyliczeń Balinsky (wrzesień 2026: 359 willi na sprzedaż, 6305 willi na wynajem) mediana willi z dwiema sypialniami przy obłożeniu 65% daje około 10% rocznie brutto i około 5% netto, willa z jedną sypialnią około 14% brutto i 7% netto. Wille z górnej ćwiartki pod względem stawki za noc osiągają około 7–10% netto. Netto oznacza po prowizjach platform, zarządzaniu, utrzymaniu i lokalnym podatku od zakwaterowania, przed podatkiem dochodowym i amortyzacją leasehold. Obłożenie hoteli z gwiazdkami na Bali wynosi około 57–65% (BPS Bali).' },
    { q: 'Leasehold czy PT PMA — jaką strukturę wybrać zagranicznemu inwestorowi?',
      a: 'Leasehold (umowna dzierżawa, zwykle 25–30 lat) pasuje do domu lub jednej-dwóch willi na wynajem: bez spółki i bez corocznych sprawozdań. PT PMA posiada prawo zabudowy (HGB, 30 + 20 + 30 lat według PP 18/2021) — nie pełną własność, niedostępną dla cudzoziemców. Pasuje do biznesu najmu; wymagany kapitał wpłacony to 2,5 mld rupii (rozporządzenie Ministerstwa Inwestycji nr 5/2025), do tego coroczne sprawozdania i 22% podatku od osób prawnych.' },
    { q: 'Jakie podatki płaci cudzoziemiec przy zakupie i posiadaniu nieruchomości na Bali?',
      a: 'Przy zakupie: VAT przy zakupie od dewelopera (efektywnie 11%), opłata BPHTB do 5% przy nabyciu zarejestrowanego prawa do gruntu i notariusz (PPAT) 0,5–1%. Przy posiadaniu: podatek od gruntu i budynków PBB do 0,5% podstawy. Od dochodu z najmu: zryczałtowane 10% od czynszu brutto dla rezydentów podatkowych; u nierezydentów zwykle potrącane 20%, obniżalne umową o unikaniu podwójnego opodatkowania. Przy sprzedaży: zryczałtowane 2,5% od ceny przeniesienia gruntu i budynku. Źródła: DJP, PwC Indonesia Tax Summaries.' },
    { q: 'Po ilu latach zwraca się willa na Bali?',
      a: 'To zależy od rentowności netto: przy 5% netto około 20 lat, przy 7% około 14, przy 10% około 10. Przy leasehold na 25–30 lat mediana zostawia mały margines — dlatego cena, realnie osiągalna stawka za noc i okres dzierżawy są ważniejsze niż rentowność z broszury.' },
    { q: 'Czym są PBG i SLF i dlaczego są ważne?',
      a: 'PBG (Persetujuan Bangunan Gedung) to pozwolenie na budowę wydawane przed rozpoczęciem prac. SLF (Sertifikat Laik Fungsi) to certyfikat zdatności do użytku wydawany po ukończeniu. Bez nich trudno o licencję na najem. W katalogu Balinsky 27% willi ma PBG lub SLF, a 16% ma złożony wniosek (wrzesień 2026) — poproś o dokumenty przed zapłatą.' },
    { q: 'Czy można uzyskać indonezyjskie zezwolenie na pobyt dzięki inwestycji w nieruchomość?',
      a: 'Sam zakup willi nie daje prawa pobytu. Możliwości to m.in. KITAS inwestora przez PT PMA, Second Home Visa (2 mld rupii na rachunku w indonezyjskim banku) i Golden Visa dla większych inwestycji. Warunki się zmieniają — sprawdź je w Dyrekcji Generalnej ds. Imigracji.' },
  ],
  sourcesH2: 'Źródła',
  sources: [
    { label: 'BPS Bali — przyjazdy zagranicznych turystów 1969–2025', href: SRC.bpsArrivals },
    { label: 'BPS Bali — statystyka turystyki, obłożenie hoteli (komunikat za listopad 2025)', href: SRC.bpsOccupancy },
    { label: 'estatemarket.io — oferty najmu krótkoterminowego (źródło bazy najmu)', href: SRC.estatemarket },
    { label: 'Balinsky — rentowność willi na Bali według okolic: metodologia i dane (po angielsku)', href: SRC.yieldEn },
    { label: 'Balinsky — strefy i pozwolenia willi na sprzedaż w liczbach (po angielsku)', href: SRC.zoningEn },
    { label: 'PP nr 18/2021 o prawach do gruntu (JDIH BPK)', href: SRC.pp18 },
    { label: 'PwC Indonesia — Tax Summaries', href: SRC.pwcTax },
    { label: 'DJP — indonezyjska administracja podatkowa', href: SRC.djp },
    { label: 'Dyrekcja Generalna ds. Imigracji Indonezji', href: SRC.immigration },
  ],
  district: {
    metaTitle: n => `Inwestycje w ${n}, Bali: stawki najmu i rentowność | Balinsky`,
    metaDescription: n => `${n}, Bali: mediana stawki za noc w willi, przychód z najmu przy obłożeniu 65% i porównanie z całą wyspą.`,
    h1: n => `Inwestycje w nieruchomości w ${n}, Bali — 2026`,
    caseTitle: n => `Willa z dwiema sypialniami w ${n} — co pokazują dane`,
    rate: (r, n) => `Mediana stawki za noc: ${r} (${n} willi z dwiema sypialniami na wynajem)`,
    revenue: a => `Przychód brutto przy obłożeniu 65%: około ${a} rocznie`,
    net: a => `Po prowizjach platform, zarządzaniu, utrzymaniu i lokalnym podatku od zakwaterowania (około 51%, przed podatkiem dochodowym): około ${a} rocznie`,
    price: (p, n) => `Mediana ceny willi w okolicy: ${p} (${n} ofert)`,
    island: 'Dla porównania: na całym Bali mediana willi z dwiema sypialniami przy obłożeniu 65% daje około 10% brutto i 5% netto rocznie, przed amortyzacją leasehold.',
    noRentals: 'W tej okolicy na wynajem jest zbyt mało willi z dwiema sypialniami, by podać wiarygodną stawkę — porównaj z sąsiednimi okolicami.',
    risksH3: 'Co tu sprawdzić',
    bestFor: 'Dla kogo',
    next: 'Kolejny krok',
    villas: n => [`Wille w ${n}`, 'Oferty ze zdjęciami, cenami, statusem pozwoleń i szacunkiem dochodu.'],
    apartments: n => [`Apartamenty w ${n}`, 'Lokale w zarządzanych kompleksach.'],
    complexes: n => [`Kompleksy mieszkaniowe w ${n}`, 'Projekty w budowie i oddane.'],
    guide: ['Pełny przewodnik inwestycyjny po Bali', 'Rentowność, leasehold, PT PMA i podatki — ze źródłami.'],
    map: 'Zobacz okolicę na mapie —',
    mapLink: 'mapa willi',
  },
}
